### ISSUE TITLE
GsonConverter doesn't play well with proguard.

### ISSUE THREAD

**Issue by k0shk0sh** [square/retrofit#1010]
i'm getting this error 
```
java.lang.UnsupportedOperationException: Attempted to serialize java.lang.Class: com.innov8tif.salesmobility.forms.model.FormDataListModel. Forgot to register a type adapter?
            at com.google.gson.internal.bind.TypeAdapters$1.a(Unknown Source)
            at com.google.gson.internal.bind.TypeAdapters$1.a(Unknown Source)
            at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.a(Unknown Source)
            at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.a(Unknown Source)
            at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.a(Unknown Source)
            at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.a(Unknown Source)
            at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.a(Unknown Source)
            at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.a(Unknown Source)
            at com.google.gson.Gson.a(Unknown Source)
            at com.google.gson.Gson.a(Unknown Source)
            at com.google.gson.Gson.a(Unknown Source)
            at com.google.gson.Gson.a(Unknown Source)
            at retrofit.converter.GsonConverter.toBody(Unknown Source)
            at retrofit.RequestBuilder.setArguments(Unknown Source)
            at retrofit.RestAdapter$RestHandler.invokeRequest(Unknown Source)
            at retrofit.RestAdapter$RestHandler.access$100(Unknown Source)
            at retrofit.RestAdapter$RestHandler$2.obtainResponse(Unknown Source)
            at retrofit.CallbackRunnable.run(Unknown Source)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at retrofit.Platform$Android$2$1.run(Unknown Source)
            at java.lang.Thread.run(Thread.java:818)
```

even tho i have registered the adapter and i'm sure that the adapter does work because i'm logging the details after registering the adapter here is how I am doing it : 
```
        Gson gson = new GsonBuilder().registerTypeAdapter(FormDataListModel.class, new FormPosterAdapter()).create();
```
and i'm setting it to the restAdapter ```.setConverter(new GsonConverter(gson)``` but however i'm getting the stack error above, if i did removed the proguard then it would work normal but with this proguard it doesn't here is my proguard: 
```
-keep class com.google.gson.** { ; }
-keep class sun.misc.Unsafe { *; }
-keep class com.google.gson.stream.** { *; }
-keep class  all the classes that deal with gson
-keepattributes Signature
-keepattributes *Annotation*
-keep class com.squareup.okhttp.** { *; }
-keep interface com.squareup.okhttp.** { *; }
-dontwarn com.squareup.okhttp.**
-dontwarn rx.**
-dontwarn retrofit.**
-dontwarn okio.**
-keep class retrofit.** { *; }
-keepclasseswithmembers class * {
    @retrofit.http.* <methods>;
}
```
i guess my proguard configuration shouldn't cause that ? any idea in how i could solve this issue?

**Comment by k0shk0sh** [comment]
please close/remove this issue as it has been fixed. sorry for inconvenience

**Comment by CCorrado** [comment]
How was this resolved? Running into a similar issue with retrofit and proguard....
```
10-21 10:54:49.751 27401-27401/com.vistakon.healthyfutures.develop E/LoginActivity:     at retrofit.RestAdapter$RestHandler.invokeRequest(Unknown Source)
10-21 10:54:49.751 27401-27401/com.vistakon.healthyfutures.develop E/LoginActivity:     at retrofit.RestAdapter$RestHandler.access$100(Unknown Source)
10-21 10:54:49.751 27401-27401/com.vistakon.healthyfutures.develop E/LoginActivity:     at retrofit.RestAdapter$RestHandler$2.obtainResponse(Unknown Source)
10-21 10:54:49.751 27401-27401/com.vistakon.healthyfutures.develop E/LoginActivity:     at retrofit.CallbackRunnable.run(Unknown Source)
10-21 10:54:49.751 27401-27401/com.vistakon.healthyfutures.develop E/LoginActivity:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
10-21 10:54:49.751 27401-27401/com.vistakon.healthyfutures.develop E/LoginActivity:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
10-21 10:54:49.751 27401-27401/com.vistakon.healthyfutures.develop E/LoginActivity:     at retrofit.Platform$Android$2$1.run(Unknown Source)
10-21 10:54:49.751 27401-27401/com.vistakon.healthyfutures.develop E/LoginActivity:     at java.lang.Thread.run(Thread.java:818)
```
