### ISSUE TITLE
[2.0] Unsubscription of RxJavaCallAdapterFactory$CallOnSubscribe$1 requires Network thread on Android

### ISSUE THREAD

**Issue by festevezga** [square/retrofit#1046]
I'm trying to unsubscribe my network request upon app pause/destruction, but I'm seeing this common bug caused by the unsubscription method calling one of the "guarded" ones, thus ending abruptly.

```
java.lang.RuntimeException: Unable to pause activity {my.project.MyActivity}: android.os.NetworkOnMainThreadException
            at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3248)
            at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3203)
            at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:3893)
            at android.app.ActivityThread.access$1000(ActivityThread.java:161)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1271)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:157)
            at android.app.ActivityThread.main(ActivityThread.java:5356)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1265)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1081)
            at dalvik.system.NativeStart.main(Native Method)
     Caused by: android.os.NetworkOnMainThreadException
            at android.os.StrictMode$AndroidBlockGuardPolicy.onNetwork(StrictMode.java:1156)
            at com.android.org.conscrypt.OpenSSLSocketImpl.close(OpenSSLSocketImpl.java:1009)
            at com.squareup.okhttp.Connection.closeIfOwnedBy(Connection.java:148)
            at com.squareup.okhttp.OkHttpClient$1.closeIfOwnedBy(OkHttpClient.java:75)
            at com.squareup.okhttp.internal.http.HttpConnection.closeIfOwnedBy(HttpConnection.java:137)
            at com.squareup.okhttp.internal.http.HttpTransport.disconnect(HttpTransport.java:135)
            at com.squareup.okhttp.internal.http.HttpEngine.disconnect(HttpEngine.java:573)
            at com.squareup.okhttp.Call.cancel(Call.java:122)
            at retrofit.OkHttpCall.cancel(OkHttpCall.java:158)
            at retrofit.RxJavaCallAdapterFactory$CallOnSubscribe$1.call(RxJavaCallAdapterFactory.java:99)
            at rx.subscriptions.BooleanSubscription.unsubscribe(BooleanSubscription.java:72)
            at rx.internal.util.SubscriptionList.unsubscribeFromAll(SubscriptionList.java:124)
            at rx.internal.util.SubscriptionList.unsubscribe(SubscriptionList.java:113)
            at rx.Subscriber.unsubscribe(Subscriber.java:98)
            at rx.internal.util.SubscriptionList.unsubscribeFromAll(SubscriptionList.java:124)
            at rx.internal.util.SubscriptionList.unsubscribe(SubscriptionList.java:113)
            at rx.Subscriber.unsubscribe(Subscriber.java:98)
            at rx.subscriptions.CompositeSubscription.unsubscribeFromAll(CompositeSubscription.java:143)
            at rx.subscriptions.CompositeSubscription.unsubscribe(CompositeSubscription.java:132)
            at rx.internal.util.SubscriptionList.unsubscribeFromAll(SubscriptionList.java:124)
            at rx.internal.util.SubscriptionList.unsubscribe(SubscriptionList.java:113)
            at rx.Subscriber.unsubscribe(Subscriber.java:98)
            at rx.internal.util.SubscriptionList.unsubscribeFromAll(SubscriptionList.java:124)
            at rx.internal.util.SubscriptionList.unsubscribe(SubscriptionList.java:113)
            at rx.Subscriber.unsubscribe(Subscriber.java:98)
            at rx.subscriptions.CompositeSubscription.unsubscribeFromAll(CompositeSubscription.java:143)
            at rx.subscriptions.CompositeSubscription.unsubscribe(CompositeSubscription.java:132)
            at rx.internal.util.SubscriptionList.unsubscribeFromAll(SubscriptionList.java:124)
            at rx.internal.util.SubscriptionList.unsubscribe(SubscriptionList.java:113)
            at rx.Subscriber.unsubscribe(Subscriber.java:98)
            at rx.internal.util.SubscriptionList.unsubscribeFromAll(SubscriptionList.java:124)
            at rx.internal.util.SubscriptionList.unsubscribe(SubscriptionList.java:113)
            at rx.Subscriber.unsubscribe(Subscriber.java:98)
            at rx.internal.util.SubscriptionList.unsubscribeFromAll(SubscriptionList.java:124)
            at rx.internal.util.SubscriptionList.unsubscribe(SubscriptionList.java:113)
            at rx.Subscriber.unsubscribe(Subscriber.java:98)
            at my.project.MyActivity.onPause(MyActivity.java:52)
```

**Comment by festevezga** [comment]
Solved by adding unsubscribeOn(Schedulers.mainThread()) on all api calls, but still.

**Comment by JakeWharton** [comment]
This is an OkHttp bug (of sorts) tracked by https://github.com/square/okhttp/issues/1592. I would advise against using `newThread()`, but something like `computation()` instead.
