### ISSUE TITLE
[Retrofit 2.0] Can't send multipart request

### ISSUE THREAD

**Issue by fuwaneko** [square/retrofit#1055]
It worked with some previous snapshot build, but stopped working in beta1.

```Kotlin
val rb = MultipartBuilder().type(MultipartBuilder.FORM).addFormDataPart("pic", fileName, RequestBody.create(MediaType.parse("image/png"), file)).build()
users.setUserPic(currentUser, rb)

public interface UserAPI {
    POST("somewhere")
    public fun setUserPic(Path("userId") userId: String, Body pic: RequestBody): Observable<Response<ResponseBody>>
}
```

This exception is thrown (I use Jackson):
```Java
java.lang.RuntimeException: com.fasterxml.jackson.databind.JsonMappingException: No serializer found for class com.squareup.okhttp.MultipartBuilder$MultipartRequestBody and no properties discovered to create BeanSerializer (to avoid exception, disable SerializationFeature.FAIL_ON_EMPTY_BEANS) )
            at retrofit.JacksonConverter.toBody(JacksonConverter.java:56)
            at retrofit.RequestBuilderAction$Body.perform(RequestBuilderAction.java:256)
            at retrofit.RequestFactory.create(RequestFactory.java:62)
            at retrofit.OkHttpCall.createRawCall(OkHttpCall.java:116)
            at retrofit.OkHttpCall.enqueue(OkHttpCall.java:56)
            at retrofit.RxJavaCallAdapterFactory$CallOnSubscribe.call(RxJavaCallAdapterFactory.java:103)
            at retrofit.RxJavaCallAdapterFactory$CallOnSubscribe.call(RxJavaCallAdapterFactory.java:85)
```

**Comment by JakeWharton** [comment]
This has already been fixed on master. Please try the latest SNAPSHOT.

**Comment by fuwaneko** [comment]
@JakeWharton thanks, that helped :+1:
