### ISSUE TITLE
JacksonConverterFactory tries to convert @Body RequestBody

### ISSUE THREAD

**Issue by hansenji** [square/retrofit#1068]
When the `JacksonConverterFactory` is used with retrofit it tries to convert `@Body RequestBody` parameters
```
Retrofit retrofit = new Retrofit.Builder()
    .baseUrl("https://baseurl.com/")
    .client(new OkHttpClient())
    .addConverterFactory(JacksonConverterFactory.create(new ObjectMapper()))
    .build();
     return retrofit.create(WebService.class);
```
```
@POST
@Streaming
Call<Foo> sync(@Url String url, @Body RequestBody requestBody);
```
```
java.lang.RuntimeException: com.fasterxml.jackson.databind.JsonMappingException: No serializer found for class com.squareup.okhttp.RequestBody$3 and no properties discovered to create BeanSerializer (to avoid exception, disable SerializationFeature.FAIL_ON_EMPTY_BEANS) )
            at retrofit.JacksonConverter.toBody(JacksonConverter.java:56)
            at retrofit.RequestBuilderAction$Body.perform(RequestBuilderAction.java:256)
            at retrofit.RequestFactory.create(RequestFactory.java:62)
            at retrofit.OkHttpCall.createRawCall(OkHttpCall.java:116)
            at retrofit.OkHttpCall.execute(OkHttpCall.java:106)
            at retrofit.ExecutorCallAdapterFactory$ExecutorCallbackCall.execute(ExecutorCallAdapterFactory.java:59)
```

**Comment by JakeWharton** [comment]
This is fixed on `master` already. You can use the latest 2.0.0-SNAPSHOT for now, I don't have any timeline on when the next beta will be, but perhaps I'll try to squeeze one out this week.
