### ISSUE TITLE
Implicit Call cancels for SPDY/3 & HTTP/2 connections can perform network I/O.

### ISSUE THREAD

**Issue by JakeWharton** [square/retrofit#1069]
```
java.lang.IllegalStateException: Fatal Exception thrown on Scheduler.Worker thread.
            at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:62)
            at android.os.Handler.handleCallback(Handler.java:739)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5254)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
     Caused by: android.os.NetworkOnMainThreadException
            at android.os.StrictMode$AndroidBlockGuardPolicy.onNetwork(StrictMode.java:1147)
            at com.android.org.conscrypt.OpenSSLSocketImpl$SSLOutputStream.write(OpenSSLSocketImpl.java:749)
            at okio.Okio$1.write(Okio.java:80)
            at okio.AsyncTimeout$1.write(AsyncTimeout.java:155)
            at okio.RealBufferedSink.flush(RealBufferedSink.java:221)
            at com.squareup.okhttp.internal.framed.Spdy3$Writer.rstStream(Spdy3.java:382)
            at com.squareup.okhttp.internal.framed.FramedConnection.writeSynReset(FramedConnection.java:356)
            at com.squareup.okhttp.internal.framed.FramedStream.close(FramedStream.java:222)
            at com.squareup.okhttp.internal.http.FramedTransport.disconnect(FramedTransport.java:215)
            at com.squareup.okhttp.internal.http.HttpEngine.disconnect(HttpEngine.java:573)
            at com.squareup.okhttp.Call.cancel(Call.java:122)
            at retrofit.OkHttpCall.cancel(OkHttpCall.java:158)
            at retrofit.RxJavaCallAdapterFactory$CallOnSubscribe$1.call(RxJavaCallAdapterFactory.java:99)
            at rx.subscriptions.BooleanSubscription.unsubscribe(BooleanSubscription.java:72)
            at rx.internal.util.SubscriptionList.unsubscribeFromAll(SubscriptionList.java:124)
            at rx.internal.util.SubscriptionList.unsubscribe(SubscriptionList.java:113)
            at rx.Subscriber.unsubscribe(Subscriber.java:98)
            at rx.internal.util.SubscriptionList.unsubscribeFromAll(SubscriptionList.java:124)
            at rx.internal.util.SubscriptionList.unsubscribe(SubscriptionList.java:113)
            at rx.Subscriber.unsubscribe(Subscriber.java:98)
            at rx.observers.SafeSubscriber.onCompleted(SafeSubscriber.java:90)
            at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.pollQueue(OperatorObserveOn.java:201)
            at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber$2.call(OperatorObserveOn.java:170)
            at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
            at android.os.Handler.handleCallback(Handler.java:739)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5254)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
```
Not really Retrofit's problem, but it also really is. This is a pre-emptive tracking issue.

**Comment by markrietveld** [comment]
It seems like everyone using Retrofit 2 and `RxJavaCallAdapterFactory` will  run into this issue in production. Isn't it worth it to make `call.cancel()` run on a background thread until the issue is addressed in OkHttp?

**Comment by Rainbow888** [comment]
It seems occered on android5.1

**Comment by imminent** [comment]
@markrietveld isn't it backwards to say "in production", thought StrictMode only ran on debug builds

**Comment by markrietveld** [comment]
@imminent the less critical `StrictMode` checks are optional, but the `NetworkOnMainThread` is on and fatal by default, including in production

**Comment by JakeWharton** [comment]
Fixed by https://github.com/square/okhttp/pull/2045 and https://github.com/square/okhttp/pull/2048.
