### ISSUE TITLE
Compile error with @Headers

### ISSUE THREAD

**Issue by ber4444** [square/retrofit#1071]
When I add a `@Headers("Content-Type: application/vnd.ll.events+json")` to my REST interface, I get:
```
Exception in thread "main" java.io.EOFException: End of input at line 1 column 1
	at com.google.gson.stream.JsonReader.nextNonWhitespace(JsonReader.java:1414)
	at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:553)
	at com.google.gson.stream.JsonReader.peek(JsonReader.java:429)
	at com.google.gson.internal.bind.TypeAdapters$13.read(TypeAdapters.java:349)
	at com.google.gson.internal.bind.TypeAdapters$13.read(TypeAdapters.java:346)
	at com.google.gson.TypeAdapter.fromJson(TypeAdapter.java:256)
	at retrofit.GsonResponseBodyConverter.convert(GsonResponseBodyConverter.java:33)
	at retrofit.GsonResponseBodyConverter.convert(GsonResponseBodyConverter.java:23)
	at retrofit.OkHttpCall.parseResponse(OkHttpCall.java:144)
	at retrofit.OkHttpCall.execute(OkHttpCall.java:112)
```
I'm using the SimpleService sample with the 2.x snapshot of Retrofit, talking to our internal service.

When I remove the `@Headers` line (without any further change), everything works, except that the server gives the response:
```
UNSUPPORTED MEDIA TYPE
```

**Comment by JakeWharton** [comment]
Are you sure your server responds appropriately with that header? The
exception indicates that it is returning an empty body.

**Comment by ber4444** [comment]
Yes, it is supposed to return 
`HTTP/1.1 202 Accepted
Content-Length: 0`
so that is an empty body. I'm unable to intercept the network traffic to know more details; so as a detour please see my question here: http://stackoverflow.com/questions/32514410/logging-with-retrofit-2, which in turn will help us debug this problem as well.

**Comment by JakeWharton** [comment]
If there is no body then you can use Void as the type (with master) or if
you're using 2.0.0-beta1 use ResponseBody.

**Comment by ber4444** [comment]
Thanks, Void seems to fix the compile error. But I'm still getting the `UNSUPPORTED MEDIA TYPE` error, probably from the server. Do you mind telling me how to intercept (log) the traffic. See my question:  http://stackoverflow.com/questions/32514410 (using retrofit 'master')

**Comment by JakeWharton** [comment]
You need to attach an interceptor to OkHttp which will give you access to the raw request and response objects. There's an example here: https://github.com/square/retrofit/issues/1072, although don't blindly copy/paste it because it has a bug (hence my comment below it). Logging for v2 is being tracked by #378 .
