### ISSUE TITLE
Problems with Lists on Android 6

### ISSUE THREAD

**Issue by cdreier** [square/retrofit#1075]
Hi,

i have some strange issues on android 6 (nexus 5, build MPA441) with lists...
i thought it is a gson problem, so i already posted something (https://github.com/google/gson/issues/648) but it seems that something is broken, even after upgradeing to retrofit 2 and using the moshi-converter.

Simple POJO with a List of another simple POJO, the response is something like

```
[
    {
        "name": "livingroom",
        "id": "1",
        "switches": [
            {
                "name": "big lamp",
                "id": "1"
            },
            {
                "name": "smaller lamp",
                "id": "2"
            }
        ]
    }
]
```

with a Retrofit Object, initialized with the MoshiConverter, no special adapters;

```
adapter = new Retrofit.Builder().baseUrl(ENDPOINT)
                    .addConverterFactory(MoshiConverterFactory.create()).build();
```

and im getting this stacktrace:

```
    java.lang.IllegalArgumentException: Unable to create converter for java.util.List<net.drailing.home.model.Room>
    for method SynchronisationService.getAll
            at retrofit.Utils.methodError(Utils.java:201)
            at retrofit.MethodHandler.createResponseConverter(MethodHandler.java:67)
            at retrofit.MethodHandler.create(MethodHandler.java:32)
            at retrofit.Retrofit.loadMethodHandler(Retrofit.java:138)
            at retrofit.Retrofit$1.invoke(Retrofit.java:127)
            at java.lang.reflect.Proxy.invoke(Proxy.java:393)
            at $Proxy0.getAll(Unknown Source)
            at net.drailing.home.MainActivity.synchronize(MainActivity.java:71)
            at net.drailing.home.MainActivity.onOptionsItemSelected(MainActivity.java:61)
            at android.app.Activity.onMenuItemSelected(Activity.java:2908)
            at android.support.v4.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:353)
            at android.support.v7.app.AppCompatActivity.onMenuItemSelected(AppCompatActivity.java:144)
            at android.support.v7.internal.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:99)
            at android.support.v7.app.AppCompatDelegateImplV7.onMenuItemSelected(AppCompatDelegateImplV7.java:541)
            at android.support.v7.internal.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:811)
            at android.support.v7.internal.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:153)
            at android.support.v7.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:958)
            at android.support.v7.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:948)
            at android.support.v7.widget.ActionMenuView.invokeItem(ActionMenuView.java:598)
            at android.support.v7.internal.view.menu.ActionMenuItemView.onClick(ActionMenuItemView.java:139)
            at android.view.View.performClick(View.java:5198)
            at android.view.View$PerformClick.run(View.java:21147)
            at android.os.Handler.handleCallback(Handler.java:739)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:148)
            at android.app.ActivityThread.main(ActivityThread.java:5417)
            at java.lang.reflect.Method.invoke(Native Method)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
     Caused by: java.lang.IllegalArgumentException: No JsonAdapter for interface retrofit.CallAdapter$Factory annotated []
            at com.squareup.moshi.Moshi.createAdapter(Moshi.java:93)
            at com.squareup.moshi.Moshi.adapter(Moshi.java:55)
            at com.squareup.moshi.Moshi.adapter(Moshi.java:46)
            at com.squareup.moshi.CollectionJsonAdapter.newArrayListAdapter(CollectionJsonAdapter.java:51)
            at com.squareup.moshi.CollectionJsonAdapter.access$000(CollectionJsonAdapter.java:28)
            at com.squareup.moshi.CollectionJsonAdapter$1.create(CollectionJsonAdapter.java:35)
            at com.squareup.moshi.Moshi.createAdapter(Moshi.java:83)
            at com.squareup.moshi.Moshi.adapter(Moshi.java:55)
            at com.squareup.moshi.ClassJsonAdapter$1.createFieldBindings(ClassJsonAdapter.java:73)
            at com.squareup.moshi.ClassJsonAdapter$1.create(ClassJsonAdapter.java:57)
            at com.squareup.moshi.Moshi.createAdapter(Moshi.java:83)
            at com.squareup.moshi.Moshi.adapter(Moshi.java:55)
            at com.squareup.moshi.ClassJsonAdapter$1.createFieldBindings(ClassJsonAdapter.java:73)
            at com.squareup.moshi.ClassJsonAdapter$1.create(ClassJsonAdapter.java:57)
            at com.squareup.moshi.Moshi.createAdapter(Moshi.java:83)
            at com.squareup.moshi.Moshi.adapter(Moshi.java:55)
            at com.squareup.moshi.ClassJsonAdapter$1.createFieldBindings(ClassJsonAdapter.java:73)
            at com.squareup.moshi.ClassJsonAdapter$1.create(ClassJsonAdapter.java:57)
            at com.squareup.moshi.Moshi.createAdapter(Moshi.java:83)
            at com.squareup.moshi.Moshi.adapter(Moshi.java:55)
            at com.squareup.moshi.Moshi.adapter(Moshi.java:46)
            at com.squareup.moshi.CollectionJsonAdapter.newArrayListAdapter(CollectionJsonAdapter.java:51)
            at com.squareup.moshi.CollectionJsonAdapter.access$000(CollectionJsonAdapter.java:28)
            at com.squareup.moshi.CollectionJsonAdapter$1.create(CollectionJsonAda
```

Any ideas? every help is much appreciated!

edit: if i remove the list from my POJO class, everything is working fine

**Comment by JakeWharton** [comment]
What is the generic type of the list?

**Comment by JakeWharton** [comment]
It looks like you are trying to convert a list of JsonAdapter.Factory to JSON from the exception.

**Comment by cdreier** [comment]
thanks for your fast response!

my POJOs are 

```
public class Room extends BaseEntity implements Serializable {

    public String name;
    public int id;

    public List<Switch> switches;

    [..]
}
```

and the switch

```
public class Switch extends BaseEntity implements Callback<String> {

    public String name;
    public Room room;
    public int id;
	
    [..]
}
```

response i posted above originally what i receive

**Comment by cdreier** [comment]
perhaps something with the BaseEntity (from a small orm), just checking if its working without extending that class

**Comment by cdreier** [comment]
same problem with real plain POJOs :-(

**Comment by baoti** [comment]
Looks like your factory field is not static.

class A {
Adapter.Factory ADAPTER_FACTORY = ...

}

**Comment by cdreier** [comment]
alright, i tested a lot and i think i got it... i had another field in my switch class, just another service to turn the switches on and off. without this service (or set to transient), everything is working fine. 

did not post it above, because i thought fields that are not in the response are just ignored.

```
public class Switch {
    public String name;
    public Room room;
    public int id;

    private SwitchService switchService;
	
	[...]
}
```

i think we can close this issue

**Comment by JakeWharton** [comment]
Ah, that explains the exception trying to serialize a `CallAdapter.Factory` instance then!

**Comment by fushenghua** [comment]
Ah，Why ?Caused by: java.lang.IllegalArgumentException: Could not locate call adapter for class java.lang.String.
                                                                        Tried:
