### ISSUE TITLE
[Retrofit 2.0-beta] Response is received in Interceptor but no RxJava onNext call

### ISSUE THREAD

**Issue by NAYOSO** [square/retrofit#1086]
Hello first of all thanks for this great library!
I'm using Retrofit 1.9.0 and RxAndroid in my master branch without problem and I started migrating to Retrofit 2.0 in my other branch recently. Everything went well from request execution and response (From what I see in OkHttp Interceptor) and I also return the response in intercept method. 

The problem is the Observable I create never pass anything to onNext or onError, even though I added RxJavaCallAdapterFactory to my retrofit object.

``` Java
        OkHttpClient okHttpClient = new OkHttpClient();
        okHttpClient.interceptors().add(new MyInterceptor());

        Retrofit retrofit = new Retrofit.Builder()
                .baseUrl(kamelioEndPoint.getUrl())
                .client(okHttpClient)
                .addConverterFactory(GsonConverterFactory.create(gson))
                .addCallAdapterFactory(RxJavaCallAdapterFactory.create())
                .build();
```

Is this a known issue? 

Thank you.

**Comment by JakeWharton** [comment]
You didn't show any of your code that actually uses Retrofit API implementations

**Comment by NAYOSO** [comment]
Sorry, this is one of the code : 

```Java
MyApplication.getRestClient().getApiService()
                    .userGetMe()
                    .subscribeOn(Schedulers.io()).cache()
                    .compose(this.<User> bindToLifecycle())
                    .subscribe(onGetUserProfile, onError);
```

Where getRestClient() will return singleton object and getApiService will return the API implementation that created by retrofit object based on my interface.

Hope this information can help
Thank you

**Comment by NAYOSO** [comment]
Sorry my fault. there is an error so it's get thrown in onError looks like there is something wrong with the gson. Will try to figure it out.

```
W/System.err: java.lang.IllegalStateException: closed
W/System.err:     at okio.RealBufferedSource.read(RealBufferedSource.java:47)
W/System.err:     at okio.ForwardingSource.read(ForwardingSource.java:35)
W/System.err:     at retrofit.ExceptionCatchingRequestBody$1.read(ExceptionCatchingRequestBody.java:43)
W/System.err:     at okio.RealBufferedSource$1.read(RealBufferedSource.java:371)
W/System.err:     at java.io.InputStreamReader.read(InputStreamReader.java:233)
W/System.err:     at com.google.gson.stream.JsonReader.fillBuffer(JsonReader.java:1300)
W/System.err:     at com.google.gson.stream.JsonReader.nextNonWhitespace(JsonReader.java:1346)
W/System.err:     at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:553)
W/System.err:     at com.google.gson.stream.JsonReader.peek(JsonReader.java:429)
W/System.err:     at com.google.gson.TypeAdapter$1.read(TypeAdapter.java:195)
W/System.err:     at com.google.gson.TypeAdapter.fromJson(TypeAdapter.java:256)
W/System.err:     at retrofit.GsonConverter.fromBody(GsonConverter.java:42)
W/System.err:     at retrofit.OkHttpCall.parseResponse(OkHttpCall.java:144)
W/System.err:     at retrofit.OkHttpCall.access$000(OkHttpCall.java:25)
W/System.err:     at retrofit.OkHttpCall$1.onResponse(OkHttpCall.java:90)
W/System.err:     at com.squareup.okhttp.Call$AsyncCall.execute(Call.java:168)
W/System.err:     at com.squareup.okhttp.internal.NamedRunnable.run(NamedRunnable.java:33)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
W/System.err:     at java.lang.Thread.run(Thread.java:818)
```

**Comment by NAYOSO** [comment]
OK I know what my mistake now.
I tried to replicate your logging system in my Interceptor (OkHttpInterceptor) with printing request detail and response detail including the response body by calling response.body().string() which will consume the source byte array and made the response body disappear.
