### ISSUE TITLE
SocketTimeoutException: timeout since latest snapshot

### ISSUE THREAD

**Issue by guiwro** [square/retrofit#1100]
Since latest snapshot (Sat Sep 19 20:41:04 UTC 2015), I keep having this error, for every request, onFailure is called and here's the stacktrace. It seems to be related with OkHttp but it's still 2.5.0 version, only Retrofit has changed.

```java
java.net.SocketTimeoutException: timeout
     at okio.Okio$3.newTimeoutException(Okio.java:207)
     at okio.AsyncTimeout.exit(AsyncTimeout.java:250)
     at okio.AsyncTimeout$2.read(AsyncTimeout.java:217)
     at okio.RealBufferedSource.indexOf(RealBufferedSource.java:306)
     at okio.RealBufferedSource.indexOf(RealBufferedSource.java:300)
     at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:196)
     at com.squareup.okhttp.internal.http.HttpConnection.readResponse(HttpConnection.java:191)
     at com.squareup.okhttp.internal.http.HttpTransport.readResponseHeaders(HttpTransport.java:80)
     at com.squareup.okhttp.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:906)
     at com.squareup.okhttp.internal.http.HttpEngine.access$300(HttpEngine.java:92)
     at com.squareup.okhttp.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:891)
     at com.squareup.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:749)
     at com.squareup.okhttp.Call.getResponse(Call.java:268)
     at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:224)
     at com.squareup.okhttp.Call.getResponseWithInterceptorChain(Call.java:195)
     at com.squareup.okhttp.Call.access$100(Call.java:34)
     at com.squareup.okhttp.Call$AsyncCall.execute(Call.java:162)
     at com.squareup.okhttp.internal.NamedRunnable.run(NamedRunnable.java:33)
     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
     at java.lang.Thread.run(Thread.java:818)
```

edit: update snapshot version

**Comment by guiwro** [comment]
Well... my server is down, that might be the reason. Sorry.

**Comment by JakeWharton** [comment]
That'll do it :grinning:

**Comment by guiwro** [comment]
It's not entirely my fault: https://status.heroku.com/incidents/811

**Comment by ZeroBrain** [comment]
it was occurred me.
the problem is that it cannot catch exception ```try-catch```

i dont know why. but it did'nt include RetrofitError.
