### ISSUE TITLE
200 Empty body fails (retrofit:2.0.0)

### ISSUE THREAD

**Issue by JonathonFry** [square/retrofit#1105]
Hi,

Noticed an issue when receiving a 200 response with an empty body.

Using the jackson-converter.

```
com.fasterxml.jackson.databind.JsonMappingException: No content to map due to end-of-input
 at [Source: java.io.InputStreamReader@2fc6f97f; line: 1, column: 1]
	at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:148)
	at com.fasterxml.jackson.databind.ObjectReader._initForReading(ObjectReader.java:381)
	at com.fasterxml.jackson.databind.ObjectReader._bindAndClose(ObjectReader.java:1494)
	at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:1119)
	at retrofit.JacksonResponseBodyConverter.convert(JacksonResponseBodyConverter.java:33)
	at retrofit.JacksonResponseBodyConverter.convert(JacksonResponseBodyConverter.java:23)
	at retrofit.OkHttpCall.parseResponse(OkHttpCall.java:144)
	at retrofit.OkHttpCall.execute(OkHttpCall.java:112)
	at retrofit.ExecutorCallAdapterFactory$ExecutorCallbackCall.execute(ExecutorCallAdapterFactory.java:60)
```

However this call works correctly if the response has status code 204 or 205.

Is there any way around this?

Cheers

**Comment by JakeWharton** [comment]
Use Void as the response body type. Empty is not valid JSON.

**Comment by JakeWharton** [comment]
Requires the latest snapshot.

**Comment by JonathonFry** [comment]
Okay, thanks!

**Comment by gurappa** [comment]
Hi @JakeWharton,

Void did not work for me either. But ResponseBody worked.

One more issue is that when my request returns 404 NOT FOUND, retrofit called onSuccess() of callback. It's the same result when I used Void, ResponseBody and JSONObject in Callback.

Could you please elaborate on how it works so that we will have a single code for all cases empty/success, empty/failure, body/success and body/failure ? Or any link to doc ?

Thanks,
Guru

**Comment by gurappa** [comment]
With retrofit beta2, it works fine with Void for me too.
Pleaseclose this here as I got to understand the stuff now with beta2.

Thanks,
Guru

**Comment by ivashov** [comment]
But how can i create Void instance in retrofit-mock?

**Comment by swankjesse** [comment]
@ivashov null will work.

**Comment by ivashov** [comment]
thx, this code crashes with RuntimeException
```
return Calls.response(null, retrofit);
```

But this works 
```
return Calls.response(Response.success((Void) null), retrofit);
```

**Comment by JakeWharton** [comment]
With what exception?

**Comment by ivashov** [comment]
```
 E/AndroidRuntime:  Caused by: java.lang.RuntimeException
 E/AndroidRuntime:     at retrofit.mock.BehaviorCall.execute(BehaviorCall.java:152)
```

**Comment by JakeWharton** [comment]
The whole trace

**Comment by ivashov** [comment]
Whole trace
```
10-25 01:04:26.549 17531-17531/com.github.ivashov.voidretrofit D/MainActivity: deleteCrash() called
10-25 01:04:29.139 17531-17531/com.github.ivashov.voidretrofit D/AndroidRuntime: Shutting down VM
10-25 01:04:29.139 17531-17531/com.github.ivashov.voidretrofit W/dalvikvm: threadid=1: thread exiting with uncaught exception (group=0x41570d88)
10-25 01:04:29.139 17531-17531/com.github.ivashov.voidretrofit E/test: Exception
10-25 01:04:29.169 17531-17531/com.github.ivashov.voidretrofit E/AndroidRuntime: FATAL EXCEPTION: main
10-25 01:04:29.169 17531-17531/com.github.ivashov.voidretrofit E/AndroidRuntime: Process: com.github.ivashov.voidretrofit, PID: 17531
10-25 01:04:29.169 17531-17531/com.github.ivashov.voidretrofit E/AndroidRuntime: java.lang.IllegalStateException: Could not execute method for android:onClick
10-25 01:04:29.169 17531-17531/com.github.ivashov.voidretrofit E/AndroidRuntime:     at android.support.v7.internal.app.AppCompatViewInflater$DeclaredOnClickListener.onClick(AppCompatViewInflater.java:278)
10-25 01:04:29.169 17531-17531/com.github.ivashov.voidretrofit E/AndroidRuntime:     at android.view.View.performClick(View.java:4584)
10-25 01:04:29.169 17531-17531/com.github.ivashov.voidretrofit E/AndroidRuntime:     at android.view.View$PerformClick.run(View.java:18568)
10-25 01:04:29.169 17531-17531/com.github.ivashov.voidretrofit E/AndroidRuntime:     at android.os.Handler.handleCallback(Handler.java:733)
10-25 01:04:29.169 17531-17531/com.github.ivashov.voidretrofit E/AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java:95)
10-25 01:04:29.169 17531-17531/com.github.ivashov.voidretrofit E/AndroidRuntime:     at android.os.Looper.loop(Looper.java:136)
10-25 01:04:29.169 17531-17531/com.github.ivashov.voidretrofit E/AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:5214)
10-25 01:04:29.169 17531-17531/com.github.ivashov.voidretrofit E/AndroidRuntime:     at java.lang.reflect.Method.invokeNative(Native Method)
10-25 01:04:29.169 17531-17531/com.github.ivashov.voidretrofit E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Method.java:515)
10-25 01:04:29.169 17531-17531/com.github.ivashov.voidretrofit E/AndroidRuntime:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:814)
10-25 01:04:29.169 17531-17531/com.github.ivashov.voidretrofit E/AndroidRuntime:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:630)
10-25 01:04:29.169 17531-17531/com.github.ivashov.voidretrofit E/AndroidRuntime:     at dalvik.system.NativeStart.main(Native Method)
10-25 01:04:29.169 17531-17531/com.github.ivashov.voidretrofit E/AndroidRuntime:  Caused by: java.lang.reflect.InvocationTargetException
10-25 01:04:29.169 17531-17531/com.github.ivashov.voidretrofit E/AndroidRuntime:     at java.lang.reflect.Method.invokeNative(Native Method)
10-25 01:04:29.169 17531-17531/com.github.ivashov.voidretrofit E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Method.java:515)
10-25 01:04:29.169 17531-17531/com.github.ivashov.voidretrofit E/AndroidRuntime:     at android.support.v7.internal.app.AppCompatViewInflater$DeclaredOnClickListener.onClick(AppCompatViewInflater.java:273)
10-25 01:04:29.169 17531-17531/com.github.ivashov.voidretrofit E/AndroidRuntime:     at android.view.View.performClick(View.java:4584) 
10-25 01:04:29.169 17531-17531/com.github.ivashov.voidretrofit E/AndroidRuntime:     at android.view.View$PerformClick.run(View.java:18568) 
10-25 01:04:29.169 17531-17531/com.github.ivashov.voidretrofit E/AndroidRuntime:     at android.os.Handler.handleCallback(Handler.java:733) 
10-25 01:04:29.169 17531-17531/com.github.ivashov.voidretrofit E/AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java:95) 
10-25 01:04:29.169 17531-17531/com.github.ivashov.voidretrofit E/AndroidRuntime:     at android.os.Looper.loop(Looper.java:136) 
10-25 01:04:29.169 17531-17531/com.github.ivashov.voidretrofit E/AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:5214) 
10-25 01:04:29.169 17531-17531/com.github.ivashov.voidretrofit E/AndroidRuntime:     at java.lang.reflect.Method.invokeNative(Native Method) 
10-25 01:04:29.169 17531-17531/com.github.ivashov.voidretrofit E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Method.java:515) 
10-25 01:04:29.169 17531-17531/com.github.ivashov.voidretrofit E/AndroidRuntime:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:814) 
10-25 01:04:29.169 17531-17531/com.github.ivashov.voidretrofit E/AndroidRuntime:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:630) 
10-25 01:04:29.169 17531-17531/com.github.ivashov.voidretrofit E/AndroidRuntime:     at dalvik.system.NativeStart.main(Native Method) 
10-25 01:04:29.169 17531-17531/com.github.ivashov.voidretrofit E/AndroidRuntime:  Caused by: java.lang.RuntimeException
10-25 01:04:29.169 17531-17531/com.github.ivashov.voidretrofit E/AndroidRuntime:     at retrofit.mock.BehaviorCall.execute(BehaviorCall.java:152)
10-25 01:04:29.169 17531-17531/com.github.ivashov.voidretrofit E/AndroidRuntime:     at com.github.ivashov.voidretrofit.MainActivity.onCrashButton(MainActivity.java:64)
10-25 01:04:29.169 17531-17531/com.github.ivashov.voidretrofit E/AndroidRuntime:     at java.lang.reflect.Method.invokeNative(Native Method) 
10-25 01:04:29.169 17531-17531/com.github.ivashov.voidretrofit E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Method.java:515) 
10-25 01:04:29.169 17531-17531/com.github.ivashov.voidretrofit E/AndroidRuntime:     at android.support.v7.internal.app.AppCompatViewInflater$DeclaredOnClickListener.onClick(AppCompatViewInflater.java:273) 
10-25 01:04:29.169 17531-17531/com.github.ivashov.voidretrofit E/AndroidRuntime:     at android.view.View.performClick(View.java:4584) 
10-25 01:04:29.169 17531-17531/com.github.ivashov.voidretrofit E/AndroidRuntime:     at android.view.View$PerformClick.run(View.java:18568) 
10-25 01:04:29.169 17531-17531/com.github.ivashov.voidretrofit E/AndroidRuntime:     at android.os.Handler.handleCallback(Handler.java:733) 
10-25 01:04:29.169 17531-17531/com.github.ivashov.voidretrofit E/AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java:95) 
10-25 01:04:29.169 17531-17531/com.github.ivashov.voidretrofit E/AndroidRuntime:     at android.os.Looper.loop(Looper.java:136) 
10-25 01:04:29.169 17531-17531/com.github.ivashov.voidretrofit E/AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:5214) 
10-25 01:04:29.169 17531-17531/com.github.ivashov.voidretrofit E/AndroidRuntime:     at java.lang.reflect.Method.invokeNative(Native Method) 
10-25 01:04:29.169 17531-17531/com.github.ivashov.voidretrofit E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Method.java:515) 
10-25 01:04:29.169 17531-17531/com.github.ivashov.voidretrofit E/AndroidRuntime:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:814) 
10-25 01:04:29.169 17531-17531/com.github.ivashov.voidretrofit E/AndroidRuntime:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:630) 
10-25 01:04:29.169 17531-17531/com.github.ivashov.voidretrofit E/AndroidRuntime:     at dalvik.system.NativeStart.main(Native Method)
```

Whole project
https://github.com/ivashov/retrofit-void-call

**Comment by JakeWharton** [comment]
Thanks. I'll take a look soon.

**Comment by akmalazlanjamal** [comment]
Hi, how to handle an API that return empty response if response is success and return a response "Error":"SessionKeyExpired" when response is failed. Both are successful API call scenario. I try to use Void but that would cause no way to handle the "Error". Thank you.

Sorry for bring up last year's thread.

**Comment by JCarlosR** [comment]
@azlanjamal Did you find a good solution for this scenario?
