### ISSUE TITLE
Unable to find Responce every time

### ISSUE THREAD

**Issue by shailesh242121** [square/retrofit#1238]
Hi 
I am using Retrofit 2.0.
Using a service on post method

it cause some time issue 
 java.io.EOFException
    at libcore.io.Streams.readAsciiLine(Streams.java:203)
    at libcore.net.http.HttpEngine.readResponseHeaders(HttpEngine.java:560)
     at libcore.net.http.HttpEngine.readResponse(HttpEngine.java:813)
     at libcore.net.http.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:274)
     at libcore.net.http.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:486)
     at retrofit.client.UrlConnectionClient.readResponse(UrlConnectionClient.java:73)
     at retrofit.client.UrlConnectionClient.execute(UrlConnectionClient.java:38)
     at retrofit.RestAdapter$RestHandler.invokeRequest(RestAdapter.java:326)
     at retrofit.RestAdapter$RestHandler.access$100(RestAdapter.java:220)
     at retrofit.RestAdapter$RestHandler$2.obtainResponse(RestAdapter.java:278)
     at retrofit.CallbackRunnable.run(CallbackRunnable.java:42)
     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
     at retrofit.Platform$Android$2$1.run(Platform.java:142)
    at java.lang.Thread.run(Thread.java:856)
END ERROR

PS I doesn't occurs each time. but after 4 or 5 successfull hits it occurs.

Is their any solution for this

**Comment by JakeWharton** [comment]
That stack trace indicates you are not using Retrofit 2. But no, that's a
platform bug in Android's HttpURLConnection and there's nothing Retrofit
can do to fix it. You can add OkHttp to your project for a more up-to-date
HTTP client that will not exhibit this bug. Retrofit will see OkHttp was
added and use it automatically.
