### ISSUE TITLE
SocketTimeoutException and ConnectException being thrown randomly

### ISSUE THREAD

**Issue by droidmonkey** [square/retrofit#1257]
I am experiencing this issue with the latest maven published Beta2. It is a serious concern because Retrofit should be swallowing these exceptions and taking care of them by issuing a failed response as a result with the reason decoded into a standard string (perhaps).

This is not a triggerable bug as it happens randomly and does not seem to have anything to do with connection status or method. There is nothing special about my code, its literally as simple as your homepage sample code.

Obligatory stack trace:
```
 Process: com.droidmonkey.moveblue, PID: 10315
 java.lang.reflect.InvocationTargetException
     at java.lang.reflect.Method.invoke(Native Method)
     at java.lang.reflect.Method.invoke(Method.java:372)
     at com.arasthel.swissknife.SwissKnife$12.run(SwissKnife.groovy:491)
     at java.lang.Thread.run(Thread.java:818)
  Caused by: java.net.ConnectException: failed to connect to mbus.doublemap.com/54.152.32.182 (port 80) after 10000ms: isConnected failed: EHOSTUNREACH (No route to host)
     at libcore.io.IoBridge.isConnected(IoBridge.java:238)
     at libcore.io.IoBridge.connectErrno(IoBridge.java:171)
     at libcore.io.IoBridge.connect(IoBridge.java:122)
     at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:183)
     at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:456)
     at java.net.Socket.connect(Socket.java:886)
     at com.squareup.okhttp.internal.Platform$Android.connectSocket(Platform.java:190)
     at com.squareup.okhttp.Connection.connectSocket(Connection.java:196)
     at com.squareup.okhttp.Connection.connect(Connection.java:172)
     at com.squareup.okhttp.Connection.connectAndSetOwner(Connection.java:367)
     at com.squareup.okhttp.OkHttpClient$1.connectAndSetOwner(OkHttpClient.java:128)
     at com.squareup.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:328)
     at com.squareup.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:245)
     at com.squareup.okhttp.Call.getResponse(Call.java:267)
     at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:224)
     at com.squareup.okhttp.Call.getResponseWithInterceptorChain(Call.java:195)
     at com.squareup.okhttp.Call.execute(Call.java:79)
     at retrofit.OkHttpCall.execute(OkHttpCall.java:116)
     at retrofit.ExecutorCallAdapterFactory$ExecutorCallbackCall.execute(ExecutorCallAdapterFactory.java:61)
     at java.lang.reflect.Method.invoke(Native Method)
     at java.lang.reflect.Method.invoke(Method.java:372)
     at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoCachedMethodSiteNoUnwrapNoCoerce.invoke(PojoMetaMethodSite.java:230)
     at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.call(PojoMetaMethodSite.java:53)
     at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
     at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:110)
     at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:114)
     at com.droidmonkey.moveblue.FeedLoader.performUpdate$background(FeedLoader.groovy:75)
     at java.lang.reflect.Method.invoke(Native Method) 
     at java.lang.reflect.Method.invoke(Method.java:372) 
     at com.arasthel.swissknife.SwissKnife$12.run(SwissKnife.groovy:491) 
     at java.lang.Thread.run(Thread.java:818) 
  Caused by: android.system.ErrnoException: isConnected failed: EHOSTUNREACH (No route to host)
     at libcore.io.IoBridge.isConnected(IoBridge.java:223)
     at libcore.io.IoBridge.connectErrno(IoBridge.java:171) 
     at libcore.io.IoBridge.connect(IoBridge.java:122) 
     at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:183) 
     at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:456) 
     at java.net.Socket.connect(Socket.java:886) 
     at com.squareup.okhttp.internal.Platform$Android.connectSocket(Platform.java:190) 
     at com.squareup.okhttp.Connection.connectSocket(Connection.java:196) 
     at com.squareup.okhttp.Connection.connect(Connection.java:172) 
     at com.squareup.okhttp.Connection.connectAndSetOwner(Connection.java:367) 
     at com.squareup.okhttp.OkHttpClient$1.connectAndSetOwner(OkHttpClient.java:128) 
     at com.squareup.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:328) 
     at com.squareup.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:245) 
     at com.squareup.okhttp.Call.getResponse(Call.java:267) 
     at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:224) 
     at com.squareup.okhttp.Call.getResponseWithInterceptorChain(Call.java:195) 
     at com.squareup.okhttp.Call.execute(Call.java:79) 
     at retrofit.OkHttpCall.execute(OkHttpCall.java:116) 
     at retrofit.ExecutorCallAdapterFactory$ExecutorCallbackCall.execute(ExecutorCallAdapterFactory.java:61) 
     at java.lang.reflect.Method.invoke(Native Method) 
     at java.lang.reflect.Method.invoke(Method.java:372) 
     at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoCachedMethodSiteNoUnwrapNoCoerce.invoke(PojoMetaMethodSite.java:230) 
     at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.call(PojoMetaMethodSite.java:53) 
     at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45) 
     at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:110) 
     at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:114) 
     at com.droidmonkey.moveblue.FeedLoader.performUpdate$background(FeedLoader.groovy:75) 
     at java.lang.reflect.Method.invoke(Native Method) 
     at java.lang.reflect.Method.invoke(Method.java:372) 
     at com.arasthel.swissknife.SwissKnife$12.run(SwissKnife.groovy:491) 
     at java.lang.Thread.run(Thread.java:818) 
```

**Comment by JakeWharton** [comment]
This is standard exception when a host is unreachable. Mobile networks are flaky, and sometimes they fail in the middle of a request because they're chaging networks or over to Wi-Fi. This is just something you have to handle.

`ConnectException` is a `SocketException` which is an `IOException` and these will inevitably happen and need to be handled. An `IOException` is a failure of the transport and you need to implement code which handles this case.

> Retrofit should be swallowing these exceptions

No. This would be terrible behavior to implement.

**Comment by droidmonkey** [comment]
Thanks for the explanation, wasn't aware these were all IOExceptions.... might be nice to mention this in the documentation when using the .execute() method (i.e., wrap it with try/catch in the event these occur).

**Comment by JakeWharton** [comment]
IOException is checked so you are forced to use a try/catch in order to
call the method.

**Comment by Diego-Franco** [comment]
@droidmonkey do you found how to handle this? i'm on the same point for a special response, but i don't know where is the try/catch ??
