### ISSUE TITLE
Add AdapterFactory functionality to MockRetrofit

### ISSUE THREAD

**Issue by Tolsi** [square/retrofit#1286]
I think what it needed to pass CallAdapterFactory to MockRetrofit or create ObservableBehaviorAdapter. If I use MockRetrofit, created with Retrofit with RxJavaCallAdapterFactory, then I get the ClassCastException:

```
java.lang.ClassCastException: rx.Observable cannot be cast to retrofit.Call
at retrofit.mock.CallBehaviorAdapter.applyBehavior(CallBehaviorAdapter.java:22)
at retrofit.mock.MockRetrofit$1.invoke(MockRetrofit.java:44)
at $Proxy1.setInviteAcceptionStatus(Native Method)
...
```

My code

```
(from dagger module)
    @Provides
    @Singleton
    Retrofit provideRetrofit() {
        Retrofit retrofit = new Retrofit.Builder()
                .baseUrl("http://OLOLO")
                .addCallAdapterFactory(RxJavaCallAdapterFactory.create())
                .build();
        return retrofit;
    }

    @Provides
    @Singleton
    ServerApi provideServerApi(Retrofit retrofit) {
        NetworkBehavior behavior = NetworkBehavior.create();
        behavior.setFailurePercent(10);
        behavior.setVariancePercent(30);
        behavior.setDelay(3, TimeUnit.SECONDS);
        MockRetrofit mockRetrofit = new MockRetrofit(behavior, new CallBehaviorAdapter(retrofit, Executors.newSingleThreadExecutor()));
        return mockRetrofit.create(ServerApi.class, new MockServerApi());
    }

...
(my api interface)
public interface ServerApi {
    @GET("/test")
    Observable<Object>           test();
}
```

**Comment by JakeWharton** [comment]
Yeah, having two completely separate systems for the same thing is dumb on my part. I'd like to figure out how to combine the two. That may mean folding the 'mock' behavior into the core of the library though.

**Comment by Tolsi** [comment]
Thank you!
