### ISSUE TITLE
OkHttp Dispatcher Process: not valid as a java.net.URI

### ISSUE THREAD

**Issue by brucetoo** [square/retrofit#1348]
I recently meet this error, [OKHttp #1962](https://github.com/square/okhttp/issues/1962) says this has been sovled, but happened again
Here My interface:
```java

   @POST("api/someaction")
    Call<SellerDetail> getSellerShowMessage(@Query("requestJson") String requestJson);

```

And the URL is just a Json string

```groovy
    compile 'com.squareup.retrofit:retrofit:2.0.0-beta2'
    compile 'com.squareup.retrofit:converter-gson:2.0.0-beta2'
```
I use the newest version,still has this error, please help me!
The final output:
```java

12-08 11:42:50.026 8358-23225/com.do1.flowersapp E/AndroidRuntime: FATAL EXCEPTION: OkHttp Dispatcher
                                                                   Process: com.do1.flowersapp, PID: 8358
                                                                   java.lang.IllegalStateException: not valid as a java.net.URI: http://113.240.224.196:9998/flower/portal/indexDisplayAction!displayInfo.action?requestJson={%22displayLoc%22:%22KaGqR43k6cQ%3D%22,%22orgId%22:%2237qWWgTWcVH8vqN7SkNVyewVMpu78dB2MALJVp7de%2BnQQuzYe3utqg%3D%3D%22,%22digest%22:%22567f089f54b5133db7ee7458dbc00f2d%22}
                                                                       at com.squareup.okhttp.HttpUrl.uri(HttpUrl.java:336)
                                                                       at com.squareup.okhttp.internal.http.RouteSelector.resetNextProxy(RouteSelector.java:135)
                                                                       at com.squareup.okhttp.internal.http.RouteSelector.<init>(RouteSelector.java:71)
                                                                       at com.squareup.okhttp.internal.http.RouteSelector.get(RouteSelector.java:76)
                                                                       at com.squareup.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:321)
                                                                       at com.squareup.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:245)
                                                                       at com.squareup.okhttp.Call.getResponse(Call.java:267)
                                                                       at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:224)
                                                                       at com.squareup.okhttp.Call.getResponseWithInterceptorChain(Call.java:195)
                                                                       at com.squareup.okhttp.Call.access$100(Call.java:34)
                                                                       at com.squareup.okhttp.Call$AsyncCall.execute(Call.java:162)
                                                                       at com.squareup.okhttp.internal.NamedRunnable.run(NamedRunnable.java:33)
                                                                       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                       at java.lang.Thread.run(Thread.java:818)

```

**Comment by JakeWharton** [comment]
Are you using the latest OkHttp?

**Comment by JakeWharton** [comment]
More specifically: this is not a Retrofit bug. Make sure you are using OkHttp 2.6.0, and if you still experience a problem try OkHttp 2.7.0-SNAPSHOT (details in OkHttp's README), and if you _still_ get an exception, file an issue on OkHttp's GitHub issues list.

**Comment by brucetoo** [comment]
Hmmm.I just notice Retrofit2 use okHttp-2.5.0 by default

**Comment by JakeWharton** [comment]
It will use 2.7 when 2.7 is released. You can specify an explicitly dependency on 2.6.0 for now.

**Comment by arlindiDev** [comment]
How can I specify Retrofit to use okHttp version 2.6.0

**Comment by JakeWharton** [comment]
Add an explicit dependency to OkHttp in your build system.

**Comment by arlindiDev** [comment]
Thank you, I resovled the issue.

**Comment by nks2180** [comment]
@JakeWharton We are still getting same exception for okHTTP library for text in URL
**I m szugpdoc fdkzhv jhidogkdo fjgjskgkx hkhhLgduf xjgdjglf jfldhdl#7 #(/8&(#8^ #(^$$/($bzjgp sjfdjfglf sjkdigl kfkglgh**

One of our user typed this and same exception arised.

We are using 'com.squareup.retrofit:retrofit:2.0.0-beta4' and  'com.squareup.okhttp3:okhttp:3.1.2'.
