### ISSUE TITLE
NoClassDefFoundError when creating new Retrofit.Builder

### ISSUE THREAD

**Issue by dgngulcan** [square/retrofit#1352]
I was developing on a device which runs Lollipop(API22), and tried to run on a device which runs Kitkat(API19) even though it does build without errors, when I run it on Kitkat device, it causes the following exception
```java
12-08 14:16:35.006 15395-15395/com.mobilion.avciavlak E/AndroidRuntime: FATAL EXCEPTION: main
                                                                        Process: com.mobilion.avciavlak, PID: 15395
                                                                        java.lang.NoClassDefFoundError: retrofit.Retrofit$Builder
                                                                            at com.mobilion.avciavlak.helpers.RestApiHelper.getRetrofitBuilder(RestApiHelper.java:22)
                                                                            at com.mobilion.avciavlak.ui.activities.LoginActivity.onCreate(LoginActivity.java:60)
                                                                            at android.app.Activity.performCreate(Activity.java:5411)
                                                                            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
                                                                            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2270)
                                                                            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2396)
                                                                            at android.app.ActivityThread.access$800(ActivityThread.java:139)
                                                                            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1293)
                                                                            at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                            at android.os.Looper.loop(Looper.java:149)
                                                                            at android.app.ActivityThread.main(ActivityThread.java:5257)
                                                                            at java.lang.reflect.Method.invokeNative(Native Method)
                                                                            at java.lang.reflect.Method.invoke(Method.java:515)
                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:609)
                                                                            at dalvik.system.NativeStart.main(Native Method)
```
### Block that causes exception
```java
new Retrofit.Builder()
                .baseUrl("http://www.mobilion.com.tr/")
                .addConverterFactory(GsonConverterFactory.create())
                .build();
```

### Gradle file
```
android {
    compileSdkVersion 23
    buildToolsVersion "23.0.2"
    packagingOptions {
        exclude 'META-INF/services/javax.annotation.processing.Processor'
        exclude 'META-INF/LICENSE.txt'
        exclude 'META-INF/NOTICE.txt'
    }
    defaultConfig {
        applicationId "com.mobilion.avciavlak"
        minSdkVersion 16
        targetSdkVersion 23
        versionCode 1
        versionName "1.0.0"
        multiDexEnabled true
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}
dependencies {
...
  compile 'com.squareup.retrofit:retrofit:2.0.0-beta2'
   compile 'com.squareup.retrofit:converter-gson:2.0.0-beta2'
...
}
```

**Comment by artem-zinnatullin** [comment]
Please check your multidex configuration and make sure you're correctly initializing MultiDex with support-multidex library.

**Comment by dgngulcan** [comment]
Yep! Thank you @artem-zinnatullin !!
Problem solved by extending my .application to multidexapplication :)

**Comment by artem-zinnatullin** [comment]
:+1: np

**Comment by Kml55** [comment]
I lost 1 plus half day. Then came to this post and tried to replace extends Application  with extends MultidexApplication . it worked.

Thanks for your solution!

**Comment by SayedMasihullah** [comment]
Please tell me how to extends Application with MultidexApplication .Where can I find that Application file? I am trying three days constantly to resolve similar error........:-(

**Comment by dgngulcan** [comment]
@SayedMasihullah after changing the gradle file with multidex dependency,  just create a class and extend it from MultidexApplication
`public class MyApplication extends MultidexApplication{
   ...
}`

and then add it to your application in manifest file as
`<application ...
 android:name="MyApplication">`

You can learn more at http://developer.android.com/tools/building/multidex.html
