### ISSUE TITLE
Pipe character not URL encoded in @Query parameter with GET requests

### ISSUE THREAD

**Issue by vnesek** [square/retrofit#1356]
If you pass a string with '|' (pipe) character to @Query parameter of service method it is not correctly URL encoded and you end up with 'not valid as a java.net.URI' exception:

```java
@GET void test(@Query String x);

service.test("Blow a ||");
```

```
Caused by: java.lang.IllegalStateException: not valid as a java.net.URI: http://xxxx/test?x=Blow+a+||
	at com.squareup.okhttp.HttpUrl.uri(HttpUrl.java:336) ~[okhttp-2.5.0.jar:na]
	at com.squareup.okhttp.internal.http.RouteSelector.resetNextProxy(RouteSelector.java:135) ~[okhttp-2.5.0.jar:na]
	at com.squareup.okhttp.internal.http.RouteSelector.<init>(RouteSelector.java:71) ~[okhttp-2.5.0.jar:na]
	at com.squareup.okhttp.internal.http.RouteSelector.get(RouteSelector.java:76) ~[okhttp-2.5.0.jar:na]
	at com.squareup.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:321) ~[okhttp-2.5.0.jar:na]
	at com.squareup.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:245) ~[okhttp-2.5.0.jar:na]
	at com.squareup.okhttp.Call.getResponse(Call.java:267) ~[okhttp-2.5.0.jar:na]
	at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:224) ~[okhttp-2.5.0.jar:na]
	at net.instantcom.rme.client.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.java:199) ~[classes:na]
	at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:221) ~[okhttp-2.5.0.jar:na]
	at com.squareup.okhttp.Call.getResponseWithInterceptorChain(Call.java:195) ~[okhttp-2.5.0.jar:na]
	at com.squareup.okhttp.Call.execute(Call.java:79) ~[okhttp-2.5.0.jar:na]
	at retrofit.OkHttpCall.execute(OkHttpCall.java:116) ~[retrofit-2.0.0-beta2.jar:na]
```

**Comment by siddharth96** [comment]
Did you try OkHttp 2.6.0? It got fixed as per this [issue](https://github.com/square/okhttp/issues/1872).

**Comment by vnesek** [comment]
Didn't try... OkHttp 2.5.0 is dep in retrofit's maven.pom and we only use it for retrofit so I didn't try to upgrade it in our project. Will try and get back here.
