### ISSUE TITLE
How to request a html page

### ISSUE THREAD

**Issue by jifaxu** [square/retrofit#1365]
I want to get a html by retorfit
```
@GET("/kjread/{folder}/{file}")
    Observable<List<Book>>getboolist(
            @Path("folder")String folder,
            @Path("file") String filename
    );
```
and
```
private static Retrofit.Builder kjbuilder=new Retrofit.Builder()
            .baseUrl(ConstantValue.URL_KJ)
            .addCallAdapterFactory(RxJavaCallAdapterFactory.create());
    
    public static <S>S createServiceKj(Class<S>c){
        return kjbuilder.build().create(c);
    }
```
But when I run it error happend
```
java.lang.RuntimeException: Unable to start activity ComponentInfo{hust.xujifa.kjread/hust.xujifa.kjread.activity.MainActivity}: java.lang.IllegalArgumentException: Unable to create converter for class java.lang.String
                                                                        for method KJApi.search
                                                                        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2325)
                                                                        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2390)
                                                                        at android.app.ActivityThread.access$800(ActivityThread.java:151)
                                                                        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
                                                                        at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                        at android.os.Looper.loop(Looper.java:135)
                                                                        at android.app.ActivityThread.main(ActivityThread.java:5257)
                                                                        at java.lang.reflect.Method.invoke(Native Method)
                                                                        at java.lang.reflect.Method.invoke(Method.java:372)
                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
                                                                     Caused by: java.lang.IllegalArgumentException: Unable to create converter for class java.lang.String
                                                                        for method KJApi.search
                                                                        at retrofit.Utils.methodError(Utils.java:177)
                                                                        at retrofit.MethodHandler.createResponseConverter(MethodHandler.java:57)
                                                                        at retrofit.MethodHandler.create(MethodHandler.java:29)
                                                                        at retrofit.Retrofit.loadMethodHandler(Retrofit.java:151)
                                                                        at retrofit.Retrofit$1.invoke(Retrofit.java:132)
                                                                        at java.lang.reflect.Proxy.invoke(Proxy.java:397)
                                                                        at $Proxy1.search(Unknown Source)
                                                                        at hust.xujifa.kjread.activity.MainActivity.onCreate(MainActivity.java:85)
                                                                        at android.app.Activity.performCreate(Activity.java:5990)
                                                                        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
                                                                        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2278)
                                                                        	... 10 more
                                                                     Caused by: java.lang.IllegalArgumentException: Could not locate ResponseBody converter for class java.lang.String. Tried:
                                                                     * retrofit.BuiltInConverters
                                                                        at retrofit.Retrofit.responseConverter(Retrofit.java:266)
                                                                        at retrofit.MethodHandler.createResponseConverter(MethodHandler.java:55)
                                                                        	... 19 more
```

**Comment by JakeWharton** [comment]
There's no built-in converter for `String`, as the exception says. Either use `ResponseBody` and call `.string()` on it or create and add a `Converter.Factory` which supports `String` to your `Retrofit.Builder` (there's one you can copy from the tests).
