### ISSUE TITLE
@QueryMap throws IllegalArgumentException

### ISSUE THREAD

**Issue by jbaginski** [square/retrofit#1442]
I have a simple class which directly extends ``HashMap``:

```java
public class SearchOptions extends HashMap<String, Object> {
    // ...
}
```

and my service is defined as:

```java
public interface ApiService {
    // ...
    @GET("...")
    Call<List<Property>> getProperties(@Path("city_id") String cityId, @Nullable @QueryMap SearchOptions options);
    // ...
}
```

After upgrading to ``v2.0.0-beta3`` I keep getting the following exception:

```
Caused by: java.lang.IllegalArgumentException: Map must include generic types (e.g., Map<String, String>) (parameter #2)
 for method ApiService.getProperties
 at retrofit2.Utils.methodError(Utils.java:154)
 at retrofit2.Utils.methodError(Utils.java:144)
 at retrofit2.RequestFactoryParser.parameterError(RequestFactoryParser.java:95)
 at retrofit2.RequestFactoryParser.parseParameters(RequestFactoryParser.java:309)
 at retrofit2.RequestFactoryParser.parse(RequestFactoryParser.java:63)
 at retrofit2.MethodHandler.create(MethodHandler.java:34)
 at retrofit2.Retrofit.loadMethodHandler(Retrofit.java:164)
 at retrofit2.Retrofit$1.invoke(Retrofit.java:145)
 at java.lang.reflect.Proxy.invoke(Proxy.java:397)
 at $Proxy1.getProperties(Unknown Source)
 	... 21 more
```

Is it intentional? It worked up to ``v2.0.0-beta2``...

**Comment by JakeWharton** [comment]
Not intentional. Will fix.

**Comment by vforandroid** [comment]
FieldMap which I use in every interface get same error...
Is there same workaround?
 Do not want to expand FieldMap to Field...

**Comment by vforandroid** [comment]
Well, get a workaround
change 

```
requestLogin(@FieldMap Map pars);
```
to

```
requestLogin(@FieldMap Map<String, String> pars);
```

**Comment by JakeWharton** [comment]
@vforandroid That isn't a workaround, your definition is incorrect. Generic types are required for using a map-based annotation.
