### ISSUE TITLE
FATAL EXCEPTION: OkHttp Dispatcher

### ISSUE THREAD

**Issue by Sebosam** [square/retrofit#1482]
I followed an issue:
```
    compile 'com.squareup.retrofit2:retrofit:2.0.0-beta3'
    compile 'com.squareup.retrofit2:converter-gson:2.0.0-beta3'
    compile 'com.squareup.okhttp3:okhttp:3.0.0-RC1'
```
trying okhttp:3.0.1 and RC1, retrofit2 - SNAPSHOT

Any request show me an error:
```
java.lang.AbstractMethodError: abstract method "void okhttp3.Callback.onFailure(okhttp3.Call, java.io.IOException)"
                                                                          at okhttp3.RealCall$AsyncCall.execute(RealCall.java:140)
                                                                          at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:33)
                                                                          at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                          at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                          at java.lang.Thread.run(Thread.java:818)
```

**Comment by ArtworkAD** [comment]
@Sebosam this issue already exists https://github.com/square/retrofit/issues/1475

**Comment by JakeWharton** [comment]
Those versions are incompatible. Use Retrofit 2.0.0-SNAPSHOT as per the linked issue.

**Comment by Sebosam** [comment]
Did it still the same:/
