### ISSUE TITLE
proguard error

### ISSUE THREAD

**Issue by diorslau** [square/retrofit#1492]
proguard file add:

-dontwarn retrofit2.**
-keep class retrofit2.** { *; }
-keepattributes Signature
-keepattributes Exceptions

java.lang.IllegalArgumentException: Unable to create converter for com.lmr.diors.a.a.e<com.lmr.diors.a.a>
                                                       for method a.a
                                                       at retrofit2.Utils.methodError(Unknown Source)
                                                       at retrofit2.MethodHandler.createResponseConverter(Unknown Source)
                                                       at retrofit2.MethodHandler.create(Unknown Source)
                                                       at retrofit2.Retrofit.loadMethodHandler(Unknown Source)
                                                       at retrofit2.Retrofit$1.invoke(Unknown Source)
                                                       at $Proxy1.a(Native Method)
                                                       at com.lmr.diors.c.a.a.a(Unknown Source)
                                                       at com.lmr.diors.e.a.a.a(Unknown Source)
                                                       at com.lmr.diors.view.fragment.impl.BeautyGroupFragment.a(Unknown Source)
                                                       at com.lmr.diors.view.fragment.impl.BeautyGroupFragment.O(Unknown Source)
                                                       at com.lmr.diors.view.fragment.impl.BeautyGroupFragment.K(Unknown Source)
                                                       at com.lmr.diors.view.fragment.impl.BeautyGroupFragment.e(Unknown Source)
                                                       at android.support.v4.b.o.i(Unknown Source)
                                                       at android.support.v4.b.ac.a(Unknown Source)
                                                       at android.support.v4.b.ac.a(Unknown Source)
                                                       at android.support.v4.b.e.run(Unknown Source)
                                                       at android.support.v4.b.ac.e(Unknown Source)
                                                       at android.support.v4.b.ac.b(Unknown Source)
                                                       at android.support.v4.b.an.b(Unknown Source)
                                                       at android.support.v4.view.ViewPager.a(Unknown Source)
                                                       at android.support.v4.view.ViewPager.c(Unknown Source)
                                                       at android.support.v4.view.ViewPager.onMeasure(Unknown Source)

**Comment by JakeWharton** [comment]
This is a configuration problem in your build and there's not enough information to even diagnose what's wrong. It's not a Retrofit bug, however, so your best bet is taking it to StackOverflow with the 'retrofit' tag and as much information as you can provide (like what that type `com.lmr.diors.a.a.e` actually is).
