### ISSUE TITLE
 java.lang.NoClassDefFoundError: retrofit2.Retrofit$Builder

### ISSUE THREAD

**Issue by StayZeal** [square/retrofit#1501]
I had add retrofit-2.0.0-beta3.jar and oktttp-3.0.1.jar to build path;
Then this line has execption:
```java
Retrofit retrofit = new Retrofit.Builder().baseUrl(apiUrl).build();
```
```java
01-20 16:05:34.543: E/AndroidRuntime(22650): Process: co.gofun.retrofitdemo, PID: 22650
01-20 16:05:34.543: E/AndroidRuntime(22650):  : retrofit2.Retrofit$Builder
01-20 16:05:34.543: E/AndroidRuntime(22650): 	at co.gofun.retrofitdemo.MainActivity.get(MainActivity.java:27)
01-20 16:05:34.543: E/AndroidRuntime(22650): 	at co.gofun.retrofitdemo.MainActivity.onCreate(MainActivity.java:21)
01-20 16:05:34.543: E/AndroidRuntime(22650): 	at android.app.Activity.performCreate(Activity.java:5451)
01-20 16:05:34.543: E/AndroidRuntime(22650): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1097)
01-20 16:05:34.543: E/AndroidRuntime(22650): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2346)
01-20 16:05:34.543: E/AndroidRuntime(22650): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2443)
01-20 16:05:34.543: E/AndroidRuntime(22650): 	at android.app.ActivityThread.access$800(ActivityThread.java:157)
01-20 16:05:34.543: E/AndroidRuntime(22650): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1354)
01-20 16:05:34.543: E/AndroidRuntime(22650): 	at android.os.Handler.dispatchMessage(Handler.java:110)
01-20 16:05:34.543: E/AndroidRuntime(22650): 	at android.os.Looper.loop(Looper.java:193)
01-20 16:05:34.543: E/AndroidRuntime(22650): 	at android.app.ActivityThread.main(ActivityThread.java:5348)
01-20 16:05:34.543: E/AndroidRuntime(22650): 	at java.lang.reflect.Method.invokeNative(Native Method)
01-20 16:05:34.543: E/AndroidRuntime(22650): 	at java.lang.reflect.Method.invoke(Method.java:515)
01-20 16:05:34.543: E/AndroidRuntime(22650): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:829)
01-20 16:05:34.543: E/AndroidRuntime(22650): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:645)
01-20 16:05:34.543: E/AndroidRuntime(22650): 	at dalvik.system.NativeStart.main(Native Method)

```

**Comment by JakeWharton** [comment]
What about OkHttp's Okio dependency?

**Comment by StayZeal** [comment]
This execption has been solved;
I added  retrofit-2.0.0-beta3.jar ,oktttp-3.0.1.jar and okio-1.6.0.jar into the project,but the execption is still exist.
I solve this problem by remove appcompat_v7 package(which I didnot use).
Finally thanks for you answer!
