### ISSUE TITLE
retrofit-2.0.0-beta3 with okhttp-3.0.1 has error

### ISSUE THREAD

**Issue by wsy858** [square/retrofit#1511]
my code like this
    compile 'com.squareup.okhttp3:okhttp:3.0.1'
    compile 'com.squareup.retrofit2:retrofit:2.0.0-beta3'
    compile 'com.squareup.retrofit2:converter-gson:2.0.0-beta3'
    compile 'com.squareup.retrofit2:retrofit-converters:2.0.0-beta3'
    compile 'com.squareup.okhttp3:logging-interceptor:3.0.1'

I get the error:
01-22 05:05:40.884  15258-15315/? E/AndroidRuntime﹕ FATAL EXCEPTION: OkHttp Dispatcher
    Process: com.yuncj.okhttpdemo, PID: 15258
    java.lang.AbstractMethodError: abstract method not implemented
            at retrofit2.OkHttpCall$1.onResponse(OkHttpCall.java)
            at okhttp3.RealCall$AsyncCall.execute(RealCall.java:133)
            at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:33)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:841)

**Comment by kafji** [comment]
Use the snapshot version.
```
repositories {
  maven { url 'https://oss.sonatype.org/content/repositories/snapshots' }
}
dependencies {
  compile 'com.squareup.retrofit2:retrofit:2.0.0-SNAPSHOT'
  compile 'com.squareup.retrofit2:converter-gson:2.0.0-SNAPSHOT'
  compile 'com.squareup.retrofit2:retrofit-converters:2.0.0-SNAPSHOT'
}
```

**Comment by ArtworkAD** [comment]
Dublicate of https://github.com/square/retrofit/issues/1475
