### ISSUE TITLE
Multiple request in single callback

### ISSUE THREAD

**Issue by tonespy** [square/retrofit#1517]
I am trying to implement a Request where I can send multiple requests at the same time using `Retrofit` so, I created an Interface like this: 

    @FormUrlEncoded
    @POST("/locations/add.json")
    void sendMultipleLocations(@Query("token")String token, @FieldMap List<Map<String, String>> multipleLocations, Callback<String> callback);

And then, I build up the map data in a List, then push.

    private void sendLocations("token", List<Map<String, String>> multipleLocations) {
        RestClient.get(this).sendMultipleLocations("token", multipleLocations, new Callback<String>() {
            @Override
            public void success(String s, Response response) {
                Log.e("MultipleLocationResp", s);
            }

            @Override
            public void failure(RetrofitError error) {
                error.printStackTrace();
            }
        });
    }

And I keep getting this error:

     java.lang.IllegalArgumentException: PodApi.sendMultipleLocations: @FieldMap parameter type must be Map. (parameter #2)
    at retrofit.RestMethodInfo.methodError(RestMethodInfo.java:107)
    at retrofit.RestMethodInfo.parameterError(RestMethodInfo.java:111)
    at retrofit.RestMethodInfo.parseParameters(RestMethodInfo.java:365)
    at retrofit.RestMethodInfo.init(RestMethodInfo.java:118)
    at retrofit.RestAdapter$RestHandler.invokeRequest(RestAdapter.java:294)
    at retrofit.RestAdapter$RestHandler.access$100(RestAdapter.java:220)
    at retrofit.RestAdapter$RestHandler$2.obtainResponse(RestAdapter.java:278)
    at retrofit.CallbackRunnable.run(CallbackRunnable.java:42)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
    at retrofit.Platform$Android$2$1.run(Platform.java:142)
    at java.lang.Thread.run(Thread.java:818)

**Comment by JakeWharton** [comment]
The error accurately describes the problem and means of fixing it. You cannot use a `List` for `@FieldMap`, you must use `Map`.

**Comment by tonespy** [comment]
Which means I've to do my operation in a `Loop` right?

**Comment by JakeWharton** [comment]
Yes. One call per request that you want to send.
