### ISSUE TITLE
Untraceable fatal Exception caused by java.lang.IllegalArgumentException: byteString == null

### ISSUE THREAD

**Issue by marcusmotill** [square/retrofit#1527]
From time to time I am experiencing this fatal error when performing a request.  It only happens to one request at a time and I cannot get it to go away until I uninstall and reinstall the application.  I am using:
com.squareup.retrofit2:retrofit:2.0.0-beta3

and here is the error:
```
E/AndroidRuntime: FATAL EXCEPTION: OkHttp Dispatcher
    Process: package_name, PID: 4804
    java.lang.IllegalArgumentException: byteString == null
    at okio.Buffer.write(Buffer.java:787)
    at com.squareup.okhttp.Cache$Entry.readCertificateList(Cache.java:628)
    at com.squareup.okhttp.Cache$Entry.<init>(Cache.java:555)
    at com.squareup.okhttp.Cache.get(Cache.java:194)
    at com.squareup.okhttp.Cache$1.get(Cache.java:139)
    at com.squareup.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:226)
    at com.squareup.okhttp.Call.getResponse(Call.java:267)
    at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:224)
    at com.squareup.okhttp.Call.getResponseWithInterceptorChain(Call.java:195)
    at com.squareup.okhttp.Call.access$100(Call.java:34)
    at com.squareup.okhttp.Call$AsyncCall.execute(Call.java:162)
    at com.squareup.okhttp.internal.NamedRunnable.run(NamedRunnable.java:33)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
    at java.lang.Thread.run(Thread.java:818)
```

Let me know if you need more information

EDIT:  I was able to get the error to stop if I went to system setting and cleared the app cache manually

**Comment by JakeWharton** [comment]
This is an OkHttp bug. Please file on its project https://github.com/square/okhttp.
