### ISSUE TITLE
Retrofit and MapBox gives FATAL EXCEPTION

### ISSUE THREAD

**Issue by NelepovDmitry** [square/retrofit#1563]
Here exception (and at https://github.com/square/retrofit/issues/1475)

```
02-03 06:32:46.207 9929-10085/com.worktofun.whatplace.debug E/AndroidRuntime: FATAL EXCEPTION: OkHttp Dispatcher
                                                                              Process: com.worktofun.whatplace.debug, PID: 9929
                                                                              java.lang.AbstractMethodError: abstract method "void okhttp3.Callback.onResponse(okhttp3.Call, okhttp3.Response)"
                                                                                  at okhttp3.RealCall$AsyncCall.execute(RealCall.java:133)
                                                                                  at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:33)
                                                                                  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                                  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                                  at java.lang.Thread.run(Thread.java:818)

```

And while i use Google Maps everything works fine, but today i add MapBox map and for any request by retrofit i got exception.

Here my gradle dependencies

```
compile 'com.squareup.retrofit2:converter-gson:2.0.0-beta3'
    compile 'com.squareup.retrofit2:retrofit:2.0.0-beta3'
//    compile 'com.squareup.okhttp3:okhttp:3.0.0-RC1'
//    compile 'com.squareup.okhttp3:okhttp:3.0.1'
//    compile 'com.squareup.okhttp3:logging-interceptor:3.0.0-RC1'
    compile 'com.squareup.picasso:picasso:2.5.2'
compile('com.mapbox.mapboxsdk:mapbox-android-sdk:3.2.0@aar') {
        transitive = true
    }
```

As u can see, i try add okhttp RC, not RC, 3.0.0 or 3.0.1, try remove them - no effect.

My retrofit instance build like
```

this.retrofit = new Retrofit
                .Builder()
                .baseUrl("http://mysite.com/")
                .addConverterFactory(GsonConverterFactory.create())
                .build();
```

When remove MapBox from gradle - everything work fine.

What is the magic of this?

**Comment by JakeWharton** [comment]
You need to use Retrofit 2.0.0-SNAPSHOT or use a Gradle resolution strategy to force OkHttp 3.0.0-RC1. Something is bumping the OkHttp version to 3.0.0 or 3.0.1 which is incompatible with Retrofit 2.0.0-beta3.

There will be a beta4 this week, maybe even tomorrow that will solve this incompatibility.

**Comment by NelepovDmitry** [comment]
Ok, thank you, i will wait for beta4.
For now SNAPSHOT - not help.

Event i just add MapBox in gradle, not use in project, i still got error
Here now gradle dep

```
//Squareup
    compile 'com.squareup.retrofit2:converter-gson:2.0.0-beta3'
    compile 'com.squareup.retrofit2:retrofit:2.0.0-SNAPSHOT'
    compile 'com.squareup.picasso:picasso:2.5.2'
//MapBox
    compile('com.mapbox.mapboxsdk:mapbox-android-sdk:3.2.0@aar') {
        transitive = true
    }
```

**Comment by JakeWharton** [comment]
Use the snapshot for all Retrofit dependencies

**Comment by NelepovDmitry** [comment]
Ok, 
 //Squareup
    compile 'com.squareup.retrofit2:converter-gson:2.0.0-SNAPSHOT'
    compile 'com.squareup.retrofit2:retrofit:2.0.0-SNAPSHOT'

But, maybe u didn't know, but 
Error:(74, 13) Failed to resolve: com.squareup.retrofit2:converter-gson:2.0.0-SNAPSHOT

**Comment by NelepovDmitry** [comment]
I will wait for beta4, but something suggesting to me, it will not fix this issue.

**Comment by JakeWharton** [comment]
It's there:
https://oss.sonatype.org/content/repositories/snapshots/com/squareup/retrofit2/converter-gson/2.0.0-SNAPSHOT/

**Comment by NelepovDmitry** [comment]
ok, thank you.

**Comment by rick-kln** [comment]
```
repositories {
    maven { url 'https://oss.sonatype.org/content/repositories/snapshots' }
}
dependencies {
    compile fileTree(include: ['*.jar'], dir: 'libs')
    testCompile 'junit:junit:4.12'
    compile 'com.android.support:appcompat-v7:23.1.1'
    compile 'com.android.support:support-v4:23.1.1'
    compile 'com.android.support:design:23.1.1'
    compile('com.mapbox.mapboxsdk:mapbox-android-sdk:3.1.0@aar') {
        transitive = true
    }
    compile 'com.squareup.retrofit2:retrofit:2.0.0-SNAPSHOT'
    compile 'com.squareup.retrofit2:converter-gson:2.0.0-SNAPSHOT'
    compile 'com.squareup.retrofit2:retrofit-converters:2.0.0-SNAPSHOT'
}
```

I have that and it is also not working for me.

**Comment by rick-kln** [comment]
I added 
`compile 'com.squareup.okhttp3:okhttp:3.0.0-RC1'`
explicitly and it still did not work but then I removed all direct usages of OkHttp in my code and all imports of:
`import okhttp3.ResponseBody;`
and that seems to have fixed it.
