### ISSUE TITLE
Interceptor Problem

### ISSUE THREAD

**Issue by cesar-oyarzun-m** [square/retrofit#1578]
Hi, I just update my build gradle to the latest versions and my app is crashing when I try to add the interceptors to OkHttpClient, here is my code

        // Define the interceptor, add authentication headers
        Interceptor interceptor = new Interceptor() {
            @Override
            public Response intercept(Chain chain) throws IOException {
                Request newRequest = chain.request().newBuilder().addHeader(AUTHORIZATION, BEARER +tokenExp).build();
                return chain.proceed(newRequest);
            }
        };

        //Logging Interceptor
        HttpLoggingInterceptor httpLoggingInterceptor = new HttpLoggingInterceptor();
        httpLoggingInterceptor.setLevel(HttpLoggingInterceptor.Level.BODY);

        // Add the interceptor to OkHttpClient
        OkHttpClient client = new OkHttpClient();
        client.interceptors().add(httpLoggingInterceptor);
        client.interceptors().add(interceptor);

my gradle configuration 

    compile 'com.squareup.retrofit2:retrofit:2.0.0-beta4'
    compile 'com.squareup.okhttp3:okhttp:3.0.1'
    compile 'com.squareup.okhttp3:logging-interceptor:3.0.1'
    compile 'com.squareup.retrofit2:converter-gson:2.0.0-beta4'
    compile 'com.squareup.retrofit2:adapter-rxjava:2.0.0-beta4'
    compile 'io.jsonwebtoken:jjwt:0.6.0'
    compile 'io.reactivex:rxandroid:1.1.0'
    compile 'io.socket:socket.io-client:0.6.2'
    compile 'io.reactivex:rxjava:1.1.0'

the exception that I get

```E/AndroidRuntime: FATAL EXCEPTION: main
                                                                 Process: exp.android.sdk, PID: 13127
                                                                 java.lang.IllegalStateException: Exception thrown on Scheduler.Worker thread. Add `onError` handling.
                                                                     at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:60)
                                                                     at android.os.Handler.handleCallback(Handler.java:739)
                                                                     at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                     at android.os.Looper.loop(Looper.java:135)
                                                                     at android.app.ActivityThread.main(ActivityThread.java:5254)
                                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                                     at java.lang.reflect.Method.invoke(Method.java:372)
                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
                                                                  Caused by: rx.exceptions.OnErrorNotImplementedException
                                                                     at rx.Observable$27.onError(Observable.java:7923)
                                                                     at rx.observers.SafeSubscriber._onError(SafeSubscriber.java:159)
                                                                     at rx.observers.SafeSubscriber.onError(SafeSubscriber.java:120)
                                                                     at rx.internal.util.ScalarSynchronousObservable$2$1.onError(ScalarSynchronousObservable.java:140)
                                                                     at rx.internal.operators.OperatorMerge$MergeSubscriber.reportError(OperatorMerge.java:240)
                                                                     at rx.internal.operators.OperatorMerge$MergeSubscriber.checkTerminate(OperatorMerge.java:776)
                                                                     at rx.internal.operators.OperatorMerge$MergeSubscriber.emitLoop(OperatorMerge.java:537)
                                                                     at rx.internal.operators.OperatorMerge$MergeSubscriber.emit(OperatorMerge.java:526)
                                                                     at rx.internal.operators.OperatorMerge$MergeSubscriber.onError(OperatorMerge.java:250)
                                                                     at rx.internal.operators.OperatorMap$1.onError(OperatorMap.java:48)
                                                                     at rx.exceptions.Exceptions.throwOrReport(Exceptions.java:187)
                                                                     at rx.internal.operators.OperatorMap$1.onNext(OperatorMap.java:56)
                                                                     at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.pollQueue(OperatorObserveOn.java:202)
                                                                     at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber$2.call(OperatorObserveOn.java:162)
                                                                     at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
                                                                     at android.os.Handler.handleCallback(Handler.java:739) 
                                                                     at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                                     at android.os.Looper.loop(Looper.java:135) 
                                                                     at android.app.ActivityThread.main(ActivityThread.java:5254) 
                                                                     at java.lang.reflect.Method.invoke(Native Method) 
                                                                     at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903) 
                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698) 
                                                                  Caused by: java.lang.UnsupportedOperationException
                                                                     at java.util.Collections$UnmodifiableCollection.add(Collections.java:928)
                                                                     at com.scala.exp.android.sdk.ExpService.init(ExpService.java:64)
                                                                     at com.scala.exp.android.sdk.Runtime$1$1.call(Runtime.java:105)
                                                                     at com.scala.exp.android.sdk.Runtime$1$1.call(Runtime.java:91)
                                                                     at rx.internal.operators.OperatorMap$1.onNext(OperatorMap.java:54)
                                                                     at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.pollQueue(OperatorObserveOn.java:202) 
                                                                     at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber$2.call(OperatorObserveOn.java:162) 
                                                                     at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55) 
                                                                     at android.os.Handler.handleCallback(Handler.java:739) 
                                                                     at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                                     at android.os.Looper.loop(Looper.java:135) 
                                                                     at android.app.ActivityThread.main(ActivityThread.java:5254) 
                                                                     at java.lang.reflect.Method.invoke(Native Method) 
                                                                     at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903) 
                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698) ```

**Comment by NightlyNexus** [comment]
Possibly unrelated:
OkHttp 3's `OkHttpClient`'s interceptor list is immutable.
```
// Add the interceptors to OkHttpClient.
OkHttpClient.Builder builder = new OkHttpClient.Builder();
client.addInterceptor(httpLoggingInterceptor);
client.addInterceptor(interceptor);
OkHttpClient client = builder.build();
```

**Comment by localhostEU** [comment]
Also getting this error in Interceptor. Unrelated to adding of Interceptor, but related to something another.

**Comment by Korzhuck** [comment]
Have the same problem.
Everything worked. But after one of updates - this error is occurres on some devices (Android 5.1, 6.0)
I think that it is connected with update of  targetSdk from 19 to 23
retrofit 2.1.0
11-08 18:30:33.930 25855-25855/by.tut.android E/Top5Fragment_: onFail
      java.net.ConnectException: Failed to connect to news.tut.by/178.172.160.5:80
      at okhttp3.internal.io.RealConnection.connectSocket(RealConnection.java:187)
      at okhttp3.internal.io.RealConnection.buildConnection(RealConnection.java:170)
      at okhttp3.internal.io.RealConnection.connect(RealConnection.java:111)
      at okhttp3.internal.http.StreamAllocation.findConnection(StreamAllocation.java:187)
      at okhttp3.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:123)
      at okhttp3.internal.http.StreamAllocation.newStream(StreamAllocation.java:93)
      at okhttp3.internal.http.HttpEngine.connect(HttpEngine.java:296)
      at okhttp3.internal.http.HttpEngine.sendRequest(HttpEngine.java:248)
      at okhttp3.RealCall.getResponse(RealCall.java:243)
      at okhttp3.RealCall$ApplicationInterceptorChain.proceed(RealCall.java:201)
      at by.tut.shared.app.RemoteApiUtils.lambda$create$35(RemoteApiUtils.java:45)
      at by.tut.shared.app.RemoteApiUtils.access$lambda$0(RemoteApiUtils.java)
      at by.tut.shared.app.RemoteApiUtils$$Lambda$1.intercept(Unknown Source)
      at okhttp3.RealCall$ApplicationInterceptorChain.proceed(RealCall.java:190)
      at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:163)
      at okhttp3.RealCall.execute(RealCall.java:57)
      at retrofit2.OkHttpCall.execute(OkHttpCall.java:174)
      at retrofit2.adapter.rxjava.RxJavaCallAdapterFactory$RequestArbiter.request(RxJavaCallAdapterFactory.java:171)
      at rx.internal.operators.OperatorSubscribeOn$1$1$1.request(OperatorSubscribeOn.java:80)
      at rx.Subscriber.setProducer(Subscriber.java:211)
      at rx.internal.operators.OperatorMap$MapSubscriber.setProducer(OperatorMap.java:99)
      at rx.internal.operators.OperatorSubscribeOn$1$1.setProducer(OperatorSubscribeOn.java:76)
      at rx.Subscriber.setProducer(Subscriber.java:205)
      at retrofit2.adapter.rxjava.RxJavaCallAdapterFactory$CallOnSubscribe.call(RxJavaCallAdapterFactory.java:152)
      at retrofit2.adapter.rxjava.RxJavaCallAdapterFactory$CallOnSubscribe.call(RxJavaCallAdapterFactory.java:138)
      at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:50)
      at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
      at rx.Observable.unsafeSubscribe(Observable.java:8460)
      at rx.internal.operators.OperatorSubscribeOn$1.call(OperatorSubscribeOn.java:94)
      at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
      at rx.internal.schedulers.ExecutorScheduler$ExecutorSchedulerWorker.run(ExecutorScheduler.java:108)
      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
      at java.lang.Thread.run(Thread.java:818)
