### ISSUE TITLE
While using Retrofit 1.9.0 i got error Not Modified"HTTP/1.1 200 OK

### ISSUE THREAD

**Issue by nikhilkatekhaye** [square/retrofit#1588]
Retro error
                                                                    retrofit.RetrofitError: Unexpected status line: "Not Modified"HTTP/1.1 200 OK
                                                                        at retrofit.RestAdapter$RestHandler.invokeRequest(RestAdapter.java:395)
                                                                        at retrofit.RestAdapter$RestHandler.invoke(RestAdapter.java:240)
                                                                        at java.lang.reflect.Proxy.invoke(Proxy.java:393)
                                                                        at $Proxy1.getRoutingServer(Unknown Source)

**Comment by JakeWharton** [comment]
What HTTP client are you using?

**Comment by JakeWharton** [comment]
Or rather, paste the entire stack trace.

**Comment by JakeWharton** [comment]
(This is an HTTP client bug, not a Retrofit one, FYI)

**Comment by nikhilkatekhaye** [comment]
okHTTP

**Comment by nikhilkatekhaye** [comment]
I am Using OKHTTP client For that.

**Comment by nikhilkatekhaye** [comment]
Now i moved on Retrofit 2.0 beta Version that issue has been sloved
