### ISSUE TITLE
Call.enqueue with null parameter throws NullPointerException

### ISSUE THREAD

**Issue by shaildyp** [square/retrofit#1661]
```code Call.enqueue ``` should add a null check. If it can't accepts ```null```parameter then it should be annotated with ```@NotNull```

```java
java.lang.NullPointerException: Attempt to invoke interface method 'void retrofit2.Callback.onResponse(retrofit2.Call, retrofit2.Response)' on a null object reference
at retrofit2.ExecutorCallAdapterFactory$ExecutorCallbackCall$1$1.run(ExecutorCallAdapterFactory.java:66)
at android.os.Handler.handleCallback(Handler.java:739)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:145)
at android.app.ActivityThread.main(ActivityThread.java:6872)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)
```

**Comment by JakeWharton** [comment]
There are no nullability annotations that are acceptable.
