### ISSUE TITLE
Error when API interface ends with "interface"

### ISSUE THREAD

**Issue by Ashotyanski** [square/retrofit#1668]
Android API 22
retrofit:2.0.0-beta4
Fires an error when I name the api interface from [SampleService](https://github.com/square/retrofit/blob/master/samples/src/main/java/com/example/retrofit/SimpleService.java) like blablaInterface.
eg
Github github  = retrofit.create(Github.class); _is ok_

GithubInterface github  = retrofit.create(GithubInterface.class);
`FATAL EXCEPTION: main
                                                              Process: com.myapp, PID: 14475
                                                              java.lang.NoClassDefFoundError: retrofit.Call
                                                                  at libcore.reflect.InternalNames.getClass(InternalNames.java:55)
                                                                  at java.lang.Class.getDexCacheType(Class.java:479)
                                                                  at java.lang.reflect.ArtMethod.getDexCacheType(ArtMethod.java:191)
                                                                  at java.lang.reflect.ArtMethod.getReturnType(ArtMethod.java:145)
                                                                  at java.lang.reflect.Method.getReturnType(Method.java:184)
                                                                  at java.lang.Class.getDeclaredMethods(Class.java:771)
                                                                  at java.lang.reflect.Proxy.getMethodsRecursive(Proxy.java:303)
                                                                  at java.lang.reflect.Proxy.getMethods(Proxy.java:292)
                                                                  at java.lang.reflect.Proxy.getProxyClass(Proxy.java:165)
                                                                  at java.lang.reflect.Proxy.newProxyInstance(Proxy.java:232)
                                                                  at retrofit2.Retrofit.create(Retrofit.java:132)
                                                                  at com.myapp.MainActivity$3.onClick(MainActivity.java:126)
                                                                  at android.view.View.performClick(View.java:4780)
                                                                  at android.view.View$PerformClick.run(View.java:19866)
                                                                  at android.os.Handler.handleCallback(Handler.java:739)
                                                                  at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                  at android.os.Looper.loop(Looper.java:135)
                                                                  at android.app.ActivityThread.main(ActivityThread.java:5254)
                                                                  at java.lang.reflect.Method.invoke(Native Method)
                                                                  at java.lang.reflect.Method.invoke(Method.java:372)
                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)`
                                                               
`Caused by: java.lang.ClassNotFoundException: Didn't find class "retrofit.Call" on path: DexPathList[[dex file "/data/data/com.myapp/files/instant-run/dex/slice-slice_9_8c11bab7d65e67470101e136f67db8e71618a366-classes.dex", dex file "/data/data/com.myapp/files/instant-run/dex/slice-slice_8_90579ff66ccd8c6bafe9f4b398388277b1f2c6dc-classes.dex", dex file "/data/data/com.myapp/files/instant-run/dex/slice-slice_7_1908d81de941cfa7fb96e9d628120ea65e37d620-classes.dex", dex file "/data/data/com.myapp/files/instant-run/dex/slice-slice_6_207c4808668c004974fbd206946f9e5eb1d82fe7-classes.dex", dex file "/data/data/com.myapp/files/instant-run/dex/slice-slice_5_985750d2fb30971b7427007754fe53ae65c107f7-classes.dex", dex file "/data/data/com.myapp/files/instant-run/dex/slice-slice_4_f8b0aa6ddf98b664f34ca2aef4645331fded2107-classes.dex", dex file "/data/data/com.myapp/files/instant-run/dex/slice-slice_3_bee32a93d7e6ae6186c8aae9b0d09d1cb48b25d1-classes.dex", dex file "/data/data/com.myapp/files/instant-run/dex/slice-slice_2_e287f706b75fcf30f9f8acbc694a3f0e7008200d-classes.dex", dex file "/data/data/com.myapp/files/instant-run/dex/slice-slice_1_2a82e4694281b0c4e480b1e20af1c9c1074d3b43-classes.dex", dex file "/data/data/com.myapp/files/instant-run/dex/slice-slice_0_c2f96fcc1a4ec7891e1ef75e45f149c53f973fe2-classes.dex", dex file "/data/data/com.myapp/files/instant-run/dex/slice-dependencies_66a9df8ffdd89fd1ab4c4f6b0b1923a379e92ce0-classes.dex"],nativeLibraryDirectories=[/vendor/lib, /system/lib, /vendor/lib, /system/lib]]
                                                                  at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                                  at com.android.tools.fd.runtime.IncrementalClassLoader$DelegateClassLoader.findClass(IncrementalClassLoader.java:90)
                                                                  at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
                                                                  at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
                                                                  at libcore.reflect.InternalNames.getClass(InternalNames.java:53)
                                                                  at java.lang.Class.getDexCacheType(Class.java:479) 
                                                                  at java.lang.reflect.ArtMethod.getDexCacheType(ArtMethod.java:191) 
                                                                  at java.lang.reflect.ArtMethod.getReturnType(ArtMethod.java:145) 
                                                                  at java.lang.reflect.Method.getReturnType(Method.java:184) 
                                                                  at java.lang.Class.getDeclaredMethods(Class.java:771) 
                                                                  at java.lang.reflect.Proxy.getMethodsRecursive(Proxy.java:303) 
                                                                  at java.lang.reflect.Proxy.getMethods(Proxy.java:292) 
                                                                  at java.lang.reflect.Proxy.getProxyClass(Proxy.java:165) 
                                                                  at java.lang.reflect.Proxy.newProxyInstance(Proxy.java:232) 
                                                                  at retrofit2.Retrofit.create(Retrofit.java:132) 
                                                                  at com.myapp.MainActivity$3.onClick(MainActivity.java:126) 
                                                                  at android.view.View.performClick(View.java:4780) 
                                                                  at android.view.View$PerformClick.run(View.java:19866) 
                                                                  at android.os.Handler.handleCallback(Handler.java:739) 
                                                                  at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                                  at android.os.Looper.loop(Looper.java:135) 
                                                                  at android.app.ActivityThread.main(ActivityThread.java:5254) 
                                                                  at java.lang.reflect.Method.invoke(Native Method) 
                                                                  at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903) 
                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698) `

**Comment by artem-zinnatullin** [comment]
Either proguard/etc strips the class or you use multidex and forgot to initialize it in the application class ([docs](http://developer.android.com/tools/building/multidex.html#mdex-pre-l)).

**Comment by Ashotyanski** [comment]
@artem-zinnatullin none of them. As I already mentioned, there are just blank activity and sampe service.

**Comment by JakeWharton** [comment]
This very clearly looks like a multidex problem based on `com.android.tools.fd.runtime` being present in the trace. I tried to reproduce the behavior in an Android app and could not.

**Comment by JakeWharton** [comment]
Actually maybe this is instant run? In either case, it's not a Retrofit bug bug a problem with the build system you are using.
