### ISSUE TITLE
is there any easy way to set lenient mode for json converter in retrofit 2.0 beta4?

### ISSUE THREAD

**Issue by seaguest** [square/retrofit#1676]
Hello, I am getting an MalformedJsonException when I am using retrofit2.

Here is my originally posted question:
http://stackoverflow.com/questions/35984898/retrofit2-0-gets-malformedjsonexception-while-the-json-seems-correct

since the stacktrace said:

>      com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 1 path $

I am wondering how to set Lenient mode for json conveter?

What I have found in the following seems not valid for retrofit 2
http://stackoverflow.com/questions/27485346/malformedjsonexception-with-retrofit-api

Could you please help?

**Comment by JakeWharton** [comment]
```java
Gson gson = new GsonBuilder()
    .setLenient()
    .build();
// ...
.addConverterFactory(GsonConverterFactory.create(gson))
```

**Comment by krupalagile** [comment]
after trying this, I got following error:

java.lang.RuntimeException: Failed to invoke public com.squareup.okhttp.ResponseBody() with no args
 at com.google.gson.internal.ConstructorConstructor$3.construct(ConstructorConstructor.java:111)
     at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:206)
    at retrofit2.converter.gson.GsonResponseBodyConverter.convert(GsonResponseBodyConverter.java:37)
    at retrofit2.converter.gson.GsonResponseBodyConverter.convert(GsonResponseBodyConverter.java:25)
    at retrofit2.OkHttpCall.parseResponse(OkHttpCall.java:211)
    at retrofit2.OkHttpCall$1.onResponse(OkHttpCall.java:106)
   at okhttp3.RealCall$AsyncCall.execute(RealCall.java:133)
   at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
    at java.lang.Thread.run(Thread.java:841)
 Caused by: java.lang.InstantiationException: can't instantiate class com.squareup.okhttp.ResponseBody
   at java.lang.reflect.Constructor.constructNative(Native Method)
     at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
   at com.google.gson.internal.ConstructorConstructor$3.construct(ConstructorConstructor.java:108)

**Comment by gbajaj** [comment]
`Gson gson = new GsonBuilder()
                .setLenient()
.create();`

**Comment by DivyShah** [comment]
I had added  this line 
 Gson gson = new GsonBuilder() .setLenient() .create();  but still gives me the same error.

**Comment by d-rahul** [comment]
https://readyandroid.wordpress.com/error-use-jsonreader-setlenienttrue-to-accept-malformed-json-at-line-1-column-1-path/
