### ISSUE TITLE
Caused by java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask  rejected from java.util.concurrent.ScheduledThreadPoolExecutor 

### ISSUE THREAD

**Issue by TonyTangAndroid** [square/retrofit#1681]
I have been using the following library for managing network request. 
`retrofit_veresion=2.0.0
okhttp_veresion=3.2.0
rxjava_version=1.0.9
rxandroid_version=0.24.0`

And I have received a lot of error report recently in fabric. But I rarely reproduce this issue in my device. Anyone else who also has run into this kind of issue? 

 Here is the detailed exception:

_Fatal Exception: java.lang.IllegalStateException: Fatal Exception thrown on Scheduler.Worker thread.
       at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:62)
       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:831)
Caused by java.util.concurrent.RejectedExecutionException: **Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@40f74bd rejected from java.util.concurrent.ScheduledThreadPoolExecutor@194f3414[Shutting down, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 1]**
       at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2011)
       at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:793)
       at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(ScheduledThreadPoolExecutor.java:298)
       at java.util.concurrent.ScheduledThreadPoolExecutor.schedule(ScheduledThreadPoolExecutor.java:503)
       at java.util.concurrent.ScheduledThreadPoolExecutor.submit(ScheduledThreadPoolExecutor.java:602)
       at rx.internal.schedulers.NewThreadWorker.scheduleActual(NewThreadWorker.java:239)
       at rx.internal.schedulers.NewThreadWorker.schedule(NewThreadWorker.java:224)
       at rx.internal.schedulers.NewThreadWorker.schedule(NewThreadWorker.java:216)
       at rx.internal.operators.OperatorSubscribeOn$1$1$1.request(OperatorSubscribeOn.java:82)
       at rx.Subscriber.request(Subscriber.java:157)
       at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.call(OperatorObserveOn.java:225)
       at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:831)_

**Comment by JakeWharton** [comment]
The executor backing the scheduler is shut down so it's not accepting any new threads. Retrofit plays no part in schedulers or their internals so you'll need to figure out what's causing the shutdown. Try StackOverflow or the RxJava mailing list and include more information about what schedulers are being used, etc.

**Comment by parkjaeiek** [comment]
same issue

**Comment by civilordergone** [comment]
this issue appeared in crashlytics once I upgraded retrofit from 1.9 to 2.0+
