### ISSUE TITLE
Retrofit 1.9 Error in API levels below 23 Rest Adapter Builder

### ISSUE THREAD

**Issue by doripandeli** [square/retrofit#1731]
Hello

I get this error every time I try to perform a call a communicator method. This happens on API levels below 23. Currently I am using retrofit 1.9.0. I also tried 2.0 and it gives me the same crash. 
Any solution?
Thanks.

```
FATAL EXCEPTION: main Process: com.example.app, PID: 25126      java.lang.NoClassDefFoundError: retrofit.RestAdapter$Builder
                                                                       at com.example.app.communicator.UserCommunicator.retrieve_clinics(UserCommunicator.java:261)
                                                                       at com.example.app.DiscoverClinic.onCreate(DiscoverClinic.java:126)
                                                                       at android.app.Activity.performCreate(Activity.java:5451)
                                                                       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1093)
                                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2298)
                                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2392)
                                                                       at android.app.ActivityThread.access$900(ActivityThread.java:169)
                                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1280)
                                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                       at android.os.Looper.loop(Looper.java:146)
                                                                       at android.app.ActivityThread.main(ActivityThread.java:5487)
                                                                       at java.lang.reflect.Method.invokeNative(Native Method)
                                                                       at java.lang.reflect.Method.invoke(Method.java:515)
                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
                                                                       at dalvik.system.NativeStart.main(Native Method)****
```

Dependencies:

```
dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    testCompile 'junit:junit:4.12'
    compile 'com.android.support:appcompat-v7:23.3.0'
    compile 'com.squareup.retrofit:retrofit:2.0.0-beta2'
    compile 'com.squareup.okhttp:okhttp:2.4.0'
    compile 'com.google.code.gson:gson:2.4'
    compile 'com.squareup.retrofit:converter-gson:2.0.0-beta2'
    compile 'com.android.support:design:23.3.0'
    compile 'com.android.support:recyclerview-v7:23.3.0'
    compile 'com.squareup:otto:1.3.5'
    compile 'com.facebook.android:facebook-android-sdk:4.6.0'
    compile 'com.github.alamkanak:android-week-view:1.2.4'
    compile 'com.google.android.gms:play-services-analytics:8.4.0'
    compile 'com.google.android.gms:play-services:8.4.0'
    compile 'com.android.support:support-v4:23.3.0'
    compile 'com.android.support:cardview-v7:23.3.0'
}
```

**Comment by JakeWharton** [comment]
This is a problem with your multidex configuration and not with the Retrofit library. Please seek support on StackOverflow, the Android developer mailing list, or by filing a bug on the Android tracker if this is actually a multidex bug.
