### ISSUE TITLE
How to solve NoSuchMethodError: retrofit2.Response.isSuccess

### ISSUE THREAD

**Issue by zhangyubao** [square/retrofit#1749]
04-19 22:33:42.956 24005-24036/com.zbao.study E/AndroidRuntime: FATAL EXCEPTION: RxCachedThreadScheduler-1
                                                                Process: com.zbao.study, PID: 24005
                                                                java.lang.IllegalStateException: Fatal Exception thrown on Scheduler.Worker thread.
                                                                    at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:62)
                                                                    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
                                                                    at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152)
                                                                    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265)
                                                                    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                    at java.lang.Thread.run(Thread.java:841)
                                                                 Caused by: java.lang.NoSuchMethodError: retrofit2.Response.isSuccess
                                                                    at retrofit2.adapter.rxjava.RxJavaCallAdapterFactory$SimpleCallAdapter$1.call(RxJavaCallAdapterFactory.java:160)
                                                                    at retrofit2.adapter.rxjava.RxJavaCallAdapterFactory$SimpleCallAdapter$1.call(RxJavaCallAdapterFactory.java:158)
                                                                    at rx.internal.operators.OperatorMap$1.onNext(OperatorMap.java:54)
                                                                    at retrofit2.adapter.rxjava.RxJavaCallAdapterFactory$CallOnSubscribe.call(RxJavaCallAdapterFactory.java:113)
                                                                    at retrofit2.adapter.rxjava.RxJavaCallAdapterFactory$CallOnSubscribe.call(RxJavaCallAdapterFactory.java:92)
                                                                    at rx.Observable$2.call(Observable.java:162)
                                                                    at rx.Observable$2.call(Observable.java:154)
                                                                    at rx.Observable$2.call(Observable.java:162)
                                                                    at rx.Observable$2.call(Observable.java:154)
                                                                    at rx.Observable.unsafeSubscribe(Observable.java:8098)
                                                                    at rx.internal.operators.OperatorSubscribeOn$1$1.call(OperatorSubscribeOn.java:62)
                                                                    at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
                                                                    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422) 
                                                                    at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
                                                                    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152) 
                                                                    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265) 
                                                                    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
                                                                    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
                                                                    at java.lang.Thread.run(Thread.java:841) 
04-19 22:33:43.868 24005-24005/com.zbao.study E/EGL_emulation: egl: destroying current context refused

**Comment by swankjesse** [comment]
The method was renamed to `isSuccessful()` in the final release of Retrofit 2.0.0. You’ll need to build against the same dependency that you deploy.

**Comment by zhangyubao** [comment]
I rebuild again but it's  still had the same error

**Comment by ArslanAli7** [comment]
you  need to upgrade the version of retrofit dependency under your build.gradle,for isSuccessful() to work.
