### ISSUE TITLE
Retrofit2.2 + RxAndroid SocketTimeoutError not to catch

### ISSUE THREAD

**Issue by AndwareSsj** [square/retrofit#1791]
error stack

```
java.lang.IllegalStateException: Fatal Exception thrown on Scheduler.Worker thread.
	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:62)
	at android.os.Handler.handleCallback(Handler.java:730)
	at android.os.Handler.dispatchMessage(Handler.java:92)
	at android.os.Looper.loop(Looper.java:137)
	at android.app.ActivityThread.main(ActivityThread.java:5178)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:525)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:745)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:561)
	at dalvik.system.NativeStart.main(Native Method)
Caused by: rx.exceptions.OnErrorFailedException: Error occurred when trying to propagate error to Observer.onError
	at rx.observers.SafeSubscriber._onError(SafeSubscriber.java:192)
	at rx.observers.SafeSubscriber.onError(SafeSubscriber.java:120)
	at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.a(OperatorObserveOn.java:254)
	at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.call(OperatorObserveOn.java:186)
	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
	... 9 more
Caused by: rx.exceptions.CompositeException: 2 exceptions occurred. 
	... 14 more
Caused by: rx.exceptions.CompositeException$CompositeExceptionCausalChain: Chain of Causes for CompositeException In Order Received =>
	at com.loc.t.a(Utils.java:123)
	at com.loc.ag.uncaughtException(DynamicExceptionHandler.java:63)
	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:693)
	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:690)
	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:66)
	... 9 more
Caused by: java.net.SocketTimeoutException: timeout
	at okio.Okio$3.newTimeoutException(Okio.java:207)
	at okio.AsyncTimeout.a(AsyncTimeout.java:261)
	at okio.AsyncTimeout$2.read(AsyncTimeout.java:215)
	at okio.RealBufferedSource.indexOf(RealBufferedSource.java:306)
	at okio.RealBufferedSource.indexOf(RealBufferedSource.java:300)
	at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:196)
	at okhttp3.internal.http.Http1xStream.readResponse(Http1xStream.java:184)
	at okhttp3.internal.http.Http1xStream.readResponseHeaders(Http1xStream.java:125)
	at okhttp3.internal.http.HttpEngine.d(HttpEngine.java:723)
	at okhttp3.internal.http.HttpEngine.b(HttpEngine.java:81)
	at okhttp3.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:708)
	at okhttp3.internal.http.HttpEngine.readResponse(HttpEngine.java:563)
	at okhttp3.RealCall.a(RealCall.java:241)
	at okhttp3.RealCall$ApplicationInterceptorChain.proceed(RealCall.java:198)
	at okhttp3.RealCall.a(RealCall.java:160)
	at okhttp3.RealCall.execute(RealCall.java:57)
	at retrofit2.OkHttpCall.execute(OkHttpCall.java:174)
	at retrofit2.adapter.rxjava.RxJavaCallAdapterFactory$RequestArbiter.request(RxJavaCallAdapterFactory.java:171)
	at rx.internal.operators.OperatorSubscribeOn$1$1$1.request(OperatorSubscribeOn.java:80)
	at rx.Subscriber.setProducer(Subscriber.java:211)
	at rx.internal.operators.OperatorSubscribeOn$1$1.setProducer(OperatorSubscribeOn.java:76)
	at rx.Subscriber.setProducer(Subscriber.java:205)
	at retrofit2.adapter.rxjava.RxJavaCallAdapterFactory$CallOnSubscribe.call(RxJavaCallAdapterFactory.java:152)
	at retrofit2.adapter.rxjava.RxJavaCallAdapterFactory$CallOnSubscribe.call(RxJavaCallAdapterFactory.java:138)
	at rx.Observable$2.a(Observable.java:162)
	at rx.Observable$2.call(Observable.java:154)
	at rx.Observable.unsafeSubscribe(Observable.java:8314)
	at rx.internal.operators.OperatorSubscribeOn$1.call(OperatorSubscribeOn.java:94)
	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390)
	at java.util.concurrent.FutureTask.run(FutureTask.java:234)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:153)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:267)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
	at java.lang.Thread.run(Thread.java:841)
Caused by: java.net.SocketTimeoutException
	at java.net.PlainSocketImpl.read(PlainSocketImpl.java:492)
	at java.net.PlainSocketImpl.access$000(PlainSocketImpl.java:46)
	at java.net.PlainSocketImpl$PlainSocketInputStream.read(PlainSocketImpl.java:241)
	at okio.Okio$2.read(Okio.java:139)
	at okio.AsyncTimeout$2.read(AsyncTimeout.java:211)
	... 33 more
rx.exceptions.OnErrorFailedException: Error occurred when trying to propagate error to Observer.onError
	at rx.observers.SafeSubscriber._onError(SafeSubscriber.java:192)
	at rx.observers.SafeSubscriber.onError(SafeSubscriber.java:120)
	at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.a(OperatorObserveOn.java:254)
	at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.call(OperatorObserveOn.java:186)
	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
	at android.os.Handler.handleCallback(Handler.java:730)
	at android.os.Handler.dispatchMessage(Handler.java:92)
	at android.os.Looper.loop(Looper.java:137)
	at android.app.ActivityThread.main(ActivityThread.java:5178)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:525)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:745)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:561)
	at dalvik.system.NativeStart.main(Native Method)
Caused by: rx.exceptions.CompositeException: 2 exceptions occurred. 
	... 14 more
Caused by: rx.exceptions.CompositeException$CompositeExceptionCausalChain: Chain of Causes for CompositeException In Order Received =>
	at com.loc.t.a(Utils.java:123)
	at com.loc.ag.uncaughtException(DynamicExceptionHandler.java:63)
	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:693)
	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:690)
	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:66)
	... 9 more
Caused by: java.net.SocketTimeoutException: timeout
	at okio.Okio$3.newTimeoutException(Okio.java:207)
	at okio.AsyncTimeout.a(AsyncTimeout.java:261)
	at okio.AsyncTimeout$2.read(AsyncTimeout.java:215)
	at okio.RealBufferedSource.indexOf(RealBufferedSource.java:306)
	at okio.RealBufferedSource.indexOf(RealBufferedSource.java:300)
	at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:196)
	at okhttp3.internal.http.Http1xStream.readResponse(Http1xStream.java:184)
	at okhttp3.internal.http.Http1xStream.readResponseHeaders(Http1xStream.java:125)
	at okhttp3.internal.http.HttpEngine.d(HttpEngine.java:723)
	at okhttp3.internal.http.HttpEngine.b(HttpEngine.java:81)
	at okhttp3.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:708)
	at okhttp3.internal.http.HttpEngine.readResponse(HttpEngine.java:563)
	at okhttp3.RealCall.a(RealCall.java:241)
	at okhttp3.RealCall$ApplicationInterceptorChain.proceed(RealCall.java:198)
	at okhttp3.RealCall.a(RealCall.java:160)
	at okhttp3.RealCall.execute(RealCall.java:57)
	at retrofit2.OkHttpCall.execute(OkHttpCall.java:174)
	at retrofit2.adapter.rxjava.RxJavaCallAdapterFactory$RequestArbiter.request(RxJavaCallAdapterFactory.java:171)
	at rx.internal.operators.OperatorSubscribeOn$1$1$1.request(OperatorSubscribeOn.java:80)
	at rx.Subscriber.setProducer(Subscriber.java:211)
	at rx.internal.operators.OperatorSubscribeOn$1$1.setProducer(OperatorSubscribeOn.java:76)
	at rx.Subscriber.setProducer(Subscriber.java:205)
	at retrofit2.adapter.rxjava.RxJavaCallAdapterFactory$CallOnSubscribe.call(RxJavaCallAdapterFactory.java:152)
	at retrofit2.adapter.rxjava.RxJavaCallAdapterFactory$CallOnSubscribe.call(RxJavaCallAdapterFactory.java:138)
	at rx.Observable$2.a(Observable.java:162)
	at rx.Observable$2.call(Observable.java:154)
	at rx.Observable.unsafeSubscribe(Observable.java:8314)
	at rx.internal.operators.OperatorSubscribeOn$1.call(OperatorSubscribeOn.java:94)
	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390)
	at java.util.concurrent.FutureTask.run(FutureTask.java:234)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:153)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:267)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
	at java.lang.Thread.run(Thread.java:841)
Caused by: java.net.SocketTimeoutException
	at java.net.PlainSocketImpl.read(PlainSocketImpl.java:492)
	at java.net.PlainSocketImpl.access$000(PlainSocketImpl.java:46)
	at java.net.PlainSocketImpl$PlainSocketInputStream.read(PlainSocketImpl.java:241)
	at okio.Okio$2.read(Okio.java:139)
	at okio.AsyncTimeout$2.read(AsyncTimeout.java:211)
	... 33 more
rx.exceptions.CompositeException: 2 exceptions occurred. 
	at rx.observers.SafeSubscriber._onError(SafeSubscriber.java:192)
	at rx.observers.SafeSubscriber.onError(SafeSubscriber.java:120)
	at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.a(OperatorObserveOn.java:254)
	at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.call(OperatorObserveOn.java:186)
	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
	at android.os.Handler.handleCallback(Handler.java:730)
	at android.os.Handler.dispatchMessage(Handler.java:92)
	at android.os.Looper.loop(Looper.java:137)
	at android.app.ActivityThread.main(ActivityThread.java:5178)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:525)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:745)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:561)
	at dalvik.system.NativeStart.main(Native Method)
  ComposedException 1 :
	java.net.SocketTimeoutException: timeout
		at okio.Okio$3.newTimeoutException(Okio.java:207)
		at okio.AsyncTimeout.a(AsyncTimeout.java:261)
		at okio.AsyncTimeout$2.read(AsyncTimeout.java:215)
		at okio.RealBufferedSource.indexOf(RealBufferedSource.java:306)
		at okio.RealBufferedSource.indexOf(RealBufferedSource.java:300)
		at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:196)
		at okhttp3.internal.http.Http1xStream.readResponse(Http1xStream.java:184)
		at okhttp3.internal.http.Http1xStream.readResponseHeaders(Http1xStream.java:125)
		at okhttp3.internal.http.HttpEngine.d(HttpEngine.java:723)
		at okhttp3.internal.http.HttpEngine.b(HttpEngine.java:81)
		at okhttp3.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:708)
		at okhttp3.internal.http.HttpEngine.readResponse(HttpEngine.java:563)
		at okhttp3.RealCall.a(RealCall.java:241)
		at okhttp3.RealCall$ApplicationInterceptorChain.proceed(RealCall.java:198)
		at okhttp3.RealCall.a(RealCall.java:160)
		at okhttp3.RealCall.execute(RealCall.java:57)
		at retrofit2.OkHttpCall.execute(OkHttpCall.java:174)
		at retrofit2.adapter.rxjava.RxJavaCallAdapterFactory$RequestArbiter.request(RxJavaCallAdapterFactory.java:171)
		at rx.internal.operators.OperatorSubscribeOn$1$1$1.request(OperatorSubscribeOn.java:80)
		at rx.Subscriber.setProducer(Subscriber.java:211)
		at rx.internal.operators.OperatorSubscribeOn$1$1.setProducer(OperatorSubscribeOn.java:76)
		at rx.Subscriber.setProducer(Subscriber.java:205)
		at retrofit2.adapter.rxjava.RxJavaCallAdapterFactory$CallOnSubscribe.call(RxJavaCallAdapterFactory.java:152)
		at retrofit2.adapter.rxjava.RxJavaCallAdapterFactory$CallOnSubscribe.call(RxJavaCallAdapterFactory.java:138)
		at rx.Observable$2.a(Observable.java:162)
		at rx.Observable$2.call(Observable.java:154)
		at rx.Observable.unsafeSubscribe(Observable.java:8314)
		at rx.internal.operators.OperatorSubscribeOn$1.call(OperatorSubscribeOn.java:94)
		at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
		at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390)
		at java.util.concurrent.FutureTask.run(FutureTask.java:234)
		at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:153)
		at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:267)
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
		at java.lang.Thread.run(Thread.java:841)
	Caused by: java.net.SocketTimeoutException
		at java.net.PlainSocketImpl.read(PlainSocketImpl.java:492)
		at java.net.PlainSocketImpl.access$000(PlainSocketImpl.java:46)
		at java.net.PlainSocketImpl$PlainSocketInputStream.read(PlainSocketImpl.java:241)
		at okio.Okio$2.read(Okio.java:139)
		at okio.AsyncTimeout$2.read(AsyncTimeout.java:211)
		at okio.RealBufferedSource.indexOf(RealBufferedSource.java:306)
		at okio.RealBufferedSource.indexOf(RealBufferedSource.java:300)
		at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:196)
		at okhttp3.internal.http.Http1xStream.readResponse(Http1xStream.java:184)
		at okhttp3.internal.http.Http1xStream.readResponseHeaders(Http1xStream.java:125)
		at okhttp3.internal.http.HttpEngine.d(HttpEngine.java:723)
		at okhttp3.internal.http.HttpEngine.b(HttpEngine.java:81)
		at okhttp3.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:708)
		at okhttp3.internal.http.HttpEngine.readResponse(HttpEngine.java:563)
		at okhttp3.RealCall.a(RealCall.java:241)
		at okhttp3.RealCall$ApplicationInterceptorChain.proceed(RealCall.java:198)
		at okhttp3.RealCall.a(RealCall.java:160)
		at okhttp3.RealCall.execute(RealCall.java:57)
		at retrofit2.OkHttpCall.execute(OkHttpCall.java:174)
		at retrofit2.adapter.rxjava.RxJavaCallAdapterFactory$RequestArbiter.request(RxJavaCallAdapterFactory.java:171)
		at rx.internal.operators.OperatorSubscribeOn$1$1$1.request(OperatorSubscribeOn.java:80)
		at rx.Subscriber.setProducer(Subscriber.java:211)
		at rx.internal.operators.OperatorSubscribeOn$1$1.setProducer(OperatorSubscribeOn.java:76)
		at rx.Subscriber.setProducer(Subscriber.java:205)
		at retrofit2.adapter.rxjava.RxJavaCallAdapterFactory$CallOnSubscribe.call(RxJavaCallAdapterFactory.java:152)
		at retrofit2.adapter.rxjava.RxJavaCallAdapterFactory$CallOnSubscribe.call(RxJavaCallAdapterFactory.java:138)
		at rx.Observable$2.a(Observable.java:162)
		at rx.Observable$2.call(Observable.java:154)
		at rx.Observable.unsafeSubscribe(Observable.java:8314)
		at rx.internal.operators.OperatorSubscribeOn$1.call(OperatorSubscribeOn.java:94)
		at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
		at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390)
		at java.util.concurrent.FutureTask.run(FutureTask.java:234)
		at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:153)
		at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:267)
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
		at java.lang.Thread.run(Thread.java:841)
  ComposedException 2 :
	java.lang.RuntimeException: Only one Looper may be created per thread
		at android.os.Looper.prepare(Looper.java:78)
		at android.os.Looper.prepare(Looper.java:73)
		at com.tuols.park.Service.retrofit.MySubscriber.a(MySubscriber.java:73)
		at com.tuols.park.Service.retrofit.TuolsSubscriber.onError(TuolsSubscriber.java:34)
		at com.tuols.park.Fragment.MyReserveFragment$1.onError(MyReserveFragment.java:103)
		at rx.observers.SafeSubscriber._onError(SafeSubscriber.java:157)
		at rx.observers.SafeSubscriber.onError(SafeSubscriber.java:120)
		at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.a(OperatorObserveOn.java:254)
		at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.call(OperatorObserveOn.java:186)
		at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
		at android.os.Handler.handleCallback(Handler.java:730)
		at android.os.Handler.dispatchMessage(Handler.java:92)
		at android.os.Looper.loop(Looper.java:137)
		at android.app.ActivityThread.main(ActivityThread.java:5178)
		at java.lang.reflect.Method.invokeNative(Native Method)
		at java.lang.reflect.Method.invoke(Method.java:525)
		at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:745)
		at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:561)
		at dalvik.system.NativeStart.main(Native Method)

rx.exceptions.CompositeException$CompositeExceptionCausalChain: Chain of Causes for CompositeException In Order Received =>
	at com.loc.t.a(Utils.java:123)
	at com.loc.ag.uncaughtException(DynamicExceptionHandler.java:63)
	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:693)
	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:690)
	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:66)
	at android.os.Handler.handleCallback(Handler.java:730)
	at android.os.Handler.dispatchMessage(Handler.java:92)
	at android.os.Looper.loop(Looper.java:137)
	at android.app.ActivityThread.main(ActivityThread.java:5178)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:525)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:745)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:561)
	at dalvik.system.NativeStart.main(Native Method)
Caused by: java.net.SocketTimeoutException: timeout
	at okio.Okio$3.newTimeoutException(Okio.java:207)
	at okio.AsyncTimeout.a(AsyncTimeout.java:261)
	at okio.AsyncTimeout$2.read(AsyncTimeout.java:215)
	at okio.RealBufferedSource.indexOf(RealBufferedSource.java:306)
	at okio.RealBufferedSource.indexOf(RealBufferedSource.java:300)
	at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:196)
	at okhttp3.internal.http.Http1xStream.readResponse(Http1xStream.java:184)
	at okhttp3.internal.http.Http1xStream.readResponseHeaders(Http1xStream.java:125)
	at okhttp3.internal.http.HttpEngine.d(HttpEngine.java:723)
	at okhttp3.internal.http.HttpEngine.b(HttpEngine.java:81)
	at okhttp3.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:708)
	at okhttp3.internal.http.HttpEngine.readResponse(HttpEngine.java:563)
	at okhttp3.RealCall.a(RealCall.java:241)
	at okhttp3.RealCall$ApplicationInterceptorChain.proceed(RealCall.java:198)
	at okhttp3.RealCall.a(RealCall.java:160)
	at okhttp3.RealCall.execute(RealCall.java:57)
	at retrofit2.OkHttpCall.execute(OkHttpCall.java:174)
	at retrofit2.adapter.rxjava.RxJavaCallAdapterFactory$RequestArbiter.request(RxJavaCallAdapterFactory.java:171)
	at rx.internal.operators.OperatorSubscribeOn$1$1$1.request(OperatorSubscribeOn.java:80)
	at rx.Subscriber.setProducer(Subscriber.java:211)
	at rx.internal.operators.OperatorSubscribeOn$1$1.setProducer(OperatorSubscribeOn.java:76)
	at rx.Subscriber.setProducer(Subscriber.java:205)
	at retrofit2.adapter.rxjava.RxJavaCallAdapterFactory$CallOnSubscribe.call(RxJavaCallAdapterFactory.java:152)
	at retrofit2.adapter.rxjava.RxJavaCallAdapterFactory$CallOnSubscribe.call(RxJavaCallAdapterFactory.java:138)
	at rx.Observable$2.a(Observable.java:162)
	at rx.Observable$2.call(Observable.java:154)
	at rx.Observable.unsafeSubscribe(Observable.java:8314)
	at rx.internal.operators.OperatorSubscribeOn$1.call(OperatorSubscribeOn.java:94)
	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390)
	at java.util.concurrent.FutureTask.run(FutureTask.java:234)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:153)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:267)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
	at java.lang.Thread.run(Thread.java:841)
Caused by: java.net.SocketTimeoutException
	at java.net.PlainSocketImpl.read(PlainSocketImpl.java:492)
	at java.net.PlainSocketImpl.access$000(PlainSocketImpl.java:46)
	at java.net.PlainSocketImpl$PlainSocketInputStream.read(PlainSocketImpl.java:241)
	at okio.Okio$2.read(Okio.java:139)
	at okio.AsyncTimeout$2.read(AsyncTimeout.java:211)
	... 33 more
java.net.SocketTimeoutException: timeout
	at okio.Okio$3.newTimeoutException(Okio.java:207)
	at okio.AsyncTimeout.a(AsyncTimeout.java:261)
	at okio.AsyncTimeout$2.read(AsyncTimeout.java:215)
	at okio.RealBufferedSource.indexOf(RealBufferedSource.java:306)
	at okio.RealBufferedSource.indexOf(RealBufferedSource.java:300)
	at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:196)
	at okhttp3.internal.http.Http1xStream.readResponse(Http1xStream.java:184)
	at okhttp3.internal.http.Http1xStream.readResponseHeaders(Http1xStream.java:125)
	at okhttp3.internal.http.HttpEngine.d(HttpEngine.java:723)
	at okhttp3.internal.http.HttpEngine.b(HttpEngine.java:81)
	at okhttp3.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:708)
	at okhttp3.internal.http.HttpEngine.readResponse(HttpEngine.java:563)
	at okhttp3.RealCall.a(RealCall.java:241)
	at okhttp3.RealCall$ApplicationInterceptorChain.proceed(RealCall.java:198)
	at okhttp3.RealCall.a(RealCall.java:160)
	at okhttp3.RealCall.execute(RealCall.java:57)
	at retrofit2.OkHttpCall.execute(OkHttpCall.java:174)
	at retrofit2.adapter.rxjava.RxJavaCallAdapterFactory$RequestArbiter.request(RxJavaCallAdapterFactory.java:171)
	at rx.internal.operators.OperatorSubscribeOn$1$1$1.request(OperatorSubscribeOn.java:80)
	at rx.Subscriber.setProducer(Subscriber.java:211)
	at rx.internal.operators.OperatorSubscribeOn$1$1.setProducer(OperatorSubscribeOn.java:76)
	at rx.Subscriber.setProducer(Subscriber.java:205)
	at retrofit2.adapter.rxjava.RxJavaCallAdapterFactory$CallOnSubscribe.call(RxJavaCallAdapterFactory.java:152)
	at retrofit2.adapter.rxjava.RxJavaCallAdapterFactory$CallOnSubscribe.call(RxJavaCallAdapterFactory.java:138)
	at rx.Observable$2.a(Observable.java:162)
	at rx.Observable$2.call(Observable.java:154)
	at rx.Observable.unsafeSubscribe(Observable.java:8314)
	at rx.internal.operators.OperatorSubscribeOn$1.call(OperatorSubscribeOn.java:94)
	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390)
	at java.util.concurrent.FutureTask.run(FutureTask.java:234)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:153)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:267)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
	at java.lang.Thread.run(Thread.java:841)
Caused by: java.net.SocketTimeoutException
	at java.net.PlainSocketImpl.read(PlainSocketImpl.java:492)
	at java.net.PlainSocketImpl.access$000(PlainSocketImpl.java:46)
	at java.net.PlainSocketImpl$PlainSocketInputStream.read(PlainSocketImpl.java:241)
	at okio.Okio$2.read(Okio.java:139)
	at okio.AsyncTimeout$2.read(AsyncTimeout.java:211)
	... 33 more
java.net.SocketTimeoutException
	at java.net.PlainSocketImpl.read(PlainSocketImpl.java:492)
	at java.net.PlainSocketImpl.access$000(PlainSocketImpl.java:46)
	at java.net.PlainSocketImpl$PlainSocketInputStream.read(PlainSocketImpl.java:241)
	at okio.Okio$2.read(Okio.java:139)
	at okio.AsyncTimeout$2.read(AsyncTimeout.java:211)
	at okio.RealBufferedSource.indexOf(RealBufferedSource.java:306)
	at okio.RealBufferedSource.indexOf(RealBufferedSource.java:300)
	at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:196)
	at okhttp3.internal.http.Http1xStream.readResponse(Http1xStream.java:184)
	at okhttp3.internal.http.Http1xStream.readResponseHeaders(Http1xStream.java:125)
	at okhttp3.internal.http.HttpEngine.d(HttpEngine.java:723)
	at okhttp3.internal.http.HttpEngine.b(HttpEngine.java:81)
	at okhttp3.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:708)
	at okhttp3.internal.http.HttpEngine.readResponse(HttpEngine.java:563)
	at okhttp3.RealCall.a(RealCall.java:241)
	at okhttp3.RealCall$ApplicationInterceptorChain.proceed(RealCall.java:198)
	at okhttp3.RealCall.a(RealCall.java:160)
	at okhttp3.RealCall.execute(RealCall.java:57)
	at retrofit2.OkHttpCall.execute(OkHttpCall.java:174)
	at retrofit2.adapter.rxjava.RxJavaCallAdapterFactory$RequestArbiter.request(RxJavaCallAdapterFactory.java:171)
	at rx.internal.operators.OperatorSubscribeOn$1$1$1.request(OperatorSubscribeOn.java:80)
	at rx.Subscriber.setProducer(Subscriber.java:211)
	at rx.internal.operators.OperatorSubscribeOn$1$1.setProducer(OperatorSubscribeOn.java:76)
	at rx.Subscriber.setProducer(Subscriber.java:205)
	at retrofit2.adapter.rxjava.RxJavaCallAdapterFactory$CallOnSubscribe.call(RxJavaCallAdapterFactory.java:152)
	at retrofit2.adapter.rxjava.RxJavaCallAdapterFactory$CallOnSubscribe.call(RxJavaCallAdapterFactory.java:138)
	at rx.Observable$2.a(Observable.java:162)
	at rx.Observable$2.call(Observable.java:154)
	at rx.Observable.unsafeSubscribe(Observable.java:8314)
	at rx.internal.operators.OperatorSubscribeOn$1.call(OperatorSubscribeOn.java:94)
	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390)
	at java.util.concurrent.FutureTask.run(FutureTask.java:234)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:153)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:267)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
	at java.lang.Thread.run(Thread.java:841)
```
onError not call in Subscriber onError, so I can't catch this error

**Comment by JakeWharton** [comment]
`onError` is clearly called and is crashing:
```
    java.lang.RuntimeException: Only one Looper may be created per thread
        at android.os.Looper.prepare(Looper.java:78)
        at android.os.Looper.prepare(Looper.java:73)
        at com.tuols.park.Service.retrofit.MySubscriber.a(MySubscriber.java:73)
        at com.tuols.park.Service.retrofit.TuolsSubscriber.onError(TuolsSubscriber.java:34)
        at com.tuols.park.Fragment.MyReserveFragment$1.onError(MyReserveFragment.java:103)
```
