### ISSUE TITLE
  java.lang.NoClassDefFoundError: retrofit2.Platform$Android

### ISSUE THREAD

**Issue by klisly** [square/retrofit#1801]
Hi, I use retrofit in my app,  when my app is running on Android 6.0, it work well.
but , when my app running on android 4.3 , I got problem, the log tip as below.
Any body can help me fix it ?
Thank you very much.
> E/Parcel: Reading a NULL string not supported here.
05-18 00:25:10.076 16398-16398/com.baidu.buidemo E/dalvikvm: Could not find class 'retrofit2.Platform$Android', referenced from method retrofit2.Platform.findPlatform
05-18 00:25:10.076 16398-16398/com.baidu.buidemo E/dalvikvm: Could not find class 'retrofit2.Platform$Java8', referenced from method retrofit2.Platform.findPlatform
05-18 00:25:10.076 16398-16398/com.baidu.buidemo E/dalvikvm: Could not find class 'retrofit2.Platform$IOS', referenced from method retrofit2.Platform.findPlatform
05-18 00:25:10.076 16398-16398/com.baidu.buidemo E/dalvikvm: Could not find class 'retrofit2.ExecutorCallAdapterFactory', referenced from method retrofit2.Platform.defaultCallAdapterFactory
05-18 00:25:10.076 16398-16398/com.baidu.buidemo E/AndroidRuntime: FATAL EXCEPTION: main
                                                                   java.lang.NoClassDefFoundError: retrofit2.Platform$Android
                                                                       at retrofit2.Platform.findPlatform(Platform.java:39)
                                                                       at retrofit2.Platform.<clinit>(Platform.java:29)
                                                                       at retrofit2.Retrofit$Builder.<init>(Retrofit.java:402)
                                                                       at com.baidu.welink.application.WeLinkApplication.initHttpFramework(WeLinkApplication.java:46)
                                                                       at com.baidu.welink.application.WeLinkApplication.onCreate(WeLinkApplication.java:27)
                                                                       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1010)
                                                                       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4507)
                                                                       at android.app.ActivityThread.access$1300(ActivityThread.java:144)
                                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1319)
                                                                       at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                       at android.os.Looper.loop(Looper.java:137)
                                                                       at android.app.ActivityThread.main(ActivityThread.java:5166)
                                                                       at java.lang.reflect.Method.invokeNative(Native Method)
                                                                       at java.lang.reflect.Method.invoke(Method.java:525)
                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:745)
                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:561)
                                                                       at dalvik.system.NativeStart.main(Native Method)

**Comment by artem-zinnatullin** [comment]
You probably use multidex, make sure you initialize it in the app class
correctly.

**Comment by irfaan008** [comment]
worked for me. Thanks.
