### ISSUE TITLE
Error when import module that uses retrofit

### ISSUE THREAD

**Issue by Ivanfulano** [square/retrofit#1811]
Hi all,
I have a library that uses library for communication. I´m using
    `compile 'com.google.code.gson:gson:2.6.2'
    compile 'com.squareup.retrofit2:retrofit:2.0.2'
    compile 'com.squareup.retrofit2:converter-gson:2.0.2'
    compile 'com.squareup.okhttp3:okhttp:3.2.0'
    compile 'com.squareup.okhttp3:okhttp-urlconnection:3.2.0'`

I add the library as new module into my app and when I try to execute the request I get this error
05-23 15:00:02.938 11152-11152/com.xxxxxx.android.demoapp E/AndroidRuntime: FATAL EXCEPTION: main
Process: com.xxxxxx.android.demoapp, PID: 11152
java.lang.NoClassDefFoundError: Failed resolution of: Lretrofit2/Retrofit$Builder;
at com.xxxxxx.android.airline.BagDeviceService.bagResourceRequest(BagDeviceService.java:1531)
at com.xxxxxx.android.airline.BagDeviceService.access$1700(BagDeviceService.java:74)
at com.xxxxxx.android.airline.BagDeviceService$MyConnectionListen.response_getUBI(BagDeviceService.java:876)
at com.xxxxxx.android.airline.LibFunction$TagConnectionCallback.response_getUBI(LibFunction.java:275)
at com.library.TagServiceImpl$Connection$ConnOperator$5.onCmdResp(TagServiceImpl.java:729)
at com.library.TagServiceImpl$Connection.rxNotifyResult(TagServiceImpl.java:1118)
at com.library.TagServiceImpl$RxHandler.handleMessage(TagServiceImpl.java:261)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:145)
at android.app.ActivityThread.main(ActivityThread.java:5953)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1400)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1195)
Caused by: java.lang.ClassNotFoundException: Didn't find class "retrofit2.Retrofit$Builder" on path: DexPathList[[dex file "/data/data/com.xxxxxx.android.demoapp/files/instant-run/dex/slice-tagblelib_f9220a7ed94f1bf006b8b3367a8fc8e40563f0d6-classes.dex", dex file "/data/data/com.xxxxxx.android.demoapp/files/instant-run/dex/slice-support-annotations-23.0.0_5d6e79e474c3bbd8b9e47d22e54f34d08ce5fed6-classes.dex", dex file "/data/data/com.xxxxxx.android.demoapp/files/instant-run/dex/slice-slice_9-classes.dex", dex file "/data/data/com.xxxxxx.android.demoapp/files/instant-run/dex/slice-slice_8-classes.dex", dex file "/data/data/com.xxxxxx.android.demoapp/files/instant-run/dex/slice-slice_7-classes.dex", dex file "/data/data/com.xxxxxx.android.demoapp/files/instant-run/dex/slice-slice_6-classes.dex", dex file "/data/data/com.xxxxxx.android.demoapp/files/instant-run/dex/slice-slice_5-classes.dex", dex file "/data/data/com.xxxxxx.android.demoapp/files/instant-run/dex/slice-slice_4-classes.dex", dex file "/data/data/com.xxxxxx.android.demoapp/files/instant-run/dex/slice-slice_3-classes.dex", dex file "/data/data/com.xxxxxx.android.demoapp/files/instant-run/dex/slice-slice_2-classes.dex", dex file "/data/data/com.xxxxxx.android.demoapp/files/instant-run/dex/slice-slice_1-classes.dex", dex file "/data/data/com.xxxxxx.android.demoapp/files/instant-run/dex/slice-slice_0-classes.dex", dex file "/data/data/com.xxxxxx.android.demoapp/files/instant-run/dex/slice-library-1.0.19_c26eb538d5bf845516162750ec2558a9f6daec3e-classes.dex", dex file "/data/data/com.xxxxxx.android.demoapp/files/instant-run/dex/slice-internal_impl-23.0.0_d97febc8cd7e165ea0fef0e7fbdaf6d2641a3d97-classes.dex", dex file "/data/data/com.xxxxxx.android.demoapp/files/instant-run/dex/slice-gson-2.6.2_f77f83325e37c6fd830a2edaf4083812f972e570-classes.dex", dex file "/data/data/com.xxxxxx.android.demoapp/files/instant-run/dex/slice-com.android.support-support-v4-23.0.0_73f3433966f90e2e8a5cacff323e13c917670c21-classes.dex", dex file "/data/data/com.xxxxxx.android.demoapp/files/instant-run/dex/slice-com.android.support-recyclerview-v7-23.0.0_ad47fa1abcbece3d63fe0d8c5524da196e57428f-classes.dex", dex file "/data/data/com.xxxxxx.android.demoapp/files/instant-run/dex/slice-com.android.support-design-23.0.0_e5dab1decbd1c36e6adc68d9b26d4def9bcb2eb7-classes.dex", dex file "/data/data/com.xxxxxx.android.demoapp/files/instant-run/dex/slice-com.android.support-appcompat-v7-23.0.0_8375a050f7854f70c876fade3d8ec9d0030031eb-classes.dex"],nativeLibraryDirectories=[/vendor/lib, /system/lib, /vendor/lib, /system/lib]]
at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
at com.android.tools.fd.runtime.IncrementalClassLoader$DelegateClassLoader.findClass(Inc

I tried by usin multidex as the explain in this post but I get the same error
[http://stackoverflow.com/questions/36649121/java-lang-noclassdeffounderror-okhttp3-okhttpclientbuilder](http://stackoverflow.com/questions/36649121/java-lang-noclassdeffounderror-okhttp3-okhttpclientbuilder)

Thanks in advance

**Comment by JakeWharton** [comment]
Looks like an instant run bug. Do a clean build and fresh deploy of the app.

**Comment by Ivanfulano** [comment]
Hi Jake, I clean the project, unsinstall the app from the device, install the app and I get the error again. So I´m not sure that it´s an instant run bug

**Comment by JakeWharton** [comment]
Are you using multidex? This is a packaging problem with your build system,
not a problem with Retrofit, so there's all kinds of things to check and
I'm just going to be guessing.

**Comment by Ivanfulano** [comment]
Hi Jake,
I implemented becasue I read it in stackoverflow but i didn work neither.
I implemented Volley and it worked perfectly
Thanks a lot for the support

**Comment by arniesaha** [comment]
Hi @Ivanfulano
Did you manage to solve this? Using retrofit in a module?

I've been facing the same issue when using retrofit 2.4.0 in a module. But works fine, if imported in the app's gradle.

Any ideas is much appreciated.

Thanks,
Arnab
