### ISSUE TITLE
okhttp3.ResponseBody.charStream()' on a null object reference with proguard

### ISSUE THREAD

**Issue by thanawatSuj** [square/retrofit#1856]
I found with error when enable proguard true in debug mode but disable proguard it not error.
`java.lang.NullPointerException: Attempt to invoke virtual method 'java.io.Reader okhttp3.ResponseBody.charStream()' on a null object reference
                                                                           at retrofit2.converter.gson.GsonResponseBodyConverter.convert(Unknown Source)
                                                                           at retrofit2.converter.gson.GsonResponseBodyConverter.convert(Unknown Source)
                                                                           at com.thanawat.boonterm.service.h.a(Unknown Source)
                                                                           at com.thanawat.boonterm.login.LoginActivity$3.onResponse(Unknown Source)
                                                                           at retrofit2.ExecutorCallAdapterFactory$ExecutorCallbackCall$1$1.run(Unknown Source)
                                                                           at android.os.Handler.handleCallback(Handler.java:739)
                                                                           at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                           at android.os.Looper.loop(Looper.java:158)
                                                                           at android.app.ActivityThread.main(ActivityThread.java:7224)
                                                                           at java.lang.reflect.Method.invoke(Native Method)
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)`

My proguard 
`# OkHttp
-keepattributes Signature
-keepattributes *Annotation*
-keep class okhttp3.** { *; }
-keep interface okhttp3.** { *; }
-dontwarn okhttp3.**
-keep class okhttp3.ResponseBody

#Okio
-keep class sun.misc.Unsafe { *; }
-dontwarn java.nio.file.*
-dontwarn org.codehaus.mojo.animal_sniffer.IgnoreJRERequirement
-dontwarn okio.**

-dontwarn retrofit2.**
-keep class retrofit2.** { *; }
-keepattributes Signature
-keepattributes Exceptions
-keepclasseswithmembers class * {
    @retrofit2.http.* <methods>;
}`

**Comment by swankjesse** [comment]
Disable ProGuard?

**Comment by thanawatSuj** [comment]
can,t disable  bcoz require proguard to security this app

**Comment by JakeWharton** [comment]
This is a configuration problem of ProGuard, not Retrofit, so we aren't really going to be able to help. Analyze your mapping.txt to see what ProGuard is changing that is causing this and then consult its documentation for the proper rules to avoid it.
