### ISSUE TITLE
GsonConverterFactory and @Streaming error

### ISSUE THREAD

**Issue by henjue** [square/retrofit#1897]
```java
retrofit = new Retrofit.Builder()
                .baseUrl(BuildConfig.API_HOST)
                .client(client)
                .addConverterFactory(GsonConverterFactory.create(gson))
                .addCallAdapterFactory(RxJavaCallAdapterFactory.create())
                .build();
```
```java
public interface CommonService {
    @GET
    @Streaming
    Observable<Response<ResponseBody>> downloadFile(@Url String url);
```
```java
String downloadUrl="http://180.153.105.142/dd.myapp.com/16891/9320A327474DDB7C4A2EC43F1A0159E4.apk?mkey=577c5556787a7790&f=5e8c&c=0&fsname=com.mentornow_2.6.4_24.apk&p=.apk";
retrofit.create(CommonService.class).downloadFile(downloadUrl).flatMap(responseBodyResponse -> {
                file = mActivity.getFileStreamPath("temp");
                return IOUtils.writeResponseBodyToDisk(responseBodyResponse.body(), file);
            }).subscribe(progress -> {
                logger.d("download audio file:%.2f", progress);
            });
```
IOUtils
```java
public class IOUtils {
    private IOUtils() {
    }

    public static Observable<Double> writeResponseBodyToDisk(ResponseBody body, File file) {
        return Observable.create(new Observable.OnSubscribe<Double>() {
            @Override
            public void call(Subscriber<? super Double> subscriber) {


                InputStream inputStream = null;
                OutputStream outputStream = null;
                try {
                    byte[] fileReader = new byte[4096];
                    long fileSize = body.contentLength();
                    long fileSizeDownloaded = 0;

                    inputStream = body.byteStream();
                    outputStream = new FileOutputStream(file);
                    while (true) {
                        int read = inputStream.read(fileReader);
                        if (read == -1) {
                            break;
                        }
                        outputStream.write(fileReader, 0, read);
                        fileSizeDownloaded += read;
                        double percent = fileSizeDownloaded / fileSize;
                        DecimalFormat df = new DecimalFormat("#.00");
                        subscriber.onNext(Double.parseDouble(df.format(percent)));
                    }
                    outputStream.flush();
                    subscriber.onCompleted();
                } catch (IOException e) {
                    subscriber.onError(e);
                } finally {
                    closeQuietly(inputStream);
                   closeQuietly(outputStream);
                }
            }
        });


    }
}
```

## console
```
 <-- 200 OK http://180.153.105.142/dd.myapp.com/16891/9320A327474DDB7C4A2EC43F1A0159E4.apk?mkey=577c5556787a7790&f=5e8c&c=0&fsname=com.mentornow_2.6.4_24.apk&p=.apk (5ms)
07-06 11:19:09.993 com.mentornow.app.android I/Okhttp: Server: 3Gdown_DK
07-06 11:19:09.993 com.mentornow.app.android I/Okhttp: Connection: keep-alive
07-06 11:19:09.993 com.mentornow.app.android I/Okhttp: Date: Wed, 06 Jul 2016 03:02:19 GMT
07-06 11:19:09.993 com.mentornow.app.android I/Okhttp: Cache-Control: max-age=31536000
07-06 11:19:09.994 com.mentornow.app.android I/Okhttp: Expires: Thu, 06 Jul 2017 03:02:19 GMT
07-06 11:19:09.994 com.mentornow.app.android I/Okhttp: Last-Modified: Fri, 01 Jul 2016 16:47:07 GMT
07-06 11:19:09.994 com.mentornow.app.android I/Okhttp: Content-Type: application/vnd.android.package-archive
07-06 11:19:09.994 com.mentornow.app.android I/Okhttp: Content-Length: 7070479
07-06 11:19:09.994 com.mentornow.app.android I/Okhttp: Content-disposition: attachment; filename=com.mentornow_2.6.4_24.apk
07-06 11:19:09.994 com.mentornow.app.android I/Okhttp: X-Cache-Lookup: Hit From DiskTank Chunk Forward
07-06 11:19:09.994 com.mentornow.app.android I/Okhttp: X-Cache-Lookup: Hit From Disktank
07-06 11:19:09.994 com.mentornow.app.android I/Okhttp: Content-disposition: attachment; filename=com.mentornow_2.6.4_24.apk
07-06 11:19:09.994 com.mentornow.app.android I/Okhttp: OkHttp-Sent-Millis: 1467774140855
07-06 11:19:09.994 com.mentornow.app.android I/Okhttp: OkHttp-Received-Millis: 1467774140869
07-06 11:19:10.400 com.mentornow.app.android I/Okhttp: PK����a��Hc0+J����h���������AndroidManifest.xml��������	t\ŕ�Km0/x�����Ֆ�e�����ū$I�m6[�dIXRK^ �6;,Ƭ�f&�%���d&��af2f9��9'���n��]��n����\�����u뾪z��<H��]J�Ij��>R�Ճ�O�͇���a���^����
                                                       6&G�9�����(�Z�]��C��!�F��`�`7���^���
                                                       �t�U��D�>|�J�|{�:-�T+��z����K-�g�P��Q��O��༏�u���	�O��=8���z�~��>����v�i#��8;��n�H��OB��Þ���w�k�[�Hs�*�&�
                                                       `P>�~�ڎ~��N�N�ʺɻj�D�NS���ȧ*U��1�T�w�<#�58��[���Qk�w�+53�B�B�?���W�}-�E�7��V�k��RX�ִ4���U�*YM�%+�Pi-�V�9`���
                                                       Vt�Q�H�.zK�%B�J���up?����/ZA5����^g,#�l�r��+O
                                                       �6��*�;Ţ]k�^u�
                                                       ��.x�c�Q9ά'��J��D�U�v9r1x���9("������3��ں�2��4lb3Pe��N�댘�7#E��J�*�,"������Ei��30������Ћ1+�4�5���(��X�N�{h�t�bޜ: z��ᤣ�ZF(��Z�jՌ��'��g��GN/]E�O9�q��2�Pp4#"8#���yP�f��4�������L���>�2?MJ:���qn�mGwᕓi�8�9z +�&��:�3�*#���G�ԟ���s�8*�4�L;>���̾�S�lfF�j~ڹ�F��2Հcj�o�o{�{/��Z���K)7*ϱVv�.��z�?��]����t��ꋲ�R�ѯ��5�y�J)���R���F�Ng���4�+�{-��5g�)層��h��zV��n_T�#�p���W6Q�c�wG������z���ۇ���plc�b�N�N�i��e3eA#߉7�}X����_��kb�|lЩ�����R������C�>�W���Y�VJ�v�������xV5Py��U�hQ��5�ߑdzy���K�Y�-���ɌNʼ�X/���w�rF�69k�e��I�����՟SN+x��u�Ƭ̞*�I�p?�nf��}Il�1�#��<�k��H�t���r����2�K��1=4;�o����+��E#�?)ݨ$�)S[�Qϒ�R�?�3h��{o��,U�5�bޙ�y�x�ft�<�h����{웁؊|)���}nf��R�)��K�F��<����\;.�<�i���渳2��d�CW��2���xڮ��RҟݷR��L���5 y�6��P�R��fX�Q*s�3�<��5U��ܽ�����	�R�O�-<]��~:���2��ǀt�b΅|�{��?s_˨�R�N��˝���Y�$z�*�s��/�d�+�^L�
                                                       t�R]���k�H	�����2�0�>��cF�N�뇓���Z]j��]UDm��)��Q1�<:��<��CZIw�n9��݆Ycv�x4vm��
07-06 11:19:10.404 com.mentornow.app.android I/Okhttp: <-- END HTTP (7070479-byte body)
07-06 11:19:10.404 com.mentornow.app.android I/art: Background sticky concurrent mark sweep GC freed 0(0B) AllocSpace objects, 1(12MB) LOS objects, 4% free, 66MB/69MB, paused 1.251ms total 156.675ms
07-06 11:19:10.407 com.mentornow.app.android W/System.err: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 1 path $
07-06 11:19:10.407 com.mentornow.app.android W/System.err:     at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1566)
07-06 11:19:10.407 com.mentornow.app.android W/System.err:     at com.google.gson.stream.JsonReader.checkLenient(JsonReader.java:1416)
07-06 11:19:10.407 com.mentornow.app.android W/System.err:     at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:597)
07-06 11:19:10.407 com.mentornow.app.android W/System.err:     at com.google.gson.stream.JsonReader.peek(JsonReader.java:429)
07-06 11:19:10.407 com.mentornow.app.android W/System.err:     at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:201)
07-06 11:19:10.407 com.mentornow.app.android W/System.err:     at com.google.gson.TypeAdapter.fromJson(TypeAdapter.java:260)
07-06 11:19:10.407 com.mentornow.app.android W/System.err:     at com.mentornow.app.android.network.compontent.GsonResponseBodyConverter.convert(GsonResponseBodyConverter.java:23)
07-06 11:19:10.407 com.mentornow.app.android W/System.err:     at com.mentornow.app.android.network.compontent.GsonResponseBodyConverter.convert(GsonResponseBodyConverter.java:13)
07-06 11:19:10.407 com.mentornow.app.android W/System.err:     at retrofit2.ServiceMethod.toResponse(ServiceMethod.java:116)
07-06 11:19:10.407 com.mentornow.app.android W/System.err:     at retrofit2.OkHttpCall.parseResponse(OkHttpCall.java:211)
07-06 11:19:10.407 com.mentornow.app.android W/System.err:     at retrofit2.OkHttpCall.execute(OkHttpCall.java:174)
07-06 11:19:10.407 com.mentornow.app.android W/System.err:     at com.mentornow.app.android.network.compontent.rxjava.RxJavaCallAdapterFactory$RequestArbiter.request(RxJavaCallAdapterFactory.java:194)
07-06 11:19:10.407 com.mentornow.app.android W/System.err:     at rx.internal.operators.OperatorSubscribeOn$1$1$1.request(OperatorSubscribeOn.java:80)
07-06 11:19:10.407 com.mentornow.app.android W/System.err:     at rx.Subscriber.setProducer(Subscriber.java:211)
07-06 11:19:10.407 com.mentornow.app.android W/System.err:     at rx.internal.operators.OperatorSubscribeOn$1$1.setProducer(OperatorSubscribeOn.java:76)
07-06 11:19:10.407 com.mentornow.app.android W/System.err:     at com.mentornow.app.android.network.compontent.rxjava.RxJavaCallAdapterFactory$CallOnSubscribe.call(RxJavaCallAdapterFactory.java:174)
07-06 11:19:10.407 com.mentornow.app.android W/System.err:     at com.mentornow.app.android.network.compontent.rxjava.RxJavaCallAdapterFactory$CallOnSubscribe.call(RxJavaCallAdapterFactory.java:159)
07-06 11:19:10.407 com.mentornow.app.android W/System.err:     at rx.Observable.unsafeSubscribe(Observable.java:8741)
07-06 11:19:10.407 com.mentornow.app.android W/System.err:     at rx.internal.operators.OperatorSubscribeOn$1.call(OperatorSubscribeOn.java:94)
07-06 11:19:10.407 com.mentornow.app.android W/System.err:     at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
07-06 11:19:10.407 com.mentornow.app.android W/System.err:     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
07-06 11:19:10.407 com.mentornow.app.android W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
07-06 11:19:10.407 com.mentornow.app.android W/System.err:     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272)
07-06 11:19:10.407 com.mentornow.app.android W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
07-06 11:19:10.407 com.mentornow.app.android W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
07-06 11:19:10.407 com.mentornow.app.android W/System.err:     at java.lang.Thread.run(Thread.java:761)
```

**Comment by henjue** [comment]
Through the source code I am sure the reason is because I tried the com.squareup.okhttp.ResponseBody, should use okhttp3.ResponseBody
