### ISSUE TITLE
I got that error " java.io.IOException: unexpected end of stream on okhttp3.Address@34845fbb"

### ISSUE THREAD

**Issue by lkhore** [square/retrofit#1898]
java.io.IOException: unexpected end of stream on okhttp3.Address@34845fbb]
                                                                   java.io.IOException: unexpected end of stream on okhttp3.Address@34845fbb
                                                                       at okhttp3.internal.http.Http1xStream.readResponse(Http1xStream.java:199)
                                                                       at okhttp3.internal.http.Http1xStream.readResponseHeaders(Http1xStream.java:125)
                                                                       at okhttp3.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:775)
                                                                       at okhttp3.internal.http.HttpEngine.access$200(HttpEngine.java:86)
                                                                       at okhttp3.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:760)
                                                                       at okhttp3.internal.http.HttpEngine.readResponse(HttpEngine.java:613)
                                                                       at okhttp3.RealCall.getResponse(RealCall.java:244)
                                                                       at okhttp3.RealCall$ApplicationInterceptorChain.proceed(RealCall.java:201)
                                                                       at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:163)
                                                                       at okhttp3.RealCall.access$100(RealCall.java:30)
                                                                       at okhttp3.RealCall$AsyncCall.execute(RealCall.java:127)
                                                                       at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
                                                                       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                       at java.lang.Thread.run(Thread.java:818)
                                                                    Caused by: java.io.EOFException: \n not found: size=0 content=…
                                                                       at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:215)
                                                                       at okhttp3.internal.http.Http1xStream.readResponse(Http1xStream.java:184)
                                                                       at okhttp3.internal.http.Http1xStream.readResponseHeaders(Http1xStream.java:125) 
                                                                       at okhttp3.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:775) 
                                                                       at okhttp3.internal.http.HttpEngine.access$200(HttpEngine.java:86) 
                                                                       at okhttp3.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:760) 
                                                                       at okhttp3.internal.http.HttpEngine.readResponse(HttpEngine.java:613) 
                                                                       at okhttp3.RealCall.getResponse(RealCall.java:244) 
                                                                       at okhttp3.RealCall$ApplicationInterceptorChain.proceed(RealCall.java:201) 
                                                                       at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:163) 
                                                                       at okhttp3.RealCall.access$100(RealCall.java:30) 
                                                                       at okhttp3.RealCall$AsyncCall.execute(RealCall.java:127) 
                                                                       at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32) 
                                                                       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
                                                                       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
                                                                       at java.lang.Thread.run(Thread.java:818)

**Comment by JakeWharton** [comment]
This is an OkHttp issue not Retrofit. It's already tracked here: https://github.com/square/okhttp/issues/1517
