### ISSUE TITLE
Exception while using Protobuf converter in Retrofit ? I am trying to deserialise Json response using proto buf

### ISSUE THREAD

**Issue by pradeepmallika** [square/retrofit#1911]
What kind of issue is this?

 - [ ] Question. This issue tracker is not the place for questions. If you want to ask how to do
       something, or to understand why something isn't working the way you expect it to, use Stack
       Overflow. https://stackoverflow.com/questions/tagged/retrofit

 - [ ] Bug report. If you’ve found a bug, spend the time to write a failing test. Bugs with tests
       get fixed. Here’s an example: https://gist.github.com/swankjesse/6608b4713ad80988cdc9

 - [ ] Feature Request. Start by telling us what problem you’re trying to solve. Often a solution
       already exists! Don’t send pull requests to implement new features without first getting our
       support. Sometimes we leave features out on purpose to keep the project small.

**Comment by pradeepmallika** [comment]
java.lang.RuntimeException: com.google.protobuf.InvalidProtocolBufferException: Protocol message tag had invalid wire type.
        at retrofit2.converter.protobuf.ProtoResponseBodyConverter.convert(ProtoResponseBodyConverter.java:40)
        at retrofit2.converter.protobuf.ProtoResponseBodyConverter.convert(ProtoResponseBodyConverter.java:26)
        at retrofit2.ServiceMethod.toResponse(ServiceMethod.java:116)
        at retrofit2.OkHttpCall.parseResponse(OkHttpCall.java:211)
        at retrofit2.OkHttpCall.execute(OkHttpCall.java:174)
        at com.testing.InvokeTestingPOS.main(InvokeTestingPOS.java:31)
Caused by: com.google.protobuf.InvalidProtocolBufferException: Protocol message tag had invalid wire type.
        at com.google.protobuf.InvalidProtocolBufferException.invalidWireType(InvalidProtocolBufferException.java:99)
        at com.google.protobuf.UnknownFieldSet$Builder.mergeFieldFrom(UnknownFieldSet.java:515)
        at com.google.protobuf.GeneratedMessage.parseUnknownField(GeneratedMessage.java:205)
        at json2pb.TestingInfo.<init>(TestingInfo.java:61)
        at json2pb.TestingInfo.<init>(TestingInfo.java:9)
        at json2pb.TestingInfo$1.parsePartialFrom(TestingInfo.java:131)
        at json2pb.TestingInfo$1.parsePartialFrom(TestingInfo.java:126)
        at com.google.protobuf.AbstractParser.parsePartialFrom(AbstractParser.java:192)
        at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:209)
        at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:49)
        at retrofit2.converter.protobuf.ProtoResponseBodyConverter.convert(ProtoResponseBodyConverter.java:38)

**Comment by JakeWharton** [comment]
This is not a Retrofit bug. The data in the HTTP response does not match what your application expects (a protocol buffer).

**Comment by srsudar** [comment]
In my case I wasn't adding `Content-Type: 'application/x-protobuf'` to my response. Even after adding that, I was still not serving a binary blob b/c node express was also appending `charset=utf-8` to the `Content-Type`. I needed to change the way I was responding so that it had only the correct header and the response was a binary blob.
