### ISSUE TITLE
How to send an string array for a HTTP Delete method

### ISSUE THREAD

**Issue by gushoubang** [square/retrofit#1940]
because it can‘t support body

**Comment by JakeWharton** [comment]
you can use `@HTTP(method = "DELETE", hasBody = true)` for the HTTP method annotation.

**Comment by gushoubang** [comment]
but I use it like this,and it's error

```
    @Headers(ANDROIRHEADER)
    @HTTP(method = "DELETE", hasBody = true)
    @DELETE("api/messages")
    Observable<JsonElement> deleteMessage(@Header("token") String token, @Body MessageIds messageRead);
```
the error like this

 java.lang.IllegalArgumentException: Only one HTTP method is allowed. Found: DELETE and DELETE.
                                                                   for method ApiService.deleteMessage
                                                                   at retrofit2.ServiceMethod$Builder.methodError(ServiceMethod.java:720)
                                                                   at retrofit2.ServiceMethod$Builder.methodError(ServiceMethod.java:711)
                                                                   at retrofit2.ServiceMethod$Builder.parseHttpMethodAndPath(ServiceMethod.java:280)
                                                                   at retrofit2.ServiceMethod$Builder.parseMethodAnnotation(ServiceMethod.java:258)
                                                                   at retrofit2.ServiceMethod$Builder.build(ServiceMethod.java:170)
                                                                   at retrofit2.Retrofit.loadServiceMethod(Retrofit.java:166)
                                                                   at retrofit2.Retrofit$1.invoke(Retrofit.java:145)
                                                                   at java.lang.reflect.Proxy.invoke(Proxy.java:393)
                                                                   at $Proxy0.deleteMessage(Unknown Source)
                                                                   at com.dituwuyou.adapter.MessageAdapter.deleteSingleMessage(MessageAdapter.java:311)
                                                                   at com.dituwuyou.adapter.MessageAdapter.removeItem(MessageAdapter.java:363)
                                                                   at com.dituwuyou.ui.MessageActivity.onClick(MessageActivity.java:150)
                                                                   at android.view.View.performClick(View.java:5204)
                                                                   at android.view.View$PerformClick.run(View.java:21153)
                                                                   at android.os.Handler.handleCallback(Handler.java:739)
                                                                   at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                   at android.os.Looper.loop(Looper.java:148)
                                                                   at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                   at java.lang.reflect.Method.invoke(Native Method)
                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by JakeWharton** [comment]
Remove @DELETE and put the path on @HTTP

**Comment by gushoubang** [comment]
OK
