### ISSUE TITLE
PUT and DELETE request Error

### ISSUE THREAD

**Issue by mdsirdiu** [square/retrofit#1948]
GET and POST working fine for me. When use PUT or DELETE then getting error. like bellow

> java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.mdsir.mess.ModelExpenseSettiings.getIsLogin()' on a null object reference
                                                                  at com.mdsir.mess.ExpenseSettings$1.onResponse(ExpenseSettings.java:69)
                                                                  at retrofit2.ExecutorCallAdapterFactory$ExecutorCallbackCall$1$1.run(ExecutorCallAdapterFactory.java:68)

My code working fine with GET and POST request. My code given bellow...

```
public class ModelExpenseSettiings {
    public String isLogin;
    public String getIsLogin() {
        return isLogin;
    }
}
```
```
public class Mdsir {
    @SerializedName("name")
    private String name;

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }
}
```

```
@POST("index.php/api/mdsir")
    Call<ModelExpenseSettiings> update(@Body Mdsir mdsir);
```

```
ApiInterface mApiService = this.getInterfaceService();
        Mdsir mdsir = new Mdsir();
        mdsir.setName("Safiqul Islam");
        Call<ModelExpenseSettiings> mService = mApiService.update(mdsir);
        mService.enqueue(new Callback<ModelExpenseSettiings>() {
            @Override
            public void onResponse(Call<ModelExpenseSettiings> call, Response<ModelExpenseSettiings> response) {
                ModelExpenseSettiings mLoginObject = response.body();
                String returnedResponse = mLoginObject.getIsLogin();
                Toast.makeText(getApplicationContext(),returnedResponse,Toast.LENGTH_LONG).show();
            }
            @Override
            public void onFailure(Call<ModelExpenseSettiings> call, Throwable t) {
                call.cancel();
                Toast.makeText(ExpenseSettings.this, t", Toast.LENGTH_LONG).show();
            }
        });
```

```
private ApiInterface getInterfaceService() {
        Retrofit retrofit = new Retrofit.Builder()
                .baseUrl(BASE_URL)
                .addConverterFactory(GsonConverterFactory.create())
                .build();
        final ApiInterface mInterfaceService = retrofit.create(ApiInterface.class);
        return mInterfaceService;
    }
```

But getting error when use
```
@PUT("index.php/api/mdsir")
    Call<ModelExpenseSettiings> update(@Body Mdsir mdsir);
```
OR

```
@DELETE("index.php/api/mdsir")
    Call<ModelExpenseSettiings> update(@Body Mdsir mdsir);
```

PLEASE help me how to fix it.

**Comment by JakeWharton** [comment]
The response.body() is null. You didn't check response.isSuccessful() first
to check for non-200 response codes.

**Comment by mdsirdiu** [comment]
I have checked response.isSuccessful() and return false.

**Comment by JakeWharton** [comment]
Right. This is why body() is null. You need to handle this case.

**Comment by mdsirdiu** [comment]
But server return {"isLogin":"ddd"}
