### ISSUE TITLE
Do costly reflection in mian thread even using subscribeOn()

### ISSUE THREAD

**Issue by CodingPapi** [square/retrofit#1974]
Retrofit interface that return **observable**

```
interface WeatherApi {
  companion object {
      val HOST = "https://api.heweather.com/x3/"
      val KEY = "41054a8f1d1a4ac992b1683e47a50146"
  }

  @GET("weather")
  fun getWeather(@Query("city") city: String, @Query("key") key: String) : Observable<Weather>
}
```

RestApi:

```
class RestApi {
var weatherApi: WeatherApi
init {
    val logInterceptor = HttpLoggingInterceptor()
    logInterceptor.level = HttpLoggingInterceptor.Level.BODY
    val okClient = OkHttpClient.Builder()
            .addInterceptor(logInterceptor)
            .retryOnConnectionFailure(true)
            .connectTimeout(15, TimeUnit.SECONDS)
            .build()
    val retrofit = Retrofit.Builder()
            .baseUrl(WeatherApi.HOST)
            .addConverterFactory(JacksonConverterFactory.create(ObjectMapper().registerModule(KotlinModule())))
            .addCallAdapterFactory(RxJavaCallAdapterFactory.create())
            .client(okClient)
            .build()

    weatherApi = retrofit.create(WeatherApi::class.java)
}

fun getWeatherData(city: String, key: String): Observable<Weather> {
    return weatherApi.getWeather(city, key)  
}
```

Fire code:

```
restApi.getWeatherData("Qingdao", WeatherApi.KEY)
                .subscribeOn(Schedulers.io())
                .observeOn(AndroidSchedulers.mainThread())
                .subscribe { t -> helloText?.text = t.data.first().basic.city }
```

> When **first** calling firecode, it will cost 3 seconds to do
> reflection things in **main thread**, I'm confused,cause I have used
> subscribeOn(Schedulers.io()).

![](http://ww2.sinaimg.cn/large/83f914a2jw1f6sn10bt2gj218g0p0qio.jpg)

When I change Retrofit interface to return "Call" and wrap response with Observable in RestApi, things will be correct.

Retrofit interface that return **Call**

```
interface WeatherApi {
companion object {
    val HOST = "https://api.heweather.com/x3/"
    val KEY = "41054a8f1d1a4ac992b1683e47a50146"
}

@GET("weather")
fun getWeather(@Query("city") city: String, @Query("key") key: String) : Call<Weather>
```

}

Create Observable myself in RestApi:

```
fun getWeatherData(city: String, key: String): Observable<Weather> {
    return Observable.fromCallable { weatherApi.getWeather("qingdao",WeatherApi.KEY).execute().body() }
}
```

Then call fire code, all costly things will be done in Schedulers.io() thread.

![](http://ww2.sinaimg.cn/large/83f914a2jw1f6smyi73xnj218g0p0dpk.jpg)

Is this buggy?

Why directly return Observable will cause this ?

**Comment by artem-zinnatullin** [comment]
Have you tried make Retrofit lazy as I suggested you in RxJava issue?

**Comment by CodingPapi** [comment]
hi @artem-zinnatullin, I have tried to init RestApi\Retrofit lazy, but it doesn't work.

**Comment by CodingPapi** [comment]
@artem-zinnatullin init Retrofit does not cost much time, but subscribe do, when it is called at first time

**Comment by artem-zinnatullin** [comment]
Okay, can you please paste complete call stack that invokes expensive
Jackson API?

**Comment by CodingPapi** [comment]
@artem-zinnatullin How can I get complete call stack that invokes expensive
Jackson API? I have tried to print stack in subscribe code block, 

    java.lang.Throwable
                                            at com.supermario.enjoy.simpleweather.MainActivity$onNavigationItemSelected$1.call(MainActivity.kt:102)
                                            at com.supermario.enjoy.simpleweather.MainActivity$onNavigationItemSelected$1.call(MainActivity.kt:22)
                                            at rx.internal.util.ActionSubscriber.onNext(ActionSubscriber.java:39)
                                            at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:139)
                                            at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.call(OperatorObserveOn.java:227)
                                            at rx.android.schedulers.LooperScheduler$ScheduledAction.run(LooperScheduler.java:107)
                                            at android.os.Handler.handleCallback(Handler.java:739)
                                            at android.os.Handler.dispatchMessage(Handler.java:95)
                                            at android.os.Looper.loop(Looper.java:135)
                                            at android.app.ActivityThread.main(ActivityThread.java:5288)
                                            at java.lang.reflect.Method.invoke(Native Method)
                                            at java.lang.reflect.Method.invoke(Method.java:372)
                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:915)
                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:710)

This stack is useless for the issue...

**Comment by CodingPapi** [comment]
[This is the Demo project](https://github.com/CodingPapi/SimpleWeather)

**Comment by NitroG42** [comment]
Here's the traceview from android studio : 

[com.supermario.enjoy.simpleweather_2016.11.02_22.03.zip](https://github.com/square/retrofit/files/567696/com.supermario.enjoy.simpleweather_2016.11.02_22.03.zip)

![capture](https://cloud.githubusercontent.com/assets/1549495/19947648/63dddf84-a149-11e6-9064-de9934a678f3.PNG)

The performance issue came from the initialization of the Jackson/Kotlin module in the main thread.
