### ISSUE TITLE
Support for Java8 interface static methods

### ISSUE THREAD

**Issue by mdeluisi** [square/retrofit#2032]
Retrofit 2.1.0 currently throws an exception building a client implementation proxy if the interface has static methods.

**Comment by JakeWharton** [comment]
Should be easy to fix. Can you paste the exception?

**Comment by mdeluisi** [comment]
static method is declared as the following in the interface:

`
static TalendClientBuilder builder() {
   return TalendClientBuilder.create();
}
`
Exception:
Caused by: java.lang.IllegalArgumentException: Could not locate call adapter for class com.corp.talend.client.v1.api.TalendClientBuilder.
  Tried:
   * retrofit2.DefaultCallAdapterFactory
	at retrofit2.Retrofit.nextCallAdapter(Retrofit.java:237) ~[retrofit-2.1.0.jar:?]
	at retrofit2.Retrofit.callAdapter(Retrofit.java:201) ~[retrofit-2.1.0.jar:?]
	at retrofit2.ServiceMethod$Builder.createCallAdapter(ServiceMethod.java:232) ~[retrofit-2.1.0.jar:?]
	at retrofit2.ServiceMethod$Builder.build(ServiceMethod.java:160) ~[retrofit-2.1.0.jar:?]
	at retrofit2.Retrofit.loadServiceMethod(Retrofit.java:166) ~[retrofit-2.1.0.jar:?]
	at retrofit2.Retrofit.eagerlyValidateMethods(Retrofit.java:156) ~[retrofit-2.1.0.jar:?]
	at retrofit2.Retrofit.create(Retrofit.java:130) ~[retrofit-2.1.0.jar:?]
...

**Comment by mdeluisi** [comment]
Looks like the issue is in Retrofit.eagerlyValidateMethods method.  It should probably just bypass the validation if the method is static.  If I disable eager validation the create() call works fine and a proxy is created.

**Comment by JakeWharton** [comment]
I don't see this failing locally. Are you sure you defined the method as static?

**Comment by mdeluisi** [comment]
Did you enable eager validation in your test?  Yea, I declared it exactly like my example posted above.

**Comment by bnorm** [comment]
I was able to reproduce an issue related to this: https://github.com/bnorm/retrofit/blob/bnorm.1030.static_method/retrofit-adapters/java8/src/test/java/retrofit2/adapter/java8/Java8StaticMethodsTest.java

I can open a pull-request with this failing unit test if that is helpful.

Also, I would be happy to contribute a fix. Should just be adding `&& (method.getModifiers() & Modifier.STATIC) != Modifier.STATIC` to the `Retrofit.eagerlyValidateMethods` method either directly or through `Platform`.
