### ISSUE TITLE
javax.net.ssl.SSLHandshakeException: java.lang.IllegalArgumentException: Invalid input to toASCII:

### ISSUE THREAD

**Issue by DaleJulian** [square/retrofit#2071]
Getting this issue when the root URL has an underscore(e.g. my_host.website.com).

Here is the whole stack trace:
```11-08 09:45:23.936 29193-29193/com.cyscorpions.tiktok W/System.err: javax.net.ssl.SSLHandshakeException: java.lang.IllegalArgumentException: Invalid input to toASCII: stg_test.tiktok.ph
11-08 09:45:23.944 29193-29193/com.cyscorpions.tiktok W/System.err:     at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:361)
11-08 09:45:23.944 29193-29193/com.cyscorpions.tiktok W/System.err:     at okhttp3.internal.io.RealConnection.connectTls(RealConnection.java:195)
11-08 09:45:23.944 29193-29193/com.cyscorpions.tiktok W/System.err:     at okhttp3.internal.io.RealConnection.connectSocket(RealConnection.java:148)
11-08 09:45:23.944 29193-29193/com.cyscorpions.tiktok W/System.err:     at okhttp3.internal.io.RealConnection.connect(RealConnection.java:111)
11-08 09:45:23.944 29193-29193/com.cyscorpions.tiktok W/System.err:     at okhttp3.internal.http.StreamAllocation.findConnection(StreamAllocation.java:188)
11-08 09:45:23.944 29193-29193/com.cyscorpions.tiktok W/System.err:     at okhttp3.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:127)
11-08 09:45:23.944 29193-29193/com.cyscorpions.tiktok W/System.err:     at okhttp3.internal.http.StreamAllocation.newStream(StreamAllocation.java:97)
11-08 09:45:23.944 29193-29193/com.cyscorpions.tiktok W/System.err:     at okhttp3.internal.http.HttpEngine.connect(HttpEngine.java:289)
11-08 09:45:23.944 29193-29193/com.cyscorpions.tiktok W/System.err:     at okhttp3.internal.http.HttpEngine.sendRequest(HttpEngine.java:241)
11-08 09:45:23.944 29193-29193/com.cyscorpions.tiktok W/System.err:     at okhttp3.RealCall.getResponse(RealCall.java:240)
11-08 09:45:23.944 29193-29193/com.cyscorpions.tiktok W/System.err:     at okhttp3.RealCall$ApplicationInterceptorChain.proceed(RealCall.java:198)
11-08 09:45:23.944 29193-29193/com.cyscorpions.tiktok W/System.err:     at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.java:203)
11-08 09:45:23.944 29193-29193/com.cyscorpions.tiktok W/System.err:     at okhttp3.RealCall$ApplicationInterceptorChain.proceed(RealCall.java:187)
11-08 09:45:23.944 29193-29193/com.cyscorpions.tiktok W/System.err:     at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:160)
11-08 09:45:23.945 29193-29193/com.cyscorpions.tiktok W/System.err:     at okhttp3.RealCall.access$100(RealCall.java:30)
11-08 09:45:23.945 29193-29193/com.cyscorpions.tiktok W/System.err:     at okhttp3.RealCall$AsyncCall.execute(RealCall.java:127)
11-08 09:45:23.945 29193-29193/com.cyscorpions.tiktok W/System.err:     at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
11-08 09:45:23.945 29193-29193/com.cyscorpions.tiktok W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
11-08 09:45:23.945 29193-29193/com.cyscorpions.tiktok W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
11-08 09:45:23.945 29193-29193/com.cyscorpions.tiktok W/System.err:     at java.lang.Thread.run(Thread.java:761)
11-08 09:45:23.947 29193-29193/com.cyscorpions.tiktok W/System.err: Caused by: java.security.cert.CertificateException: java.lang.IllegalArgumentException: Invalid input to toASCII: stg_test.tiktok.ph
11-08 09:45:23.947 29193-29193/com.cyscorpions.tiktok W/System.err:     at com.android.org.conscrypt.OpenSSLSocketImpl.verifyCertificateChain(OpenSSLSocketImpl.java:617)
11-08 09:45:23.947 29193-29193/com.cyscorpions.tiktok W/System.err:     at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
11-08 09:45:23.947 29193-29193/com.cyscorpions.tiktok W/System.err:     at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:357)
11-08 09:45:23.947 29193-29193/com.cyscorpions.tiktok W/System.err: 	... 19 more
11-08 09:45:23.949 29193-29193/com.cyscorpions.tiktok W/System.err: Caused by: java.lang.IllegalArgumentException: Invalid input to toASCII: stg_test.tiktok.ph
11-08 09:45:23.949 29193-29193/com.cyscorpions.tiktok W/System.err:     at java.net.IDN.toASCII(IDN.java:112)
11-08 09:45:23.949 29193-29193/com.cyscorpions.tiktok W/System.err:     at javax.net.ssl.SNIHostName.<init>(SNIHostName.java:99)
11-08 09:45:23.949 29193-29193/com.cyscorpions.tiktok W/System.err:     at com.android.org.conscrypt.Platform.getSSLParameters(Platform.java:133)
11-08 09:45:23.950 29193-29193/com.cyscorpions.tiktok W/System.err:     at com.android.org.conscrypt.OpenSSLSocketImpl.getSSLParameters(OpenSSLSocketImpl.java:1320)
11-08 09:45:23.950 29193-29193/com.cyscorpions.tiktok W/System.err:     at com.android.org.conscrypt.TrustManagerImpl.getTrustedChainForServer(TrustManagerImpl.java:302)
11-08 09:45:23.950 29193-29193/com.cyscorpions.tiktok W/System.err:     at android.security.net.config.NetworkSecurityTrustManager.checkServerTrusted(NetworkSecurityTrustManager.java:94)
11-08 09:45:23.950 29193-29193/com.cyscorpions.tiktok W/System.err:     at android.security.net.config.RootTrustManager.checkServerTrusted(RootTrustManager.java:88)
11-08 09:45:23.950 29193-29193/com.cyscorpions.tiktok W/System.err:     at com.android.org.conscrypt.Platform.checkServerTrusted(Platform.java:178)
11-08 09:45:23.950 29193-29193/com.cyscorpions.tiktok W/System.err:     at com.android.org.conscrypt.OpenSSLSocketImpl.verifyCertificateChain(OpenSSLSocketImpl.java:596)
11-08 09:45:23.950 29193-29193/com.cyscorpions.tiktok W/System.err: 	... 21 more
11-08 09:45:23.950 29193-29193/com.cyscorpions.tiktok W/System.err: Caused by: The input does not conform to the STD 3 ASCII rules. line:  0. preContext:  . postContext: g_test
11-08 09:45:23.950 29193-29193/com.cyscorpions.tiktok W/System.err:     at android.icu.impl.IDNA2003.convertToASCII(IDNA2003.java:214)
11-08 09:45:23.951 29193-29193/com.cyscorpions.tiktok W/System.err:     at android.icu.impl.IDNA2003.convertIDNToASCII(IDNA2003.java:275)
11-08 09:45:23.951 29193-29193/com.cyscorpions.tiktok W/System.err:     at android.icu.text.IDNA.convertIDNToASCII(IDNA.java:652)
11-08 09:45:23.951 29193-29193/com.cyscorpions.tiktok W/System.err:     at java.net.IDN.toASCII(IDN.java:110)
11-08 09:45:23.951 29193-29193/com.cyscorpions.tiktok W/System.err: 	... 29 more```

**Comment by swankjesse** [comment]
Please report this bug against AOSP. There's nothing we can do about it here. BTW, underscores in hostnames are a bad idea if you care about interop.

**Comment by mb040574** [comment]
You can try to change the protocol to HTTP instead on this error. Might work for some pages or ressources.
