### ISSUE TITLE
Any clue of this Fatal exception  java.lang.NullPointerException: value == null ?

### ISSUE THREAD

**Issue by bs2015** [square/retrofit#2088]
```
FATAL EXCEPTION: OkHttp Dispatcher
Process: com.mobitino.mobitinopersonal, PID: 12087
                                                                               java.lang.NullPointerException: value == null
                                                                                   at okhttp3.Headers$Builder.checkNameAndValue(Headers.java:316)
                                                                                   at okhttp3.Headers$Builder.add(Headers.java:270)
                                                                                   at okhttp3.Request$Builder.addHeader(Request.java:175)
                                                                                   at com.mobitino.mobitinopersonal.network.retrofit.TokenInterceptor.intercept(TokenInterceptor.java:46)
                                                                                   at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
                                                                                   at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
                                                                                   at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.java:212)
                                                                                   at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
                                                                                   at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
                                                                                   at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:170)
                                                                                   at okhttp3.RealCall.execute(RealCall.java:60)
                                                                                   at retrofit2.OkHttpCall.execute(OkHttpCall.java:174)
                                                                                   at retrofit2.ExecutorCallAdapterFactory$ExecutorCallbackCall.execute(ExecutorCallAdapterFactory.java:89)
                                                                                   at com.mobitino.mobitinopersonal.network.retrofit.TokenProvider.refreshToken(TokenProvider.java:61)
                                                                                   at com.mobitino.mobitinopersonal.network.retrofit.TokenInterceptor.intercept(TokenInterceptor.java:54)
                                                                                   at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
                                                                                   at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
                                                                                   at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.java:212)
                                                                                   at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
                                                                                   at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
                                                                                   at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:170)
                                                                                   at okhttp3.RealCall.access$100(RealCall.java:33)
                                                                                   at okhttp3.RealCall$AsyncCall.execute(RealCall.java:120)
                                                                                   at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
                                                                                   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                                   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                                   at java.lang.Thread.run(Thread.java:818)
```

**Comment by JakeWharton** [comment]
Your token interceptor is trying to add a null header.

**Comment by bs2015** [comment]
Thanks bro! It solved my issue.
