### ISSUE TITLE
Strange behaviour after 500 error

### ISSUE THREAD

**Issue by JenyaKirmizaTripTop** [square/retrofit#2146]
I'm using rx java with retrofit 2(2.1.0) 

```
        Gson gson = new GsonBuilder()
                .serializeNulls()
                .setDateFormat("yyyy-MM-dd'T'HH:mm:ssZ")
                .create();

        final OkHttpClient.Builder builder = new OkHttpClient.Builder();

            LogingInterceptorFullLog logging = new LogingInterceptorFullLog();
            logging.setLevel(LogingInterceptorFullLog.Level.FULL);
            builder.addInterceptor(logging);
        

        String serverUrl= BuildConfig.SERVER_PREFIX;

        Retrofit retrofit = new Retrofit.Builder()
                .baseUrl(serverUrl)
                .client(builder.build())
                .addCallAdapterFactory(RxJavaCallAdapterFactory.create())
                .addConverterFactory(GsonConverterFactory.create(gson))
                .build();
```

then i get some exception that occurs inside rx or retrofit2 layer

```
Process: , PID: 25410
                                                                             java.lang.IllegalStateException: Fatal Exception thrown on Scheduler.Worker thread.
                                                                                 at rx.android.schedulers.LooperScheduler$ScheduledAction.run(LooperScheduler.java:114)
                                                                                 at android.os.Handler.handleCallback(Handler.java:739)
                                                                                 at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                 at android.os.Looper.loop(Looper.java:135)
                                                                                 at android.app.ActivityThread.main(ActivityThread.java:5343)
                                                                                 at java.lang.reflect.Method.invoke(Native Method)
                                                                                 at java.lang.reflect.Method.invoke(Method.java:372)
                                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905)
                                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:700)
                                                                              Caused by: rx.exceptions.OnErrorFailedException: Error occurred when trying to propagate error to Observer.onError
                                                                                 at rx.observers.SafeSubscriber._onError(SafeSubscriber.java:192)
                                                                                 at rx.observers.SafeSubscriber.onError(SafeSubscriber.java:120)
                                                                                 at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.checkTerminated(OperatorObserveOn.java:276)
                                                                                 at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.call(OperatorObserveOn.java:219)
                                                                                 at rx.android.schedulers.LooperScheduler$ScheduledAction.run(LooperScheduler.java:107)
                                                                                 at android.os.Handler.handleCallback(Handler.java:739) 
                                                                                 at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                                                 at android.os.Looper.loop(Looper.java:135) 
                                                                                 at android.app.ActivityThread.main(ActivityThread.java:5343) 
                                                                                 at java.lang.reflect.Method.invoke(Native Method) 
                                                                                 at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905) 
                                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:700) 
                                                                              Caused by: rx.exceptions.CompositeException: 2 exceptions occurred. 
                                                                                 at rx.observers.SafeSubscriber._onError(SafeSubscriber.java:192) 
                                                                                 at rx.observers.SafeSubscriber.onError(SafeSubscriber.java:120) 
                                                                                 at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.checkTerminated(OperatorObserveOn.java:276) 
                                                                                 at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.call(OperatorObserveOn.java:219) 
                                                                                 at rx.android.schedulers.LooperScheduler$ScheduledAction.run(LooperScheduler.java:107) 
                                                                                 at android.os.Handler.handleCallback(Handler.java:739) 
                                                                                 at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                                                 at android.os.Looper.loop(Looper.java:135) 
                                                                                 at android.app.ActivityThread.main(ActivityThread.java:5343) 
                                                                                 at java.lang.reflect.Method.invoke(Native Method) 
                                                                                 at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905) 
                                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:700) 
                                                                              Caused by: rx.exceptions.CompositeException$CompositeExceptionCausalChain: Chain of Causes for CompositeException In Order Received =>
                                                                                 at android.util.Log.getStackTraceString(Log.java:519)
                                                                                 at com.android.internal.os.RuntimeInit.Clog_e(RuntimeInit.java:59)
                                                                                 at com.android.internal.os.RuntimeInit.access$200(RuntimeInit.java:43)
                                                                                 at com.android.internal.os.RuntimeInit$UncaughtHandler.uncaughtException(RuntimeInit.java:85)
                                                                                 at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:693)
                                                                                 at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:690)
                                                                                 at rx.android.schedulers.LooperScheduler$ScheduledAction.run(LooperScheduler.java:118)
                                                                                 at android.os.Handler.handleCallback(Handler.java:739) 
                                                                                 at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                                                 at android.os.Looper.loop(Looper.java:135) 
                                                                                 at android.app.ActivityThread.main(ActivityThread.java:5343) 
                                                                                 at java.lang.reflect.Method.invoke(Native Method) 
                                                                                 at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905) 
                                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:700) 
                                                                              Caused by: retrofit2.adapter.rxjava.HttpException: HTTP 500 Internal Server Error
                                                                                 at retrofit2.adapter.rxjava.OperatorMapResponseToBodyOrError$1.onNext(OperatorMapResponseToBodyOrError.java:43)
                                                                                 at retrofit2.adapter.rxjava.OperatorMapResponseToBodyOrError$1.onNext(OperatorMapResponseToBodyOrError.java:38)
                                                                                 at retrofit2.adapter.rxjava.RxJavaCallAdapterFactory$RequestArbiter.request(RxJavaCallAdapterFactory.java:173)
                                                                                 at rx.internal.operators.OperatorSubscribeOn$1$1$1.request(OperatorSubscribeOn.java:80)
                                                                                 at rx.Subscriber.setProducer(Subscriber.java:211)
                                                                                 at rx.internal.operators.OperatorMap$MapSubscriber.setProducer(OperatorMap.java:99)
                                                                                 at rx.internal.operators.OperatorSubscribeOn$1$1.setProducer(OperatorSubscribeOn.java:76)
                                                                                 at rx.Subscriber.setProducer(Subscriber.java:205)
                                                                                 at retrofit2.adapter.rxjava.RxJavaCallAdapterFactory$CallOnSubscribe.call(RxJavaCallAdapterFactory.java:152)
                                                                                 at retrofit2.adapter.rxjava.RxJavaCallAdapterFactory$CallOnSubscribe.call(RxJavaCallAdapterFactory.java:138)
                                                                                 at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:50)
                                                                                 at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
                                                                                 at rx.Observable.unsafeSubscribe(Observable.java:8666)
                                                                                 at rx.internal.operators.OperatorSubscribeOn$1.call(OperatorSubscribeOn.java:94)
                                                                                 at rx.internal.schedulers.CachedThreadScheduler$EventLoopWorker$1.call(CachedThreadScheduler.java:220)
                                                                                 at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
                                                                                 at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
                                                                                 at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                                 at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152)
                                                                                 at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265)
                                                                                 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                                 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                                 at java.lang.Thread.run(Thread.java:818)
                                                                             Caused

```

**Comment by JakeWharton** [comment]
This indicates your onError callback is throwing an exception while
handling the HttpException from Retrofit. The stack trace is truncated so
we can't see the problem in your onError code.

**Comment by JenyaKirmizaTripTop** [comment]
@JakeWharton  hello, sir. How can i get full trace?

**Comment by JenyaKirmizaTripTop** [comment]
@JakeWharton  sorry, the problem has been solved. Its just was an issue on my side, i output the full log and found it. The business error from server had different structure than in my model so it crashed in Gson conversion. Thank you for awesome libraries, that make our lives brighter and easier) and close this issue

**Comment by jaredsburrows** [comment]
@JenyaKirmizaTripTop Can you close this?

**Comment by demo-Ashif** [comment]
@JenyaKirmizaTripTop  can you please explain how you solved it . facing similar problem . 
you can knock in mail too --> nmujtoba@gmail.com
