### ISSUE TITLE
When Wifi "ON" but internet not working

### ISSUE THREAD

**Issue by lovekeshargalon** [square/retrofit#2163]
```
FATAL EXCEPTION: OkHttp Dispatcher   Process: com.argalon.vmychat, PID: 12677                                                                     java.lang.NullPointerException: interceptor com.sourcecanyon.whatsClone.api.APIService$2@a017686 returned null
                                                                         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:102)
                                                                         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
                                                                         at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:170)
                                                                         at okhttp3.RealCall.access$100(RealCall.java:33)
                                                                         at okhttp3.RealCall$AsyncCall.execute(RealCall.java:120)
                                                                         at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
                                                                         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                         at java.lang.Thread.run(Thread.java:818)
```

My application crashes ,when wifi on but internet off.

Also getting this issue:-

`D/OkHttp: <-- HTTP FAILED: java.net.UnknownHostException: Unable to resolve host "vwebdevelopment.com": No address associated with hostname`

**Comment by JakeWharton** [comment]
This is not a problem with Retrofit as evidenced by your stacktrace. Your interceptor is returning null which is not allowed.

**Comment by lovekeshargalon** [comment]
But i am getting when internet off.
