### ISSUE TITLE
Retrofit2 does not seem to handle multipart responses

### ISSUE THREAD

**Issue by cdongieux** [square/retrofit#2164]
Retrofit2 (2.1.0) does not seem to handle Multipart (multipart/mixed for instance) responses like that:
```
200 http://host/path
content-type: multipart/related;boundary=foobar;start=start.foobar;type="application/json"
--foobar
Content-Type: application/json; charset=UTF-8
{"message":"hohiii"}
--foobar
Content-Type: application/octet-stream
<binary stuff>
--foobar--
```

Declaring the following API service and using it results in a JSON exception:
```
Call<MultipartBody> getMultipart();
```

```
                com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 1 path $
                    at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1559)
                    at com.google.gson.stream.JsonReader.checkLenient(JsonReader.java:1401)
                    at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:593)
                    at com.google.gson.stream.JsonReader.peek(JsonReader.java:425)
                    at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:205)
                    at retrofit2.converter.gson.GsonResponseBodyConverter.convert(GsonResponseBodyConverter.java:37)
                    at retrofit2.converter.gson.GsonResponseBodyConverter.convert(GsonResponseBodyConverter.java:25)
                    at retrofit2.ServiceMethod.toResponse(ServiceMethod.java:117)
                    at retrofit2.OkHttpCall.parseResponse(OkHttpCall.java:211)
                    at retrofit2.OkHttpCall$1.onResponse(OkHttpCall.java:106)
                    at okhttp3.RealCall$AsyncCall.execute(RealCall.java:135)
                    at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
                    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                    at java.lang.Thread.run(Thread.java:818)
```

**Comment by JakeWharton** [comment]
OkHttp's `MultipartBody` is a `RequestBody` and is only appropriate for sending multipart requests, not parsing multipart responses. In OkHttp 4.x this might change, but for now that's what we have.

If you need to parse a multipart response then your best bet would be to write your own type or find an existing one and then write a custom `Converter` that takes the `ResponseBody` and turns it into your type.

**Comment by cdongieux** [comment]
Hi Jack,

Thanks for your answer, I understand.
But it would be great if `MultipartBody` could be also used for responses: calling `parts()` on it would give the parts list, and dealing with them would be a lot easier.
