### ISSUE TITLE
Not getting Session with base url (async task android project retrofit example

### ISSUE THREAD

**Issue by deepakmalhotra633** [square/retrofit#2184]
this is my log cat.
   02-01 16:37:29.870 19680-19680/eg.edu.guc.android.eshop W/ResourceType: Found multiple library tables, ignoring...
02-01 16:37:29.886 19680-19680/eg.edu.guc.android.eshop W/ResourceType: Found multiple library tables, ignoring...
02-01 16:37:29.923 19680-19680/eg.edu.guc.android.eshop I/Timeline: Timeline: Activity_launch_request id:eg.edu.guc.android.eshop time:3216553
02-01 16:37:31.051 19680-19800/eg.edu.guc.android.eshop D/OpenGLRenderer: Use EGL_SWAP_BEHAVIOR_PRESERVED: true
02-01 16:37:31.075 19680-19680/eg.edu.guc.android.eshop D/Atlas: Validating map...
02-01 16:37:31.150 19680-19800/eg.edu.guc.android.eshop I/Adreno-EGL: <qeglDrvAPI_eglInitialize:410>: EGL 1.4 QUALCOMM build: AU_LINUX_ANDROID_LA.AF.1.1_RB1.05.00.02.006.020_msm8960_LA.AF.1.1_RB1__release_AU ()
                                                                      OpenGL ES Shader Compiler Version: E031.25.03.06
                                                                      Build Date: 05/22/15 Fri
                                                                      Local Branch: mybranch10237523
                                                                      Remote Branch: quic/LA.AF.1.1_rb1.18
                                                                      Local Patches: NONE
                                                                      Reconstruct Branch: AU_LINUX_ANDROID_LA.AF.1.1_RB1.05.00.02.006.020 + 9b2699f + 2215637 + 60aa592 + f2362e6 + 5c64f59 + 82411a1 + 89a0db6 + 6151be1 +  NOTHING
02-01 16:37:31.151 19680-19800/eg.edu.guc.android.eshop I/OpenGLRenderer: Initialized EGL, version 1.4
02-01 16:37:31.326 19680-19800/eg.edu.guc.android.eshop D/OpenGLRenderer: Enabling debug mode 0
02-01 16:37:31.782 19680-19680/eg.edu.guc.android.eshop I/Timeline: Timeline: Activity_idle id: android.os.BinderProxy@3fce1ea9 time:3218413
02-01 16:37:47.338 19680-19680/eg.edu.guc.android.eshop I/Timeline: Timeline: Activity_idle id: android.os.BinderProxy@3fce1ea9 time:3233969
02-01 16:38:46.870 19680-19680/eg.edu.guc.android.eshop D/eg.edu.guc.android.eshop: Login with 'deepadeepakmalhotra633@gmail.com@hotmail.com' and 'deepak96'
02-01 16:38:46.935 19680-19680/eg.edu.guc.android.eshop I/Timeline: Timeline: Activity_launch_request id:eg.edu.guc.android.eshop time:3293565
02-01 16:38:46.975 19680-23108/eg.edu.guc.android.eshop D/Retrofit: ---> HTTP POST https://www.clickoncare.com/api/v2_soap/?wsdl=1/sessions
02-01 16:38:46.975 19680-23108/eg.edu.guc.android.eshop D/Retrofit: Content-Type: application/x-www-form-urlencoded; charset=UTF-8
02-01 16:38:46.975 19680-23108/eg.edu.guc.android.eshop D/Retrofit: Content-Length: 98
02-01 16:38:46.982 19680-23108/eg.edu.guc.android.eshop D/Retrofit: session%5Bemail%5D=deepadeepakmalhotra633%40gmail.com%40hotmail.com&session%5Bpassword%5D=deepak96
02-01 16:38:46.982 19680-23108/eg.edu.guc.android.eshop D/Retrofit: ---> END HTTP (98-byte body)
02-01 16:38:46.983 19680-19680/eg.edu.guc.android.eshop I/Timeline: Timeline: Activity_launch_request id:eg.edu.guc.android.eshop time:3293613
02-01 16:38:47.036 19680-23108/eg.edu.guc.android.eshop D/Retrofit: ---- ERROR https://www.clickoncare.com/api/v2_soap/?wsdl=1/sessions
02-01 16:38:47.041 19680-23108/eg.edu.guc.android.eshop D/Retrofit: java.net.UnknownHostException: Unable to resolve host "www.clickoncare.com": No address associated with hostname
                                                                        at java.net.InetAddress.lookupHostByName(InetAddress.java:457)
                                                                        at java.net.InetAddress.getAllByNameImpl(InetAddress.java:252)
                                                                        at java.net.InetAddress.getAllByName(InetAddress.java:215)
                                                                        at com.squareup.okhttp.internal.Network$1.resolveInetAddresses(Network.java:29)
                                                                        at com.squareup.okhttp.internal.http.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:259)
                                                                        at com.squareup.okhttp.internal.http.RouteSelector.nextProxy(RouteSelector.java:233)
                                                                        at com.squareup.okhttp.internal.http.RouteSelector.nextUnconnected(RouteSelector.java:159)
                                                                        at com.squareup.okhttp.internal.http.RouteSelector.next(RouteSelector.java:133)
                                                                        at com.squareup.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:314)
                                                                        at com.squareup.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:237)
                                                                        at com.squareup.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:423)
                                                                        at com.squareup.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:105)
                                                                        at com.squareup.okhttp.internal.huc.HttpURLConnectionImpl.getOutputStream(HttpURLConnectionImpl.java:239)
                                                                        at com.squareup.okhttp.internal.huc.DelegatingHttpsURLConnection.getOutputStream(DelegatingHttpsURLConnection.java:218)
                                                                        at com.squareup.okhttp.internal.huc.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:25)
                                                                        at retrofit.client.UrlConnectionClient.prepareRequest(UrlConnectionClient.java:68)
                                                                        at retrofit.client.UrlConnectionClient.execute(UrlConnectionClient.java:37)
                                                                        at retrofit.RestAdapter$RestHandler.invokeRequest(RestAdapter.java:321)
                                                                        at retrofit.RestAdapter$RestHandler.access$100(RestAdapter.java:220)
                                                                        at retrofit.RestAdapter$RestHandler$2.obtainResponse(RestAdapter.java:278)
                                                                        at retrofit.CallbackRunnable.run(CallbackRunnable.java:42)
                                                                        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                        at retrofit.Platform$Android$2$1.run(Platform.java:142)
                                                                        at java.lang.Thread.run(Thread.java:818)
                                                                     Caused by: android.system.GaiException: android_getaddrinfo failed: EAI_NODATA (No address associated with hostname)
                                                                        at libcore.io.Posix.android_getaddrinfo(Native Method)
                                                                        at libcore.io.ForwardingOs.android_getaddrinfo(ForwardingOs.java:55)
                                                                        at java.net.InetAddress.lookupHostByName(InetAddress.java:438)
                                                                        at java.net.InetAddress.getAllByNameImpl(InetAddress.java:252) 
                                                                        at java.net.InetAddress.getAllByName(InetAddress.java:215) 
                                                                        at com.squareup.okhttp.internal.Network$1.resolveInetAddresses(Network.java:29) 
                                                                        at com.squareup.okhttp.internal.http.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:259) 
                                                                        at com.squareup.okhttp.internal.http.RouteSelector.nextProxy(RouteSelector.java:233) 
                                                                        at com.squareup.okhttp.internal.http.RouteSelector.nextUnconnected(RouteSelector.java:159) 
                                                                        at com.squareup.okhttp.internal.http.RouteSelector.next(RouteSelector.java:133) 
                                                                        at com.squareup.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:314) 
                                                                        at com.squareup.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:237) 
                                                                        at com.squareup.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:423) 
                                                                        at com.squareup.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:105) 
                                                                        at com.squareup.okhttp.internal.huc.HttpURLConnectionImpl.getOutputStream(HttpURLConnectionImpl.java:239) 
                                                                        at com.squareup.okhttp.internal.huc.DelegatingHttpsURLConnection.getOutputStream(DelegatingHttpsURLConnection.java:218) 
                                                                        at com.squareup.okhttp.internal.huc.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:25) 
                                                                        at retrofit.client.UrlConnectionClient.prepareRequest(UrlConnectionClient.java:68) 
                                                                        at retrofit.client.UrlConnectionClient.execute(UrlConnectionClient.java:37) 
                                                                        at retrofit.RestAdapter$RestHandler.invokeRequest(RestAdapter.java:321) 
                                                                        at retrofit.RestAdapter$RestHandler.access$100(RestAdapter.java:220) 
                                                                        at retrofit.RestAdapter$RestHandler$2.obtainResponse(RestAdapter.java:278) 
                                                                        at retrofit.CallbackRunnable.run(CallbackRunnable.java:42) 
                                                                        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
                                                                        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
                                                                        at retrofit.Platform$Android$2$1.run(Platform.java:142) 
                                                                        at java.lang.Thread.run(Thread.java:818) 
02-01 16:38:47.041 19680-23108/eg.edu.guc.android.eshop D/Retrofit: ---- END ERROR
02-01 16:38:47.177 19680-19680/eg.edu.guc.android.eshop I/Timeline: Timeline: Activity_idle id: android.os.BinderProxy@3b3b866d time:3293807
02-01 16:39:16.106 19680-19680/eg.edu.guc.android.eshop D/eg.edu.guc.android.eshop: Login with 'deepakmalhotra633@gmail.com' and 'deepak96'
02-01 16:39:16.107 19680-19680/eg.edu.guc.android.eshop I/Timeline: Timeline: Activity_launch_request id:eg.edu.guc.android.eshop time:3322737
02-01 16:39:16.121 19680-23108/eg.edu.guc.android.eshop D/Retrofit: ---> HTTP POST https://www.clickoncare.com/api/v2_soap/?wsdl=1/sessions
02-01 16:39:16.121 19680-23108/eg.edu.guc.android.eshop D/Retrofit: Content-Type: application/x-www-form-urlencoded; charset=UTF-8
02-01 16:39:16.121 19680-23108/eg.edu.guc.android.eshop D/Retrofit: Content-Length: 79
02-01 16:39:16.125 19680-23108/eg.edu.guc.android.eshop D/Retrofit: session%5Bemail%5D=deepakmalhotra633%40gmail.com&session%5Bpassword%5D=deepak96
02-01 16:39:16.126 19680-23108/eg.edu.guc.android.eshop D/Retrofit: ---> END HTTP (79-byte body)
02-01 16:39:16.138 19680-23108/eg.edu.guc.android.eshop D/Retrofit: ---- ERROR https://www.clickoncare.com/api/v2_soap/?wsdl=1/sessions
02-01 16:39:16.143 19680-23108/eg.edu.guc.android.eshop D/Retrofit: java.net.UnknownHostException: Unable to resolve host "www.clickoncare.com": No address associated with hostname
                                                                        at java.net.InetAddress.lookupHostByName(InetAddress.java:457)
                                                                        at java.net.InetAddress.getAllByNameImpl(InetAddress.java:252)
                                                                        at java.net.InetAddress.getAllByName(InetAddress.java:215)
                                                                        at com.squareup.okhttp.internal.Network$1.resolveInetAddresses(Network.java:29)
                                                                        at com.squareup.okhttp.internal.http.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:259)
                                                                        at com.squareup.okhttp.internal.http.RouteSelector.nextProxy(RouteSelector.java:233)
                                                                        at com.squareup.okhttp.internal.http.RouteSelector.nextUnconnected(RouteSelector.java:159)
                                                                        at com.squareup.okhttp.internal.http.RouteSelector.next(RouteSelector.java:133)
                                                                        at com.squareup.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:314)
                                                                        at com.squareup.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:237)
                                                                        at com.squareup.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:423)
                                                                        at com.squareup.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:105)
                                                                        at com.squareup.okhttp.internal.huc.HttpURLConnectionImpl.getOutputStream(HttpURLConnectionImpl.java:239)
                                                                        at com.squareup.okhttp.internal.huc.DelegatingHttpsURLConnection.getOutputStream(DelegatingHttpsURLConnection.java:218)
                                                                        at com.squareup.okhttp.internal.huc.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:25)
                                                                        at retrofit.client.UrlConnectionClient.prepareRequest(UrlConnectionClient.java:68)
                                                                        at retrofit.client.UrlConnectionClient.execute(UrlConnectionClient.java:37)
                                                                        at retrofit.RestAdapter$RestHandler.invokeRequest(RestAdapter.java:321)
                                                                        at retrofit.RestAdapter$RestHandler.access$100(RestAdapter.java:220)
                                                                        at retrofit.RestAdapter$RestHandler$2.obtainResponse(RestAdapter.java:278)
                                                                        at retrofit.CallbackRunnable.run(CallbackRunnable.java:42)
                                                                        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                        at retrofit.Platform$Android$2$1.run(Platform.java:142)
                                                                        at java.lang.Thread.run(Thread.java:818)
                                                                     Caused by: android.system.GaiException: android_getaddrinfo failed: EAI_NODATA (No address associated with hostname)
                                                                        at libcore.io.Posix.android_getaddrinfo(Native Method)
                                                                        at libcore.io.ForwardingOs.android_getaddrinfo(ForwardingOs.java:55)
                                                                        at java.net.InetAddress.lookupHostByName(InetAddress.java:438)
                                                                        at java.net.InetAddress.getAllByNameImpl(InetAddress.java:252) 
                                                                        at java.net.InetAddress.getAllByName(InetAddress.java:215) 
                                                                        at com.squareup.okhttp.internal.Network$1.resolveInetAddresses(Network.java:29) 
                                                                        at com.squareup.okhttp.internal.http.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:259) 
                                                                        at com.squareup.okhttp.internal.http.RouteSelector.nextProxy(RouteSelector.java:233) 
                                                                        at com.squareup.okhttp.internal.http.RouteSelector.nextUnconnected(RouteSelector.java:159) 
                                                                        at com.squareup.okhttp.internal.http.RouteSelector.next(RouteSelector.java:133) 
                                                                        at com.squareup.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:314) 
                                                                        at com.squareup.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:237) 
                                                                        at com.squareup.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:423) 
                                                                        at com.squareup.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:105) 
                                                                        at com.squareup.okhttp.internal.huc.HttpURLConnectionImpl.getOutputStream(HttpURLConnectionImpl.java:239) 
                                                                        at com.squareup.okhttp.internal.huc.DelegatingHttpsURLConnection.getOutputStream(DelegatingHttpsURLConnection.java:218) 
                                                                        at com.squareup.okhttp.internal.huc.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:25) 
                                                                        at retrofit.client.UrlConnectionClient.prepareRequest(UrlConnectionClient.java:68) 
                                                                        at retrofit.client.UrlConnectionClient.execute(UrlConnectionClient.java:37) 
                                                                        at retrofit.RestAdapter$RestHandler.invokeRequest(RestAdapter.java:321) 
                                                                        at retrofit.RestAdapter$RestHandler.access$100(RestAdapter.java:220) 
                                                                        at retrofit.RestAdapter$RestHandler$2.obtainResponse(RestAdapter.java:278) 
                                                                        at retrofit.CallbackRunnable.run(CallbackRunnable.java:42) 
                                                                        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
                                                                        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
                                                                        at retrofit.Platform$Android$2$1.run(Platform.java:142) 
                                                                        at java.lang.Thread.run(Thread.java:818) 
02-01 16:39:16.144 19680-23108/eg.edu.guc.android.eshop D/Retrofit: ---- END ERROR
02-01 16:39:16.207 19680-19680/eg.edu.guc.android.eshop I/Timeline: Timeline: Activity_launch_request id:eg.edu.guc.android.eshop time:3322837
02-01 16:39:16.407 19680-19680/eg.edu.guc.android.eshop I/Timeline: Timeline: Activity_idle id: android.os.BinderProxy@3ce79277 time:3323037
02-01 16:39:30.347 19680-19680/eg.edu.guc.android.eshop W/IInputConnectionWrapper: showStatusIcon on inactive InputConnection

**Comment by JakeWharton** [comment]
> java.net.UnknownHostException: Unable to resolve host "www.clickoncare.com": No address associated with hostname

This is your problem, and it's not one from Retrofit. Either your internet is down or your domain is broken.

**Comment by deepakmalhotra633** [comment]
can you send me steps for magento connection
