### ISSUE TITLE
How to deal with this oom?

### ISSUE THREAD

**Issue by Zooc** [square/retrofit#2202]
java.lang.IllegalStateException: Fatal Exception thrown on Scheduler.Worker thread.
	at rx.internal.schedulers.ScheduledAction.void run()(Unknown Source)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:818)
Caused by: java.lang.OutOfMemoryError: Failed to allocate a 2060 byte allocation with 1288 free bytes and 1288B until OOM
	at okio.Segment.void <init>()(Unknown Source)
                 void <init>(okio.Segment)
                 void <init>(byte[],int,int)
	at okio.SegmentPool.okio.Segment take()(Unknown Source)
                     void recycle(okio.Segment)
	at okio.Buffer.okio.BufferedSink emit()(Unknown Source)
                java.lang.String readUtf8Line(long)
                okio.Segment writableSegment(int)
	at okio.Buffer.okio.Buffer buffer()(Unknown Source)
                byte getByte(long)
                okio.Buffer write(byte[])
                okio.Buffer write(byte[],int,int)
                okio.Buffer writeByte(int)
                okio.BufferedSink writeUtf8(java.lang.String)
                okio.BufferedSink write(okio.ByteString)
	at okio.Buffer$1.void write(int)(Unknown Source)
                  void write(byte[],int,int)
	at java.io.OutputStreamWriter.flushBytes(OutputStreamWriter.java:167)
	at java.io.OutputStreamWriter.convert(OutputStreamWriter.java:181)
	at java.io.OutputStreamWriter.write(OutputStreamWriter.java:324)
	at com.google.gson.stream.JsonWriter.void string(java.lang.String)(Unknown Source)
	at com.google.gson.stream.JsonWriter.com.google.gson.stream.JsonWriter value(java.lang.String)(Unknown Source)
                                      com.google.gson.stream.JsonWriter value(boolean)
                                      com.google.gson.stream.JsonWriter value(double)
                                      com.google.gson.stream.JsonWriter value(long)
                                      com.google.gson.stream.JsonWriter value(java.lang.Number)
	at com.google.gson.internal.bind.TypeAdapters$17.void write(com.google.gson.stream.JsonWriter,java.lang.String)(Unknown Source)
                                                  void write(com.google.gson.stream.JsonWriter,java.lang.Object)
	at com.google.gson.internal.bind.TypeAdapters$17.void write(com.google.gson.stream.JsonWriter,java.lang.String)(Unknown Source)
                                                  void write(com.google.gson.stream.JsonWriter,java.lang.Object)
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.void write(com.google.gson.stream.JsonWriter,java.lang.Object)(Unknown Source)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.void write(com.google.gson.stream.JsonWriter,java.lang.Object)(Unknown Source)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.void write(com.google.gson.stream.JsonWriter,java.lang.Object)(Unknown Source)
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.void write(com.google.gson.stream.JsonWriter,java.lang.Object)(Unknown Source)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.void write(com.google.gson.stream.JsonWriter,java.lang.Object)(Unknown Source)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.void write(com.google.gson.stream.JsonWriter,java.lang.Object)(Unknown Source)
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.void write(com.google.gson.stream.JsonWriter,java.lang.Object)(Unknown Source)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.void write(com.google.gson.stream.JsonWriter,java.lang.Object)(Unknown Source)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.void write(com.google.gson.stream.JsonWriter,java.lang.Object)(Unknown Source)
	at com.google.gson.internal.bind.ObjectTypeAdapter.void write(com.google.gson.stream.JsonWriter,java.lang.Object)(Unknown Source)
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.void write(com.google.gson.stream.JsonWriter,java.lang.Object)(Unknown Source)
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.void write(com.google.gson.stream.JsonWriter,java.util.Map)(Unknown Source)
                                                                void write(com.google.gson.stream.JsonWriter,java.lang.Object)
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.void write(com.google.gson.stream.JsonWriter,java.util.Map)(Unknown Source)
                                                                void write(com.google.gson.stream.JsonWriter,java.lang.Object)
	at retrofit2.converter.gson.GsonRequestBodyConverter.okhttp3.RequestBody convert(java.lang.Object)(Unknown Source)
                                                      java.lang.Object convert(java.lang.Object)
	at retrofit2.converter.gson.GsonRequestBodyConverter.okhttp3.RequestBody convert(java.lang.Object)(Unknown Source)
                                                      java.lang.Object convert(java.lang.Object)
	at retrofit2.ParameterHandler$Body.void apply(retrofit2.RequestBuilder,java.lang.Object)(Unknown Source)
	at retrofit2.ServiceMethod.okhttp3.Request toRequest(java.lang.Object[])(Unknown Source)
	at retrofit2.OkHttpCall.okhttp3.Call createRawCall()(Unknown Source)
	at retrofit2.OkHttpCall.retrofit2.Response execute()(Unknown Source)
	at retrofit2.adapter.rxjava.RxJavaCallAdapterFactory$RequestArbiter.void request(long)(Unknown Source)
	at rx.internal.operators.OperatorSubscribeOn$1$1$1.void request(long)(Unknown Source)
	at rx.Subscriber.void setProducer(rx.Producer)(Unknown Source)
	at rx.Subscriber.void setProducer(rx.Producer)(Unknown Source)
	at rx.internal.operators.OperatorSubscribeOn$1$1.void setProducer(rx.Producer)(Unknown Source)
	at rx.Subscriber.void setProducer(rx.Producer)(Unknown Source)
	at retrofit2.adapter.rxjava.RxJavaCallAdapterFactory$CallOnSubscribe.void call(rx.Subscriber)(Unknown Source)
                                                                      void call(java.lang.Object)
	at retrofit2.adapter.rxjava.RxJavaCallAdapterFactory$CallOnSubscribe.void call(rx.Subscriber)(Unknown Source)
                                                                      void call(java.lang.Object)
	at rx.internal.operators.OnSubscribeLift.void call(rx.Subscriber)(Unknown Source)
	at rx.internal.operators.OnSubscribeLift.void call(java.lang.Object)(Unknown Source)
	at rx.Observable.rx.Observable create(rx.Observable$OnSubscribe)(Unknown Source)
                  rx.Observable lift(rx.Observable$Operator)
                  rx.Single toSingle()
                  rx.Observable just(java.lang.Object)
                  rx.Observable merge(rx.Observable)
                  rx.Observable zip(rx.Observable,rx.Observable,rx.functions.Func2)
                  rx.Observable delay(long,java.util.concurrent.TimeUnit)
                  rx.Observable delay(long,java.util.concurrent.TimeUnit,rx.Scheduler)
                  rx.Observable doOnCompleted(rx.functions.Action0)
                  rx.Observable doOnNext(rx.functions.Action1)
                  rx.Observable flatMap(rx.functions.Func1)
                  rx.Observable observeOn(rx.Scheduler)
                  rx.Observable observeOn(rx.Scheduler,int)
                  rx.Observable observeOn(rx.Scheduler,boolean,int)
                  rx.Subscription unsafeSubscribe(rx.Subscriber)
                  rx.Subscription subscribe(rx.Subscriber,rx.Observable)
	at rx.internal.operators.OperatorSubscribeOn$1.void call()(Unknown Source)
	at rx.internal.schedulers.CachedThreadScheduler$EventLoopWorker$1.void call()(Unknown Source)
	... 8 more
java.lang.OutOfMemoryError: Failed to allocate a 2060 byte allocation with 1288 free bytes and 1288B until OOM
	at okio.Segment.void <init>()(Unknown Source)
                 void <init>(okio.Segment)
                 void <init>(byte[],int,int)
	at okio.SegmentPool.okio.Segment take()(Unknown Source)
                     void recycle(okio.Segment)
	at okio.Buffer.okio.BufferedSink emit()(Unknown Source)
                java.lang.String readUtf8Line(long)
                okio.Segment writableSegment(int)
	at okio.Buffer.okio.Buffer buffer()(Unknown Source)
                byte getByte(long)
                okio.Buffer write(byte[])
                okio.Buffer write(byte[],int,int)
                okio.Buffer writeByte(int)
                okio.BufferedSink writeUtf8(java.lang.String)
                okio.BufferedSink write(okio.ByteString)
	at okio.Buffer$1.void write(int)(Unknown Source)
                  void write(byte[],int,int)
	at java.io.OutputStreamWriter.flushBytes(OutputStreamWriter.java:167)
	at java.io.OutputStreamWriter.convert(OutputStreamWriter.java:181)
	at java.io.OutputStreamWriter.write(OutputStreamWriter.java:324)
	at com.google.gson.stream.JsonWriter.void string(java.lang.String)(Unknown Source)
	at com.google.gson.stream.JsonWriter.com.google.gson.stream.JsonWriter value(java.lang.String)(Unknown Source)
                                      com.google.gson.stream.JsonWriter value(boolean)
                                      com.google.gson.stream.JsonWriter value(double)
                                      com.google.gson.stream.JsonWriter value(long)
                                      com.google.gson.stream.JsonWriter value(java.lang.Number)
	at com.google.gson.internal.bind.TypeAdapters$17.void write(com.google.gson.stream.JsonWriter,java.lang.String)(Unknown Source)
                                                  void write(com.google.gson.stream.JsonWriter,java.lang.Object)
	at com.google.gson.internal.bind.TypeAdapters$17.void write(com.google.gson.stream.JsonWriter,java.lang.String)(Unknown Source)
                                                  void write(com.google.gson.stream.JsonWriter,java.lang.Object)
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.void write(com.google.gson.stream.JsonWriter,java.lang.Object)(Unknown Source)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.void write(com.google.gson.stream.JsonWriter,java.lang.Object)(Unknown Source)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.void write(com.google.gson.stream.JsonWriter,java.lang.Object)(Unknown Source)
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.void write(com.google.gson.stream.JsonWriter,java.lang.Object)(Unknown Source)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.void write(com.google.gson.stream.JsonWriter,java.lang.Object)(Unknown Source)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.void write(com.google.gson.stream.JsonWriter,java.lang.Object)(Unknown Source)
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.void write(com.google.gson.stream.JsonWriter,java.lang.Object)(Unknown Source)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.void write(com.google.gson.stream.JsonWriter,java.lang.Object)(Unknown Source)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.void write(com.google.gson.stream.JsonWriter,java.lang.Object)(Unknown Source)
	at com.google.gson.internal.bind.ObjectTypeAdapter.void write(com.google.gson.stream.JsonWriter,java.lang.Object)(Unknown Source)
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.void write(com.google.gson.stream.JsonWriter,java.lang.Object)(Unknown Source)
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.void write(com.google.gson.stream.JsonWriter,java.util.Map)(Unknown Source)
                                                                void write(com.google.gson.stream.JsonWriter,java.lang.Object)
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.void write(com.google.gson.stream.JsonWriter,java.util.Map)(Unknown Source)
                                                                void write(com.google.gson.stream.JsonWriter,java.lang.Object)
	at retrofit2.converter.gson.GsonRequestBodyConverter.okhttp3.RequestBody convert(java.lang.Object)(Unknown Source)
                                                      java.lang.Object convert(java.lang.Object)
	at retrofit2.converter.gson.GsonRequestBodyConverter.okhttp3.RequestBody convert(java.lang.Object)(Unknown Source)
                                                      java.lang.Object convert(java.lang.Object)
	at retrofit2.ParameterHandler$Body.void apply(retrofit2.RequestBuilder,java.lang.Object)(Unknown Source)
	at retrofit2.ServiceMethod.okhttp3.Request toRequest(java.lang.Object[])(Unknown Source)
	at retrofit2.OkHttpCall.okhttp3.Call createRawCall()(Unknown Source)
	at retrofit2.OkHttpCall.retrofit2.Response execute()(Unknown Source)
	at retrofit2.adapter.rxjava.RxJavaCallAdapterFactory$RequestArbiter.void request(long)(Unknown Source)
	at rx.internal.operators.OperatorSubscribeOn$1$1$1.void request(long)(Unknown Source)
	at rx.Subscriber.void setProducer(rx.Producer)(Unknown Source)
	at rx.Subscriber.void setProducer(rx.Producer)(Unknown Source)
	at rx.internal.operators.OperatorSubscribeOn$1$1.void setProducer(rx.Producer)(Unknown Source)
	at rx.Subscriber.void setProducer(rx.Producer)(Unknown Source)
	at retrofit2.adapter.rxjava.RxJavaCallAdapterFactory$CallOnSubscribe.void call(rx.Subscriber)(Unknown Source)
                                                                      void call(java.lang.Object)
	at retrofit2.adapter.rxjava.RxJavaCallAdapterFactory$CallOnSubscribe.void call(rx.Subscriber)(Unknown Source)
                                                                      void call(java.lang.Object)
	at rx.internal.operators.OnSubscribeLift.void call(rx.Subscriber)(Unknown Source)
	at rx.internal.operators.OnSubscribeLift.void call(java.lang.Object)(Unknown Source)
	at rx.Observable.rx.Observable create(rx.Observable$OnSubscribe)(Unknown Source)
                  rx.Observable lift(rx.Observable$Operator)
                  rx.Single toSingle()
                  rx.Observable just(java.lang.Object)
                  rx.Observable merge(rx.Observable)
                  rx.Observable zip(rx.Observable,rx.Observable,rx.functions.Func2)
                  rx.Observable delay(long,java.util.concurrent.TimeUnit)
                  rx.Observable delay(long,java.util.concurrent.TimeUnit,rx.Scheduler)
                  rx.Observable doOnCompleted(rx.functions.Action0)
                  rx.Observable doOnNext(rx.functions.Action1)
                  rx.Observable flatMap(rx.functions.Func1)
                  rx.Observable observeOn(rx.Scheduler)
                  rx.Observable observeOn(rx.Scheduler,int)
                  rx.Observable observeOn(rx.Scheduler,boolean,int)
                  rx.Subscription unsafeSubscribe(rx.Subscriber)
                  rx.Subscription subscribe(rx.Subscriber,rx.Observable)
	at rx.internal.operators.OperatorSubscribeOn$1.void call()(Unknown Source)
	at rx.internal.schedulers.CachedThreadScheduler$EventLoopWorker$1.void call()(Unknown Source)
	at rx.internal.schedulers.ScheduledAction.void run()(Unknown Source)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:818)

**Comment by JakeWharton** [comment]
You'll have to take a heap dump and see where all your memory is going. OOMs are almost never actually caused by the thing in their stack trace–that was just the action that put it over the edge. Usually it's a pathological problem caused by a memory leak or processing more data than your system can handle.
