### ISSUE TITLE
java.lang.IllegalStateException: closed

### ISSUE THREAD

**Issue by boyfox** [square/retrofit#2220]
02-26 00:19:55.231 16617-17259/com.takeal.stm E/AndroidRuntime: FATAL EXCEPTION: TakeAlCoreNetworkExecutor-1
    Process: com.takeal.stm, PID: 16617
    java.lang.IllegalStateException: closed
        at okhttp3.internal.http1.Http1Codec$FixedLengthSource.read(Http1Codec.java:381)
        at okio.RealBufferedSource.readAll(RealBufferedSource.java:162)
        at retrofit2.Utils.buffer(Utils.java:303)
        at retrofit2.OkHttpCall.parseResponse(OkHttpCall.java:198)
        at retrofit2.OkHttpCall.execute(OkHttpCall.java:174)
        at retrofit2.ExecutorCallAdapterFactory$ExecutorCallbackCall.execute(ExecutorCallAdapterFactory.java:89)
        at com.takeal.stm.fragments.authregpages.AuthPage$9.run(AuthPage.java:614)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
        at java.lang.Thread.run(Thread.java:818)

**Comment by JakeWharton** [comment]
Please provide a failing test case.

**Comment by boyfox** [comment]
Reproducing this error easy, For example : need create response with model - 

`Response<UserResp> resp = ...`

if server will be return error with 404 status code and response content will not matched with model then will be this error

**Comment by boyfox** [comment]
Here is my code:

`try {
    Response<UserResp> resp = TakeAlApp.mMobileCoreApis.loginFB("facebook", token, FirebaseInstanceId.getInstance().getToken()).execute();
    if (resp.isSuccessful()) {
        UserResp userResp = resp.body();
        ....
    } else {
        Converter<ResponseBody, HttpError> errorConverter = TakeAlApp.mRetrofitMobile
                .responseBodyConverter(HttpError.class, new Annotation[0]);
        final HttpError error = errorConverter.convert(resp.errorBody());
        Timber.e("doLogin -----------> ERROR: %s", error.message);
    }
} catch (IOException e) {
    e.printStackTrace();
}`

**Comment by boyfox** [comment]
@JakeWharton you can close this issue, @Jesse Wilson helped to me for finding wrong code in my Login Interceptor class. Sorry.

**Comment by chintan-mishra** [comment]
@boyfox can you share what was wrong in your code? I am having a similar issue.
