### ISSUE TITLE
java.io.EOFException: End of input at line 1 column 1 path 

### ISSUE THREAD

**Issue by aswanth-bonthala** [square/retrofit#2241]
I Have a First Request call which collects multiple provider id's, with that generated provider id's i made multiple Asynchronous Requests inside  onResponse of First Request Call. While running the application the calls are being onFailed(). But while debugging application everything works fine with same code. Please make me clear and solve my doubt

Detailed Log is below:

at com.google.gson.stream.JsonReader.nextNonWhitespace(JsonReader.java:1393)
at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:549)
at com.google.gson.stream.JsonReader.peek(JsonReader.java:425)
at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:205)
at retrofit2.converter.gson.GsonResponseBodyConverter.convert(GsonResponseBodyConverter.java:37)
at retrofit2.converter.gson.GsonResponseBodyConverter.convert(GsonResponseBodyConverter.java:25)
at retrofit2.ServiceMethod.toResponse(ServiceMethod.java:117)
at retrofit2.OkHttpCall.parseResponse(OkHttpCall.java:211)
at retrofit2.OkHttpCall$1.onResponse(OkHttpCall.java:106)
at okhttp3.RealCall$AsyncCall.execute(RealCall.java:133)
at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
at java.lang.Thread.run(Thread.java:818)

**Comment by JakeWharton** [comment]
Your server is returning an empty response. I can't see how this is a problem with Retrofit. Please provide a test case or sample demonstrating the problem so it can be diagnosed.

**Comment by aswanth-bonthala** [comment]
Thanks for the information. I gone through the problem, the server is returning empty response for the first time. So, I changed my request call.Sorry for raising issue.
