### ISSUE TITLE
java.lang.IllegalStateException On 500 error response

### ISSUE THREAD

**Issue by Kazunka** [square/retrofit#2264]
I use RxJava Single method and I handle error on following way.

`private String handleErrors(Throwable error) {
        String errorMsg = null;

        if (error instanceof HttpException) {
            ResponseBody body = ((HttpException) error).response().errorBody();
            Converter<ResponseBody, NetworkErrors> errorConverter = retrofit.responseBodyConverter(NetworkErrors.class, new Annotation[0]);
            try {
                NetworkErrors networkErrors = errorConverter.convert(body); // Convert the error body into our Error type.
                Log.d("Error Occured" , networkErrors.code+" "+ networkErrors.message);
                errorCode = networkErrors.code;
                errorMsg = getNetWorkErrorMessage(networkErrors.code);
                Log.d("Error", errorMsg);
            } catch (IOException e) {
                errorMsg = mContext.getString(R.string.server_down);
                e.printStackTrace();
            }
        } else if (error instanceof IOException){
            errorMsg = mContext.getString(R.string.server_down);
            //TODO: handle io exception
        } else {
            errorMsg = mContext.getString(R.string.server_down);
            //TODO: handle exception
        }
        return errorMsg;
    }`

When ONLY in some time with 500 status code errors. App crashes with this messages. 

This is the error log.

`03-30 17:14:15.602 6974-6974/com.crowderia.grade5 E/AndroidRuntime: FATAL EXCEPTION: main
                                                                    Process: com.crowderia.grade5, PID: 6974
                                                                    java.lang.IllegalStateException: Fatal Exception thrown on Scheduler.Worker thread.
                                                                        at rx.android.schedulers.LooperScheduler$ScheduledAction.run(LooperScheduler.java:114)
                                                                        at android.os.Handler.handleCallback(Handler.java:751)
                                                                        at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                        at android.os.Looper.loop(Looper.java:154)
                                                                        at android.app.ActivityThread.main(ActivityThread.java:6077)
                                                                        at java.lang.reflect.Method.invoke(Native Method)
                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
                                                                     Caused by: rx.exceptions.OnErrorFailedException: Error occurred when trying to propagate error to Observer.onError
                                                                        at rx.observers.SafeSubscriber._onError(SafeSubscriber.java:192)
                                                                        at rx.observers.SafeSubscriber.onError(SafeSubscriber.java:120)
                                                                        at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.checkTerminated(OperatorObserveOn.java:276)
                                                                        at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.call(OperatorObserveOn.java:219)
                                                                        at rx.android.schedulers.LooperScheduler$ScheduledAction.run(LooperScheduler.java:107)
                                                                        at android.os.Handler.handleCallback(Handler.java:751) 
                                                                        at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                                        at android.os.Looper.loop(Looper.java:154) 
                                                                        at android.app.ActivityThread.main(ActivityThread.java:6077) 
                                                                        at java.lang.reflect.Method.invoke(Native Method) 
                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865) 
                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755) 
                                                                     Caused by: rx.exceptions.CompositeException: 2 exceptions occurred. 
                                                                        at rx.observers.SafeSubscriber._onError(SafeSubscriber.java:192) 
                                                                        at rx.observers.SafeSubscriber.onError(SafeSubscriber.java:120) 
                                                                        at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.checkTerminated(OperatorObserveOn.java:276) 
                                                                        at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.call(OperatorObserveOn.java:219)  at rx.android.schedulers.LooperScheduler$ScheduledAction.run(LooperScheduler.java:107) 
                                                                        at android.os.Handler.handleCallback(Handler.java:751) 
                                                                        at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                                        at android.os.Looper.loop(Looper.java:154) 
                                                                        at android.app.ActivityThread.main(ActivityThread.java:6077) 
                                                                        at java.lang.reflect.Method.invoke(Native Method) 
                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865) 
                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755) 
                                                                     Caused by: rx.exceptions.CompositeException$CompositeExceptionCausalChain: Chain of Causes for CompositeException In Order Received =>
                                                                        at android.util.Log.printlns(Log.java:415)
                                                                        at com.android.internal.os.RuntimeInit.Clog_e(RuntimeInit.java:61)
                                                                        at com.android.internal.os.RuntimeInit.-wrap0(RuntimeInit.java)
                                                                        at com.android.internal.os.RuntimeInit$UncaughtHandler.uncaughtException(RuntimeInit.java:86)
                                                                        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1068)
                                                                        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1063)
                                                                        at rx.android.schedulers.LooperScheduler$ScheduledAction.run(LooperScheduler.java:118)
                                                                        at android.os.Handler.handleCallback(Handler.java:751) 
                                                                        at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                                        at android.os.Looper.loop(Looper.java:154) 
                                                                        at android.app.ActivityThread.main(ActivityThread.java:6077) 
                                                                        at java.lang.reflect.Method.invoke(Native Method) 
                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865) 
                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755) 
                                                                     Caused by: retrofit2.adapter.rxjava.HttpException: HTTP 500 Internal Server Error
                                                                        at retrofit2.adapter.rxjava.OperatorMapResponseToBodyOrError$1.onNext(OperatorMapResponseToBodyOrError.java:43)
                                                                        at retrofit2.adapter.rxjava.OperatorMapResponseToBodyOrError$1.onNext(OperatorMapResponseToBodyOrError.java:38)
                                                                        at retrofit2.adapter.rxjava.RxJavaCallAdapterFactory$RequestArbiter.request(RxJavaCallAdapterFactory.java:173)
                                                                        at rx.Subscriber.setProducer(Subscriber.java:211)
                                                                        at rx.Subscriber.setProducer(Subscriber.java:205)
                                                                        at retrofit2.adapter.rxjava.RxJavaCallAdapterFactory$CallOnSubscribe.call(RxJavaCallAdapterFactory.java:152)
                                                                        at retrofit2.adapter.rxjava.RxJavaCallAdapterFactory$CallOnSubscribe.call(RxJavaCallAdapterFactory.java:138)
                                                                        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:50)
                                                                        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
                                                                        at rx.Observable.unsafeSubscribe(Observable.java:8666)
                                                                        at rx.internal.operators.OnSubscribeSingle.call(OnSubscribeSingle.java:84)
                                                                        at rx.internal.operators.OnSubscribeSingle.call(OnSubscribeSingle.java:30)
                                                                        at rx.Single$1.call(Single.java:94)
                                                                        at rx.Single$1.call(Single.java:74)
                                                                        at rx.Single.subscribe(Single.java:1822)
                                                                        at rx.Single.subscribe(Single.java:1899)
                                                                        at rx.Single$19$1.call(Single.java:1954)
                                                                        at rx.internal.schedulers.CachedThreadScheduler$EventLoopWorker$1.call(CachedThreadScheduler.java:220)
                                                                        at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
                                                                        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
                                                                        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272)
                                                                        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                                        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                                        at java.lang.Thread.run(Thread.java:761)
                                                                     Caused by: java.lang.RuntimeException: Duplicate found in causal chain so cropping to prevent loop ...
                                                                        at android.util.Log.printlns(Log.java:415)`

When I debug it it runs all try block. and app crashes after that. Can't find anything wrong, No object mismatch. Where it went wrong?

**Comment by JakeWharton** [comment]
I don't see anything related to Retrofit here. It's calling your onError callback which then looks like it throws another exception somewhere and then Android's uncaught exception handler crashes trying to log that exception.

If you can provide a test case that reproduces the problem I can take a look, but it doesn't seem related to Retrofit.

**Comment by Kazunka** [comment]
Thank you very much. I found the error, It was onError callback. Sorry for the mistake. I really enjoy this library, supper fast.

**Comment by MegaAndroidDeveloper666** [comment]
> Thank you very much. I found the error, It was onError callback. Sorry for the mistake. I really enjoy this library, supper fast.

Hello! Can you provide more information how to fix this issue?
