### ISSUE TITLE
rxjava  :   Fatal Exception thrown on Scheduler.Worker thread.  network socket time out

### ISSUE THREAD

**Issue by myhcqgithub** [square/retrofit#2283]
java.lang.IllegalStateException: Fatal Exception thrown on Scheduler.Worker thread.
                                                                  at rx.android.schedulers.LooperScheduler$ScheduledAction.run(LooperScheduler.java:114)
                                                                  at android.os.Handler.handleCallback(Handler.java:739)
                                                                  at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                  at android.os.Looper.loop(Looper.java:148)
                                                                  at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                  at java.lang.reflect.Method.invoke(Native Method)
                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                                                               Caused by: rx.exceptions.OnErrorFailedException: Error occurred when trying to propagate error to Observer.onError
                                                                  at rx.observers.SafeSubscriber._onError(SafeSubscriber.java:187)
                                                                  at rx.observers.SafeSubscriber.onError(SafeSubscriber.java:115)
                                                                  at rx.internal.operators.OnSubscribeMap$MapSubscriber.onError(OnSubscribeMap.java:88)
                                                                  at rx.internal.operators.OnSubscribeMap$MapSubscriber.onError(OnSubscribeMap.java:88)
                                                                  at rx.internal.operators.OperatorMerge$MergeSubscriber.reportError(OperatorMerge.java:266)
                                                                  at rx.internal.operators.OperatorMerge$MergeSubscriber.checkTerminate(OperatorMerge.java:818)
                                                                  at rx.internal.operators.OperatorMerge$MergeSubscriber.emitLoop(OperatorMerge.java:579)
                                                                  at rx.internal.operators.OperatorMerge$MergeSubscriber.emit(OperatorMerge.java:568)
                                                                  at rx.internal.operators.OperatorMerge$MergeSubscriber.onError(OperatorMerge.java:276)
                                                                  at rx.internal.operators.OnSubscribeMap$MapSubscriber.onError(OnSubscribeMap.java:88)
                                                                  at rx.internal.operators.OperatorMerge$MergeSubscriber.reportError(OperatorMerge.java:266)
                                                                  at rx.internal.operators.OperatorMerge$MergeSubscriber.checkTerminate(OperatorMerge.java:818)
                                                                  at rx.internal.operators.OperatorMerge$MergeSubscriber.emitLoop(OperatorMerge.java:579)
                                                                  at rx.internal.operators.OperatorMerge$MergeSubscriber.emit(OperatorMerge.java:568)
                                                                  at rx.internal.operators.OperatorMerge$InnerSubscriber.onError(OperatorMerge.java:852)
                                                                  at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.checkTerminated(OperatorObserveOn.java:273)
                                                                  at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.call(OperatorObserveOn.java:216)
                                                                  at rx.android.schedulers.LooperScheduler$ScheduledAction.run(LooperScheduler.java:107)
                                                                  at android.os.Handler.handleCallback(Handler.java:739) 
                                                                  at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                                  at android.os.Looper.loop(Looper.java:148) 
                                                                  at android.app.ActivityThread.main(ActivityThread.java:5417) 
                                                                  at java.lang.reflect.Method.invoke(Native Method) 
                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
                                                               Caused by: rx.exceptions.CompositeException: 2 exceptions occurred. 
                                                                  at rx.observers.SafeSubscriber._onError(SafeSubscriber.java:187) 
                                                                  at rx.observers.SafeSubscriber.onError(SafeSubscriber.java:115) 
                                                                  at rx.internal.operators.OnSubscribeMap$MapSubscriber.onError(OnSubscribeMap.java:88) 
                                                                  at rx.internal.operators.OnSubscribeMap$MapSubscriber.onError(OnSubscribeMap.java:88) 
                                                                  at rx.internal.operators.OperatorMerge$MergeSubscriber.reportError(OperatorMerge.java:266) 
                                                                  at rx.internal.operators.OperatorMerge$MergeSubscriber.checkTerminate(OperatorMerge.java:818) 
                                                                  at rx.internal.operators.OperatorMerge$MergeSubscriber.emitLoop(OperatorMerge.java:579) 
                                                                  at rx.internal.operators.OperatorMerge$MergeSubscriber.emit(OperatorMerge.java:568) 
                                                                  at rx.internal.operators.OperatorMerge$MergeSubscriber.onError(OperatorMerge.java:276) 
                                                                  at rx.internal.operators.OnSubscribeMap$MapSubscriber.onError(OnSubscribeMap.java:88) 
                                                                  at rx.internal.operators.OperatorMerge$MergeSubscriber.reportError(OperatorMerge.java:266) 
                                                                  at rx.internal.operators.OperatorMerge$MergeSubscriber.checkTerminate(OperatorMerge.java:818) 
                                                                  at rx.internal.operators.OperatorMerge$MergeSubscriber.emitLoop(OperatorMerge.java:579) 
                                                                  at rx.internal.operators.OperatorMerge$MergeSubscriber.emit(OperatorMerge.java:568) 
                                                                  at rx.internal.operators.OperatorMerge$InnerSubscriber.onError(OperatorMerge.java:852) 
                                                                  at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.checkTerminated(OperatorObserveOn.java:273) 
                                                                  at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.call(OperatorObserveOn.java:216) 
                                                                  at rx.android.schedulers.LooperScheduler$ScheduledAction.run(LooperScheduler.java:107) 
                                                                  at android.os.Handler.handleCallback(Handler.java:739) 
                                                                  at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                                  at android.os.Looper.loop(Looper.java:148) 
                                                                  at android.app.ActivityThread.main(ActivityThread.java:5417) 
                                                                  at java.lang.reflect.Method.invoke(Native Method) 
                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
                                                               Caused by: rx.exceptions.CompositeException$CompositeExceptionCausalChain: Chain of Causes for CompositeException In Order Received =>
                                                                  at android.util.Log.getStackTraceString(Log.java:338)
                                                                  at com.android.internal.os.RuntimeInit.Clog_e(RuntimeInit.java:61)
                                                                  at com.android.internal.os.RuntimeInit.-wrap0(RuntimeInit.java)
                                                                  at com.android.internal.os.RuntimeInit$UncaughtHandler.uncaughtException(RuntimeInit.java:86)
                                                                  at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:693)
                                                                  at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:690)
                                                                  at rx.android.schedulers.LooperScheduler$ScheduledAction.run(LooperScheduler.java:118)
                                                                  at android.os.Handler.handleCallback(Handler.java:739) 
                                                                  at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                                  at android.os.Looper.loop(Looper.java:148) 
                                                                  at android.app.ActivityThread.main(ActivityThread.java:5417) 
                                                                  at java.lang.reflect.Method.invoke(Native Method) 
                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
                                                               Caused by: java.net.SocketTimeoutException: failed to connect to /192.168.0.109 (port 10000) after 10000ms
                                                                  at libcore.io.IoBridge.connectErrno(IoBridge.java:169)
                                                                  at libcore.io.IoBridge.connect(IoBridge.java:122)
                                                                  at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:183)
                                                                  at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:452)
                                                                  at java.net.Socket.connect(Socket.java:884)
                                                                  at okhttp3.internal.platform.AndroidPlatform.connectSocket(AndroidPlatform.java:63)
                                                                  at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:220)
                                                                  at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:146)
                                                                  at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:186)
                                                                  at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:121)
                                                                  at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:100)
                                                              	at okhttp3.internal.connection.ConnectInterceptor.intercep

**Comment by artem-zinnatullin** [comment]
SocketTimeoutException occurred while you were making network request, this
can happen and you should add error handling.

**Comment by JakeWharton** [comment]
Yep, socket timeouts and all kinds of IOExceptions around the network being
broken are normal, regular occurrences that your code needs to handle.

**Comment by egpayawal** [comment]
Hi @JakeWharton,

Good day. I'm having the issue above and I'm wondering how can I fix it? thank you in advanced.

**Comment by JakeWharton** [comment]
Add error-handling to your subscribers.

**Comment by egpayawal** [comment]
@JakeWharton thank you. I'll try that one. 👍

**Comment by egpayawal** [comment]
Hi @JakeWharton,

I just realized that you are referring on handling error from throwable in subscriber. Because on my code (please see below) that I'm handling the error. But the cause of error is the another throwable within throwable, is that correct? So, my question is which of the two solution below is better of error-handling? A or B?

```
mSubscription = mDataSource.getObjectList()
                    .subscribeOn(mRxSchedulerConfiguration.getComputationThread())
                    .observeOn(mRxSchedulerConfiguration.getMainThread())
                    .subscribe(list -> {
                        // todo
                    }, throwable -> {
                        // todo
                    });
```
**Solution A:**
```
mSubscription = mDataSource.getObjectList()
                    .subscribeOn(mRxSchedulerConfiguration.getComputationThread())
                    .observeOn(mRxSchedulerConfiguration.getMainThread())
                    .subscribe(list -> {
                        // todo
                    }, throwable -> {
                        try {
                            // todo
                        } catch (Throwable e) {
                            Log.e(TAG, "Within Throwable Exception::" + e.getMessage());
                        }
                    });
```
**Solution B.**
https://blog.mindorks.com/rxjava2-and-retrofit2-error-handling-on-a-single-place-8daf720d42d6

Best Regards,
E.R.

**Comment by JakeWharton** [comment]
You're not allowed to throw from an onError handler. If that second
exception is crashing your app it seems like the correct behavior since you
errored while trying to recover from an error.
