### ISSUE TITLE
Exception in thread "main" java.lang.NoClassDefFoundError: retrofit2/converter/jackson/JacksonConverterFactory

### ISSUE THREAD

**Issue by sufikrodon** [square/retrofit#2298]
I'm setting consul client api in eclipse. I got below error. Even included following jars. Didnt help.

![capture](https://cloud.githubusercontent.com/assets/25240866/25272407/4a70ea5a-26a5-11e7-95c1-41d6651e2d90.PNG)

Exception in thread "main" java.lang.NoClassDefFoundError: retrofit2/converter/jackson/JacksonConverterFactory
	at com.orbitz.consul.Consul.builder(Consul.java:202)
	at com.demo.Client2.main(Client2.java:10)
Caused by: java.lang.ClassNotFoundException: retrofit2.converter.jackson.JacksonConverterFactory
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 2 more

This is my code:
### public static void main(String[] args) throws NotRegisteredException {
		Consul consul = Consul.builder().build(); // connect to Consul
													// onlocalhost
		AgentClient agentClient = consul.agentClient();

		String serviceName = "MyService";
		String serviceId = "1";

		agentClient.register(8090, 3L, serviceName, serviceId); // registers
																// with a TTL of
																// 3 seconds
		agentClient.pass(serviceId);

	}

**Comment by JakeWharton** [comment]
You need to include [the Jackson converter][1], not the Gson converter.

 [1]: https://github.com/square/retrofit/tree/bd8e38d406fff637ed69b1b312a8e439aa28b012/retrofit-converters/jackson
