### ISSUE TITLE
Simplexml converter exception when '#' is present in xml element data 

### ISSUE THREAD

**Issue by shabarishbk** [square/retrofit#2350]
SimpleXml converter runs into exception when there is '#' character in the response xml

Sample response : <eTag>01#20170516120742429#fbb:b-6062e7b214132b199adf5f264dd3c-4006155-7a7383d2-be2f-4e66-8b1f-3866eec618</eTag>

`android.os.HandlerThread.run(HandlerThread.java:61)
 Caused by: org.xmlpull.v1.XmlPullParserException: unterminated entity ref (position:TEXT @1:184 in okhttp3.ResponseBody$BomAwareReader@fafd8f8)
     at org.kxml2.io.KXmlParser.readEntity(KXmlParser.java:1219)
     at org.kxml2.io.KXmlParser.readValue(KXmlParser.java:1401)
     at org.kxml2.io.KXmlParser.next(KXmlParser.java:393)
     at org.kxml2.io.KXmlParser.next(KXmlParser.java:313)
     at org.simpleframework.xml.stream.PullReader.read(PullReader.java:105)
     at org.simpleframework.xml.stream.PullReader.next(PullReader.java:89)
     at org.simpleframework.xml.stream.NodeReader.readElement(NodeReader.java:111)
     at org.simpleframework.xml.stream.NodeReader.readRoot(NodeReader.java:85)
     at org.simpleframework.xml.stream.NodeBuilder.read(NodeBuilder.java:84)
     at org.simpleframework.xml.stream.NodeBuilder.read(NodeBuilder.java:71)
     at org.simpleframework.xml.core.Persister.read(Persister.java:562)
     at retrofit2.converter.simplexml.SimpleXmlResponseBodyConverter.convert(SimpleXmlResponseBodyConverter.java:36)`

**Comment by JakeWharton** [comment]
This is not a problem with Retrofit but one with Simple XML. Please file a
bug on that project.
