### ISSUE TITLE
Response.error(int, ResponseBody) throws an IllegalStateException

### ISSUE THREAD

**Issue by kylefowler-uptake** [square/retrofit#2359]
When trying to build a Retrofit error Response, an Illegal state exception is thrown because a `message` is not supplied to the OkHttp3.Response.Builder.

Exception:
```
java.lang.IllegalStateException: message == null

	at okhttp3.Response$Builder.build(Response.java:431)
	at retrofit2.Response.error(Response.java:72)
```

Test Case:
```
package com.uptake.login;

import okhttp3.MediaType;
import okhttp3.ResponseBody;
import org.junit.Test;
import retrofit2.Response;

public class ExampleUnitTest {

    @Test
    public void buildRetrofitResponseFromResponseBody() throws Exception {
        Response r = Response.error(500, ResponseBody.create(MediaType.parse("text/plain"),"There was a problem"));
        assert r != null;
    }
}
```

**Comment by JakeWharton** [comment]
Use 2.3.0
