### ISSUE TITLE
[ Crash ] FATAL EXCEPTION: OkHttp Dispatcher

### ISSUE THREAD

**Issue by chihung93** [square/retrofit#2368]
Samsung J5 prime
Android 6.0

```
dependencies {
    compile fileTree(include: ['*.jar'], dir: 'libs')
    /**
     * Support
     * */
    compile "com.android.support:appcompat-v7:$supportLibraryVersion"
    compile "com.android.support:support-v4:$supportLibraryVersion"
    compile "com.android.support:design:$supportLibraryVersion"
    compile "com.android.support:percent:$supportLibraryVersion"

    /**
     * Squareup
     * */
    compile "com.squareup.retrofit2:retrofit:$retrofit"
    compile "com.squareup.retrofit2:converter-gson:$retrofit"
    /**
     *  Google
     * */
    compile "com.google.android.gms:play-services-analytics:$playServicesVersion"
    compile "com.google.firebase:firebase-core:$playServicesVersion"
    compile "com.google.android.gms:play-services-gcm:$playServicesVersion"
    compile "com.google.android.gms:play-services-maps:$playServicesVersion"
    compile 'com.google.guava:guava:22.0-rc1-android'

    compile 'com.squareup.okhttp3:logging-interceptor:3.8.0'
    compile 'com.squareup.okhttp3:okhttp:3.8.0'

    compile 'com.github.bumptech.glide:glide:3.8.0'
    compile 'org.greenrobot:eventbus:3.0.0'
    compile 'com.kyleduo.switchbutton:library:1.4.4'
    compile 'com.github.franmontiel:PersistentCookieJar:v1.0.1'
    compile 'com.github.arimorty:floatingsearchview:2.0.3'
    compile 'org.androidannotations:androidannotations-api:4.1.0'
    compile 'com.wang.avi:library:2.1.3'
    compile 'com.thefinestartist:finestwebview:1.2.7'
    compile 'com.github.pwittchen:reactivenetwork-rx2:0.9.1'
    compile 'me.relex:circleindicator:1.2.2@aar'
    apt 'org.androidannotations:androidannotations:4.1.0'
}



FATAL EXCEPTION: OkHttp Dispatcher
                                                                    Process: hung.nc.com, PID: 5368
                                                                    java.util.NoSuchElementException
                                                                        at okhttp3.internal.connection.RouteSelector.next(RouteSelector.java:78)
                                                                        at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:171)
                                                                        at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:121)
                                                                        at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:100)
                                                                        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
                                                                        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
                                                                        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
                                                                        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
                                                                        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
                                                                        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
                                                                        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
                                                                        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
                                                                        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:120)
                                                                        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
                                                                        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
                                                                        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:185)
                                                                        at okhttp3.RealCall$AsyncCall.execute(RealCall.java:135)
                                                                        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
                                                                        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                        at java.lang.Thread.run(Thread.java:818)

```

**Comment by JakeWharton** [comment]
Not a Retrofit issue. See https://github.com/square/okhttp/issues/3308.

**Comment by Apprika** [comment]
@JakeWharton I get that this is not a retrofit crash. okHttp issue #3308 has been fixed but how do i go about fixing this issue within our app. 

`
ext {
  butterKnifeVersion = '8.5.1'
  icepickVersion = '3.2.0'
  mosbyLibraryVersion = '3.0.0'
  parcelerVersion = '1.1.6'
  supportLibraryVersion = '25.3.1'
  eventBusVersion = '3.0.0'
  googlePlayServicesVersion = '10.2.1'
  hockeyAppVersion = '4.1.3'
  facebookSDKVersion = '4.22.0'
  retrofitVersion = '2.3.0'
  sthethoVersion = '1.5.0'
}
dependencies {
  compile fileTree(include: ['*.jar'], dir: 'libs')
  testCompile 'junit:junit:4.12'
  compile('com.crashlytics.sdk.android:crashlytics:2.6.7@aar') {
    transitive = true;
  }
  compile "com.android.support:appcompat-v7:$supportLibraryVersion"
  compile "com.android.support:design:$supportLibraryVersion"
  compile "com.android.support:customtabs:$supportLibraryVersion"
  compile "com.android.support:animated-vector-drawable:$supportLibraryVersion"
  compile "com.android.support:cardview-v7:$supportLibraryVersion"
  compile "com.android.support:support-v4:$supportLibraryVersion"
  // https://github.com/JakeWharton/butterknife
  compile "com.jakewharton:butterknife:$butterKnifeVersion"
  apt "com.jakewharton:butterknife-compiler:$butterKnifeVersion"
  // https://github.com/johncarl81/parceler
  compile "org.parceler:parceler-api:$parcelerVersion"
  apt "org.parceler:parceler:$parcelerVersion"
  // https://github.com/frankiesardo/icepick
  compile "frankiesardo:icepick:$icepickVersion"
  provided "frankiesardo:icepick-processor:$icepickVersion"
  // https://github.com/sockeqwe/mosby
  compile "com.hannesdorfmann.mosby3:mvp:$mosbyLibraryVersion"
  compile "com.hannesdorfmann.mosby3:viewstate:$mosbyLibraryVersion"
  // https://github.com/google/gson
  compile 'com.google.code.gson:gson:2.8.0'
  // https://github.com/greenrobot/EventBus
  compile "org.greenrobot:eventbus:$eventBusVersion"
  // https://github.com/81813780/AVLoadingIndicatorView
  compile 'com.wang.avi:library:2.1.3'
  // https://github.com/ApmeM/android-flowlayout
  compile 'org.apmem.tools:layouts:1.10@aar'
  // https://github.com/bitstadium/HockeySDK-Android
  compile "net.hockeyapp.android:HockeySDK:$hockeyAppVersion"
  // https://github.com/Clans/FloatingActionButton
  compile 'com.github.clans:fab:1.6.4'
  // https://developers.google.com/android/guides/setup
  compile "com.google.android.gms:play-services-analytics:$googlePlayServicesVersion"
  compile "com.google.android.gms:play-services-location:$googlePlayServicesVersion"
  // https://github.com/bumptech/glide
  compile 'com.github.bumptech.glide:glide:3.7.0'
  //https://github.com/square/retrofit
  compile "com.squareup.retrofit2:retrofit:$retrofitVersion"
  compile "com.squareup.retrofit2:converter-gson:$retrofitVersion"
  // http://facebook.github.io/stetho/
  compile "com.facebook.stetho:stetho:$sthethoVersion"
  compile "com.facebook.stetho:stetho-okhttp3:$sthethoVersion"
  // https://github.com/facebook/facebook-android-sdk
  compile "com.facebook.android:facebook-android-sdk:$facebookSDKVersion"
  // https://developer.android.com/studio/build/multidex.html#mdex-gradle
  compile 'com.android.support:multidex:1.0.1'
  // https://docs.fabric.io/android/twitter/compose-tweets.html
  compile('com.twitter.sdk.android:tweet-composer:2.3.1@aar') {
    transitive = true;
  }
  compile "com.google.firebase:firebase-core:$googlePlayServicesVersion"
  compile "com.google.firebase:firebase-messaging:$googlePlayServicesVersion"

  //https://developer.android.com/topic/libraries/architecture/adding-components.html
  compile "android.arch.lifecycle:runtime:1.0.0-alpha3"
  compile "android.arch.lifecycle:extensions:1.0.0-alpha3"
  apt "android.arch.lifecycle:compiler:1.0.0-alpha3"

}`
