### ISSUE TITLE
Non-fatal Exception: javax.net.ssl.SSLHandshakeException: Connection closed by peer

### ISSUE THREAD

**Issue by jonathansds** [square/retrofit#2388]
The following exception is thrown when the server is offline or connection is closed:

using: 
`compile 'com.squareup.retrofit2:retrofit:2.1.0'`
`compile 'com.squareup.retrofit2:converter-gson:2.1.0'`

`Non-fatal Exception: javax.net.ssl.SSLHandshakeException: Connection closed by peer
       at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(NativeCrypto.java)
       at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:324)
       at okhttp3.internal.connection.RealConnection.connectTls(RealConnection.java:268)
       at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.java:238)
       at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:149)
       at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:192)
       at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:121)
       at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:100)
       at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
       at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
       at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
       at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:120)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
       at com.jd.myworld.service.ServiceMWR$MWInterceptor.intercept(ServiceMWR.java:65)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
       at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:185)
       at okhttp3.RealCall$AsyncCall.execute(RealCall.java:135)
       at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
       at java.lang.Thread.run(Thread.java:818)`

**Comment by JakeWharton** [comment]
This is normal. You need to be resistant to IOException.

**Comment by WillEllis** [comment]
I get a number of exceptions like this in my interceptor. Whats the best way to handle it? catch all IOExceptions, log a warning and then not rethrow? Or would that cause issues in OKHttp for other circumstances?

**Comment by swankjesse** [comment]
Usually this is handled with a passive offline indication to your user, such as a "try again" button.

**Comment by Bajranghudda** [comment]
@JakeWharton and @swankjesse I don't understand. 
I am also getting the same exception some times, I used the "Try Again" feature with recalling APIs but no success, it keeps throwing the same error for some times and after some time it starts working fine.
