### ISSUE TITLE
UndeliverableException , noClassDefFoundError: rx.Observable

### ISSUE THREAD

**Issue by GitHubMurt** [square/retrofit#2415]
I'm using RxJava2 togother with kotlin.

RxVersion
```
// RxJava
    compile 'io.reactivex.rxjava2:rxandroid:2.0.1'
    compile 'io.reactivex.rxjava2:rxjava:2.1.1'
    compile 'io.reactivex.rxjava2:rxkotlin:2.1.0'
```
I create stream like this
```
carDetailsUsecase.carAndContractDetails
                .subscribeOn(Schedulers.io())
                .observeOn(AndroidSchedulers.mainThread())
                .subscribeBy( onSuccess = {
                    SettingsSharedPref.setRegistrationNumber(it.registrationNumber)
                }, onError = {
                    Timber.e(it, "Error while refreshing car registration number")
                })
```

My usecase looks like
```
class CarDetailsUsecase {
    lateinit var backed: RestApiService

    init {
        Application.getApiComponent().inject(this)
}

    val carAndContractDetails: Single<CarDetails>
        get() = backed!!.carAndContractDetails
}
```
I got strange exception

```
07-18 12:27:52.971 20267-20291/E/AndroidRuntime: FATAL EXCEPTION: RxCachedThreadScheduler-1
                                                                      Process: pl.intenso.carefleet, PID: 20267
                                                                      io.reactivex.exceptions.UndeliverableException: java.lang.NoClassDefFoundError: rx.Observable
                                                                          at io.reactivex.plugins.RxJavaPlugins.onError(RxJavaPlugins.java:349)
                                                                          at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:64)
                                                                          at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:52)
                                                                          at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                          at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272)
                                                                          at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                                          at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                                          at java.lang.Thread.run(Thread.java:761)
                                                                       Caused by: java.lang.NoClassDefFoundError: rx.Observable
                                                                          at libcore.reflect.InternalNames.getClass(InternalNames.java:55)
                                                                          at java.lang.Class.getDexCacheType(Class.java:2551)
                                                                          at java.lang.reflect.Method.getReturnType(Method.java:150)
                                                                          at java.lang.Class.getDeclaredMethods(Class.java:1811)
                                                                          at com.fasterxml.jackson.databind.introspect.AnnotatedClass._findClassMethods(AnnotatedClass.java:1195)
                                                                          at com.fasterxml.jackson.databind.introspect.AnnotatedClass._addMemberMethods(AnnotatedClass.java:723)
                                                                          at com.fasterxml.jackson.databind.introspect.AnnotatedClass.resolveMemberMethods(AnnotatedClass.java:539)
                                                                          at com.fasterxml.jackson.databind.introspect.AnnotatedClass.memberMethods(AnnotatedClass.java:322)
                                                                          at com.fasterxml.jackson.databind.introspect.POJOPropertiesCollector._addMethods(POJOPropertiesCollector.java:510)
                                                                          at com.fasterxml.jackson.databind.introspect.POJOPropertiesCollector.collectAll(POJOPropertiesCollector.java:302)
                                                                          at com.fasterxml.jackson.databind.introspect.POJOPropertiesCollector.getPropertyMap(POJOPropertiesCollector.java:266)
                                                                          at com.fasterxml.jackson.databind.introspect.POJOPropertiesCollector.getProperties(POJOPropertiesCollector.java:158)
                                                                          at com.fasterxml.jackson.databind.introspect.BasicBeanDescription._properties(BasicBeanDescription.java:144)
                                                                          at com.fasterxml.jackson.databind.introspect.BasicBeanDescription.findProperties(BasicBeanDescription.java:219)
                                                                          at com.fasterxml.jackson.databind.deser.BasicDeserializerFactory._findCreatorsFromProperties(BasicDeserializerFactory.java:332)
                                                                          at com.fasterxml.jackson.databind.deser.BasicDeserializerFactory._constructDefaultValueInstantiator(BasicDeserializerFactory.java:314)
                                                                          at com.fasterxml.jackson.databind.deser.BasicDeserializerFactory.findValueInstantiator(BasicDeserializerFactory.java:253)
                                                                          at com.fasterxml.jackson.databind.deser.BeanDeserializerFactory.buildBeanDeserializer(BeanDeserializerFactory.java:219)
                                                                          at com.fasterxml.jackson.databind.deser.BeanDeserializerFactory.createBeanDeserializer(BeanDeserializerFactory.java:141)
                                                                          at com.fasterxml.jackson.databind.deser.DeserializerCache._createDeserializer2(DeserializerCache.java:403)
                                                                          at com.fasterxml.jackson.databind.deser.DeserializerCache._createDeserializer(DeserializerCache.java:349)
                                                                          at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCache2(DeserializerCache.java:264)
                                                                          at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCacheValueDeserializer(DeserializerCache.java:244)
                                                                          at com.fasterxml.jackson.databind.deser.DeserializerCache.findValueDeserializer(DeserializerCache.java:142)
                                                                          at com.fasterxml.jackson.databind.DeserializationContext.findRootValueDeserializer(DeserializationContext.java:476)
                                                                          at com.fasterxml.jackson.databind.ObjectReader._prefetchRootDeserializer(ObjectReader.java:1902)
                                                                          at com.fasterxml.jackson.databind.ObjectReader.<init>(ObjectReader.java:185)
                                                                          at com.fasterxml.jackson.databind.ObjectMapper._newReader(ObjectMapper.java:650)
                                                                          at com.fasterxml.jackson.databind.ObjectMapper.readerFor(ObjectMapper.java:3356)
                                                                          at retrofit2.converter.jackson.JacksonConverterFactory.responseBodyConverter(JacksonConverterFactory.java:60)
07-18 12:27:52.971 20267-20291/E/AndroidRuntime:     at retrofit2.Retrofit.nextResponseBodyConverter(Retrofit.java:330)
                                                                          at retrofit2.Retrofit.responseBodyConverter(Retrofit.java:313)
                                                                          at retrofit2.ServiceMethod$Builder.createResponseConverter(ServiceMethod.java:736)
                                                                          at retrofit2.ServiceMethod$Builder.build(ServiceMethod.java:169)
                                                                          at retrofit2.Retrofit.loadServiceMethod(Retrofit.java:170)
                                                                          at retrofit2.Retrofit$1.invoke(Retrofit.java:147)
                                                                          at java.lang.reflect.Proxy.invoke(Proxy.java:813)
                                                                          at $Proxy1.getCarAndContractDetails(Unknown Source)
                                                                          at CarDetailsUsecase.getCarAndContractDetails(CarDetailsUsecase.kt:33)
                                                                          at .UI.MainScreen.RefreshGeneralInfoPresenter.refreshRegistrationNumber(RefreshGeneralInfoPresenter.kt:27)
                                                                          at UI.MainScreen.RefreshGeneralInfoPresenter.refresh(RefreshGeneralInfoPresenter.kt:22)
                                                                          at UI.MainScreen.MainActivity.onCreate(MainActivity.java:91)
                                                                          at android.app.Activity.performCreate(Activity.java:6662)
                                                                          at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
                                                                          at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2599)
                                                                          at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2707)
                                                                          at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                                          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1460)
                                                                          at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                          at android.os.Looper.loop(Looper.java:154)
                                                                          at android.app.ActivityThread.main(ActivityThread.java:6077)
                                                                          at java.lang.reflect.Method.invoke(Native Method)
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866)
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756)
                                                                       Caused by: java.lang.ClassNotFoundException: Didn't find class "rx.Observable" on path: DexPathList[[zip file "/data/app/pl.intenso.carefleet-2/base.apk", zip file "/data/app/pl.intenso.carefleet-2/split_lib_dependencies_apk.apk", zip file "/data/app/app/split_lib_slice_0_apk.apk", zip file "/data/app/pl.intenso.carefleet-2/split_lib_slice_1_apk.apk", zip file "/data/app/app/split_lib_slice_2_apk.apk", zip file "/data/app/app/split_lib_slice_3_apk.apk", zip file "/data/app/app/split_lib_slice_4_apk.apk", zip file "/data/app/app/split_lib_slice_5_apk.apk", zip file "/data/app/app/split_lib_slice_6_apk.apk", zip file "/data/app/app/split_lib_slice_7_apk.apk", zip file "/data/app/app/split_lib_slice_8_apk.apk", zip file "/data/app/app/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/app/lib/x86, /data/app/app/base.apk!/lib/x86, /data/app/app/split_lib_dependencies_apk.apk!/lib/x86, /data/app/app/split_lib_slice_0_apk.apk!/lib/x86, /data/app/app/split_lib_slice_1_apk.apk!/lib/x86, /data/app/app/split_lib_slice_2_apk.apk!/lib/x86, /data/app/app/split_lib_slice_3_apk.apk!/lib/x86, /data/app/app/split_lib_slice_4_apk.apk!/lib/x86, /data/app/app/split_lib_slice_5_apk.apk!/lib/x86, /data/app/app/split_lib_slice_6_apk.apk!/lib/x86, /data/app/app/split_lib_slice_7_apk.apk!/lib/x86, /data/app/app/split_lib_slice_8_apk.apk!/lib/x86, /data/app/app/split_lib_slice_9_apk.apk!/lib/x86, /system/lib, /vendor/lib]]
                                                                          at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                                          at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
                                                                          at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
                                                                          at libcore.reflect.InternalNames.getClass(InternalNames.java:53)
```

**Comment by GitHubMurt** [comment]
Ok issue is realted with
https://github.com/FasterXML/jackson-databind/issues/1070

**Comment by JakeWharton** [comment]
Not a problem with Retrofit so closing.
