### ISSUE TITLE
IllegalArgumentException: class c.h$b declares multiple JSON fields named a

### ISSUE THREAD

**Issue by user849651** [square/retrofit#2443]
I'm using Retrofit and Realm for my Android app.

My app has a user login feature that lets the user log in to their account.

However, when I run my app (release build) and try to log into my account, it crashes and gives me this error:

```
java.lang.IllegalArgumentException: class c.h$b declares multiple JSON fields named a
    at com.google.a.b.a.i.a(Unknown Source)
    at com.google.a.b.a.i.a(Unknown Source)
    at com.google.a.f.a(Unknown Source)
    at com.google.a.b.a.m.a(Unknown Source)
    at com.google.a.b.a.i$1.a(Unknown Source)
    at com.google.a.b.a.i$a.a(Unknown Source)
    at com.google.a.b.a.m.a(Unknown Source)
    at com.google.a.b.a.i$1.a(Unknown Source)
    at com.google.a.b.a.i$a.a(Unknown Source)
    at com.google.a.f.a(Unknown Source)
    at com.google.a.f.a(Unknown Source)
    at com.google.a.f.a(Unknown Source)
    at com.google.a.f.a(Unknown Source)
    at com.example.android.api.d.a$1.a(Unknown Source)
    at c.g$a$1$1.run(Unknown Source)
    at android.os.Handler.handleCallback(Handler.java:751)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:154)
    at android.app.ActivityThread.main(ActivityThread.java:6682)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)
```

I believe this has something to do with ProGuard, but I'm not certain.

I have far too many POJO classes to post them all here, but here are a few:

**Post.java**:
```
@Parcel(implementations = { PostRealmProxy.class },
        value = Parcel.Serialization.BEAN,
        analyze = { Post.class })
public class Post extends RealmObject implements Serializable {

    @PrimaryKey
    @SerializedName("id")
    @Expose
    private Integer id;

    @SerializedName("user_id")
    @Expose
    private Integer userId;

    @SerializedName("message")
    @Expose
    private String message;

    @SerializedName("created_at")
    @Expose
    private String createdAt;

    @SerializedName("updated_at")
    @Expose
    private String updatedAt;

    @SerializedName("images")
    @Expose
    private RealmList<PostImage> images = null;

    @SerializedName("user")
    @Expose
    private User user;

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getUserId() {
        return userId;
    }

    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    public String getMessage() {
        return message;
    }

    public void setMessage(String message) {
        this.message = message;
    }

    public String getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(String createdAt) {
        this.createdAt = createdAt;
    }

    public String getUpdatedAt() {
        return updatedAt;
    }

    public void setUpdatedAt(String updatedAt) {
        this.updatedAt = updatedAt;
    }

    public RealmList<PostImage> getImages() {
        return images;
    }

    @ParcelPropertyConverter(PostImageListParcelConverter.class)
    public void setImages(RealmList<PostImage> images) {
        this.images = images;
    }

    public User getUser() {
        return user;
    }

    public void setUser(User user) {
        this.user = user;
    }

}
```

**PostImage.java**:
```
@Parcel(implementations = { PostImageRealmProxy.class },
        value = Parcel.Serialization.BEAN,
        analyze = { PostImage.class })
public class PostImage extends RealmObject implements Serializable {

    @PrimaryKey
    @SerializedName("id")
    @Expose
    private Integer id;

    @SerializedName("post_id")
    @Expose
    private Integer postId;

    @SerializedName("file_name")
    @Expose
    private String fileName;

    @SerializedName("created_at")
    @Expose
    private String createdAt;

    @SerializedName("updated_at")
    @Expose
    private String updatedAt;

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getPostId() {
        return postId;
    }

    public void setPostId(Integer postId) {
        this.postId = postId;
    }

    public String getFileName() {
        return fileName;
    }

    public void setFileName(String fileName) {
        this.fileName = fileName;
    }

    public String getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(String createdAt) {
        this.createdAt = createdAt;
    }

    public String getUpdatedAt() {
        return updatedAt;
    }

    public void setUpdatedAt(String updatedAt) {
        this.updatedAt = updatedAt;
    }

}
```

**User.java**:
```
public class User extends RealmObject implements Serializable {

    @PrimaryKey
    @SerializedName("id")
    @Expose
    private Integer id;

    @SerializedName("username")
    @Expose
    private String username;

    @SerializedName("created_at")
    @Expose
    private String createdAt;

    @SerializedName("updated_at")
    @Expose
    private String updatedAt;

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(String createdAt) {
        this.createdAt = createdAt;
    }

    public String getUpdatedAt() {
        return updatedAt;
    }

    public void setUpdatedAt(String updatedAt) {
        this.updatedAt = updatedAt;
    }

}
```

And here is my `proguard-rules.pro` file:

```
-keep class com.example.android.model.** { *; }

-dontwarn okio.**
-dontwarn javax.annotation.**

# Platform calls Class.forName on types which do not exist on Android to determine platform.
-dontnote retrofit2.Platform
# Platform used when running on Java 8 VMs. Will not be used at runtime.
-dontwarn retrofit2.Platform$Java8
# Retain generic type information for use by reflection by converters and adapters.
-keepattributes Signature
# Retain declared checked exceptions for use by a Proxy instance.
-keepattributes Exceptions

-keepclasseswithmembers class * {
    @retrofit2.http.* <methods>;
}

-keepclassmembers enum * { *; }

-keep public class * implements com.bumptech.glide.module.GlideModule
-keep public class * extends com.bumptech.glide.AppGlideModule
-keep public enum com.bumptech.glide.load.resource.bitmap.ImageHeaderParser$** {
  **[] $VALUES;
  public *;
}

# Parceler library
-keep interface org.parceler.Parcel
-keep @org.parceler.Parcel class * { *; }
-keep class **$$Parcelable { *; }
```

What could the problem be?

**Comment by JakeWharton** [comment]
ProGuard is renaming the field in your class hierarchy to use the same letter. Since Gson relies on reflection on field names, you need to prevent it from renaming them or your JSON will have meaningless keys.

This isn't a Retrofit problem, but an interaction between ProGuard and Gson so if you have question StackOverflow is likely your best bet.

**Comment by user849651** [comment]
The problem did turn out to be Retrofit & ProGuard related.

Adding the following line to my ProGuard file stopped the error:

```
-keep class retrofit2.** { *; }
```

**Comment by JakeWharton** [comment]
If you're going to do that you might as well just disable ProGuard and save
yourself some headache.

**Comment by ralphgabrielle** [comment]
any official fix for this ? only occurs on release build.
