### ISSUE TITLE
Cannot use retrofit in background service

### ISSUE THREAD

**Issue by Sketusky** [square/retrofit#2459]
When I try to use Retrofit in background service (after activity killed and service restarted) it gives me an error

> E/AndroidRuntime: FATAL EXCEPTION: Thread-23016
                                                                Process: com.sketusky.iot, PID: 9337
                                                                java.lang.UnsatisfiedLinkError: No implementation found for long com.android.tools.profiler.support.network.HttpTracker$Connection.nextId() (tried Java_com_android_tools_profiler_support_network_HttpTracker_00024Connection_nextId and Java_com_android_tools_profiler_support_network_HttpTracker_00024Connection_nextId__)
                                                                    at com.android.tools.profiler.support.network.HttpTracker$Connection.nextId(Native Method)
                                                                    at com.android.tools.profiler.support.network.HttpTracker$Connection.<init>(HttpTracker.java:191)
                                                                    at com.android.tools.profiler.support.network.HttpTracker$Connection.<init>(HttpTracker.java:186)
                                                                    at com.android.tools.profiler.support.network.HttpTracker.trackConnection(HttpTracker.java:280)
                                                                    at com.android.tools.profiler.support.network.okhttp.OkHttp3Interceptor.track(OkHttp3Interceptor.java:78)
                                                                    at com.android.tools.profiler.support.network.okhttp.OkHttp3Interceptor.invoke(OkHttp3Interceptor.java:55)
                                                                    at java.lang.reflect.Proxy.invoke(Proxy.java:393)
                                                                    at $Proxy0.intercept(Unknown Source)
                                                                    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
                                                                    at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)
                                                                    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
                                                                    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
                                                                    at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
                                                                    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
                                                                    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
                                                                    at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
                                                                    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
                                                                    at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:120)
                                                                    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
                                                                    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
                                                                    at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:185)
                                                                    at okhttp3.RealCall.execute(RealCall.java:69)
                                                                    at retrofit2.OkHttpCall.execute(OkHttpCall.java:180)
                                                                    at retrofit2.ExecutorCallAdapterFactory$ExecutorCallbackCall.execute(ExecutorCallAdapterFactory.java:91)

**Comment by JakeWharton** [comment]
The stack trace indicates a problem with Android Studio's network profiler. Report to b.android.com

**Comment by Laubeee** [comment]
Is there a solution to this? I get this error but only in specific cases, not sure (yet) how exactly to reproduce it

**Comment by sekanbas** [comment]
> The error got resolved when I disabled "Advance Profiling Option" on Android studio -> RUN -> Edit Configuration -> Profiling

[https://stackoverflow.com/a/49875421](https://stackoverflow.com/a/49875421)
