### ISSUE TITLE
Override requestBodyConverter in GsonConverterFactory 

### ISSUE THREAD

**Issue by hmedat2008** [square/retrofit#2497]
I'm using GsonConverterFactory to parse the API Response, but in some case the API return invalid JSON, maybe the Json corrupted  or the response doesn't match what we handle in the app side. 

This is the stack trace for my issue, 
`Non-fatal Exception: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 1 path $
       at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1567)
       at com.google.gson.stream.JsonReader.checkLenient(JsonReader.java:1416)
       at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:597)
       at com.google.gson.stream.JsonReader.peek(JsonReader.java:429)
       at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:201)
       at retrofit2.converter.gson.GsonResponseBodyConverter.convert(GsonResponseBodyConverter.java:37)
       at retrofit2.converter.gson.GsonResponseBodyConverter.convert(GsonResponseBodyConverter.java:25)
       at retrofit2.ServiceMethod.toResponse(ServiceMethod.java:116)
       at retrofit2.OkHttpCall.parseResponse(OkHttpCall.java:211)
       at retrofit2.OkHttpCall$1.onResponse(OkHttpCall.java:106)
       at okhttp3.RealCall$AsyncCall.execute(RealCall.java:126)
       at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:841)`

So what i need to override the requestBodyConverter in GsonConverterFactory to catch this crash and send it via fabric, to told our server guys what is the issue. 

Or tell me  if you have a better solution.

**Comment by NightlyNexus** [comment]
maybe something like this? could also be in a call adapter for more features.
```java
final class LoggingResponseConverterFactory extends Converter.Factory {
  @Override public Converter<ResponseBody, ?> responseBodyConverter(
    Type type, Annotation[] annotations, Retrofit retrofit) {
    final Converter<ResponseBody, ?> converter =
        retrofit.nextResponseBodyConverter(this, type, annotations);
    return new Converter<ResponseBody, Object>() {
      @Override public Object convert(ResponseBody responseBody) throws IOException {
        try {
          return converter.convert(responseBody);
        } catch (MalformedJsonException | RuntimeException e) {
          // do some logging.
          throw e;
        }
      }
    };
  }
}
```

**Comment by JakeWharton** [comment]
A delegated Retrofit converter or delegating Gson type adapter is the best approach here. There are samples of each in the respective repos. For more information please ask on StackOverflow.
