### ISSUE TITLE
使用Retrofit请求数据，报错：java.lang.NoClassDefFoundError: d.h.c; 改使用Volley请求，没有报错了。

### ISSUE THREAD

**Issue by jamin918** [square/retrofit#2501]
Error Log: 
AndroidRuntime: FATAL EXCEPTION: main
                                                                   Process: com.epuxun.ewater, PID: 12147
                                                                   java.lang.NoClassDefFoundError: d.h.c
                                                                       at d.bm.a(Observable.java:79)
                                                                       at c.a.a.i.a(RxJavaCallAdapter.java:64)
                                                                       at c.x.invoke(Retrofit.java:149)
                                                                       at $Proxy1.d(Native Method)
                                                                       at com.epuxun.ewater.activity.ACT_Main4Child.c(ACT_Main4Child.java:257)
                                                                       at com.epuxun.ewater.activity.ACT_Main4Child.onResume(ACT_Main4Child.java:432)
                                                                       at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1206)
                                                                       at cn.jiguang.a.a.c.a.a.d.callActivityOnResume(Unknown Source)
                                                                       at android.app.Activity.performResume(Activity.java:5345)
                                                                       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2820)
                                                                       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:2859)
                                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2284)
                                                                       at android.app.ActivityThread.access$800(ActivityThread.java:142)
                                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1213)
                                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                       at android.os.Looper.loop(Looper.java:136)
                                                                       at android.app.ActivityThread.main(ActivityThread.java:5241)
                                                                       at java.lang.reflect.Method.invokeNative(Native Method)
                                                                       at java.lang.reflect.Method.invoke(Method.java:515)
                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:818)
                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:634)
                                                                       at dalvik.system.NativeStart.main(Native Method)

phone info ：
 Coolpad 8297-W01
Android 4.4.4

Retrofit vesion:
com.squareup.retrofit2:retrofit:2.3.0
com.squareup.retrofit2:adapter-rxjava:2.3.0
io.reactivex:rxandroid:1.2.1
io.reactivex:rxjava:1.1.9

**Comment by jamin918** [comment]
at com.epuxun.ewater.activity.ACT_Main4Child.c(ACT_Main4Child.java:257)
at com.epuxun.ewater.activity.ACT_Main4Child.onResume(ACT_Main4Child.java:432)
定位代码如下：
/**
     * 获取已绑定宝宝信息
     */
    private void getBindBabyInfo() {
        final Dialog dialog = DialogUtils.createRefreshDialog(this, "正在获取数据...");

        RetrofitManager.getInstance().getService()
                .findBabyMainInfo(new RequestParams().add("systemType", "android"))
                .compose(new BaseSchedulerTransformer<JsonResultBean<HomeVo>>())
                .subscribe(new BaseSubscriber<>(new RequestCallback<JsonResultBean<HomeVo>>() {
                    @Override
                    public void beforeRequest() {
                        dialog.show();
                    }

                    @Override
                    public void requestError(String msg) {
                        dialog.dismiss();
                        showToastShort(msg);
                    }

                    @Override
                    public void requestComplete() {
                        dialog.dismiss();
                    }

                    @Override
                    public void requestSuccess(JsonResultBean<HomeVo> data) {
                        updateUi(data);
                    }
                }));
    }
属于正常使用retroifit请求数据，在Android 5.0以上的测试机上没有报错。

**Comment by youngonlyforyou** [comment]
你说汉语，人家能看懂嘛？😄哈哈

**Comment by JakeWharton** [comment]
It's not clear what `d.h.c` is or why you think it's a Retrofit bug. It sounds like misconfigured ProGuard. If you believe it's a Retrofit bug, we need a failing test case or standalone executable sample that reproduces the behavior to identify the cause.
