### ISSUE TITLE
Cast of OutOfMemoryError to RuntimeException

### ISSUE THREAD

**Issue by yschimke** [square/retrofit#2507]
https://github.com/square/okhttp/issues/3637

```
Fatal Exception: java.lang.ClassCastException: java.lang.OutOfMemoryError cannot be cast to java.lang.RuntimeException
       at retrofit2.OkHttpCall.request(OkHttpCall.java:63)
       at retrofit2.ExecutorCallAdapterFactory$ExecutorCallbackCall.request(ExecutorCallAdapterFactory.java:108)
       at com.abelkit.android.api.AbelCallback.onFailure(AbelCallback.java:47)
       at retrofit2.ExecutorCallAdapterFactory$ExecutorCallbackCall$1$2.run(ExecutorCallAdapterFactory.java:79)
       at android.os.Handler.handleCallback(Handler.java:751)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6321)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
```

**Comment by NightlyNexus** [comment]
looks like Errors can sneak in here: https://github.com/square/retrofit/blob/af406dd527830832c5825db80a3a6071821aac9f/retrofit/src/main/java/retrofit2/OkHttpCall.java#L93

**Comment by JakeWharton** [comment]
It's really weird to deliver an OOM to a callback.

**Comment by JakeWharton** [comment]
Ah, ok it isn't. We should be allowing VM errors to bubble up.
