### ISSUE TITLE
Retrofit2 on EJB Project

### ISSUE THREAD

**Issue by aristofanio** [square/retrofit#2508]
Where @PersistenceContext (javax.persistence.PersistenceContext) is present in project with Retrofit2 an fail occurs on compilation time.

```
Caused by: java.lang.RuntimeException: com.sun.tools.javac.code.Symbol$CompletionFailure: class file for android.os.Handler not found
        at org.eclipse.persistence.internal.jpa.modelgen.CanonicalModelProcessor.process(CanonicalModelProcessor.java:407)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:794)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:705)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment.access$1800(JavacProcessingEnvironment.java:91)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1035)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1176)
        at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1170)
        at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:856)
        at com.sun.tools.javac.main.Main.compile(Main.java:523)
        ... 28 more
Caused by: com.sun.tools.javac.code.Symbol$CompletionFailure: class file for android.os.Handler not found
```

**This is an BUG or it is an limitation?**

Dependences in use:
> retrofit2:retrofit:2.3.0:retrofit-2.3.0.jar
>org.eclipse.persistence:org.eclipse.persistence.jpa.modelgen.processor:2.5.2:org.eclipse.persistence.jpa.modelgen.processor-2.5.2.jar

**Comment by JakeWharton** [comment]
That's a bug in whatever provides `org.eclipse.persistence.internal.jpa.modelgen.CanonicalModelProcessor`, presumably EJB. Their annotation processor is crashing on a class reference which isn't present on your classpath. This is perfectly fine at runtime, Retrofit uses this as an indication as to whether it's running on Android or the JVM. You should report the bug to EJB.
