### ISSUE TITLE
gzip finished without exhausting source

### ISSUE THREAD

**Issue by uburoiubu** [square/retrofit#2513]
Declaration inside API interface:

```
@POST("MobileServer/IMobileTelematicsNav/GetZoneList")
    Single<Response<ResponseBody>> getZoneList(@Header("Cookie") String cookies, @Body JsonObject body);
```

And the method:

```
private void getZoneListFromApi(JsonObject jsonObjectBodyZoneList) {
        Disposable d = Api.getApi().getZoneList(cookies, jsonObjectBodyZoneList)
                .subscribeOn(Schedulers.io())
                .observeOn(Schedulers.io())
                .subscribe(new Consumer<Response<ResponseBody>>() {
                    @Override
                    public void accept(@NonNull Response<ResponseBody> response) throws Exception {

                        try {
                            if (response.body() != null) {
                                String str = response.body().string();

                                if (Utils.isJSONValid(str)) {
                                    Gson gson = Utils.createGsonWithTypeString();
                                    Type type = new TypeToken<List<ZoneObj>>() {
                                    }.getType();
                                    final ArrayList<ZoneObj> zoneListObjs = gson.fromJson(str, type);

                                    Realm realm = Realm.getDefaultInstance();
                                    realm.executeTransaction(new Realm.Transaction() {
                                        @Override
                                        public void execute(Realm realm) {
                                            realm.copyToRealmOrUpdate(zoneListObjs);
                                        }
                                    });

                                    realm.close();
                                }
                            }
                        } catch (IOException e) {
                            Log.e("Response received error", "");
                            e.printStackTrace();
                        }

                    }
                }, new Consumer<Throwable>() {
                    @Override
                    public void accept(@NonNull Throwable e) throws Exception {
                        Log.e("ZoneListFromApi Error: ", e.getMessage());
                        e.printStackTrace();
                    }
                });

        compositeDisposable.add(d);
    }
```

**Logcat message:**

```
0-06 16:09:15.668 22665-23355/work.phobos.flagman E/ZoneListFromApi Error:: gzip finished without exhausting source
10-06 16:09:15.669 22665-23355/work.phobos.flagman W/System.err: java.io.IOException: gzip finished without exhausting source
10-06 16:09:15.670 22665-23355/work.phobos.flagman W/System.err:     at okio.GzipSource.read(GzipSource.java:100)
10-06 16:09:15.670 22665-22876/work.phobos.flagman I/[MALI][Gralloc]: [-]r_hnd(0x7f6fce02a0), client(52), share_fd(59)
10-06 16:09:15.670 22665-23355/work.phobos.flagman W/System.err:     at okio.RealBufferedSource.read(RealBufferedSource.java:46)
10-06 16:09:15.671 22665-23355/work.phobos.flagman W/System.err:     at okio.ForwardingSource.read(ForwardingSource.java:35)
10-06 16:09:15.671 22665-23355/work.phobos.flagman W/System.err:     at retrofit2.OkHttpCall$ExceptionCatchingRequestBody$1.read(OkHttpCall.java:291)
10-06 16:09:15.671 22665-23355/work.phobos.flagman W/System.err:     at okio.RealBufferedSource.readAll(RealBufferedSource.java:163)
10-06 16:09:15.671 22665-23355/work.phobos.flagman W/System.err:     at retrofit2.Utils.buffer(Utils.java:304)
10-06 16:09:15.671 22665-23355/work.phobos.flagman W/System.err:     at retrofit2.BuiltInConverters$BufferingResponseBodyConverter.convert(BuiltInConverters.java:82)
10-06 16:09:15.671 22665-23355/work.phobos.flagman W/System.err:     at retrofit2.BuiltInConverters$BufferingResponseBodyConverter.convert(BuiltInConverters.java:75)
10-06 16:09:15.671 22665-23355/work.phobos.flagman W/System.err:     at retrofit2.ServiceMethod.toResponse(ServiceMethod.java:119)
10-06 16:09:15.671 22665-23355/work.phobos.flagman W/System.err:     at retrofit2.OkHttpCall.parseResponse(OkHttpCall.java:218)
10-06 16:09:15.671 22665-23355/work.phobos.flagman W/System.err:     at retrofit2.OkHttpCall.execute(OkHttpCall.java:180)
10-06 16:09:15.671 22665-23355/work.phobos.flagman W/System.err:     at retrofit2.adapter.rxjava2.CallExecuteObservable.subscribeActual(CallExecuteObservable.java:41)
10-06 16:09:15.671 22665-23355/work.phobos.flagman W/System.err:     at io.reactivex.Observable.subscribe(Observable.java:10842)
10-06 16:09:15.671 22665-23355/work.phobos.flagman W/System.err:     at io.reactivex.internal.operators.observable.ObservableSingleSingle.subscribeActual(ObservableSingleSingle.java:35)
10-06 16:09:15.671 22665-23355/work.phobos.flagman W/System.err:     at io.reactivex.Single.subscribe(Single.java:2703)
10-06 16:09:15.671 22665-23355/work.phobos.flagman W/System.err:     at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
10-06 16:09:15.671 22665-23355/work.phobos.flagman W/System.err:     at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:452)
10-06 16:09:15.671 22665-23355/work.phobos.flagman W/System.err:     at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:61)
10-06 16:09:15.671 22665-23355/work.phobos.flagman W/System.err:     at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:52)
10-06 16:09:15.671 22665-22876/work.phobos.flagman I/[MALI][Gralloc]: [-]r_hnd(0x7f6fce0480), client(52), share_fd(62)
10-06 16:09:15.671 22665-23355/work.phobos.flagman W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
10-06 16:09:15.671 22665-23355/work.phobos.flagman W/System.err:     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:269)
10-06 16:09:15.671 22665-23355/work.phobos.flagman W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
10-06 16:09:15.672 22665-23355/work.phobos.flagman W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
10-06 16:09:15.672 22665-23355/work.phobos.flagman W/System.err:     at java.lang.Thread.run(Thread.java:818)
```

Some screens from Charles:

This is how compressed response starts:

![screen shot 2017-10-06 at 16 18 27](https://user-images.githubusercontent.com/21975311/31279523-018fc766-aab2-11e7-8839-aaebc6121688.png)

And this is how it ends:

![screen shot 2017-10-06 at 16 17 45](https://user-images.githubusercontent.com/21975311/31279486-ed40d656-aab1-11e7-806d-44593021970c.png)

**P.S. If I use Postman, I don't have any issues.**

**Comment by swankjesse** [comment]
Why are there `00` bytes at the end of this message? Something is writing an overlong response.
