### ISSUE TITLE
@Path annotation throw null pointer

### ISSUE THREAD

**Issue by hussainahmad** [square/retrofit#2554]
```@FormUrlEncoded
    @POST("{url}")
    Observable<MyClass> getCategories(
            @Path(value = "url", encoded = true) String url,
            @Field("param") String param
    );
and  
String url = Url.HOME_URL;
        mSubscription = ApiService.getApi().getCategoriesAndHome(url,cateId)
......
```
through java.lang.IllegalArgumentException: Path parameter "url" value must not be null.
but when I call  this method in this way 
```mSubscription = ApiService.getDevApi().getCategoriesAndHome("/api/home.php",cateId)```
it run fine , give no error

**Comment by hussainahmad** [comment]
Logcat
```11-13 21:11:45.256 8415-8415/com.myCompany.MyProject W/System.err: java.lang.IllegalArgumentException: Path parameter "url" value must not be null.
11-13 21:11:45.256 8415-8415/com.myCompany.MyProject W/System.err:     at retrofit2.ParameterHandler$Path.apply(ParameterHandler.java:103)
11-13 21:11:45.256 8415-8415/com.myCompany.MyProject W/System.err:     at retrofit2.ServiceMethod.toRequest(ServiceMethod.java:108)
11-13 21:11:45.257 8415-8415/com.myCompany.MyProject W/System.err:     at retrofit2.OkHttpCall.createRawCall(OkHttpCall.java:178)
11-13 21:11:45.257 8415-8415/com.myCompany.MyProject W/System.err:     at retrofit2.OkHttpCall.execute(OkHttpCall.java:162)
11-13 21:11:45.257 8415-8415/com.myCompany.MyProject W/System.err:     at retrofit2.adapter.rxjava.RxJavaCallAdapterFactory$CallOnSubscribe.call(RxJavaCallAdapterFactory.java:144)
11-13 21:11:45.257 8415-8415/com.myCompany.MyProject W/System.err:     at retrofit2.adapter.rxjava.RxJavaCallAdapterFactory$CallOnSubscribe.call(RxJavaCallAdapterFactory.java:125)
11-13 21:11:45.257 8415-8415/com.myCompany.MyProject W/System.err:     at rx.Observable$2.call(Observable.java:162)
11-13 21:11:45.257 8415-8415/com.myCompany.MyProject W/System.err:     at rx.Observable$2.call(Observable.java:154)
11-13 21:11:45.257 8415-8415/com.myCompany.MyProject W/System.err:     at rx.Observable$2.call(Observable.java:162)
11-13 21:11:45.257 8415-8415/com.myCompany.MyProject W/System.err:     at rx.Observable$2.call(Observable.java:154)
11-13 21:11:45.257 8415-8415/com.myCompany.MyProject W/System.err:     at rx.Observable$2.call(Observable.java:162)
11-13 21:11:45.257 8415-8415/com.myCompany.MyProject W/System.err:     at rx.Observable$2.call(Observable.java:154)
11-13 21:11:45.257 8415-8415/com.myCompany.MyProject W/System.err:     at rx.Observable.unsafeSubscribe(Observable.java:8314)
11-13 21:11:45.257 8415-8415/com.myCompany.MyProject W/System.err:     at rx.internal.operators.OperatorSubscribeOn$1.call(OperatorSubscribeOn.java:94)
11-13 21:11:45.257 8415-8415/com.myCompany.MyProject W/System.err:     at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
11-13 21:11:45.257 8415-8415/com.myCompany.MyProject W/System.err:     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
11-13 21:11:45.257 8415-8415/com.myCompany.MyProject W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
11-13 21:11:45.257 8415-8415/com.myCompany.MyProject W/System.err:     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272)
11-13 21:11:45.257 8415-8415/com.myCompany.MyProject W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
11-13 21:11:45.257 8415-8415/com.myCompany.MyProject W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
11-13 21:11:45.257 8415-8415/com.myCompany.MyProject W/System.err:     at java.lang.Thread.run(Thread.java:762)

**Comment by JakeWharton** [comment]
The exception tells you the problem. You are passing `null` to the `url` argument and that is not allowed. Did you mean to use the `@Url` annotation on the first param?

**Comment by hussainahmad** [comment]
but ```String url = Url.HOME_URL;``` it has value , showing in `logcat` , I only want to replace path with `/api/home.php`

**Comment by JakeWharton** [comment]
You haven't shown any evidence that it has a value, and when you replace it with a hard-coded string it works. This pretty clearly indicates that the variable is actually `null` at the time of the method call.

**Comment by hussainahmad** [comment]
Sorry @JakeWharton It's my mistake , how I am stupid
