### ISSUE TITLE
baseUrl == null

### ISSUE THREAD

**Issue by emilany** [square/retrofit#2579]
Any clue for this error?

```
java.lang.RuntimeException: Unable to start service com.app.indoor.main.CheckNotificationService@5f72c7e with null: java.lang.NullPointerException: baseUrl == null
at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3230)
at android.app.ActivityThread.-wrap17(ActivityThread.java)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1590)
at android.os.Handler.dispatchMessage(Handler.java:111)
at android.os.Looper.loop(Looper.java:207)
at android.app.ActivityThread.main(ActivityThread.java:5742)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)
Caused by: java.lang.NullPointerException: baseUrl == null
at retrofit2.Utils.checkNotNull(Utils.java:285)
at retrofit2.Retrofit$Builder.baseUrl(Retrofit.java:434)
at com.app.indoor.api.RetrofitManager.getRetrofit(RetrofitManager.java:59)
at com.app.indoor.api.RetrofitManager.getApiInterface(RetrofitManager.java:143)
at com.app.indoor.main.CheckNotificationService.loadNotifications(CheckNotificationService.java:55)
at com.app.indoor.main.CheckNotificationService.access$200(CheckNotificationService.java:23)
at com.app.indoor.main.CheckNotificationService$QueryNotification.run(CheckNotificationService.java:85)
at com.app.indoor.main.CheckNotificationService.onStartCommand(CheckNotificationService.java:36)
at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3213)
... 8 more
java.lang.NullPointerException: baseUrl == null
at retrofit2.Utils.checkNotNull(Utils.java:285)
at retrofit2.Retrofit$Builder.baseUrl(Retrofit.java:434)
at com.app.indoor.api.RetrofitManager.getRetrofit(RetrofitManager.java:59)
at com.app.indoor.api.RetrofitManager.getApiInterface(RetrofitManager.java:143)
at com.app.indoor.main.CheckNotificationService.loadNotifications(CheckNotificationService.java:55)
at com.app.indoor.main.CheckNotificationService.access$200(CheckNotificationService.java:23)
at com.app.indoor.main.CheckNotificationService$QueryNotification.run(CheckNotificationService.java:85)
at com.app.indoor.main.CheckNotificationService.onStartCommand(CheckNotificationService.java:36)
at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3213)
at android.app.ActivityThread.-wrap17(ActivityThread.java)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1590)
at android.os.Handler.dispatchMessage(Handler.java:111)
at android.os.Looper.loop(Looper.java:207)
at android.app.ActivityThread.main(ActivityThread.java:5742)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)
```

**Comment by oldergod** [comment]
You need to set a URL when building your retrofit instance, as shown in the [documentation](http://square.github.io/retrofit/). If you are already setting it, make sure it is not `null`.

```java
Retrofit retrofit = new Retrofit.Builder()
  .baseUrl("https://api.github.com/")
  .build();
```
