### ISSUE TITLE
StringIndexOutOfBoundsException on multiple devices

### ISSUE THREAD

**Issue by vandac** [square/retrofit#2583]
Hello, after upgrading to retrofit2, we have started seeing the following issue:

```
Caused by java.lang.StringIndexOutOfBoundsException: String index out of range: 6684777
       at java.lang.String.codePointAt(String.java:602)
       at java.util.WeakHashMap.transfer(WeakHashMap.java:499)
       at java.util.WeakHashMap.resize(WeakHashMap.java:475)
       at java.util.WeakHashMap.put(WeakHashMap.java:448)
       at java.util.Collections$SynchronizedMap.put(Collections.java:2318)
       at java.lang.reflect.Proxy.getProxyClass0(Proxy.java:573)
       at java.lang.reflect.Proxy.newProxyInstance(Proxy.java:741)
       at libcore.reflect.AnnotationFactory.createAnnotation(AnnotationFactory.java:95)
       at java.lang.reflect.Method.getParameterAnnotationsNative(Method.java)
       at java.lang.reflect.Method.getParameterAnnotations(Method.java:594)
       at retrofit2.ServiceMethod$Builder.(ServiceMethod.java)
       at retrofit2.Retrofit.loadServiceMethod(Retrofit.java:170)
       at retrofit2.Retrofit$1.invoke(Retrofit.java:147)
       at java.lang.reflect.Proxy.invoke(Proxy.java:813)
       at $Proxy2.a(Unknown Source)
```

This happens to many of our users running Android 7.0 or 7.1, 
when a POST method is called which we pass a @Body parameter.
`    @POST(URL_PATH)
    Observable<MyModelClass> send(@Body BodyType body);`

We cannot reproduce this issue ourselves but since many of our users are affected, I'd like to ask if there are any recommendations of what could go wrong. We currently use retrofit version 2.3.0.

**Comment by JakeWharton** [comment]
Are there specific OEMs that this crash occurs on? This isn't a problem with Retrofit, the crash is occurring deep inside the Android runtime. The stacktrace itself makes no sense, as `WeakHashMap` should _never_ be calling `codePointAt` on a `String`. The best you can do is probably to file a bug on http://b.android.com/new, although if it's not occurring on 8.0 then it's likely already fixed.

**Comment by vandac** [comment]
Our userbase is mostly on Samsung Galaxy devices, which do not have Android 8 yet, but the issue is occurring on multiple device models running Android 7 and 7.1 and started on a particular date on various versions of our app.
Thanks for a quick response, will report it to the Android team. 
Is there anything in particular we should report on using Retrofit library?

**Comment by JakeWharton** [comment]
The stacktrace is pretty indicative of the problem. It looks like a problem
with their implementation of reflection which is causing the crash to
happen. I'm not sure if it's in regular Android or in a version of it
customized by some OEM.
