### ISSUE TITLE
use retrofit print log is  sending message to a Handler on a dead thread

### ISSUE THREAD

**Issue by 616226821** [square/retrofit#2585]
MessageQueue: Handler (android.os.Handler) {77a61e8} sending message to a Handler on a dead thread
                                               java.lang.IllegalStateException: Handler (android.os.Handler) {77a61e8} sending message to a Handler on a dead thread
                                                   at android.os.MessageQueue.enqueueMessage(MessageQueue.java:616)
                                                   at android.os.Handler.enqueueMessage(Handler.java:653)
                                                   at android.os.Handler.sendMessageAtTime(Handler.java:622)
                                                   at android.os.Handler.sendMessageDelayed(Handler.java:592)
                                                   at android.os.Handler.post(Handler.java:345)
                                                   at android.os.ResultReceiver$MyResultReceiver.send(ResultReceiver.java:57)
                                                   at com.android.internal.os.IResultReceiver$Stub.onTransact(IResultReceiver.java:58)
                                                   at android.os.Binder.execTransact(Binder.java:565)

**Comment by JakeWharton** [comment]
Retrofit doesn't log anything so it's not clear why you thinking Retrofit is to blame or what the problem is. If you have an executable sample that demonstrates the problem we can take a look, but otherwise there's no information here to discern any problem.
