### ISSUE TITLE
HTTP entity may not be null

### ISSUE THREAD

**Issue by askarali** [square/retrofit#2595]
Fail to sendHttpRequest
                                              java.lang.IllegalArgumentException: HTTP entity may not be null
                                                  at org.apache.http.util.EntityUtils.toString(EntityUtils.java:115)
                                                  at org.apache.http.util.EntityUtils.toString(EntityUtils.java:151)
                                                  at miui.util.ErrorReport.c(SourceFile:396)
                                                  at miui.util.ErrorReport.sendReportRequest(SourceFile:353)
                                                  at miui.util.ErrorReport$1.a(SourceFile:369)
                                                  at miui.util.ErrorReport$1.doInBackground(SourceFile:366)
                                                  at android.os.AsyncTask$2.call(AsyncTask.java:295)
                                                  at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                  at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
                                                  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                  at java.lang.Thread.run(Thread.java:818)

**Comment by JakeWharton** [comment]
This stack trace is not from Retrofit but Apache HTTP client.

**Comment by askarali** [comment]
No when i use retrofit static instance only the application crashing .. I have posted a question here.
Kindly read it
https://stackoverflow.com/questions/47975464/android-crashing-with-retrofit-static-instance
