### ISSUE TITLE
Random "Non-body HTTP method cannot contain @Body" Retrofit 2.3.0

### ISSUE THREAD

**Issue by tomkoptel** [square/retrofit#2598]
Hello,

For some unknown reason, I am receiving in production application a crash that points the following [line of code](https://github.com/square/retrofit/blob/522592bb11fc8aa1ee491c3e7a1fe55675c372cd/retrofit/src/main/java/retrofit2/ServiceMethod.java#L211). The tough part is that I can not reproduce it with unit test.

I am using `Retrofit 2.3.0` and `OkHttp 3.9.1`. The problem is that it should not crash in theory because the condition that triggers exception should not have been met.

```java
public interface DrmApi {
  @POST
  Call<ResponseBody> sendProvisionKeyRequest(@Url HttpUrl provisionUrl, @Body RequestBody requestBody);
}
```

```java
Caused by java.lang.IllegalArgumentException: Non-body HTTP method cannot contain @Body.
    for method DrmApi.sendProvisionKeyRequest
       at retrofit2.ServiceMethod$Builder.methodError(ServiceMethod.java:720)
       at retrofit2.ServiceMethod$Builder.methodError(ServiceMethod.java:711)
       at retrofit2.ServiceMethod$Builder.build(ServiceMethod.java:209)
       at retrofit2.Retrofit.loadServiceMethod(Retrofit.java:166)
       at retrofit2.Retrofit$1.invoke(Retrofit.java:145)
       at java.lang.reflect.Proxy.invoke(Proxy.java:913)
       at $Proxy5.sendProvisionKeyRequest(Unknown Source)
```

**Comment by swankjesse** [comment]
Executable test case?

**Comment by amiyo-biswas-mongia** [comment]
Facing same issue.
