### ISSUE TITLE
Random internal exceptions in ServiceMethod.Builder

### ISSUE THREAD

**Issue by vandus** [square/retrofit#2677]
Hello, we are seeing a bunch of random exceptions occurring on our customers' devices, though we cannot reproduce the issue internally.

I'd like to get advise if we are doing something wrong (maybe something missing in proguard?) or there is actually a bug in the lib. We use Dagger, RxJava2 and Retrofit2 and there is proxy set up on these devices.

`Caused by java.lang.ArrayStoreException: java.lang.ref.FinalizerReference cannot be stored in an array of type java.util.WeakHashMap$Entry[]
       at java.util.WeakHashMap.transfer(WeakHashMap.java:507)
       at java.util.WeakHashMap.resize(WeakHashMap.java:475)
       at java.util.WeakHashMap.put(WeakHashMap.java:448)
       at java.util.Collections$SynchronizedMap.put(Collections.java:2318)
       at java.lang.reflect.Proxy.getProxyClass0(Proxy.java:573)
       at java.lang.reflect.Proxy.newProxyInstance(Proxy.java:741)
       at libcore.reflect.AnnotationFactory.createAnnotation(AnnotationFactory.java:95)
       at java.lang.reflect.Method.getParameterAnnotationsNative(Method.java)
       at java.lang.reflect.Method.getParameterAnnotations(Method.java:594)
       at retrofit2.ServiceMethod$Builder.(ServiceMethod.java:158)
       at retrofit2.Retrofit.loadServiceMethod(Retrofit.java:170)
       at retrofit2.Retrofit$1.invoke(Retrofit.java:147)
       at java.lang.reflect.Proxy.invoke(Proxy.java:813)
       at $Proxy3.a(Unknown Source)`

`Caused by java.lang.ArrayStoreException: android.os.Parcel cannot be stored in an array of type java.util.WeakHashMap$Entry[]
       at java.util.WeakHashMap.transfer(WeakHashMap.java:507)
       at java.util.WeakHashMap.resize(WeakHashMap.java:475)
       at java.util.WeakHashMap.put(WeakHashMap.java:448)
       at java.util.Collections$SynchronizedMap.put(Collections.java:2318)
       at java.lang.reflect.Proxy.getProxyClass0(Proxy.java:573)
       at java.lang.reflect.Proxy.newProxyInstance(Proxy.java:741)
       at libcore.reflect.AnnotationFactory.createAnnotation(AnnotationFactory.java:95)
       at java.lang.reflect.Method.getParameterAnnotationsNative(Method.java)
       at java.lang.reflect.Method.getParameterAnnotations(Method.java:594)
       at retrofit2.ServiceMethod$Builder.(ServiceMethod.java:158)
       at retrofit2.Retrofit.loadServiceMethod(Retrofit.java:170)
       at retrofit2.Retrofit$1.invoke(Retrofit.java:147)
       at java.lang.reflect.Proxy.invoke(Proxy.java:813)
       at $Proxy2.a(Unknown Source)`

`Caused by java.lang.StringIndexOutOfBoundsException: String index out of range: 16
       at java.lang.String.codePointAt(String.java:602)
       at java.util.WeakHashMap.transfer(WeakHashMap.java:499)
       at java.util.WeakHashMap.resize(WeakHashMap.java:475)
       at java.util.WeakHashMap.put(WeakHashMap.java:448)
       at java.util.Collections$SynchronizedMap.put(Collections.java:2318)
       at java.lang.reflect.Proxy.getProxyClass0(Proxy.java:573)
       at java.lang.reflect.Proxy.newProxyInstance(Proxy.java:741)
       at libcore.reflect.AnnotationFactory.createAnnotation(AnnotationFactory.java:95)
       at java.lang.reflect.Method.getParameterAnnotationsNative(Method.java)
       at java.lang.reflect.Method.getParameterAnnotations(Method.java:594)
       at retrofit2.ServiceMethod$Builder.(ServiceMethod.java:158)
       at retrofit2.Retrofit.loadServiceMethod(Retrofit.java:170)
       at retrofit2.Retrofit$1.invoke(Retrofit.java:147)
       at java.lang.reflect.Proxy.invoke(Proxy.java:813)
       at $Proxy2.a(Unknown Source)`

All issues are only occurring on Android 7.0 and 7.1, on various Samsung Galaxy devices (that's our main device base). 

Thank you.

**Comment by JakeWharton** [comment]
These are all bugs in Android. Sounds like Samsung altered their VM poorly. I don't really see any action Retrofit can take. These exceptions don't occur in Retrofit code, but deep inside the Java APIs that it uses. Have you reported these to Samsung?

**Comment by vandus** [comment]
Thanks, I am going to, just wanted to make sure it's not the library.
