### ISSUE TITLE
JAXB converter throws java.lang.ClassNotFoundException for ContextFactory

### ISSUE THREAD

**Issue by FrostRocket** [square/retrofit#2707]
I'm using the new JAXB converter and dropping in my gradle dependencies like so:

`    implementation "com.squareup.retrofit2:retrofit:2.4.0"
    implementation 'com.squareup.retrofit2:converter-jaxb:2.4.0'
    implementation 'com.squareup.retrofit2:adapter-rxjava2:2.4.0'`

However, when I go to build my app, I'm getting the following stack. 
`[java.lang.ClassNotFoundException: Didn't find class "com.sun.xml.internal.bind.v2.ContextFactory" on path: DexPathList[[zip file "/data/app/com.package-1/base.apk"],nativeLibraryDirectories=[/data/app/com.frostrocket.windsock-1/lib/arm64, /system/lib64, /vendor/lib64]]]
                      at retrofit2.converter.jaxb.JaxbConverterFactory.contextForType(JaxbConverterFactory.java:76)
                      at retrofit2.converter.jaxb.JaxbConverterFactory.responseBodyConverter(JaxbConverterFactory.java:67)
                      at retrofit2.Retrofit.nextResponseBodyConverter(Retrofit.java:330)
                      at retrofit2.Retrofit.responseBodyConverter(Retrofit.java:313)
                      at retrofit2.ServiceMethod$Builder.createResponseConverter(ServiceMethod.java:739)
                      	... 66 more
                   Caused by: javax.xml.bind.JAXBException`

**Comment by JakeWharton** [comment]
Unless you're doing code generation, JAXB doesn't work on Android via reflection.

If you are looking for an alternative to Simple XML Framework you can try https://github.com/Tickaroo/tikxml.

**Comment by JakeWharton** [comment]
I just merged a PR to document this: #2704

**Comment by FrostRocket** [comment]
Damn, that response time. Thanks for the info @JakeWharton
