### ISSUE TITLE
SSLHandshakeException   [Android 8.1.0]

### ISSUE THREAD

**Issue by thymleaf** [square/retrofit#2758]
javax.net.ssl.SSLHandshakeException: java.lang.RuntimeException: error:04000071:RSA routines:OPENSSL_internal:DATA_TOO_LARGE

 Caused by: java.security.cert.CertificateException: java.lang.RuntimeException: error:04000071:RSA routines:OPENSSL_internal:DATA_TOO_LARGE

at com.android.org.conscrypt.OpenSSLX509Certificate.verifyOpenSSL(OpenSSLX509Certificate.java:366)
at com.android.org.conscrypt.OpenSSLX509Certificate.verify(OpenSSLX509Certificate.java:394)

at com.android.org.conscrypt.ConscryptFileDescriptorSocket.verifyCertificateChain(ConscryptFileDescriptorSocket.java:399)
        at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
        at com.android.org.conscrypt.SslWrapper.doHandshake(SslWrapper.java:374)
        at com.android.org.conscrypt.ConscryptFileDescriptorSocket.startHandshake(ConscryptFileDescriptorSocket.java:217)
    	... 43 more
    Caused by: java.lang.RuntimeException: error:04000071:RSA routines:OPENSSL_internal:DATA_TOO_LARGE

this is my **SSLContext** and **X509TrustManager**  

`
  private SSLContext getSslContext(Context context)
    {
        SSLContext sslContext = null;
        try
        {
//            sslContext = SSLContext.getInstance("TLS");
            sslContext = SSLContext.getInstance("SSL");
            sslContext.init(null, getTrustAllCerts(context), null);
        }
        catch (NoSuchAlgorithmException e)
        {
            e.printStackTrace();
        }
        catch (KeyManagementException e)
        {
            e.printStackTrace();
        }
        return  sslContext;
    }
`

`
  private X509TrustManager[] getTrustAllCerts(Context context)
    {
        return new X509TrustManager[]{new X509TrustManager()
        {
            @Override
            public void checkClientTrusted(X509Certificate[] chain, String authType) throws CertificateException
            {

            }

            @Override
            public void checkServerTrusted(X509Certificate[] chain, String authType) throws CertificateException
            {
                if (chain == null)
                {
                    throw new IllegalArgumentException("Check Server X509Certificate Is Null");
                }
                if (chain.length < 0)
                {
                    throw new IllegalArgumentException("Check Server X509Certificate Is Empty");
                }

                for (X509Certificate cert : chain)
                {
                    cert.checkValidity();
                    try
                    {
                        InputStream is = new BufferedInputStream(context.getAssets().open("my.pem"));
                        CertificateFactory certificateFactory = CertificateFactory.getInstance("X.509");
                        X509Certificate serverCert = (X509Certificate) certificateFactory.generateCertificate(is);
                        cert.verify(serverCert.getPublicKey());
                    }
                    catch (NoSuchAlgorithmException e)
                    {
                        e.printStackTrace();
                    }
                    catch (InvalidKeyException e)
                    {
                        e.printStackTrace();
                    }
                    catch (NoSuchProviderException e)
                    {
                        e.printStackTrace();
                    }
                    catch (SignatureException e)
                    {
                        e.printStackTrace();
                    }
                    catch (IOException e)
                    {
                        e.printStackTrace();
                    }
                }
            }

            @Override
            public X509Certificate[] getAcceptedIssuers()
            {
                return new X509Certificate[0];
            }
        }};
    }
`

below 8.0.0 run well ,please help me

**Comment by JakeWharton** [comment]
Retrofit doesn't deal with SSL. This exception comes from layers waaay beneath Retrofit. You'll have better luck on StackOverflow since there's nothing Retrofit-specific about this.

**Comment by thymleaf** [comment]
sorry , I should append more info, detail log about okhttp and retrofit :

<-- HTTP FAILED: javax.net.ssl.SSLHandshakeException: java.lang.RuntimeException: error:04000071:RSA routines:OPENSSL_internal:DATA_TOO_LARGE
 javax.net.ssl.SSLHandshakeException: java.lang.RuntimeException: error:04000071:RSA routines:OPENSSL_internal:DATA_TOO_LARGE
     at com.android.org.conscrypt.ConscryptFileDescriptorSocket.startHandshake(ConscryptFileDescriptorSocket.java:219)
        at okhttp3.internal.connection.RealConnection.connectTls(RealConnection.java:281)
     at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.java:251)
     at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:151)
        at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:192)
        at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:121)
        at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:100)
     at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:120)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
        at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.java:211)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
        at com.qiandw.app.GlobalConfiguration$2.intercept(GlobalConfiguration.java:164)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:185)
    at okhttp3.RealCall.execute(RealCall.java:69)
        at retrofit2.OkHttpCall.execute(OkHttpCall.java:180)
        at retrofit2.adapter.rxjava2.CallExecuteObservable.subscribeActual(CallExecuteObservable.java:41)
        at io.reactivex.Observable.subscribe(Observable.java:10901)
        at retrofit2.adapter.rxjava2.BodyObservable.subscribeActual(BodyObservable.java:34)

        
 Caused by: java.security.cert.CertificateException: java.lang.RuntimeException: error:04000071:RSA routines:OPENSSL_internal:DATA_TOO_LARGE
     at com.android.org.conscrypt.OpenSSLX509Certificate.verifyOpenSSL(OpenSSLX509Certificate.java:366)
     at com.android.org.conscrypt.OpenSSLX509Certificate.verify(OpenSSLX509Certificate.java:394)
        at com.android.org.conscrypt.Platform.checkServerTrusted(Platform.java:201)
        at com.android.org.conscrypt.ConscryptFileDescriptorSocket.verifyCertificateChain(ConscryptFileDescriptorSocket.java:399)
        at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
        at com.android.org.conscrypt.SslWrapper.doHandshake(SslWrapper.java:374)
     at com.android.org.conscrypt.ConscryptFileDescriptorSocket.startHandshake(ConscryptFileDescriptorSocket.java:217)
 	... 43 more

 Caused by: java.lang.RuntimeException: error:04000071:RSA routines:OPENSSL_internal:DATA_TOO_LARGE
     at com.android.org.conscrypt.NativeCrypto.X509_verify(Native Method)
        at com.android.org.conscrypt.OpenSSLX509Certificate.verifyOpenSSL(OpenSSLX509Certificate.java:364)
    	... 50 more

**Comment by hmaclean82** [comment]
"runs well in Android 8.0" are you sure it wasn't just throwing a `SignatureException` that you are catching? I had a similar issue where I was handling `SignatureException` but since Android 8.1 this became `CertificateException` which I was not...
