### ISSUE TITLE
java.net.ProtocolException: Expected ':status' header not present 

### ISSUE THREAD

**Issue by hiteshcla00** [square/retrofit#2765]
i am also getting this error but when i update dependencies . then getting this all errors below link
https://stackoverflow.com/questions/50447511/android-when-updating-retrofit-2-9-1-and-okhttp-3-x-x-the-json-converter-library

https://stackoverflow.com/questions/50453522/error-when-trying-to-upgrade-retrofit-library

D/Retrofit: java.net.ProtocolException: Expected ':status' header not present
                at com.squareup.okhttp.internal.http.SpdyTransport.readNameValueBlock(SpdyTransport.java:197)
                at com.squareup.okhttp.internal.http.SpdyTransport.readResponseHeaders(SpdyTransport.java:104)
                at com.squareup.okhttp.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:830)
                at com.squareup.okhttp.internal.http.HttpEngine.access$200(HttpEngine.java:95)
                at com.squareup.okhttp.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:823)
                at com.squareup.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:684)
                at com.squareup.okhttp.Call.getResponse(Call.java:272)
                at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:228)
                at com.squareup.okhttp.Call.getResponseWithInterceptorChain(Call.java:199)
                at com.squareup.okhttp.Call.execute(Call.java:79)
                at retrofit.client.OkClient.execute(OkClient.java:53)
                at retrofit.RestAdapter$RestHandler.invokeRequest(RestAdapter.java:326)
                at retrofit.RestAdapter$RestHandler.access$100(RestAdapter.java:220)
                at retrofit.RestAdapter$RestHandler$2.obtainResponse(RestAdapter.java:278)
                at retrofit.CallbackRunnable.run(CallbackRunnable.java:42)
                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                at retrofit.Platform$Android$2$1.run(Platform.java:142)
                at java.lang.Thread.run(Thread.java:818)
            ---- END ERROR

**Comment by JakeWharton** [comment]
That error is from an exceedingly old version of the libraries for which there are new versions of both Retrofit and OkHttp. Asking on StackOverflow for build system problems is the correct location for upgrade questions, but those two questions you linked lack sufficient information to diagnose what the underlying problems are. You'll need to provide more information in order for those reading to understand where the issue lie.

Closing since this issue tracker is for feature requests and bug reports on Retrofit and this is neither.

**Comment by hiteshcla00** [comment]
but its not solving when i updating libraries

**Comment by JakeWharton** [comment]
The problem exists at the OkHttp layer, not Retrofit. If you can create a representative sample (preferably against MockWebServer) and file an issue on OkHttp we can take a look. But without more information it's impossible to diagnose what's going on.

**Comment by hiteshcla00** [comment]
i am using this
mplementation 'com.squareup.retrofit:retrofit:1.9.0'
    implementation 'com.squareup.okhttp:mockwebserver:2.3.0'
    implementation 'org.codehaus.jackson:jackson-mapper-asl:1.9.13'

**Comment by hiteshcla00** [comment]
so please tell me which one are replace all this ?

**Comment by JakeWharton** [comment]
2.4.0 is the latest of Retrofit.

**Comment by hiteshcla00** [comment]
but is not working for my app when i use this version thats all code have error Multipart cannot resolve and  okclient  also cannot reslove
