### ISSUE TITLE
Feature Request: "IllegalArgumentException: Path parameter XXX value must not be null." should include url

### ISSUE THREAD

**Issue by tir38** [square/retrofit#2773]
I was not properly setting a `Path` parameter and saw:

`Caused by: java.lang.IllegalArgumentException: Path parameter "user_id" value must not be null.`

The problem is that I have ~20 web requests all with the `user_id` path parameter. I have no easy way to diagnose which one I'm calling incorrectly. It would be great if that error message included the url.

I think it should be pretty easy to update `Path` to:

```
static final class Path<T> extends ParameterHandler<T> {
    @Override
    void apply(RequestBuilder builder, @Nullable T value) throws IOException {
        if (value == null) {
            throw new IllegalArgumentException(
                    "Path parameter \"" + name + "\" value must not be null in request "
                            + builder.baseUrl + builder.relativeUrl);
        }
        builder.addPathParam(name, valueConverter.convert(value), encoded);
    }
}
```

Probably worth updating all `ParameterHandler`s that throw when value is null.

For the record, calling a service method inside RxJava stream results in a stack trace that isn't very helpful:

```
   io.reactivex.exceptions.OnErrorNotImplementedException: Path parameter "user_id" value must not be null.
        at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:704)
        at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:701)
        at io.reactivex.internal.observers.ConsumerSingleObserver.onError(ConsumerSingleObserver.java:47)
        at io.reactivex.internal.operators.single.SingleObserveOn$ObserveOnSingleObserver.run(SingleObserveOn.java:79)
        at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:109)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6121)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
     Caused by: java.lang.IllegalArgumentException: Path parameter "user_id" value must not be null.
        at retrofit2.ParameterHandler$Path.apply(ParameterHandler.java:96)
        at retrofit2.ServiceMethod.toRequest(ServiceMethod.java:111)
        at retrofit2.OkHttpCall.createRawCall(OkHttpCall.java:184)
        at retrofit2.OkHttpCall.execute(OkHttpCall.java:168)
        at retrofit2.adapter.rxjava2.CallExecuteObservable.subscribeActual(CallExecuteObservable.java:41)
        at io.reactivex.Observable.subscribe(Observable.java:12025)
        at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
        at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:571)
        at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
        at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:761)
```

**Comment by tir38** [comment]
I'd be willing to work on this if I get a 👍

**Comment by JakeWharton** [comment]
For configuration problems the exceptions include the class name and method name. We could do the same here which should be fairly straightforward by retaining the `Method` instance.

**Comment by tir38** [comment]
"the exceptions include the class name and method name" I looked around and couldn't find this. Will you point me in the right direction?

**Comment by JakeWharton** [comment]
There are exception factories for methods and parameters in `Utils`.

**Comment by vitorhugods** [comment]
Came through this issue too. Had a bad time figuring out where the null came from in a non-Kotlin project.

Most of the `ParameterHandler.apply` implementations can throw exceptions. And the `Utils.methodError` methods for throwing exceptions asks for a `Method` parameter.

I think the best way of doing it is adding a `Method` parameter in the constructor of handler implementations that can throw exceptions and hold the method instance. But these implementations have public constructors, so if anyone is instantiating these handlers directly (which I can't see why someone would, but nevertheless) would have a bad time.

I will do this and we could discuss more on the PR.

**Comment by JakeWharton** [comment]
Improvement was merged.

**Comment by tir38** [comment]
@vitorhugods thanks!
