### ISSUE TITLE
io.reactivex.Flowable not found ???

### ISSUE THREAD

**Issue by zzy904494436** [square/retrofit#2776]
issues is : i am not good at it ...

> 
`
java.lang.NoClassDefFoundError: Failed resolution of: Lio/reactivex/Flowable;
	at retrofit2.adapter.rxjava2.RxJava2CallAdapterFactory.get(RxJava2CallAdapterFactory.java:104)
	at retrofit2.Retrofit.nextCallAdapter(Retrofit.java:221)
	at retrofit2.Retrofit.callAdapter(Retrofit.java:205)
	at retrofit2.ServiceMethod$Builder.createCallAdapter(ServiceMethod.java:235)
	at retrofit2.ServiceMethod$Builder.build(ServiceMethod.java:162)
	at retrofit2.Retrofit.loadServiceMethod(Retrofit.java:170)
	at retrofit2.Retrofit$1.invoke(Retrofit.java:147)
	at java.lang.reflect.Proxy.invoke(Proxy.java:393)
	at $Proxy5.pushLogPage(Unknown Source)
	at com.gm88.user.UserCore.pushLogPage(UserCore.java:1276)
	at com.gm88.user.GmUserCore.pushPageLog(GmUserCore.java:472)
	at com.gm88.gmsdk.manager.InitManager.ActivityInit(InitManager.java:99)
	at com.gm88.gmsdk.SDKCore.initMainActivity(SDKCore.java:122)
	at com.gm88.gmsdk.GMSDK.initMainActivity(GMSDK.java:52)
	at com.gm88.demo.MainActivity.onCreate(MainActivity.java:72)
	at android.app.Activity.performCreate(Activity.java:6237)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
	at android.app.ActivityThread.-wrap11(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5417)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
Caused by: java.lang.ClassNotFoundException: Didn't find class "io.reactivex.Flowable" on path: DexPathList[[zip file "/data/app/com.gm88.demo-1/base.apk"],nativeLibraryDirectories=[/data/app/com.gm88.demo-1/lib/arm64, /data/app/com.gm88.demo-1/base.apk!/lib/arm64-v8a, /vendor/lib64, /system/lib64]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
	... 27 more
	Suppressed: java.lang.NoClassDefFoundError: io.reactivex.Flowable
		at dalvik.system.DexFile.defineClassNative(Native Method)
		at dalvik.system.DexFile.defineClass(DexFile.java:226)
		at dalvik.system.DexFile.loadClassBinaryName(DexFile.java:219)
		at dalvik.system.DexPathList.findClass(DexPathList.java:338)
		at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:54)
		... 29 more
	Suppressed: java.lang.ClassNotFoundException: io.reactivex.Flowable
		at java.lang.Class.classForName(Native Method)
		at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
		at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
		at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
		... 28 more
	Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available
`

**Comment by NightlyNexus** [comment]
I noticed Android classes in the stack trace.
Any chance you're using something like ProGuard? Those kinds of tools can wreck your code.
