### ISSUE TITLE
When call Delete reqeust first time，The next call throws under Exception

### ISSUE THREAD

**Issue by MilkCatLZ** [square/retrofit#2803]
When call Delete reqeust first time，The next call throws under Exception
And the ["message"]... is the Delete respon body. why

`06-21 16:09:19.481 30903-30903/shy.car.sdk W/System.err: java.net.ProtocolException: Unexpected status line: {"message":"\u64cd\u4f5c\u6210\u529f"}HTTP/1.1 201 Created
06-21 16:09:19.485 30903-30903/shy.car.sdk W/System.err:     at okhttp3.internal.http.StatusLine.parse(StatusLine.java:69)
        at okhttp3.internal.http1.Http1Codec.readResponseHeaders(Http1Codec.java:189)
06-21 16:09:19.486 30903-30903/shy.car.sdk W/System.err:     at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:88)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)
06-21 16:09:19.487 30903-30903/shy.car.sdk W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
06-21 16:09:19.488 30903-30903/shy.car.sdk W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
06-21 16:09:19.489 30903-30903/shy.car.sdk W/System.err:     at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:126)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.java:145)
06-21 16:09:19.490 30903-30903/shy.car.sdk W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at com.base.network.retrofit.BaseInterceptor.intercept(BaseInterceptor.kt:33)
06-21 16:09:19.491 30903-30903/shy.car.sdk W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200)
06-21 16:09:19.492 30903-30903/shy.car.sdk W/System.err:     at okhttp3.RealCall.execute(RealCall.java:77)
        at retrofit2.OkHttpCall.execute(OkHttpCall.java:180)
        at retrofit2.adapter.rxjava2.CallExecuteObservable.subscribeActual(CallExecuteObservable.java:42)
        at io.reactivex.Observable.subscribe(Observable.java:12005)
06-21 16:09:19.493 30903-30903/shy.car.sdk W/System.err:     at retrofit2.adapter.rxjava2.BodyObservable.subscribeActual(BodyObservable.java:34)
        at io.reactivex.Observable.subscribe(Observable.java:12005)
06-21 16:09:19.494 30903-30903/shy.car.sdk W/System.err:     at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
06-21 16:09:19.496 30903-30903/shy.car.sdk W/System.err:     at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:571)
        at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
        at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
06-21 16:09:19.497 30903-30903/shy.car.sdk W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
06-21 16:09:19.498 30903-30903/shy.car.sdk W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)`

**Comment by JakeWharton** [comment]
Please provide a failing test case. This is caused by not consuming the response body from the first requeset.

**Comment by JakeWharton** [comment]
Here's mine, which passes:
```java
@Rule public final MockWebServer server = new MockWebServer();

interface Delete {
  @DELETE("/") Call<String> delete();
}

@Test public void twoDeletes() throws IOException {
  Retrofit retrofit = new Retrofit.Builder()
      .baseUrl(server.url("/"))
      .addConverterFactory(new ToStringConverterFactory())
      .build();
  Delete example = retrofit.create(Delete.class);

  server.enqueue(new MockResponse().setBody("Hi"));
  server.enqueue(new MockResponse().setBody("Hi"));

  Response<String> response1 = example.delete().execute();
  assertThat(response1.isSuccessful()).isTrue();
  assertThat(response1.body()).isEqualTo("Hi");

  Response<String> response2 = example.delete().execute();
  assertThat(response2.isSuccessful()).isTrue();
  assertThat(response2.body()).isEqualTo("Hi");
}
```
