### ISSUE TITLE
Null Response Body - EOFException

### ISSUE THREAD

**Issue by jnrbo** [square/retrofit#2810]
Hi!

I have in my server an API that receives a POST request and doesn't return anything if succeeded.

(WebService) For example:
```
@PostMapping(value = "update-user-value.json")
public void updateUserValue(Long user, String newValue) {
    service.updateUserValue(user, newValue);
}
```

I'm executing the request in my Android (kotlin) app like this:

```
disposable = myApiService
    .updateUserValue(user.id, newValue)
    .subscribeOn(Schedulers.io())
    .observeOn(AndroidSchedulers.mainThread())
    .subscribe()
```

**myApiService.updateUserValue is like:**

```
@POST("update-user-value.json")
@FormUrlEncoded
fun updateUserValue(@Field("user") user: Long, @Field("newValue") newValue: String) : Maybe<String>
```

I read the issue [2242 (comment)](https://github.com/square/retrofit/issues/2242#issuecomment-300850574) but even trying to return **`Observable<Int>`**, **`Single<Int>`**, **`Maybe`**. I only didn't used **`Observable<Response<BodyType>>`**, because I don't know what should instead of "_BodyType_"

**Exception:**

```
java.io.EOFException: End of input at line 1 column 1 path $
  at com.google.gson.stream.JsonReader.nextNonWhitespace(JsonReader.java:1401)
  at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:549)
  at com.google.gson.stream.JsonReader.peek(JsonReader.java:425)
  at com.google.gson.internal.bind.TypeAdapters$16.read(TypeAdapters.java:393)
  at com.google.gson.internal.bind.TypeAdapters$16.read(TypeAdapters.java:390)
  at retrofit2.converter.gson.GsonResponseBodyConverter.convert(GsonResponseBodyConverter.java:39)
  at retrofit2.converter.gson.GsonResponseBodyConverter.convert(GsonResponseBodyConverter.java:27)
  at retrofit2.ServiceMethod.toResponse(ServiceMethod.java:122)
  at retrofit2.OkHttpCall.parseResponse(OkHttpCall.java:217)
  at retrofit2.OkHttpCall.execute(OkHttpCall.java:180)
  at retrofit2.adapter.rxjava2.CallExecuteObservable.subscribeActual(CallExecuteObservable.java:42)
  at io.reactivex.Observable.subscribe(Observable.java:10179)
  at retrofit2.adapter.rxjava2.BodyObservable.subscribeActual(BodyObservable.java:34)
  at io.reactivex.Observable.subscribe(Observable.java:10179)
  at io.reactivex.internal.operators.observable.ObservableSingleMaybe.subscribeActual(ObservableSingleMaybe.java:30)
  at io.reactivex.Maybe.subscribe(Maybe.java:3540)
  at io.reactivex.internal.operators.maybe.MaybeSubscribeOn$SubscribeTask.run(MaybeSubscribeOn.java:54)
  at io.reactivex.Scheduler$1.run(Scheduler.java:134)
  at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:59)
  at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:51)
  at java.util.concurrent.FutureTask.run(FutureTask.java:237)
  at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
  at java.lang.Thread.run(Thread.java:761)
```

**Comment by jnrbo** [comment]
Fixed using `Observable<Response<Void>>` as 'response type'
