### ISSUE TITLE
Check for @Url as the first parameter doesn't work on Kotlin

### ISSUE THREAD

**Issue by MarkMjw** [square/retrofit#2845]
I set @Url default value in function with last param，like this:
```
     @GET
     fun batch(@HeaderMap header: Map<String, String>, @QueryMap param: Map<String, String>, @Url url: String = "http://xxx.xxx./xxx"): Flowable<Result>
```

and the log:
```
java.lang.NullPointerException: Attempt to invoke virtual method 'okhttp3.HttpUrl$Builder okhttp3.HttpUrl$Builder.addQueryParameter(java.lang.String, java.lang.String)' on a null object reference
        at retrofit2.RequestBuilder.addQueryParam(RequestBuilder.java:162)
        at retrofit2.ParameterHandler$QueryMap.apply(ParameterHandler.java:176)
        at retrofit2.ParameterHandler$QueryMap.apply(ParameterHandler.java:139)
        at retrofit2.ServiceMethod.toCall(ServiceMethod.java:110)
        at retrofit2.OkHttpCall.createRawCall(OkHttpCall.java:184)
        at retrofit2.OkHttpCall.execute(OkHttpCall.java:167)
        at retrofit2.adapter.rxjava2.CallExecuteObservable.subscribeActual(CallExecuteObservable.java:42)
        at io.reactivex.Observable.subscribe(Observable.java:12051)
        at retrofit2.adapter.rxjava2.BodyObservable.subscribeActual(BodyObservable.java:34)
        at io.reactivex.Observable.subscribe(Observable.java:12051)
        at io.reactivex.internal.operators.flowable.FlowableFromObservable.subscribeActual(FlowableFromObservable.java:29)
        at io.reactivex.Flowable.subscribe(Flowable.java:14349)
        at io.reactivex.internal.operators.flowable.FlowableOnBackpressureLatest.subscribeActual(FlowableOnBackpressureLatest.java:32)
        at io.reactivex.Flowable.subscribe(Flowable.java:14349)
        at io.reactivex.Flowable.subscribe(Flowable.java:14295)
        at io.reactivex.internal.operators.flowable.FlowableSubscribeOn$SubscribeOnSubscriber.run(FlowableSubscribeOn.java:82)
        at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
        at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
```

**Comment by JakeWharton** [comment]
`@Url` must be first. We have a test which enforces this invariant. I'll look into why it doesn't work here.

**Comment by MarkMjw** [comment]
Thanks, set @Url as the first parameter, it's working for me.
