### ISSUE TITLE
When I try to pass an id with name "id" I have an error java.lang.NumberFormatException

### ISSUE THREAD

**Issue by JonataKlabunde** [square/retrofit#2857]
When I try to pass an id with name "id" I have an error java.lang.NumberFormatException: For input string

@GET("customer/favored")
fun getFavoredToTransfer(@Query("id") id: String): Call<FavoredReadModel>

**Comment by JakeWharton** [comment]
Please supply a full stack trace or failing test case.

**Comment by JonataKlabunde** [comment]
this is the "stack trace"

`    com.google.gson.JsonSyntaxException: java.lang.NumberFormatException: For input string: "e9800543-d8b4-4990-a646-22b9ec9728e8"
        at com.google.gson.internal.bind.TypeAdapters$7.read(TypeAdapters.java:227)
        at com.google.gson.internal.bind.TypeAdapters$7.read(TypeAdapters.java:217)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:129)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:220)
        at retrofit2.converter.gson.GsonResponseBodyConverter.convert(GsonResponseBodyConverter.java:39)
        at retrofit2.converter.gson.GsonResponseBodyConverter.convert(GsonResponseBodyConverter.java:27)
        at retrofit2.ServiceMethod.toResponse(ServiceMethod.java:122)
        at retrofit2.OkHttpCall.parseResponse(OkHttpCall.java:217)
        at retrofit2.OkHttpCall$1.onResponse(OkHttpCall.java:116)
        at okhttp3.RealCall$AsyncCall.execute(RealCall.java:153)
        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:761)
     Caused by: java.lang.NumberFormatException: For input string: "e9800543-d8b4-4990-a646-22b9ec9728e8"
        at java.lang.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:1306)
        at java.lang.Double.parseDouble(Double.java:547)
        at com.google.gson.stream.JsonReader.nextInt(JsonReader.java:1201)
        at com.google.gson.internal.bind.TypeAdapters$7.read(TypeAdapters.java:225)
        at com.google.gson.internal.bind.TypeAdapters$7.read(TypeAdapters.java:217) 
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:129) 
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:220) 
        at retrofit2.converter.gson.GsonResponseBodyConverter.convert(GsonResponseBodyConverter.java:39) 
        at retrofit2.converter.gson.GsonResponseBodyConverter.convert(GsonResponseBodyConverter.java:27) 
        at retrofit2.ServiceMethod.toResponse(ServiceMethod.java:122) 
        at retrofit2.OkHttpCall.parseResponse(OkHttpCall.java:217) 
        at retrofit2.OkHttpCall$1.onResponse(OkHttpCall.java:116) 
        at okhttp3.RealCall$AsyncCall.execute(RealCall.java:153) 
        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) 
        at java.lang.Thread.run(Thread.java:761) `

**Comment by JakeWharton** [comment]
This exception happens inside of Gson while it's parsing the response body of the request. It's not something Retrofit can fix since it's a problem between your response body data model and the response body JSON. Somewhere you've declared a property as an integer but it's actually a string.
