### ISSUE TITLE
call.execute() Android 9 - sdk 28

### ISSUE THREAD

**Issue by dudisitchy** [square/retrofit#2879]
Hi there,

My app crash when retrofit is called after update do Android 9 SDK 28. Any other device below this version works.

Crash on this line:
`Response<ResponseBody> response = call.execute();`

Do you have any solution or tip?

Thanks!!

**Comment by JakeWharton** [comment]
With what exception?

**Comment by dudisitchy** [comment]
Sorry for that!!

--------- beginning of crash
09-06 13:17:16.710 12799-12839/br.com.iesde.saequestoes E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #1
    Process: br.com.iesde.saequestoes, PID: 12799
    java.lang.RuntimeException: An error occurred while executing doInBackground()
        at android.os.AsyncTask$3.done(AsyncTask.java:354)
        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
        at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
        at java.util.concurrent.FutureTask.run(FutureTask.java:271)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lorg/apache/http/client/ClientProtocolException;
        at com.newrelic.agent.android.util.ExceptionHelper.exceptionToErrorCode(ExceptionHelper.java:36)
        at com.newrelic.agent.android.instrumentation.TransactionStateUtil.setErrorCodeFromException(TransactionStateUtil.java:202)
        at com.newrelic.agent.android.instrumentation.okhttp3.CallExtension.error(CallExtension.java:94)
        at com.newrelic.agent.android.instrumentation.okhttp3.CallExtension.execute(CallExtension.java:46)
        at retrofit2.OkHttpCall.execute(OkHttpCall.java:180)
        at retrofit2.ExecutorCallAdapterFactory$ExecutorCallbackCall.execute(ExecutorCallAdapterFactory.java:91)
        at br.com.iesde.saequestoes.global.online.StandardAsync.postDataToURL(StandardAsync.java:105)
        at br.com.iesde.saequestoes.start.LoginActivity$LoginAsync.doInBackground(LoginActivity.java:249)
        at br.com.iesde.saequestoes.start.LoginActivity$LoginAsync.doInBackground(LoginActivity.java:232)
        at android.os.AsyncTask$2.call(AsyncTask.java:333)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:764) 
     Caused by: java.lang.ClassNotFoundException: Didn't find class "org.apache.http.client.ClientProtocolException" on path: DexPathList[[zip file "/data/app/br.com.iesde.saequestoes-VFVm0eYSqR7KFVpO8_FwCQ==/base.apk"],nativeLibraryDirectories=[/data/app/br.com.iesde.saequestoes-VFVm0eYSqR7KFVpO8_FwCQ==/lib/x86, /data/app/br.com.iesde.saequestoes-VFVm0eYSqR7KFVpO8_FwCQ==/base.apk!/lib/x86, /system/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at com.newrelic.agent.android.util.ExceptionHelper.exceptionToErrorCode(ExceptionHelper.java:36) 
        at com.newrelic.agent.android.instrumentation.TransactionStateUtil.setErrorCodeFromException(TransactionStateUtil.java:202) 
        at com.newrelic.agent.android.instrumentation.okhttp3.CallExtension.error(CallExtension.java:94) 
        at com.newrelic.agent.android.instrumentation.okhttp3.CallExtension.execute(CallExtension.java:46) 
        at retrofit2.OkHttpCall.execute(OkHttpCall.java:180) 
        at retrofit2.ExecutorCallAdapterFactory$ExecutorCallbackCall.execute(ExecutorCallAdapterFactory.java:91) 
        at br.com.iesde.saequestoes.global.online.StandardAsync.postDataToURL(StandardAsync.java:105) 
        at br.com.iesde.saequestoes.start.LoginActivity$LoginAsync.doInBackground(LoginActivity.java:249) 
        at br.com.iesde.saequestoes.start.LoginActivity$LoginAsync.doInBackground(LoginActivity.java:232) 
        at android.os.AsyncTask$2.call(AsyncTask.java:333) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:764) 
```

**Comment by JakeWharton** [comment]
This is a problem with the NewRelic library and not Retrofit. It is using types which are no longer available by default in the classpath.
