### ISSUE TITLE
Stream closed IO exception

### ISSUE THREAD

**Issue by mayankkussh** [square/retrofit#2883]
What kind of issue is this?
Retrofit version 2.4.0
 - [ ] Question. "Stream closed" IOException in case of 4xx response code Express

Stack trace
W/System.err: java.io.IOException: stream closed
        at okhttp3.internal.http2.Http2Stream$FramingSource.checkNotClosed(Http2Stream.java:433)
        at okhttp3.internal.http2.Http2Stream$FramingSource.read(Http2Stream.java:338)
        at okhttp3.internal.http2.Http2Codec$StreamFinishingSource.read(Http2Codec.java:210)
        at okio.RealBufferedSource.readAll(RealBufferedSource.java:173)
        at retrofit2.Utils.buffer(Utils.java:298)
        at retrofit2.OkHttpCall.parseResponse(OkHttpCall.java:203)
        at retrofit2.OkHttpCall$1.onResponse(OkHttpCall.java:116)
        at okhttp3.RealCall$AsyncCall.execute(RealCall.java:153)
        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
        at java.lang.Thread.run(Thread.java:818)

Response
D/OkHttp: <-- 422 https://developmentwow.wedmegood.com/node/v1/whitelabel/update-vendor-status (60ms)
    date: Fri, 07 Sep 2018 13:06:48 GMT
    content-type: application/json; charset=utf-8
    content-length: 61
    x-powered-by: Express
    access-control-allow-origin: *
    etag: W/"3d-yQEZU5ubQ5+cb/FcwF0EjXS7NTo"
    vary: Accept-Encoding
    {"errorMessage":"Invalid Action","errorCode":400,"errors":[]}
    <-- END HTTP (61-byte body)

**Comment by JakeWharton** [comment]
This is not a Retrofit problem. It looks like the server sent a close frame prior to finishing the body? It's hard to tell. It might be an OkHttp bug. If you can reliably reproduce it with a test case or sample please file a bug at https://github.com/square/okhttp/issues

**Comment by mayankkussh** [comment]
Thanks @JakeWharton

**Comment by rajatsharma45** [comment]
Maybe you are reading the stream somewhere else like in some ErrorInterceptor etc. and its closing the stream.
