### ISSUE TITLE
Random failures on error responses with Windows 10 emulator

### ISSUE THREAD

**Issue by jorisdeguet** [square/retrofit#2946]
Hi,

I teach Android and some of my students spotted a strange bug.

- only happens on AVDs runnning on top of Windows 10 so far
- we tested a bunch of recent physical Android devices and none shows the bug
- I tested emulators on a MacOS machine with no bug

It looks like an emulator bug but I can't tell for sure so here it is.

When sending multiple requests to a web service that consistently returns a 400 http response, I obtain two different results at random:

- sometimes I receive a well formed response that is not successful (onResponse)
- sometimes I receive an Exception (onFailure):
```
java.net.ProtocolException: unexpected end of stream
2018-11-01 14:25:17.224 6554-6571/org.deguet.cookieandroid W/System.err:     at okhttp3.internal.http1.Http1Codec$FixedLengthSource.read(Http1Codec.java:409)
2018-11-01 14:25:17.224 6554-6571/org.deguet.cookieandroid W/System.err:     at okio.RealBufferedSource.readAll(RealBufferedSource.java:173)
2018-11-01 14:25:17.224 6554-6571/org.deguet.cookieandroid W/System.err:     at retrofit2.Utils.buffer(Utils.java:298)
2018-11-01 14:25:17.224 6554-6571/org.deguet.cookieandroid W/System.err:     at retrofit2.OkHttpCall.parseResponse(OkHttpCall.java:203)
2018-11-01 14:25:17.224 6554-6571/org.deguet.cookieandroid W/System.err:     at retrofit2.OkHttpCall.execute(OkHttpCall.java:180)
2018-11-01 14:25:17.224 6554-6571/org.deguet.cookieandroid W/System.err:     at retrofit2.ExecutorCallAdapterFactory$ExecutorCallbackCall.execute(ExecutorCallAdapterFactory.java:91)
2018-11-01 14:25:17.224 6554-6571/org.deguet.cookieandroid W/System.err:     at org.deguet.cookieandroid.ExampleInstrumentedTest.testError(ExampleInstrumentedTest.java:31)
```
This is weird but this does not happen on http 200 responses, only on 400 responses.
[BugAndroid.zip](https://github.com/square/retrofit/files/2539600/BugAndroid.zip)

To reproduce launch the androidTest on an AVD running on Windows 10.

I have reproduced the bug on emulators running API 22 to 28 with Android Studio 3.2.1.

By the way, thanks for retrofit okhttp. A great tool for teaching.

Joris

**Comment by jorisdeguet** [comment]
Hi,

If anyone wants to track the Google bug report, here it is:
https://issuetracker.google.com/issues/119027639

Jo
