### ISSUE TITLE
A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.

### ISSUE THREAD

**Issue by cuong292** [square/retrofit#2956]
i have this problem.Everything is just ok when i call the API using retrofit.but if i turn the wifi off -> reload and got onFailure -> turn on the wifi -> reload,it caught this exception

**Explicit termination method 'close' not called
        at dalvik.system.CloseGuard.open(CloseGuard.java:184)
        at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:271)
        at com.android.okhttp.Connection.upgradeToTls(Connection.java:197)
        at com.android.okhttp.Connection.connect(Connection.java:151)
        at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:276)**

This is my CallBack

**@Override
  public void onResponse(Call<T> call, Response<T> response) {
    if (!response.isSuccessful()) {
      if (response.code() == 401) {
        onAuthenFailed();
      }

      onUnsuccessful(response);
      return;
    }

    onSucessful(call, response);
  }**

and this is the client builder 

**OkHttpClient.Builder builder = new OkHttpClient.Builder();
        builder.connectTimeout(60, TimeUnit.SECONDS);
        builder.readTimeout(120, TimeUnit.SECONDS);
        builder.addInterceptor(new HeadersInterceptor());
        builder.addInterceptor(new AuthorizationInterceptor(getContext()));

JacksonConverterFactory factory = JacksonConverterFactory.create(objectMapper);

        Retrofit retrofit = new Retrofit.Builder()
                .baseUrl(Constants.BASE_API_URL)
                .addConverterFactory(factory)
                .client(builder.build())
                .build();**

**Comment by JakeWharton** [comment]
Retrofit does not use HttpURLConnection (which is powered by com.android.okhttp) so this stack trace is coming from something else. The stacktrace should contain more lines below what you've posted which indicates who is using HttpURLConnection and causing the connection leak.

**Comment by cuong292** [comment]
@JakeWharton thank you for reply.this is the full trace

 **at dalvik.system.CloseGuard.open(CloseGuard.java:184)
        at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:271)
        at com.android.okhttp.Connection.upgradeToTls(Connection.java:197)
        at com.android.okhttp.Connection.connect(Connection.java:151)
        at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:276)
        at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:211)
        at com.android.okhttp.internal.http.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:373)
        at com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:323)
        at com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:491)
        at com.android.okhttp.internal.http.DelegatingHttpsURLConnection.getResponseCode(DelegatingHttpsURLConnection.java:105)
        at com.android.okhttp.internal.http.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:25)
        at io.fabric.sdk.android.services.network.HttpRequest.code(HttpRequest.java:1353)
        at io.fabric.sdk.android.services.settings.DefaultSettingsSpiCall.handleResponse(DefaultSettingsSpiCall.java:106)
        at io.fabric.sdk.android.services.settings.DefaultSettingsSpiCall.invoke(DefaultSettingsSpiCall.java:90)
        at io.fabric.sdk.android.services.settings.DefaultSettingsController.loadSettingsData(DefaultSettingsController.java:80)
        at io.fabric.sdk.android.services.settings.DefaultSettingsController.loadSettingsData(DefaultSettingsController.java:64)
        at io.fabric.sdk.android.services.settings.Settings.loadSettingsData(Settings.java:155)
        at io.fabric.sdk.android.Onboarding.retrieveSettingsData(Onboarding.java:126)
        at io.fabric.sdk.android.Onboarding.doInBackground(Onboarding.java:99)
        at io.fabric.sdk.android.Onboarding.doInBackground(Onboarding.java:45)
        at io.fabric.sdk.android.InitializationTask.doInBackground(InitializationTask.java:63)
        at io.fabric.sdk.android.InitializationTask.doInBackground(InitializationTask.java:28)
        at io.fabric.sdk.android.services.concurrency.AsyncTask$2.call(AsyncTask.java:311)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
        at java.lang.Thread.run(Thread.java:818)**

**Comment by cuong292** [comment]
cant find out the problem,btw i caught this on emulator.just using that to call a single API per action and just on the case below,its caugh that warning and destroy process by StrictMode

**Comment by cuong292** [comment]
@JakeWharton i just use the Fabric SDK Crashlytics and all other place doesnt got any problem so i guess it because when i turn the emulator network on and it not finished some http connection yet.if i hold for a feel second,its not caught that problem.thanks for all of your support
