### ISSUE TITLE
The response not closed if this exceptions, I think

### ISSUE THREAD

**Issue by gMan1990** [square/retrofit#2990]
```
java.net.ProtocolException: Expected leading [0-9a-fA-F] character but was 0x48
	at okhttp3.internal.http1.Http1Codec$ChunkedSource.readChunkSize(Http1Codec.java:476) ~[okhttp-3.10.0.jar:?]
	at okhttp3.internal.http1.Http1Codec$ChunkedSource.read(Http1Codec.java:449) ~[okhttp-3.10.0.jar:?]
	at okio.RealBufferedSource.read(RealBufferedSource.java:47) ~[okio-1.14.0.jar:?]
	at okio.RealBufferedSource.exhausted(RealBufferedSource.java:57) ~[okio-1.14.0.jar:?]
	at okio.InflaterSource.refill(InflaterSource.java:102) ~[okio-1.14.0.jar:?]
	at okio.InflaterSource.read(InflaterSource.java:62) ~[okio-1.14.0.jar:?]
	at okio.GzipSource.read(GzipSource.java:80) ~[okio-1.14.0.jar:?]
	at okio.RealBufferedSource.request(RealBufferedSource.java:68) ~[okio-1.14.0.jar:?]
	at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.java:241) ~[logging-interceptor-3.10.0.jar:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) ~[okhttp-3.10.0.jar:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121) ~[okhttp-3.10.0.jar:?]
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200) ~[okhttp-3.10.0.jar:?]
	at okhttp3.RealCall.execute(RealCall.java:77) ~[okhttp-3.10.0.jar:?]
	at retrofit2.OkHttpCall.execute(OkHttpCall.java:180) ~[retrofit-2.4.0.jar:?]
	at ***
	... 5 more
```
```
java.io.IOException: gzip finished without exhausting source
	at okio.GzipSource.read(GzipSource.java:100) ~[okio-1.14.0.jar:?]
	at okio.RealBufferedSource.request(RealBufferedSource.java:68) ~[okio-1.14.0.jar:?]
	at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.java:241) ~[logging-interceptor-3.10.0.jar:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) ~[okhttp-3.10.0.jar:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121) ~[okhttp-3.10.0.jar:?]
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200) ~[okhttp-3.10.0.jar:?]
	at okhttp3.RealCall.execute(RealCall.java:77) ~[okhttp-3.10.0.jar:?]
	at retrofit2.OkHttpCall.execute(OkHttpCall.java:180) ~[retrofit-2.4.0.jar:?]
	at ***
	... 5 more
```
```
java.io.EOFException
	at okio.RealBufferedSource.require(RealBufferedSource.java:61) ~[okio-1.14.0.jar:?]
	at okio.RealBufferedSource.readHexadecimalUnsignedLong(RealBufferedSource.java:304) ~[okio-1.14.0.jar:?]
	at okhttp3.internal.http1.Http1Codec$ChunkedSource.readChunkSize(Http1Codec.java:469) ~[okhttp-3.10.0.jar:?]
	at okhttp3.internal.http1.Http1Codec$ChunkedSource.read(Http1Codec.java:449) ~[okhttp-3.10.0.jar:?]
	at okio.RealBufferedSource.read(RealBufferedSource.java:47) ~[okio-1.14.0.jar:?]
	at okio.RealBufferedSource.exhausted(RealBufferedSource.java:57) ~[okio-1.14.0.jar:?]
	at okio.InflaterSource.refill(InflaterSource.java:102) ~[okio-1.14.0.jar:?]
	at okio.InflaterSource.read(InflaterSource.java:62) ~[okio-1.14.0.jar:?]
	at okio.GzipSource.read(GzipSource.java:80) ~[okio-1.14.0.jar:?]
	at okio.RealBufferedSource.request(RealBufferedSource.java:68) ~[okio-1.14.0.jar:?]
	at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.java:241) ~[logging-interceptor-3.10.0.jar:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) ~[okhttp-3.10.0.jar:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121) ~[okhttp-3.10.0.jar:?]
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200) ~[okhttp-3.10.0.jar:?]
	at okhttp3.RealCall.execute(RealCall.java:77) ~[okhttp-3.10.0.jar:?]
	at retrofit2.OkHttpCall.execute(OkHttpCall.java:180) ~[retrofit-2.4.0.jar:?]
	at ***
	... 5 more
```

**Comment by JakeWharton** [comment]
What converters are you using? The only way this could occur at the Retrofit layer is if you are using a converter that is not closing the body (or using `@Streaming` and not closing it yourself).

**Comment by gMan1990** [comment]
@JakeWharton Not related to the converter, bug in HttpLoggingInterceptor.java, see https://github.com/square/okhttp/issues/4447

**Comment by JakeWharton** [comment]
I'm not familiar enough with the implementation of OkHttp to comment one
way or the other.
