### ISSUE TITLE
BodyObservable: AssertionError: This should never happen! Report as a bug with the full stacktrace.

### ISSUE THREAD

**Issue by bmc08gt** [square/retrofit#2994]
Crash reported in wild

```
12-19 12:42:26.859 15627 15794 W System.err: io.reactivex.exceptions.UndeliverableException: java.lang.AssertionError: This should never happen! Report as a bug with the full stacktrace.
12-19 12:42:26.860 15627 15794 W System.err: 	at io.reactivex.plugins.RxJavaPlugins.onError(RxJavaPlugins.java:367)
12-19 12:42:26.860 15627 15794 W System.err: 	at retrofit2.adapter.rxjava2.BodyObservable$BodyObserver.onError(BodyObservable.java:79)
12-19 12:42:26.860 15627 15794 W System.err: 	at retrofit2.adapter.rxjava2.CallEnqueueObservable$CallCallback.onResponse(CallEnqueueObservable.java:68)
12-19 12:42:26.860 15627 15794 W System.err: 	at retrofit2.OkHttpCall$1.onResponse(OkHttpCall.java:123)
12-19 12:42:26.860 15627 15794 W System.err: 	at okhttp3.v$a.c(RealCall.java:153)
12-19 12:42:26.860 15627 15794 W System.err: 	at okhttp3.internal.b.run(NamedRunnable.java:32)
12-19 12:42:26.860 15627 15794 W System.err: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
12-19 12:42:26.860 15627 15794 W System.err: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
12-19 12:42:26.860 15627 15794 W System.err: 	at java.lang.Thread.run(Thread.java:761)
12-19 12:42:26.861 15627 15794 W System.err: Caused by: java.lang.AssertionError: This should never happen! Report as a bug with the full stacktrace.
12-19 12:42:26.861 15627 15794 W System.err: 	at retrofit2.adapter.rxjava2.BodyObservable$BodyObserver.onError(BodyObservable.java:75)
12-19 12:42:26.861 15627 15794 W System.err: 	at java.lang.Thread.nativeCreate(Native Method)
12-19 12:42:26.861 15627 15794 W System.err: 	at java.lang.Thread.start(Thread.java:730)
12-19 12:42:26.862 15627 15794 W System.err: 	at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:941)
12-19 12:42:26.862 15627 15794 W System.err: 	at java.util.concurrent.ThreadPoolExecutor.ensurePrestart(ThreadPoolExecutor.java:1582)
12-19 12:42:26.862 15627 15794 W System.err: 	at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(ScheduledThreadPoolExecutor.java:313)
12-19 12:42:26.862 15627 15794 W System.err: 	at java.util.concurrent.ScheduledThreadPoolExecutor.schedule(ScheduledThreadPoolExecutor.java:533)
12-19 12:42:26.862 15627 15794 W System.err: 	at java.util.concurrent.ScheduledThreadPoolExecutor.submit(ScheduledThreadPoolExecutor.java:635)
12-19 12:42:26.862 15627 15794 W System.err: 	at rx.internal.schedulers.NewThreadWorker.scheduleActual(NewThreadWorker.java:246)
12-19 12:42:26.862 15627 15794 W System.err: 	at rx.internal.schedulers.CachedThreadScheduler$EventLoopWorker.schedule(CachedThreadScheduler.java:224)
12-19 12:42:26.862 15627 15794 W System.err: 	at rx.internal.schedulers.CachedThreadScheduler$EventLoopWorker.schedule(CachedThreadScheduler.java:214)
12-19 12:42:26.862 15627 15794 W System.err: 	at rx.internal.operators.SingleObserveOn$ObserveOnSingleSubscriber.onSuccess(SingleObserveOn.java:69)
12-19 12:42:26.862 15627 15794 W System.err: 	at rx.internal.util.ScalarSynchronousSingle$2$1.onSuccess(ScalarSynchronousSingle.java:140)
12-19 12:42:26.862 15627 15794 W System.err: 	at rx.internal.operators.SingleFromCallable.call(SingleFromCallable.java:48)
12-19 12:42:26.862 15627 15794 W System.err: 	at rx.internal.operators.SingleFromCallable.call(SingleFromCallable.java:29)
12-19 12:42:26.862 15627 15794 W System.err: 	at rx.Single.subscribe(Single.java:1979)
12-19 12:42:26.862 15627 15794 W System.err: 	at rx.internal.util.ScalarSynchronousSingle$2.call(ScalarSynchronousSingle.java:144)
12-19 12:42:26.862 15627 15794 W System.err: 	at rx.internal.util.ScalarSynchronousSingle$2.call(ScalarSynchronousSingle.java:124)
```

**Comment by JakeWharton** [comment]
Reproduced. This happens when a non-200 response is received by someone wanting only the body (e.g., `Observable<Foo>`) which is then sent to `onError` which then has to crash with an `OutOfMemoryError` (or any other fatal error). The fix is easy. Testing the fix... not so much.
