### ISSUE TITLE
 java.lang.NoClassDefFoundError: Failed resolution of: Lokhttp3/ws/WebSocketCall;

### ISSUE THREAD

**Issue by dj-4war** [square/retrofit#3032]
What kind of issue is this?

- We are using 2.5.0 retrofit and below are my gradle dependencies. 

   **implementation "com.squareup.retrofit2:converter-gson:$retrofit_version"
    implementation "com.squareup.retrofit2:retrofit:$retrofit_version"
    implementation "com.squareup.retrofit2:adapter-rxjava2:$retrofit_version"
     implementation 'org.webrtc:google-webrtc:1.0.24277'
    implementation('io.socket:socket.io-client:0.8.2') {
        exclude group: 'org.json', module: 'json'
    }**
  
Issue is when we try to build the project its claiming that 
 java.lang.NoClassDefFoundError: Failed resolution of: Lokhttp3/ws/WebSocketCall;

Seems OkHTTP3(okhttp-ws) is already been used by 2 libraries so we tried to add below excludes as per the discussions. 

configurations {
all*.exclude group: 'com.squareup.okhttp3', module: 'okhttp'
}

Once it is added it removed all the internal libraries of OkHttp and retro.

Then we tried to remove only for the retro project by adding 
implementation "com.squareup.retrofit2:retrofit:$retrofit_version"{
exclude group: 'com.squareup.okhttp3', module: 'okhttp'
}

Also tried : 
  configurations.all {
        // OkHttp 3.5.0+ includes the websockets API, so we need this to prevent a conflict
        exclude module: 'okhttp-ws'
    }

Getting same exception. 

Still the same issue, please help us to find solution  for this. 

Trace : 

java.lang.NoClassDefFoundError: Failed resolution of: Lokhttp3/ws/WebSocketCall;
        at io.socket.engineio.client.transports.WebSocket.doOpen(WebSocket.java:83)
        at io.socket.engineio.client.Transport$1.run(Transport.java:82)
        at io.socket.thread.EventThread.exec(EventThread.java:55)
        at io.socket.engineio.client.Transport.open(Transport.java:77)
        at io.socket.engineio.client.Socket.probe(Socket.java:472)
        at io.socket.engineio.client.Socket.onOpen(Socket.java:485)
        at io.socket.engineio.client.Socket.onHandshake(Socket.java:526)
        at io.socket.engineio.client.Socket.onPacket(Socket.java:499)
        at io.socket.engineio.client.Socket.access$1000(Socket.java:31)
        at io.socket.engineio.client.Socket$5.call(Socket.java:313)
        at io.socket.emitter.Emitter.emit(Emitter.java:117)
        at io.socket.engineio.client.Transport.onPacket(Transport.java:134)
        at io.socket.engineio.client.transports.Polling.access$700(Polling.java:17)
        at io.socket.engineio.client.transports.Polling$2.call(Polling.java:124)
        at io.socket.engineio.parser.Parser.decodePayload(Parser.java:251)
        at io.socket.engineio.client.transports.Polling._onData(Polling.java:134)
        at io.socket.engineio.client.transports.Polling.onData(Polling.java:106)
        at io.socket.engineio.client.transports.PollingXHR$5$1.run(PollingXHR.java:111)
        at io.socket.thread.EventThread$2.run(EventThread.java:80)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:762)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "okhttp3.ws.WebSocketCall" on path:

**Comment by JakeWharton** [comment]
The websocket API in newer versions of OkHttp is not binary compatible with the experimental API in older versions that lived in a separate artifact. Libraries depending on this API will need to be updated to use the built-in support (they shouldn't have shipped a dependency on an experimental API in the first place). So it looks like you'll have to request the io.socket library update to the public, stable websocket API.

**Comment by dj-4war** [comment]
> The websocket API in newer versions of OkHttp is not binary compatible with the experimental API in older versions that lived in a separate artifact. Libraries depending on this API will need to be updated to use the built-in support (they shouldn't have shipped a dependency on an experimental API in the first place). So it looks like you'll have to request the io.socket library update to the public, stable websocket API.

Used latest socket library (1.0.0) resolved the issue. Thanks Jake for the quick response and helping us to resolve the issue 👍
