### ISSUE TITLE
Retrofit not callback if HTTP status code is 500

### ISSUE THREAD

**Issue by onlymash** [square/retrofit#3036]
Device Android version: 9 (LineageOS 16.0)
```
fun create(): DanbooruApi {
            val logger = HttpLoggingInterceptor(HttpLoggingInterceptor.Logger { log ->
                Log.d("DanbooruApi", log)
            }).apply {
                level = HttpLoggingInterceptor.Level.BASIC
            }
            val interceptor = Interceptor { chain ->
                val requests =  chain.request().newBuilder()
                    .removeHeader(Constants.USER_AGENT_KEY)
                    .addHeader(Constants.USER_AGENT_KEY, UserAgent.get())
                    .build()
                chain.proceed(requests)
            }
            val client = OkHttpClient.Builder().apply {
                connectTimeout(10, TimeUnit.SECONDS)
                readTimeout(10, TimeUnit.SECONDS)
                writeTimeout(15, TimeUnit.SECONDS)
                    .addInterceptor(interceptor)
                    .addInterceptor(logger)
            }
                .build()
            return Retrofit.Builder()
                .baseUrl(BASE_URL)
                .client(client)
                .addConverterFactory(GsonConverterFactory.create())
                .build()
                .create(DanbooruApi::class.java)
        }

    @FormUrlEncoded
    @POST
    fun favPost(@Url url: String,
                @Field("post_id") id: Int,
                @Field("login") username: String,
                @Field("api_key") apiKey: String): Call<VoteDan>

    data class VoteDan(
        var success: Boolean = true,
        var message: String = "",
        var id: Int = -1,
        var score: Int = -1) 
```

```
override fun addDanFav(vote: Vote) {
        danbooruApi.favPost(
            url = ApiUrlHelper.getDanAddFavUrl(vote),
            id = vote.post_id,
            username = vote.username,
            apiKey = vote.auth_key
        ).enqueue(object : Callback<VoteDan> {
            override fun onFailure(call: Call<VoteDan>, t: Throwable) {
                if (t is HttpException) {
                    val data = t.response().body()
                    if (t.code() == 500 && data is VoteDan){
                        onFailed(data.message)
                    } else {
                        onFailed(t.message())
                    }
                } else {
                    onFailed(t.message.toString())
                }
            }
            override fun onResponse(call: Call<VoteDan>, response: Response<VoteDan>) {
                val data = response.body()
                when (response.code()) {
                    200, 201 -> {
                        Log.w(TAG, data.toString())
                        onSuccess()
                    }
                    500 -> {
                        if (data != null) {
                            onFailed(data.message)
                        } else {
                            onFailed(response.message())
                        }
                    }
                    else -> {
                        onFailed(response.message())
                    }
                }
            }
        })
    }
   override fun onFailed(msg: String) {
        Log.e(TAG, msg)
    }
```

when status code is 500 and HttpLoggingInterceptor.Level.BASIC
not any callback output
```
D/DanbooruApi: --> POST https://danbooru.donmai.us/favorites.json (63-byte body)
D/DanbooruApi: <-- 500 https://danbooru.donmai.us/favorites.json (556ms, unknown-length body)
V/FA: Inactivity, disconnecting from the service
D/DanbooruApi: --> POST https://danbooru.donmai.us/favorites.json (63-byte body)
D/DanbooruApi: <-- 500 https://danbooru.donmai.us/favorites.json (557ms, unknown-length body)
V/FA: Recording user engagement, ms: 182624
```
when status code is 201
callback is normal 
```
D/DanbooruApi: --> POST https://danbooru.donmai.us/favorites.json (63-byte body)
D/DanbooruApi: <-- 201 https://danbooru.donmai.us/favorites.json (559ms, unknown-length body)
W/VoteData: VoteDan(success=true, message=, id=3424391, score=42)
```
then change http loger level to HttpLoggingInterceptor.Level.BODY
when status code is 500 
```
D/DanbooruApi: <-- 500 https://danbooru.donmai.us/favorites.json (1035ms)
D/DanbooruApi: date: Fri, 22 Feb 2019 15:29:56 GMT
D/DanbooruApi: content-type: application/json; charset=utf-8
D/DanbooruApi: set-cookie: __cfduid=daf76ec0xxxxxxxxx
D/DanbooruApi: x-frame-options: SAMEORIGIN
D/DanbooruApi: x-xss-protection: 1; mode=block
D/DanbooruApi: x-content-type-options: nosniff
D/DanbooruApi: x-download-options: noopen
D/DanbooruApi: x-permitted-cross-domain-policies: none
D/DanbooruApi: referrer-policy: strict-origin-when-cross-origin
D/DanbooruApi: access-control-allow-origin: *
D/DanbooruApi: cache-control: no-cache
D/DanbooruApi: x-request-id: 2d8618acxxxxxxx
D/DanbooruApi: x-runtime: 0.013841
D/DanbooruApi: strict-transport-security: max-age=31556952; preload
D/DanbooruApi: expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
D/DanbooruApi: server: cloudflare
D/DanbooruApi: cf-ray: 4ad27db7cda139b8-PHX
D/DanbooruApi:   {
        "success": false,
        "message": "You have already favorited this post",
        "backtrace": ["app/models/favorite.rb:15:in `block in add'","app/models/favorite.rb:9:in `add'","app/models/post.rb:969:in `add_favorite!'","app/controllers/favorites_controller.rb:28:in `create'"]
      }
D/DanbooruApi: <-- END HTTP (287-byte body)
```

**Comment by JiongBull** [comment]
![image](https://user-images.githubusercontent.com/4413502/61355325-b36fd900-a8a6-11e9-8aa5-7e19edde895a.png)

Android 4.4.2
Retrofit 2.5.0 does not throw HttpException with 500 code.

**Comment by onlymash** [comment]
I no longer use enqueue
