### ISSUE TITLE
java.lang.NoClassDefFoundError: java.util.Objects

### ISSUE THREAD

**Issue by miladheydari** [square/retrofit#3042]
this error throw when using retrofit version 2.5.0 in android lower than api 19

`java.lang.NoClassDefFoundError: java.util.Objects
at okhttp3.CertificatePinner.withCertificateChainCleaner(CertificatePinner.java:231)
at okhttp3.OkHttpClient.<init>(OkHttpClient.java:271)
at okhttp3.OkHttpClient$Builder.build(OkHttpClient.java:1054)`

**Comment by JakeWharton** [comment]
This is a problem with [OkHttp](https://github.com/square/okhttp), not Retrofit. Note OkHttp 3.13+ requires API 21+ but if you're using 3.12 or earlier please file a bug.

**Comment by miladheydari** [comment]
ok, when retrofit depend on okhttp how to fix it for api level lower than 19?

**Comment by JakeWharton** [comment]
Retrofit doesn't require nor depend on 3.13 so it isn't forcing minSdk 21

**Comment by sunil91** [comment]
E/AndroidRuntime: FATAL EXCEPTION: main
    java.lang.NoClassDefFoundError: java.util.Objects
        at okhttp3.CertificatePinner.withCertificateChainCleaner(CertificatePinner.java:231)
        at okhttp3.OkHttpClient.<init>(OkHttpClient.java:238)
        at okhttp3.OkHttpClient.<init>(OkHttpClient.java:202)

**Comment by sunil91** [comment]
E/AndroidRuntime: FATAL EXCEPTION: main
    java.lang.NoClassDefFoundError: java.util.Objects
        at okhttp3.CertificatePinner.withCertificateChainCleaner(CertificatePinner.java:231)
        at okhttp3.OkHttpClient.<init>(OkHttpClient.java:238)
        at okhttp3.OkHttpClient.<init>(OkHttpClient.java:202) 

@JakeWharton

**Comment by tadell** [comment]
> ok, when retrofit depend on okhttp how to fix it for api level lower than 19?
> @JakeWharton

is your problem solved?
i have the same problem just in release apk and my okhhtp version is lower than 3.12.

**Comment by berkedel** [comment]
From Retrofit's [changelog](https://github.com/square/retrofit/blob/master/CHANGELOG.md), from Retrofit 2.7.0 depends on OkHttp 3.14.4 that changes minimum requirements to Android 5 or later.

To support min SDK version 16, use Retrofit 2.6.4 and make sure OkHttp version 3.12.x (see [this](https://developer.squareup.com/blog/okhttp-3-13-requires-android-5/))
