### ISSUE TITLE
Non-SDK methods used 

### ISSUE THREAD

**Issue by anjani0401** [square/retrofit#3053]
Hello,
Is there any plans of fixing this issue in latest release for using hidden methods for sdk version 28.

Accessing hidden method Ldalvik/system/CloseGuard;->get()Ldalvik/system/CloseGuard; (light greylist, reflection)
 D/StrictMode: StrictMode policy violation: android.os.strictmode.NonSdkApiUsedViolation: Ldalvik/system/CloseGuard;->get()Ldalvik/system/CloseGuard;
at android.os.StrictMode.lambda$static$1(StrictMode.java:428)
at android.os.-$$Lambda$StrictMode$lu9ekkHJ2HMz0jd3F8K8MnhenxQ.accept(Unknown Source:2)
at java.lang.Class.getDeclaredMethodInternal(Native Method)
at java.lang.Class.getPublicMethodRecursive(Class.java:2075)
at java.lang.Class.getMethod(Class.java:2063)
at java.lang.Class.getMethod(Class.java:1690)
at okhttp3.internal.platform.AndroidPlatform$CloseGuard.get(AndroidPlatform.java:368)
at okhttp3.internal.platform.AndroidPlatform.<init>(AndroidPlatform.java:56)
at okhttp3.internal.platform.AndroidPlatform.buildIfSupported(AndroidPlatform.java:258)
at okhttp3.internal.platform.Platform.findPlatform(Platform.java:199)
at okhttp3.internal.platform.Platform.<clinit>(Platform.java:78)
at okhttp3.internal.platform.Platform.get(Platform.java:84)
at okhttp3.OkHttpClient.systemDefaultSslSocketFactory(OkHttpClient.java:300)
at okhttp3.OkHttpClient.<init>(OkHttpClient.java:255)
at okhttp3.OkHttpClient.<init>(OkHttpClient.java:228)
at elika.version2.webServices.apiCalls.ApiClient.getRequestHeader(ApiClient.java:126)
at elika.version2.webServices.apiCalls.ApiClient.apiCall(ApiClient.java:47)
at elika.version2.webServices.api_callback.AppVersionDetailsCallback.callApi(AppVersionDetailsCallback.java:39)
at elika.version2.manager.MyApplication$2.run(MyApplication.java:297)
at android.os.Handler.handleCallback(Handler.java:874)
at android.os.Handler.dispatchMessage(Handler.java:100)
at android.os.Looper.loop(Looper.java:198)
at android.app.ActivityThread.main(ActivityThread.java:6729)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

 Accessing hidden method Ldalvik/system/CloseGuard;->open(Ljava/lang/String;)V (light greylist, reflection)
D/StrictMode: StrictMode policy violation: android.os.strictmode.NonSdkApiUsedViolation: Ldalvik/system/CloseGuard;->open(Ljava/lang/String;)V
at android.os.StrictMode.lambda$static$1(StrictMode.java:428)
at android.os.-$$Lambda$StrictMode$lu9ekkHJ2HMz0jd3F8K8MnhenxQ.accept(Unknown Source:2)
at java.lang.Class.getDeclaredMethodInternal(Native Method)
at java.lang.Class.getPublicMethodRecursive(Class.java:2075)
at java.lang.Class.getMethod(Class.java:2063)
at java.lang.Class.getMethod(Class.java:1690)
at okhttp3.internal.platform.AndroidPlatform$CloseGuard.get(AndroidPlatform.java:369)
at okhttp3.internal.platform.AndroidPlatform.<init>(AndroidPlatform.java:56)
at okhttp3.internal.platform.AndroidPlatform.buildIfSupported(AndroidPlatform.java:258)
at okhttp3.internal.platform.Platform.findPlatform(Platform.java:199)
at okhttp3.internal.platform.Platform.<clinit>(Platform.java:78)
at okhttp3.internal.platform.Platform.get(Platform.java:84)
at okhttp3.OkHttpClient.systemDefaultSslSocketFactory(OkHttpClient.java:300)
at okhttp3.OkHttpClient.<init>(OkHttpClient.java:255)
at okhttp3.OkHttpClient.<init>(OkHttpClient.java:228)
at elika.version2.webServices.apiCalls.ApiClient.getRequestHeader(ApiClient.java:126)
at elika.version2.webServices.apiCalls.ApiClient.apiCall(ApiClient.java:47)
at elika.version2.webServices.api_callback.AppVersionDetailsCallback.callApi(AppVersionDetailsCallback.java:39)
at elika.version2.manager.MyApplication$2.run(MyApplication.java:297)
at android.os.Handler.handleCallback(Handler.java:874)
at android.os.Handler.dispatchMessage(Handler.java:100)
at android.os.Looper.loop(Looper.java:198)
at android.app.ActivityThread.main(ActivityThread.java:6729)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

 W/elika.version2: Accessing hidden method Ldalvik/system/CloseGuard;->warnIfOpen()V (light greylist, reflection)
 D/StrictMode: StrictMode policy violation: android.os.strictmode.NonSdkApiUsedViolation: Ldalvik/system/CloseGuard;->warnIfOpen()V
at android.os.StrictMode.lambda$static$1(StrictMode.java:428)
at android.os.-$$Lambda$StrictMode$lu9ekkHJ2HMz0jd3F8K8MnhenxQ.accept(Unknown Source:2)
at java.lang.Class.getDeclaredMethodInternal(Native Method)
at java.lang.Class.getPublicMethodRecursive(Class.java:2075)
at java.lang.Class.getMethod(Class.java:2063)
at java.lang.Class.getMethod(Class.java:1690)
at okhttp3.internal.platform.AndroidPlatform$CloseGuard.get(AndroidPlatform.java:370)
at okhttp3.internal.platform.AndroidPlatform.<init>(AndroidPlatform.java:56)
at okhttp3.internal.platform.AndroidPlatform.buildIfSupported(AndroidPlatform.java:258)
at okhttp3.internal.platform.Platform.findPlatform(Platform.java:199)
at okhttp3.internal.platform.Platform.<clinit>(Platform.java:78)
at okhttp3.internal.platform.Platform.get(Platform.java:84)
at okhttp3.OkHttpClient.systemDefaultSslSocketFactory(OkHttpClient.java:300)
at okhttp3.OkHttpClient.<init>(OkHttpClient.java:255)
at okhttp3.OkHttpClient.<init>(OkHttpClient.java:228)
at elika.version2.webServices.apiCalls.ApiClient.getRequestHeader(ApiClient.java:126)
at elika.version2.webServices.apiCalls.ApiClient.apiCall(ApiClient.java:47)
at elika.version2.webServices.api_callback.AppVersionDetailsCallback.callApi(AppVersionDetailsCallback.java:39)
at elika.version2.manager.MyApplication$2.run(MyApplication.java:297)
at android.os.Handler.handleCallback(Handler.java:874)
at android.os.Handler.dispatchMessage(Handler.java:100)
at android.os.Looper.loop(Looper.java:198)
at android.app.ActivityThread.main(ActivityThread.java:6729)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
2019-03-19 15:25:56.984 13060-13060/elika.version2 W/ActivityThread: handleWindowVisibility: no activity for token android.os.BinderProxy@b7c1ad4

**Comment by JakeWharton** [comment]
Those all come from OkHttp, not Retrofit.
