### ISSUE TITLE
Invalid Malformed URL

### ISSUE THREAD

**Issue by nathancassano** [square/retrofit#3080]
The path of a URL contains a colon symbol which is causing the call to fail.

Using version com.squareup.retrofit2:retrofit:2.5.0

Code:
```
public interface ClientApi {
    @PUT("user:email={email}/login")
    Call<ResponseBody> login(@Path("email") String email, @Body String pass);

    @PUT("./user:email={email}/login")
    Call<ResponseBody> loginRelative(@Path("email") String email, @Body String pass);
...
```

**Regular path**
Stack trace:
```
Caused by: java.lang.IllegalArgumentException: Malformed URL. Base: https://test.com/restapi/, Relative: user:email=me@test.com/login
        at retrofit2.RequestBuilder.get(RequestBuilder.java:221)
        at retrofit2.RequestFactory.create(RequestFactory.java:111)
        at retrofit2.OkHttpCall.createRawCall(OkHttpCall.java:190)
        at retrofit2.OkHttpCall.execute(OkHttpCall.java:173)
        at Service.login(Service.java:38)
```
Think the code needs to treat the relative portion of the URL like an absolute URL when parsing.

**Relative path**
Using a retaliative path  annotation `./` does not solve this issue.
Stack trace:
```
Caused by: java.lang.IllegalArgumentException: @Path parameters shouldn't perform path traversal ('.' or '..'):
        at retrofit2.RequestBuilder.addPathParam(RequestBuilder.java:113)
        at retrofit2.ParameterHandler$Path.apply(ParameterHandler.java:99)
        at retrofit2.RequestFactory.create(RequestFactory.java:108)
        at retrofit2.OkHttpCall.createRawCall(OkHttpCall.java:190)
        at retrofit2.OkHttpCall.execute(OkHttpCall.java:173)
```

Bug report unit test
https://gist.github.com/nathancassano/f675e2fd1c64d4b6002afea37bf5fee4

**Comment by JakeWharton** [comment]
Yeah this should be allowed.

cc @swankjesse

**Comment by sangeetha5491** [comment]
can I work on this issue?

**Comment by swankjesse** [comment]
No, we need to study to learn what the correct behavior is.

**Comment by thezukkino** [comment]
Is there any news about this issue? This problem causes a version lock to 2.4.0.

**Comment by AhmedMourad0** [comment]
When can we expect this? any workarounds? snapshot?

**Comment by bio007** [comment]
Hi, any update on this?

**Comment by roshanrajaratnam** [comment]
Hi any update on this? colon in a path variable seem to be encoded as `%253A` instead of just `%3A`.

**Comment by yagyank** [comment]
Hey can I pick this issue?

**Comment by guyferguson** [comment]
Still an isue....

**Comment by sagar392** [comment]
Is this issue closed because I am unable to see the following code in search

**Comment by guyferguson** [comment]
I am using the latest retrofit version and this issue persists.   Can you specify the specific Interface you say does not exist, or would it be better for me to find teh line in retrofit that generates the error msg?

**Comment by richardbn** [comment]
Still an isue....

**Comment by DawnNguyenAhiho** [comment]
Hi, any update here. The URL with only the `:stuff` can be workaround with `./` but if url has Path like `{foo}:bar` will completely broken

**Comment by roshanrajaratnam** [comment]
literally 5 years later and people are facing the same issue...

**Comment by tompson** [comment]
still a Problem in 2025 and preventing projects from upgrading to versions after 2.4.0

**Comment by roshanrajaratnam** [comment]
@JakeWharton @swankjesse any updates on this?

**Comment by abdellahi-brahim** [comment]
Any workarround for this? Do we need to use @Url ?

**Comment by abdellahi-brahim** [comment]
2026 reminder :(

**Comment by abdellahi-brahim** [comment]
Hi all, here is a suggested fix for this issue, I left some open questions in the comment, please let me know what do you think:

- https://github.com/lysine-dev/retrofit/pull/4623
