### ISSUE TITLE
JsonSyntaxException in NullOnEmptyConverterFactory of Retrofit

### ISSUE THREAD

**Issue by Ali-Rezaei** [square/retrofit#3084]
I receive following exception when I build the app :

```
[2019-04-19 20:09:17.137 29835-29835/com.sample.android.superhero E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.sample.android.superhero, PID: 29835
    com.google.gson.JsonSyntaxException: java.lang.NumberFormatException: For input string: "null"
        at com.google.gson.internal.bind.TypeAdapters$7.read(TypeAdapters.java:228)
        at com.google.gson.internal.bind.TypeAdapters$7.read(TypeAdapters.java:218)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222)
        at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41)
        at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:82)
        at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:61)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222)
        at retrofit2.converter.gson.GsonResponseBodyConverter.convert(GsonResponseBodyConverter.java:39)
        at retrofit2.converter.gson.GsonResponseBodyConverter.convert(GsonResponseBodyConverter.java:27)
        at com.sample.android.superhero.util.NullOnEmptyConverterFactory$1.convert(NullOnEmptyConverterFactory.java:21)
        at com.sample.android.superhero.util.NullOnEmptyConverterFactory$1.convert(NullOnEmptyConverterFactory.java:17)
        at retrofit2.OkHttpCall.parseResponse(OkHttpCall.java:223)
        at retrofit2.OkHttpCall$1.onResponse(OkHttpCall.java:121)
        at okhttp3.RealCall$AsyncCall.execute(RealCall.java:206)
        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: java.lang.NumberFormatException: For input string: "null"
        at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2043)
        at sun.misc.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
        at java.lang.Double.parseDouble(Double.java:539)
        at com.google.gson.stream.JsonReader.nextInt(JsonReader.java:1201)
        at com.google.gson.internal.bind.TypeAdapters$7.read(TypeAdapters.java:226)
        at com.google.gson.internal.bind.TypeAdapters$7.read(TypeAdapters.java:218) 
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131) 
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222) 
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131) 
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222) 
        at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41) 
        at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:82) 
        at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:61) 
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131) 
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222) 
        at retrofit2.converter.gson.GsonResponseBodyConverter.convert(GsonResponseBodyConverter.java:39) 
        at retrofit2.converter.gson.GsonResponseBodyConverter.convert(GsonResponseBodyConverter.java:27) 
        at com.sample.android.superhero.util.NullOnEmptyConverterFactory$1.convert(NullOnEmptyConverterFactory.java:21) 
        at com.sample.android.superhero.util.NullOnEmptyConverterFactory$1.convert(NullOnEmptyConverterFactory.java:17) 
        at retrofit2.OkHttpCall.parseResponse(OkHttpCall.java:223) 
        at retrofit2.OkHttpCall$1.onResponse(OkHttpCall.java:121) 
        at okhttp3.RealCall$AsyncCall.execute(RealCall.java:206) 
        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636) 
        at java.lang.Thread.run(Thread.java:764)](url)
```

And this is [NullOnEmptyConverterFactory](https://github.com/square/retrofit/issues/1554) class:

```
public class NullOnEmptyConverterFactory extends Converter.Factory {

    @Override
    public Converter<ResponseBody, ?> responseBodyConverter(Type type, Annotation[] annotations, Retrofit retrofit) {
        final Converter<ResponseBody, ?> delegate = retrofit.nextResponseBodyConverter(this, type, annotations);
        return new Converter<ResponseBody, Object>() {
            @Override
            public Object convert(@NotNull ResponseBody body) throws IOException {
                if (body.contentLength() == 0) return null;
                return delegate.convert(body);
            }
        };
    }
}
```
Which is used in Retrofit :
```
Retrofit.Builder()
            .baseUrl(BuildConfig.SUPER_HERO_BASE_URL)
            .client(okHttpClient)
            .addConverterFactory(NullOnEmptyConverterFactory())
            .addConverterFactory(GsonConverterFactory.create())
            .addCallAdapterFactory(CoroutineCallAdapterFactory())
            .build()
```
I have 2 versions of the app :

1 - Just support online which works as expected : https://github.com/Ali-Rezaei/SuperHero-Coroutines
```
fun showHeroes(query: String) {
        uiScope.launch {
            _dataLoading.value = true
            getHeroes(query)
        }
    }

    private suspend fun getHeroes(query: String) {
        withContext(Dispatchers.IO) {
                val response = api.searchHero(query).await()
                if (response.isSuccessful && response.body()?.response == "success") {
                    _isLoadingError.postValue(false)
                    with(heroes) {
                        clear()
                        response.body()?.let { addAll(it.wrapper) }
                    }
                    _dataLoading.postValue(false)
                } else {
                    _isLoadingError.postValue(true)
                    _dataLoading.postValue(false)
                    _errorMsg.postValue(response.body()?.error)
                }
         }
}
```
2 - offline support which receive Exception that I pasted when I search in app : https://github.com/Ali-Rezaei/SuperHero-Coroutines/tree/offline_support
```
override suspend fun getHeroes(query: String): Result<List<Hero>> = withContext(Dispatchers.IO) {
        try {
            val response = api.searchHero(query).await()
            if (response.isSuccessful && response.body()?.response == "success") {
                Result.Success(response.body()?.wrapper!!)
            } else {
                Result.Error(DataSourceException(response.body()?.error))
            }
        } catch (e: ConnectException) {
            Result.Error(DataSourceException(e.message ?: "unknown error"))
        } catch (e: SocketTimeoutException) {
            Result.Error(
                DataSourceException(context.getString(R.string.no_internet_connection))
            )
        } catch (e: IOException) {
            Result.Error(DataSourceException(e.message ?: "unknown error"))
        } catch (e : Exception) {
        Result.Error(DataSourceException(e.message ?: "unknown error")
    }
```

**Comment by JakeWharton** [comment]
This is not a problem with Retrofit or the converter. Your JSON contains the value "null" for a property that you are trying to bind as an `int` with Gson. You'll need to change to `Integer` (or `Int?` for Kotlin) so that null is allowed.
