### ISSUE TITLE
Error: Multipart: Boundary not found

### ISSUE THREAD

**Issue by rajeshdeva23** [square/retrofit#3097]
I am using upload image using multipart . when i am uploading in backend server returning some error. that error i mentioned below

: Error: Multipart: Boundary not found
   at new Multipart (/usr/share/nginx/html/winbid/node_modules/busboy/lib/types/multipart.js:58:11)
   at Multipart (/usr/share/nginx/html/winbid/node_modules/busboy/lib/types/multipart.js:26:12)
   at Busboy.parseHeaders (/usr/share/nginx/html/winbid/node_modules/busboy/lib/main.js:71:22)
   at new Busboy (/usr/share/nginx/html/winbid/node_modules/busboy/lib/main.js:22:10)
   at /usr/share/nginx/html/winbid/node_modules/multer/index.js:54:20
   at Layer.handle [as handle_request] (/usr/share/nginx/html/winbid/node_modules/express/lib/router/layer.js:95:5)
   at trim_prefix (/usr/share/nginx/html/winbid/node_modules/express/lib/router/index.js:317:13)
   at /usr/share/nginx/html/winbid/node_modules/express/lib/router/index.js:284:7
   at Function.process_params (/usr/share/nginx/html/winbid/node_modules/express/lib/router/index.js:335:12)
   at next (/usr/share/nginx/html/winbid/node_modules/express/lib/router/index.js:275:10)

but i was try postman it working fine and also working in fine in shift.
Anybody give me solution for this. thankyou

**Comment by JakeWharton** [comment]
Please provide a failing test case or sample that demonstrates the problem
