### ISSUE TITLE
java.lang.IllegalArgumentException: No Retrofit annotation found. (parameter #1) suspend function

### ISSUE THREAD

**Issue by SSVerma1916** [square/retrofit#3115]
java.lang.IllegalArgumentException: No Retrofit annotation found. (parameter #1)
2019-06-05 17:19:11.659 11502-11502/com.ssverma.alphatest W/System.err:     for method ApiEndpoints.someRequest
2019-06-05 17:19:11.659 11502-11502/com.ssverma.alphatest W/System.err:     at retrofit2.Utils.methodError(Utils.java:52)
2019-06-05 17:19:11.659 11502-11502/com.ssverma.alphatest W/System.err:     at retrofit2.Utils.methodError(Utils.java:42)
2019-06-05 17:19:11.659 11502-11502/com.ssverma.alphatest W/System.err:     at retrofit2.Utils.parameterError(Utils.java:61)
2019-06-05 17:19:11.660 11502-11502/com.ssverma.alphatest W/System.err:     at retrofit2.RequestFactory$Builder.parseParameter(RequestFactory.java:311)
2019-06-05 17:19:11.660 11502-11502/com.ssverma.alphatest W/System.err:     at retrofit2.RequestFactory$Builder.build(RequestFactory.java:182)
2019-06-05 17:19:11.660 11502-11502/com.ssverma.alphatest W/System.err:     at retrofit2.RequestFactory.parseAnnotations(RequestFactory.java:65)
2019-06-05 17:19:11.660 11502-11502/com.ssverma.alphatest W/System.err:     at retrofit2.ServiceMethod.parseAnnotations(ServiceMethod.java:25)
2019-06-05 17:19:11.660 11502-11502/com.ssverma.alphatest W/System.err:     at retrofit2.Retrofit.loadServiceMethod(Retrofit.java:168)
2019-06-05 17:19:11.660 11502-11502/com.ssverma.alphatest W/System.err:     at retrofit2.Retrofit$1.invoke(Retrofit.java:147)
2019-06-05 17:19:11.660 11502-11502/com.ssverma.alphatest W/System.err:     at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
2019-06-05 17:19:11.660 11502-11502/com.ssverma.alphatest W/System.err:     at $Proxy1.someRequest(Unknown Source)

**Comment by SSVerma1916** [comment]
@GET("https://demo5571300.mockable.io/someEndpoint")
    suspend fun someRequest(): Deferred<Response<SomeModel>>

**Comment by NikolaDespotoski** [comment]
Ensure you have removed `CoroutineCallAdapterFactory()` as it has been stated [in the migration tip here](https://github.com/JakeWharton/SdkSearch/pull/170/files#diff-4bcb6d931489d751b736c53a038cbdfe)

**Comment by luis-cortes** [comment]
@SSVerma1916 Are you sure you're using v2.6.0?

**Comment by MohamedMedhat1998** [comment]
> @SSVerma1916 Are you sure you're using v2.6.0?

Thanks a lot, that was my problem. I was using v2.5.0.
