### ISSUE TITLE
 Unable to create @Body

### ISSUE THREAD

**Issue by NicolasLeveque** [square/retrofit#3157]
Hello,
I try to use Moshi with Retrofit, I used Yelp to generate calls and objects (https://github.com/Yelp/swagger-gradle-codegen)

I receive an error : 
`Unable to create @Body converter for class ObjectRequest (parameter #1)`

```
@POST("/xxxxxxx")
fun call(@Body object: ObjectRequest): Single<ObjectResponse>
```

```
class ObjectRequest {
    @Json(name = "field")
    var field: String? = null
}
```
``` 1st try
Retrofit.Builder()
            .baseUrl("xxxxxxxxxxxxxx")
            .addConverterFactory(MoshiConverterFactory.create())
            .addCallAdapterFactory(RxJava2CallAdapterFactory.create())
            .client(okHttpClient)
            .build()
            .create(xxxxxx::class.java)
```
``` 2nd try
    val moshi = Moshi.Builder()
            .add(XNullableAdapterFactory())
            .add(KotlinJsonAdapterFactory())
            .add(TypesAdapterFactory())
            .build()

Retrofit.Builder()
            .baseUrl("xxxxxxxxxxxxxx")
            .addConverterFactory(MoshiConverterFactory.create(moshi))
            .addCallAdapterFactory(RxJava2CallAdapterFactory.create())
            .client(okHttpClient)
            .build()
            .create(xxxxxx::class.java)
```

**Comment by JakeWharton** [comment]
Please provide the full stack trace

**Comment by NicolasLeveque** [comment]
Apparently there are no adapter for ArrayList, is it normal ?

```
2019-07-10 14:44:59.346 22969-23435/ E/AndroidRuntime: FATAL EXCEPTION: Thread-37
    Process:  PID: 22969
    java.lang.IllegalArgumentException: Unable to create @Body converter for class XXXXXRequest (parameter #1)
        for method XXXXXX
        at retrofit2.Utils.methodError(Utils.java:52)
        at retrofit2.Utils.parameterError(Utils.java:57)
        at retrofit2.RequestFactory$Builder.parseParameterAnnotation(RequestFactory.java:735)
        at retrofit2.RequestFactory$Builder.parseParameter(RequestFactory.java:306)
        at retrofit2.RequestFactory$Builder.build(RequestFactory.java:193)
        at retrofit2.RequestFactory.parseAnnotations(RequestFactory.java:67)
        at retrofit2.ServiceMethod.parseAnnotations(ServiceMethod.java:26)
        at retrofit2.Retrofit.loadServiceMethod(Retrofit.java:170)
        at retrofit2.Retrofit$1.invoke(Retrofit.java:149)
        at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
     Caused by: java.lang.IllegalArgumentException: Platform java.util.ArrayList<XXXXXXRequest> (with no annotations) requires explicit JsonAdapter to be registered
    for java.util.ArrayList<XXXXXXRequest<
    for class XXXXXXRequest
        at com.squareup.moshi.Moshi$LookupChain.exceptionWithLookupStack(Moshi.java:348)
        at com.squareup.moshi.Moshi.adapter(Moshi.java:149)
        at com.squareup.moshi.kotlin.reflect.KotlinJsonAdapterFactory.create(KotlinJsonAdapter.kt:241)
        at com.squareup.moshi.Moshi.adapter(Moshi.java:137)
        at com.squareup.moshi.Moshi.adapter(Moshi.java:97)
        at retrofit2.converter.moshi.MoshiConverterFactory.requestBodyConverter(MoshiConverterFactory.java:106)
        at retrofit2.Retrofit.nextRequestBodyConverter(Retrofit.java:282)
        at retrofit2.Retrofit.requestBodyConverter(Retrofit.java:262)
        at retrofit2.RequestFactory$Builder.parseParameterAnnotation(RequestFactory.java:732)
        	... 16 more
     Caused by: java.lang.IllegalArgumentException: Platform java.util.ArrayList<XXXXXRequest> (with no annotations) requires explicit JsonAdapter to be registered
        at com.squareup.moshi.ClassJsonAdapter$1.create(ClassJsonAdapter.java:60)
        at com.squareup.moshi.Moshi.adapter(Moshi.java:137)
        	... 24 more
```

**Comment by JakeWharton** [comment]
Yes. Moshi does not serialize platform types by default. Change it to the interface `List` or register an adapter for `ArrayList` with Moshi.

**Comment by NicolasLeveque** [comment]
I don't understand, I use Moshi and Yelp, and Yelp generated my objects with ArrayList from a swagger, Why ? if Moshi does not handle ArrayList ..

**Comment by JakeWharton** [comment]
Sounds like a bug in the code generator tool then. When using Moshi, it should be using List, not ArrayList. I would file a bug on that project. It doesn't make sense for them to be using ArrayList.

**Comment by cortinico** [comment]
Hey @NicolasLeveque 

Agree with @JakeWharton, looks like a bug on our end. Can you please open a Issue on our tracker here: https://github.com/Yelp/swagger-gradle-codegen/issues and attach the Swagger file you used.

The generator uses `List` (and not `ArrayList`) to represent Swagger arrays, so you might have found a bug somewhere.

**Comment by NicolasLeveque** [comment]
My bad, i have auto-formatted some classes with ArrayList instead of List,
it works
