### ISSUE TITLE
App is crashing when Image file is having special characters in file name

### ISSUE THREAD

**Issue by SanjayKushwah0601** [square/retrofit#3223]
Unable to upload multipart image file which is having chinese file name. And it is mandatory to send file name as it is.  

**`val body = MultipartBody.Part.createFormData("image", "電子郵件.jpeg", reqFile)`**

```
Process: com.meural.Meural, PID: 23387
    java.lang.IllegalArgumentException: Unexpected char 0x671d at 35 in Content-Disposition value: form-data; name="image"; filename="朝圣者网络.jpeg"
        at okhttp3.Headers.checkValue(Headers.java:272)
        at okhttp3.Headers.of(Headers.java:224)
        at okhttp3.MultipartBody$Part.createFormData(MultipartBody.java:259)
        at com.meural.meural.service.ImageUploadJobIntentService.uploadImage(ImageUploadJobIntentService.kt:155)
        at com.meural.meural.service.ImageUploadJobIntentService$uploadAll$$inlined$forEach$lambda$1.invokeSuspend(ImageUploadJobIntentService.kt:69)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:233)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:742)
```

@JakeWharton Could you please provide its solution so that i can upload images having chinese file name.

**Comment by SanjayKushwah0601** [comment]
I have found work around for this see my answer on 
[Stackoverflow ](https://stackoverflow.com/a/58247404/6481933)
