### ISSUE TITLE
Unable to invoke no-args constructor for retrofit2.Call

### ISSUE THREAD

**Issue by zy888802** [square/retrofit#3226]
**Version ： retrofit 2.6.2 
Json: GsonConverterFactory**

**When I use Call.awaitResponse() Call.await() hava error
but I use Call.enqueue()  Call.execute() no problem**

```
java.lang.RuntimeException: Unable to invoke no-args constructor for retrofit2.Call. Registering an InstanceCreator with Gson for this type may fix this problem.
        at com.google.gson.internal.ConstructorConstructor$14.construct(ConstructorConstructor.java:228)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:212)
        at retrofit2.converter.gson.GsonResponseBodyConverter.convert(GsonResponseBodyConverter.java:39)
        at retrofit2.converter.gson.GsonResponseBodyConverter.convert(GsonResponseBodyConverter.java:27)
        at retrofit2.OkHttpCall.parseResponse(OkHttpCall.java:225)
        at retrofit2.OkHttpCall$1.onResponse(OkHttpCall.java:121)
        at okhttp3.RealCall$AsyncCall.run(RealCall.kt:138)
        at java.util.concurrent.ThreadPoolExecutor.processTask(ThreadPoolExecutor.java:1187)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:784)
 Caused by: java.lang.UnsupportedOperationException: Interface can't be instantiated! Interface name: retrofit2.Call
        at com.google.gson.internal.UnsafeAllocator.assertInstantiable(UnsafeAllocator.java:117)
        at com.google.gson.internal.UnsafeAllocator$1.newInstance(UnsafeAllocator.java:49)
        at com.google.gson.internal.ConstructorConstructor$14.construct(ConstructorConstructor.java:225)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:212) 
        at retrofit2.converter.gson.GsonResponseBodyConverter.convert(GsonResponseBodyConverter.java:39) 
        at retrofit2.converter.gson.GsonResponseBodyConverter.convert(GsonResponseBodyConverter.java:27) 
        at retrofit2.OkHttpCall.parseResponse(OkHttpCall.java:225) 
        at retrofit2.OkHttpCall$1.onResponse(OkHttpCall.java:121) 
        at okhttp3.RealCall$AsyncCall.run(RealCall.kt:138) 
        at java.util.concurrent.ThreadPoolExecutor.processTask(ThreadPoolExecutor.java:1187) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:784) 

```

**Comment by JakeWharton** [comment]
Please provide a complete failing test case or reproducing sample. Seems like you're doing something like `Call<Call<..>>` or `suspend fun(..): Call<..>`.

**Comment by zy888802** [comment]
`suspend fun(..): Call<..>`
I delete suspend to solve the problem
Thank you very much！

**Comment by chuwuwang** [comment]
> `suspend fun(..): Call<..>`
> I delete suspend to solve the problem
> Thank you very much！

Thank you

**Comment by isunaslabs** [comment]
> `suspend fun(..): Call<..>`
> I delete suspend to solve the problem
> Thank you very much！

Thank you sooooooo much

**Comment by Ronnie-Bain** [comment]
> `suspend fun(..): Call<..>`
> I delete suspend to solve the problem
> Thank you very much！

Not sure if it's ideal? I mean it might freeze UI. 
Don't you wanna push the data fetching to the background?

**Comment by ar5-rehman** [comment]
Hello @Ronnie-Bain,

To make your UI works freely from your API calls, do not remove suspend keyword(it's good that your api's works in the background asynchronous mode), solution for the above problem is to use retrofit2 Response in place of call.

Happy coding :)

**Comment by anasnadifiA** [comment]
> `suspend fun(..): Call<..>` I delete suspend to solve the problem Thank you very much！
saved my day thank you

**Comment by iamraajkanchan** [comment]
> Please provide a complete failing test case or reproducing sample. Seems like you're doing something like `Call<Call<..>>` or `suspend fun(..): Call<..>`.

So do we don't need to use suspend functions while making post requests? Please clarify.

**Comment by Chandra-Sekhar-Bala** [comment]
In the latest release, you'll find that retrofit completely works with coroutine.
So from now on, you can remove  ``` Call<...>``` hence you can Write ```suspend fun getUser() : List<User>``` if and only if you're familiar with coroutines. For example you can see this [repo](https://github.com/Chandra-Sekhar-Bala/MVVM-ToDo/blob/main/app/src/main/java/com/sekhar/todo/app/repo/network/ApiService.kt)
Read  about coroutines [here](https://developer.android.com/kotlin/coroutines)
