### ISSUE TITLE
Explicit termination method 'end' not called with gzip and StrictMode

### ISSUE THREAD

**Issue by benoitdion** [square/retrofit#324]
Getting the following error when the response stream is gzip encoded and strict mode is enabled:

```
ERROR/StrictMode(10161): A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.
        java.lang.Throwable: Explicit termination method 'end' not called
        at dalvik.system.CloseGuard.open(CloseGuard.java:184)
        at java.util.zip.Inflater.<init>(Inflater.java:82)
        at java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:96)
        at java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:81)
        at libcore.net.http.HttpEngine.initContentStream(HttpEngine.java:547)
        at libcore.net.http.HttpEngine.readResponse(HttpEngine.java:850)
        at libcore.net.http.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:283)
        at libcore.net.http.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:497)
        at retrofit.client.UrlConnectionClient.readResponse(UrlConnectionClient.java:90)
        at retrofit.client.UrlConnectionClient.execute(UrlConnectionClient.java:48)
        at retrofit.RestAdapter$RestHandler.invokeRequest(RestAdapter.java:281)
        at retrofit.RestAdapter$RestHandler.invoke(RestAdapter.java:216)
        at $Proxy8.postDevice(Native Method)
```

It also reproduces with okhttp:

```
ERROR/StrictMode(13248): A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.
        java.lang.Throwable: Explicit termination method 'end' not called
        at dalvik.system.CloseGuard.open(CloseGuard.java:184)
        at java.util.zip.Inflater.<init>(Inflater.java:82)
        at java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:96)
        at java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:81)
        at com.squareup.okhttp.internal.http.HttpEngine.initContentStream(HttpEngine.java:454)
        at com.squareup.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:651)
        at com.squareup.okhttp.internal.http.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:390)
        at com.squareup.okhttp.internal.http.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:339)
        at com.squareup.okhttp.internal.http.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:540)
        at retrofit.client.UrlConnectionClient.readResponse(UrlConnectionClient.java:90)
        at retrofit.client.UrlConnectionClient.execute(UrlConnectionClient.java:48)
        at retrofit.RestAdapter$RestHandler.invokeRequest(RestAdapter.java:281)
        at retrofit.RestAdapter$RestHandler.invoke(RestAdapter.java:216)
        at $Proxy8.postDevice(Native Method)
```

**Comment by pakerfeldt** [comment]
Sorry for digging this up again but are you really sure this is on retrofit? I see the same error and we're not using retrofit at all.

```java
06-02 16:03:45.044    1669-1682/com.s.m.debug.service E/StrictMode﹕ A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.
    java.lang.Throwable: Explicit termination method 'end' not called
            at dalvik.system.CloseGuard.open(CloseGuard.java:184)
            at java.util.zip.Inflater.<init>(Inflater.java:82)
            at okio.GzipSource.<init>(GzipSource.java:62)
            at com.squareup.okhttp.internal.http.HttpEngine.unzip(HttpEngine.java:574)
            at com.squareup.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:756)
            at com.squareup.okhttp.Call.getResponse(Call.java:272)
            at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:228)
            at com.s.m.a.http.WebgateAuthorizer.intercept(WebgateAuthorizer.java:32)
            at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:225)
            at com.s.m.a.http.WebgateRateLimiter.intercept(WebgateRateLimiter.java:67)
            at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:225)
            at com.squareup.okhttp.Call.getResponseWithInterceptorChain(Call.java:199)
            at com.squareup.okhttp.Call.execute(Call.java:79)
            at com.squareup.okhttp.apache.OkApacheClient.execute(OkApacheClient.java:170)
            at com.squareup.okhttp.apache.OkApacheClient.execute(OkApacheClient.java:155)
            at com.s.m.a.core.internal.HttpConnection$2.run(HttpConnection.java:203)
```
This is on 2.3.0 however. Will try to repro on latest as well.

**Comment by duanbo1983** [comment]
Same experience as @pakerfeldt , my app doesn't depend on retrofit at all. But it still happens.
