### ISSUE TITLE
Fatal Exception: java.util.NoSuchElementException

### ISSUE THREAD

**Issue by rmdan90** [square/retrofit#3250]
Hey, some of users getting this weird crash.

The crash stack trace from crashlytics:

`Fatal Exception: java.util.NoSuchElementException
       at okhttp3.internal.connection.RouteSelector.next(RouteSelector.java:75)
       at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.java:187)
       at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.java:107)
       at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.java:87)
       at okhttp3.internal.connection.Transmitter.newExchange(Transmitter.java:169)
       at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:41)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
       at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:94)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
       at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
       at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:88)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
       at com.goadroit.adroitdrivers.network.ConnectivityInterceptor.intercept(ConnectivityInterceptor.java:20)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
       at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:221)
       at okhttp3.RealCall$AsyncCall.execute(RealCall.java:172)
       at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
       at java.lang.Thread.run(Thread.java:764)`

I'm using the following dependencies: 

com.squareup.retrofit2:retrofit:2.5.0
com.squareup.retrofit2:converter-gson:2.5.0
com.squareup.okhttp3:logging-interceptor:3.14.1
com.squareup.retrofit2:converter-scalars:2.5.0

Base requestsClient code:

`private long DEFUALT_CALL_TIMEOUT = 15;
    private long DEFUALT_CONNECT_TIMEOUT = 5;

OkHttpClient.Builder okHttpClientBuilder = new OkHttpClient.Builder()
                .callTimeout(DEFUALT_CALL_TIMEOUT,TimeUnit.SECONDS)
                .connectTimeout(DEFUALT_CONNECT_TIMEOUT, TimeUnit.SECONDS);

if (BuildConfig.DEBUG) {
            HttpLoggingInterceptor logging = new HttpLoggingInterceptor();
            logging.setLevel(HttpLoggingInterceptor.Level.BODY);
            okHttpClientBuilder.addInterceptor(logging);
        }
        okHttpClientBuilder.addInterceptor(new ConnectivityInterceptor());

retrofit = new Retrofit.Builder()
                .baseUrl(AppConstants.SERVER_URL)
                .addConverterFactory(GsonConverterFactory.create())
                .client(okHttpClientBuilder.build())
                .build();`

**Comment by JakeWharton** [comment]
This originates from OkHttp, not Retrofit. I would encourage you to search their issue tracker as there are several similar traces that have been reported in the last 6 months and the bug fixes are in versions newer than 3.14.1.
