### ISSUE TITLE
Can support for Kotlin  be made optional?

### ISSUE THREAD

**Issue by misl** [square/retrofit#3269]
What kind of issue is this?

 - [X ] Question. This issue tracker is not the place for questions. If you want to ask how to do
       something, or to understand why something isn't working the way you expect it to, use Stack
       Overflow. https://stackoverflow.com/questions/tagged/retrofit

 - [] Bug report. If you’ve found a bug, spend the time to write a failing test. Bugs with tests
       get fixed. Here’s an example: https://gist.github.com/swankjesse/6608b4713ad80988cdc9

 - [ X] Feature Request. Start by telling us what problem you’re trying to solve. Often a solution
       already exists! Don’t send pull requests to implement new features without first getting our
       support. Sometimes we leave features out on purpose to keep the project small.

Context:
I am working on a pure Java application using [InfluxDB java client](https://github.com/influxdata/influxdb-java) library . That library makes use of Retrofit to communicate with the InfluxDB server. The intention is to use [Quarkus](https://quarkus.io/) to create native executables.

Right now I get error when I try to create native executables:
```
...
Error: com.oracle.graal.pointsto.constraints.UnresolvedElementException: Discovered unresolved type during parsing: kotlin.Unit. To diagnose the issue you can use the --allow-incomplete-classpath option. The missing type is then reported at run time when it is accessed the first time.
Trace: 
	at parsing retrofit2.BuiltInConverters.responseBodyConverter(BuiltInConverters.java:43)
Call path from entry point to retrofit2.BuiltInConverters.responseBodyConverter(Type, Annotation[], Retrofit): 
	at retrofit2.BuiltInConverters.responseBodyConverter(BuiltInConverters.java:33)
	at retrofit2.Retrofit.nextResponseBodyConverter(Retrofit.java:330)
	at retrofit2.Retrofit.responseBodyConverter(Retrofit.java:313)
	at retrofit2.HttpServiceMethod.createResponseConverter(HttpServiceMethod.java:113)
	at retrofit2.HttpServiceMethod.parseAnnotations(HttpServiceMethod.java:82)
	at retrofit2.ServiceMethod.parseAnnotations(ServiceMethod.java:37)
	at retrofit2.Retrofit.loadServiceMethod(Retrofit.java:170)
	at retrofit2.Retrofit.eagerlyValidateMethods(Retrofit.java:158)
	at retrofit2.Retrofit.create(Retrofit.java:133)
	at org.influxdb.impl.InfluxDBImpl.<init>(InfluxDBImpl.java:178)
	at org.influxdb.impl.InfluxDBImpl.<init>(InfluxDBImpl.java:120)
	at org.influxdb.impl.InfluxDBImpl.<init>(InfluxDBImpl.java:184)
	at org.influxdb.InfluxDBFactory.connect(InfluxDBFactory.java:48)
...
```

This is about the absence of `kotlin.Unit`. I get similar errors for other Kotlin clases. Now in my current situation I don't need (and don't want) Kotlin. Adding the dependency would just bloat my application. 

Understanding the needs of others, I wondered whether this could be made optional in some way.

**Comment by JakeWharton** [comment]
Support _is_ optional which is why this warning occurs. If Kotlin was required, we would declare a dependency on it like we do with OkHttp and no warning would be produced. The downside of the optional approach is that tools which process the entirety of the bytecode will see classes that are not available to link at compile-time. At runtime, the codepaths are either unable to be taken without you first declaring the Kotlin type or they're guarded by try/catch for `NoClassDefFoundError`.

I believe graal's native image tool (which I'm guessing is what you're using) has a means of suppressing these warnings with some JSON format. We have the same problem with tools like ProGuard and R8, although those allow us to embed warning suppression rules with the artifact.

**Comment by misl** [comment]
I noticed the optional dependencies in the pom files. I hadn't noticed the `NoClassDevFoundError` exception handling. With Quarkus I managed to work around these missing dependency errors by specifically adding them. But that brought me to the next error:

```
Error: com.oracle.svm.hosted.substitute.DeletedElementException: Unsupported type java.lang.invoke.MemberName is reachable: All methods from java.lang.invoke should have been replaced during image building.
To diagnose the issue, you can add the option --report-unsupported-elements-at-runtime. The unsupported element is then reported at run time when it is accessed the first time.
Detailed message:
Trace: 
	at parsing java.lang.invoke.MethodHandles$Lookup.unreflectSpecial(MethodHandles.java:1233)
Call path from entry point to java.lang.invoke.MethodHandles$Lookup.unreflectSpecial(Method, Class): 
	at java.lang.invoke.MethodHandles$Lookup.unreflectSpecial(MethodHandles.java:1231)
	at retrofit2.Platform$Java8.invokeDefaultMethod(Platform.java:102)
	at retrofit2.Retrofit$1.invoke(Retrofit.java:147)
	at com.sun.proxy.$Proxy273.toString(Unknown Source)
	at java.lang.String.valueOf(String.java:2994)
	at java.lang.StringBuilder.append(StringBuilder.java:131)
	at com.oracle.svm.core.amd64.AMD64CPUFeatureAccess.verifyHostSupportsArchitecture(AMD64CPUFeatureAccess.java:179)
	at com.oracle.svm.core.JavaMainWrapper.runCore(JavaMainWrapper.java:129)
	at com.oracle.svm.core.JavaMainWrapper.run(JavaMainWrapper.java:186)
	at com.oracle.svm.core.code.IsolateEnterStub.JavaMainWrapper_run_5087f5482cc9a6abc971913ece43acb471d2631b(generated:0)
```

I guess I will need to build a real Quarkus Retrofit extension.

**Comment by lburgazzoli** [comment]
@misl I'm working on a quarkus extension for camel, if I'm able to make it, I'll contribute to quarkus

**Comment by JakeWharton** [comment]
Going to close since there's no action to take on Retrofit's side. Aside from removing the Kotlin support, though, let me know if there is anything I can do to help.

**Comment by springified** [comment]
Hi there
I am facing the same issue. Created a quarkus app. I have a dependency of influx java client. 

I got the following issue while trying to build a native image

`Error: Unsupported features in 2 methods
Detailed message:
Error: com.oracle.graal.pointsto.constraints.UnresolvedElementException: Discovered unresolved type during parsing: kotlin.Unit. To diagnose the issue you can use the --allow-incomplete-classpath option. The missing type is then reported at run time when it is accessed the first time.
Trace:
	at parsing retrofit2.BuiltInConverters.responseBodyConverter(BuiltInConverters.java:43)
Call path from entry point to retrofit2.BuiltInConverters.responseBodyConverter(Type, Annotation[], Retrofit):
	at retrofit2.BuiltInConverters.responseBodyConverter(BuiltInConverters.java:33)
	at retrofit2.Retrofit.nextResponseBodyConverter(Retrofit.java:328)
	at retrofit2.Retrofit.responseBodyConverter(Retrofit.java:311)
	at retrofit2.HttpServiceMethod.createResponseConverter(HttpServiceMethod.java:68)
	at retrofit2.HttpServiceMethod.parseAnnotations(HttpServiceMethod.java:46)
	at retrofit2.ServiceMethod.parseAnnotations(ServiceMethod.java:36)
	at retrofit2.Retrofit.loadServiceMethod(Retrofit.java:168)
	at retrofit2.Retrofit$1.invoke(Retrofit.java:147)
	at com.sun.proxy.$Proxy82.hashCode(Unknown Source)
	at java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:936)
	at java.util.Properties.getProperty(Properties.java:1125)
	at com.oracle.svm.core.jdk.SystemPropertiesSupport.getProperty(SystemPropertiesSupport.java:144)
	at com.oracle.svm.core.jdk.Target_java_lang_System.getProperty(JavaLangSubstitutions.java:345)
	at com.oracle.svm.jni.JNIJavaCallWrappers.jniInvoke_VARARGS:Ljava_lang_System_2_0002egetProperty_00028Ljava_lang_String_2_00029Ljava_lang_String_2(generated:0)
Error: com.oracle.svm.hosted.substitute.DeletedElementException: Unsupported type java.lang.invoke.MemberName is reachable: All methods from java.lang.invoke should have been replaced during image building.
To diagnose the issue, you can add the option --report-unsupported-elements-at-runtime. The unsupported element is then reported at run time when it is accessed the first time.
Trace:
	at parsing java.lang.invoke.MethodHandles$Lookup.unreflectSpecial(MethodHandles.java:1795)
Call path from entry point to java.lang.invoke.MethodHandles$Lookup.unreflectSpecial(Method, Class):
	at java.lang.invoke.MethodHandles$Lookup.unreflectSpecial(MethodHandles.java:1793)
	at retrofit2.Platform$Java8.invokeDefaultMethod(Platform.java:105)
	at retrofit2.Retrofit$1.invoke(Retrofit.java:145)
	at com.sun.proxy.$Proxy82.hashCode(Unknown Source)
	at java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:936)
	at java.util.Properties.getProperty(Properties.java:1125)
	at com.oracle.svm.core.jdk.SystemPropertiesSupport.getProperty(SystemPropertiesSupport.java:144)
	at com.oracle.svm.core.jdk.Target_java_lang_System.getProperty(JavaLangSubstitutions.java:345)
	at com.oracle.svm.jni.JNIJavaCallWrappers.jniInvoke_VARARGS:Ljava_lang_System_2_0002egetProperty_00028Ljava_lang_String_2_00029Ljava_lang_String_2(generated:0)`
