### ISSUE TITLE
Crash on Android 4 and 5

### ISSUE THREAD

**Issue by awaisalam** [square/retrofit#3328]
Hi! 
I am getting this crash on all devices on Android 4.4.2 - 5.1.1
on all api calls. 
Fatal Exception: java.lang.ExceptionInInitializerError
       at okhttp3.OkHttpClient.newSslSocketFactory(OkHttpClient.java:263)
       at okhttp3.OkHttpClient.<init>(OkHttpClient.java:229)
       at okhttp3.OkHttpClient$Builder.build(OkHttpClient.java:1015)
       at com.roamerpk.network.WsProxyRetrofit.getClient(WsProxyRetrofit.java:35)
       at com.roamerpk.activities.SplashActivity.createAccountRequest(SplashActivity.java:990)
       at com.roamerpk.activities.SplashActivity.validateSignUpFields(SplashActivity.java:661)
       at com.roamerpk.activities.SplashActivity.onClick(SplashActivity.java:587)
       at android.view.View.performClick(View.java:4463)
       at android.view.View$PerformClick.run(View.java:18770)
       at android.os.Handler.handleCallback(Handler.java:808)
       at android.os.Handler.dispatchMessage(Handler.java:103)
       at android.os.Looper.loop(Looper.java:193)
       at android.app.ActivityThread.main(ActivityThread.java:5333)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:829)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:645)
       at dalvik.system.NativeStart.main(NativeStart.java)

**Comment by JakeWharton** [comment]
This is a crash in OkHttp, not Retrofit. But before filing a bug on OkHttp, I would ensure that you are using the latest version. Note: only OkHttp 3.12.x supports pre-Android 5. To use anything newer your minSdk must be 21 or higher.

**Comment by awaisalam** [comment]
Hi!

I am using 2.7.+ version of okhttp and 2.7.2 of retrofit should i downgrade
retrofit version if yes to which one?
thanks.

**Comment by JakeWharton** [comment]
Retrofit 2 does not use OkHttp 2.x. Since Retrofit 2.7 you'll need OkHttp 3.14 or newer.

**Comment by awaisalam** [comment]
Thanks
