### ISSUE TITLE
Fatal Exception: java.io.InterruptedIOException: timeout

### ISSUE THREAD

**Issue by SuperTizzyGod** [square/retrofit#3329]
Fatal Exception: java.io.InterruptedIOException: timeout
at okhttp3.internal.connection.RealCall.timeoutExit(RealCall.java:384)
at okhttp3.internal.connection.RealCall.maybeReleaseConnection(RealCall.java:346)
at okhttp3.internal.connection.RealCall.noMoreExchanges$okhttp(RealCall.java:310)
at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.java:205)
at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.java:502)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
at java.lang.Thread.run(Thread.java:764)
Caused by java.io.IOException: Canceled
at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.java:200)
at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.java:502)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
at java.lang.Thread.run(Thread.java:764)

My gradle config:
okioVersio = '2.4.3'
okhttp3Version = '4.4.0'
retrofitVersion = '2.7.1'
moshiVersion = '1.9.2'

Please let me know what is the issue and how to resolve this?

**Comment by lvcmenezes** [comment]
I currently have the same problem =/

**Comment by JakeWharton** [comment]
This looks like a normal timeout. What makes you think it's a bug?

**Comment by JakeWharton** [comment]
I see you also posted https://github.com/square/okhttp/issues/5849 so I'm just closing this. Pleae don't cross-post.
