### ISSUE TITLE
Invocation on package private interface not supported in Java 14

### ISSUE THREAD

**Issue by ben-manes** [square/retrofit#3371]
Java 14 changes some of the rules on method handle invocations, which requires minor adjustments to dynamic proxies. This restricts some invocations due to not having the same level of access permissions.

I haven't looked into your implementation, but in my own usage I had to change a call from
`.privateLookupIn(interfaceClass, MethodHandles.lookup().in(interfaceClass))`
to
`.privateLookupIn(interfaceClass, MethodHandles.lookup())`.

The following passes on Java 11 and fails on Java 14.

```java
public class InvokeTest {

  @Test
  public void invoke() throws IOException {
    Retrofit retrofit = new Retrofit.Builder()
        .baseUrl("https://example.com/")
        .build();
    var client = retrofit.create(Client.class);
    client.syncCall();
  }

  interface Client {
    @GET("/call")
    Call<Void> call();

    default Response<Void> syncCall() throws IOException {
      return call().execute();
    }
  }
}
```

<details>
<summary>
IllegalAccessException: class is not public
</summary>
FAILED: invoke
java.lang.reflect.UndeclaredThrowableException
	at $Proxy7.syncCall(Unknown Source)
	at InvokeTest.invoke(InvokeTest.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1510)
	at org.testng.TestRunner.privateRun(TestRunner.java:766)
	at org.testng.TestRunner.run(TestRunner.java:587)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
	at org.testng.SuiteRunner.run(SuiteRunner.java:286)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
	at org.testng.TestNG.runSuites(TestNG.java:1039)
	at org.testng.TestNG.run(TestNG.java:1007)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: java.lang.IllegalAccessException: class is not public: InvokeTest$Client.syncCall[Ljava.lang.Object;@3a4621bd/invokeSpecial, from interface InvokeTest$Client (unnamed module @31dadd46)
	at java.base/java.lang.invoke.MemberName.makeAccessException(MemberName.java:954)
	at java.base/java.lang.invoke.MethodHandles$Lookup.checkAccess(MethodHandles.java:2977)
	at java.base/java.lang.invoke.MethodHandles$Lookup.checkMethod(MethodHandles.java:2917)
	at java.base/java.lang.invoke.MethodHandles$Lookup.getDirectMethodCommon(MethodHandles.java:3062)
	at java.base/java.lang.invoke.MethodHandles$Lookup.getDirectMethodNoSecurityManager(MethodHandles.java:3055)
	at java.base/java.lang.invoke.MethodHandles$Lookup.unreflectSpecial(MethodHandles.java:2540)
	at retrofit2.Platform.invokeDefaultMethod(Platform.java:111)
	at retrofit2.Retrofit$1.invoke(Retrofit.java:147)
	... 30 more
</details>

**Comment by JakeWharton** [comment]
Thanks for the report. We finally have the infrastructure to actually test this and it seems like we're missing coverage for this case. It _was_ mitigated for early Java versions but I guess we omitted a test. Either that or the fact that our tests live in the same package as the code means we're not testing what we think (since that's the shape of nearly all of our tests). Will look.

**Comment by JakeWharton** [comment]
Yep. Reproduced by moving our existing default method tests to a subpackage.

`privateLookupIn` is Java 9+ so we either need to reflect on that or move to a multi-release jar. Any thoughts on that? When we fixed #3281 the person wasn't too keen on MR jars because they shadow the library.

**Comment by ben-manes** [comment]
It was trivial to fix by making the interface public and since the outer class was package private it had no visibility leak. I’d be fine with this in your backlog, but you might not be since others will upgrade slowly and might hit this.

I would use reflection, as I did similar in caffeine for a Java 9 api (delayedExecutor). If you cache the method object it is fast to invoke. MRJars are poorly supported and very rare, so I wouldn’t have a popular project be the first adopter.

There was a memory leak with method handles that bit me in JDK8, which you should probably be aware of. https://github.com/ben-manes/caffeine/issues/222
