### ISSUE TITLE
retrofit2.6.1 OK retrofit2.7.1 ,2.8.1 error

### ISSUE THREAD

**Issue by zhoudahuai252** [square/retrofit#3388]
`     getAppDataBtn.setOnClickListener {
            val retrofit = Retrofit.Builder()
                    .baseUrl("http://10.0.2.2/")
                    .addConverterFactory(GsonConverterFactory.create())
                    .build()
            val appService = retrofit.create(AppService::class.java)
            appService.getAppData().enqueue(object : Callback<List<App>> {
                override fun onFailure(call: Call<List<App>>, t: Throwable) {
                    t.printStackTrace()

                }

                override fun onResponse(call: Call<List<App>>, response: Response<List<App>>) {
                    val list = response.body()
                    list?.forEach {
                        Log.d("MainActivity", "id is ${it.id}")
                        Log.d("MainActivity", "name is ${it.name}")
                        Log.d("MainActivity", "version is ${it.version}")
                    }
                }
            })
        }`

`2020-05-10 19:53:13.330 17821-17821/com.example.retrofittest E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.retrofittest, PID: 17821
    java.lang.NoSuchMethodError: No static method metafactory(Ljava/lang/invoke/MethodHandles$Lookup;Ljava/lang/String;Ljava/lang/invoke/MethodType;Ljava/lang/invoke/MethodType;Ljava/lang/invoke/MethodHandle;Ljava/lang/invoke/MethodType;)Ljava/lang/invoke/CallSite; in class Ljava/lang/invoke/LambdaMetafactory; or its super classes (declaration of 'java.lang.invoke.LambdaMetafactory' appears in /apex/com.android.runtime/javalib/core-oj.jar)
        at okhttp3.internal.Util.<clinit>(Util.java:87)
        at okhttp3.internal.Util.skipLeadingAsciiWhitespace(Util.java:321)
        at okhttp3.HttpUrl$Builder.parse(HttpUrl.java:1313)
        at okhttp3.HttpUrl.get(HttpUrl.java:917)
        at retrofit2.Retrofit$Builder.baseUrl(Retrofit.java:492)
        at com.example.retrofittest.MainActivity$onCreate$1.onClick(MainActivity.kt:20)
        at android.view.View.performClick(View.java:7125)
        at android.view.View.performClickInternal(View.java:7102)
        at android.view.View.access$3500(View.java:801)
        at android.view.View$PerformClick.run(View.java:27336)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)`

**Comment by zhoudahuai252** [comment]
When I use retrofit
![QQ截图20200510195954](https://user-images.githubusercontent.com/15266473/81498688-e7fec680-92f8-11ea-8c99-fa9b28e6ddd1.png)
2.6.1 okay, 2.7.1, 2.8.1 error
