### ISSUE TITLE
Android Java 8 API desugaring and Query parameters exceptions

### ISSUE THREAD

**Issue by rig-jguldemeester** [square/retrofit#3426]
What kind of issue is this?

 - [ ] Question. This issue tracker is not the place for questions. If you want to ask how to do
       something, or to understand why something isn't working the way you expect it to, use Stack
       Overflow. https://stackoverflow.com/questions/tagged/retrofit

 - [x] Bug report. If you’ve found a bug, spend the time to write a failing test. Bugs with tests
       get fixed. Here’s an example: https://gist.github.com/swankjesse/6608b4713ad80988cdc9

 - [ ] Feature Request. Start by telling us what problem you’re trying to solve. Often a solution
       already exists! Don’t send pull requests to implement new features without first getting our
       support. Sometimes we leave features out on purpose to keep the project small.

I was trying out the new Java 8+ API desugaring support (Android Gradle Plugin 4.0.0+). This was mostly focusses around using `java.time` API's. In our app we do a GET request with a query parameters that is a `Instant`. When using the desugaring support I faced the following exception on Android 6 devices:
```
    java.lang.TypeNotPresentException: Type java.time.Instant not present
        at libcore.reflect.ParameterizedTypeImpl.getRawType(ParameterizedTypeImpl.java:67)
        at libcore.reflect.ParameterizedTypeImpl.getResolvedType(ParameterizedTypeImpl.java:76)
        at libcore.reflect.ListOfTypes.resolveTypes(ListOfTypes.java:70)
        at libcore.reflect.ListOfTypes.getResolvedTypes(ListOfTypes.java:55)
        at libcore.reflect.Types.getTypeArray(Types.java:50)
        at java.lang.reflect.Method.getGenericParameterTypes(Method.java:246)
        at retrofit2.RequestFactory$Builder.<init>(RequestFactory.java:175)
        at retrofit2.RequestFactory.parseAnnotations(RequestFactory.java:67)
        at retrofit2.ServiceMethod.parseAnnotations(ServiceMethod.java:26)
        at retrofit2.Retrofit.loadServiceMethod(Retrofit.java:202)
        at retrofit2.Retrofit$1.invoke(Retrofit.java:160)
        at java.lang.reflect.Proxy.invoke(Proxy.java:393)
        at $Proxy0.queryInstant(Unknown Source)
```

I tried adding a `Converter.Factory` in the hope to solve the problem and didn't work. For now I solved it by replacing the `Instant` with a `String` and cast it before passing it to the retrofit client. 

Also I created an example app to demostrate the issue: [repository](https://github.com/rig-jguldemeester/RetrofitAndroidDesugaring/blob/master/app/src/main/java/nl/guldem/retrofitdesugaring/MainActivity.kt)

**Comment by JakeWharton** [comment]
Thanks! This is tracked (and fixed) by https://issuetracker.google.com/issues/158124557. You can follow the instructions in the comments to test out the fix and report back to Google whether it's working or not.
