### ISSUE TITLE
java.lang.IllegalStateException with Kotlin Coroutine

### ISSUE THREAD

**Issue by whitestarlau** [square/retrofit#3458]
I'm now using kotlin 1.3.72 and retrofit 2.9. In the past, I used to access network data through Rxjava+retrofit2. Recently, I tried to switch to Kotlin coroutine. However, I found that some exception could not be caught by try catch. I guess the reason is that the thread was switched inside the retrofit and the corresponding exception was not passed to the outside.

For example, if I change the API address a little, I will get a 404 return. At this time, the following exception will appear. This exception can be caught when using rxjava.

```
java.lang.IllegalStateException
        at okhttp3.internal.connection.Transmitter.prepareToConnect(Transmitter.java:129)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:79)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
        at com.eebbk.bfc.network.retrofit2.external.BfcDNSInterceptor.intercept(BfcDNSInterceptor.java:115)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
        at com.eebbk.wrongdiagnosis.base.network.utils.DynamicTimeoutInterceptor.intercept(DynamicTimeoutInterceptor.java:57)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
        at com.eebbk.wrongdiagnosis.base.network.manager.ParameterInterceptor.intercept(ParameterInterceptor.kt:36)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
        at com.eebbk.bfc.network.retrofit2.external.BfcWebAuthenInterceptor.intercept(BfcWebAuthenInterceptor.java:20)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
        at com.eebbk.wrongdiagnosis.base.network.utils.OfflineHttpCacheInterceptor.intercept(OfflineHttpCacheInterceptor.java:50)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:229)
        at okhttp3.RealCall$AsyncCall.execute(RealCall.java:172)
        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
```

I have try okhttp4,now the crash log is change,like this:

```
java.lang.IllegalStateException: cannot make a new request because the previous response is still open: please call response.close()
        at okhttp3.internal.connection.RealCall.enterNetworkInterceptorExchange(RealCall.kt:229)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:66)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at com.eebbk.bfc.network.retrofit2.external.BfcDNSInterceptor.intercept(BfcDNSInterceptor.java:115)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at com.eebbk.wrongdiagnosis.base.network.utils.DynamicTimeoutInterceptor.intercept(DynamicTimeoutInterceptor.java:57)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at com.eebbk.wrongdiagnosis.base.network.manager.ParameterInterceptor.intercept(ParameterInterceptor.kt:36)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at com.eebbk.bfc.network.retrofit2.external.BfcWebAuthenInterceptor.intercept(BfcWebAuthenInterceptor.java:20)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at com.eebbk.wrongdiagnosis.base.network.utils.OfflineHttpCacheInterceptor.intercept(OfflineHttpCacheInterceptor.java:50)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
        at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:517)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
```

It's RetryAndFollowUpInterceptor's bug?Should I move this issue to okhttp repo?

**Comment by whitestarlau** [comment]
I have try to use Response<T>,try-catch,CoroutineThrowableHandler, these methods are all useless.

**Comment by whitestarlau** [comment]
OK,now I know why.Ours BfcDNSInterceptor will try again when it met a 404 error,but it didn't close last reponse.I try close last reponse before retry,the 404 error will throw out and try-catch by caller.
