### ISSUE TITLE
R8 breaks interface inheritance when service is cast to supertype

### ISSUE THREAD

**Issue by ntsik** [square/retrofit#3466]
What kind of issue is this?

 - [ ] Question. This issue tracker is not the place for questions. If you want to ask how to do
       something, or to understand why something isn't working the way you expect it to, use Stack
       Overflow. https://stackoverflow.com/questions/tagged/retrofit

 - [x] Bug report. If you’ve found a bug, spend the time to write a failing test. Bugs with tests
       get fixed. Here’s an example: https://gist.github.com/swankjesse/6608b4713ad80988cdc9

 - [ ] Feature Request. Start by telling us what problem you’re trying to solve. Often a solution
       already exists! Don’t send pull requests to implement new features without first getting our
       support. Sometimes we leave features out on purpose to keep the project small.

-----

Using Retrofit 2.9.0.

```
internal class InterfaceInheritanceTest {
    interface BaseService {
        fun doTheThing(): Call<Unit>
    }

    interface RetrofitService : BaseService {
        @POST("/")
        override fun doTheThing(): Call<Unit>
    }

    private val service = Retrofit.Builder()
        .baseUrl("https://example.com")
        .build()
        .create(RetrofitService::class.java)

    @Test
    fun passes() {
        service.doTheThing()
    }

    /*
    java.lang.IllegalArgumentException: HTTP method annotation is required (e.g., @GET, @POST, etc.).
        for method BaseService.doTheThing
        at retrofit2.Utils.methodError(Utils.java:54)
        at retrofit2.Utils.methodError(Utils.java:43)
        at retrofit2.RequestFactory$Builder.build(RequestFactory.java:185)
        at retrofit2.RequestFactory.parseAnnotations(RequestFactory.java:67)
        at retrofit2.ServiceMethod.parseAnnotations(ServiceMethod.java:26)
        at retrofit2.Retrofit.loadServiceMethod(Retrofit.java:202)
        at retrofit2.Retrofit$1.invoke(Retrofit.java:160)
        at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
        at $Proxy27.doTheThing(Unknown Source)
     */
    @Test
    fun fails() {
        (service as BaseService).doTheThing()
    }
}
```

This test needs to be run with R8 enabled for `fails` to actually fail. Last time I tried to do so, I couldn't get R8 to run for tests in an Android library module, so it might need to be run in an application module. Also, no clue if Proguard exhibits the same behavior.

When debugging into this issue, I found that the `Method` being passed to the `Proxy` in the failing case was `BaseService.doTheThing`. The passing case uses the correct `RetrofitService.doTheThing`. Unfortunately, I've reached the limit of my knowledge here and can't tell what the proper fix would be - changing Proguard rules, bug in R8, bug in Retrofit - hence this report.

The actual use case for this is having `BaseService` in a Kotlin multiplatform `commonMain` and `RetrofitService` in `androidMain`. For now, I've fixed the issue on my side by using `actual`/`expect` rather than inheritance, but that unfortunately also requires that other platforms need to provide `actual`s rather than using a base `interface`.

**Comment by BugsBunnyBR** [comment]
We found this behaviour this week on our app.
Is there any fix for this?
@JakeWharton @swankjesse
