### ISSUE TITLE
Socket is closed || stream was reset: CANCEL

### ISSUE THREAD

**Issue by gfaiers** [square/retrofit#3469]
Issue: since change from 2.6.2 -> 2.9.0 seeing exceptions called
```
java.net.SocketException: socket is closed
  at com.android.org.conscrypt.ConscryptFileDescriptorSocket$SSLInputStream.read(ConscryptFileDescriptorSocket.java:546)
  at okio.Okio$2.read(Okio.java:140)
  at okio.AsyncTimeout$2.read(AsyncTimeout.java:237)
  at okio.RealBufferedSource.request(RealBufferedSource.java:72)
  at okio.RealBufferedSource.require(RealBufferedSource.java:65)
  at okhttp3.internal.http2.Http2Reader.nextFrame(Http2Reader.java:96)
  at okhttp3.internal.http2.Http2Connection$ReaderRunnable.execute(Http2Connection.java:668)
  at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
  at java.lang.Thread.run(Thread.java:764)
```

And:

```
okhttp3.internal.http2.StreamResetException: stream was reset: CANCEL
	at okhttp3.internal.http2.Http2Stream$FramingSource.read(Http2Stream.java:384)
	at okhttp3.internal.connection.Exchange$ResponseBodySource.read(Exchange.java:286)
	at okio.RealBufferedSource.read(RealBufferedSource.java:51)
	at okio.ForwardingSource.read(ForwardingSource.java:35)
	at retrofit2.OkHttpCall$ExceptionCatchingResponseBody$1.read(OkHttpCall.java:314)
	at okio.RealBufferedSource$1.read(RealBufferedSource.java:447)
	at java.io.InputStreamReader.read(InputStreamReader.java:233)
	at okhttp3.ResponseBody$BomAwareReader.read(ResponseBody.java:263)
	at com.google.gson.stream.JsonReader.fillBuffer(JsonReader.java:1291)
	at com.google.gson.stream.JsonReader.nextNonWhitespace(JsonReader.java:1329)
	at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:539)
	at com.google.gson.stream.JsonReader.peek(JsonReader.java:426)
	at retrofit2.converter.gson.GsonResponseBodyConverter.convert(GsonResponseBodyConverter.java:41)
	at retrofit2.converter.gson.GsonResponseBodyConverter.convert(GsonResponseBodyConverter.java:27)
	at retrofit2.OkHttpCall.parseResponse(OkHttpCall.java:243)
	at retrofit2.OkHttpCall.execute(OkHttpCall.java:204)
	at retrofit2.adapter.rxjava2.CallExecuteObservable.subscribeActual(CallExecuteObservable.java:46)
	at io.reactivex.Observable.subscribe(Observable.java:12267)
	at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
	at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:269)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
	at java.lang.Thread.run(Thread.java:818)
```

The exact stack trace of each issue varies each time.

See the example project that I've created https://github.com/gfaiers/test_retrofit

Gif of example in action: https://github.com/gfaiers/test_retrofit/blob/main/test_retrofit.gif

In this example:
```
implementation 'com.squareup.retrofit2:adapter-rxjava2:2.9.0'
implementation 'com.squareup.retrofit2:converter-gson:2.9.0'
```

Change this to 2.6.2 and then you'll see no crashes.

You will need to connect this to an externally hosted api, when I tried it on a locally hosted api it didn't happen.

After further investigation, looks like this issue isn't present in Android 8.1 +.

I've managed to replicate the error on Android 6.0, 8.0 and 8.1.0. Not tried any others.

**Comment by JakeWharton** [comment]
Something like this is entirely controlled by OkHttp. The behavior change you are seeing as a result of updating Retrofit is actually because the transitive dependency on OkHttp was also updated. If you stick on the old Retrofit version but explicitly upgrade OkHttp to the version that new Retrofit uses you will see the same error. Conversely, if you force downgrade the version of OkHttp on new Retrofit to the one that old Retrofit uses the error will go away. All of that is to say that Retrofit does not play a part in this behavior and we have no real control over it, you would see the same behavior with raw OkHttp and you'll need to seek resolution with the use/configuration of OkHttp.
