### ISSUE TITLE
Cant handle exception with coroutines

### ISSUE THREAD

**Issue by vitaliiermakov** [square/retrofit#3498]
Hi! Looks like I find some bug with retrofit in case of using coroutines.
Stack trace: 
```
    Process: com.onetwotrip.onetwotrip, PID: 32132
    retrofit2.HttpException: HTTP 400 
        at retrofit2.KotlinExtensions$await$2$2.onResponse(KotlinExtensions.kt:53)
        at retrofit2.OkHttpCall$1.onResponse(OkHttpCall.java:161)
        at okhttp3.RealCall$AsyncCall.execute(RealCall.java:174)
        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
```

This bug began to reproduce after updating kotlin version from '1.3.61' to '1.4.10'
I'm using:
```
[group: 'org.jetbrains.kotlinx', name: 'kotlinx-coroutines-core', version: '1.4.1'] 
[group: 'com.squareup.retrofit2', name: 'retrofit', version: '2.9.0']
```

Retrofit builder:
```
Retrofit.Builder provideTestRestBuilder(
            @Named(PROVIDE_LONG_OK_HTTP_CLIENT) OkHttpClient client) {
        GsonConverterFactory factory = GsonConverterFactory.create();
        return new Retrofit.Builder()
                .baseUrl(BASE_URL)
                .addConverterFactory(factory)
                .client(client);
    }
```

Rest provider:
```
VirtualCardRest provideVirtualCardRest(@Named(PROVIDE_LONG_ADAPTER_RETROFIT2_BUILDER) Retrofit.Builder restAdapterBuilder) {
        return restAdapterBuilder.build()
                .create(VirtualCardRest.class);
    }
```

```
Some rest function:
@GET("some_request")
    suspend fun requestSome(@Query("someQuery")
```

This huge function for processing result in my repository, not sure that I need to put it here
```
    private suspend inline fun <T : BaseResponse<Any?, String?>, reified T2> processRequest(
            crossinline requestFunc: suspend () -> T,
            crossinline toVo: (Any) -> T2): BaseResponse<T2, ApiErrorDetails?> {
        var result: T2? = null
        var error: ApiErrorDetails?
        val response = CoroutineUtills.handleRequest {
            requestFunc.invoke()
        }

        if (response.isSuccess && response.getOrNull()?.result != null) {
            val voResult = response.getOrNull()?.result?.let(toVo)
            if (voResult is T2)
                result = voResult
            else
                error = ApiErrorDetails(ClassCastException(), response.getOrNull()?.error)
        }

        error = ApiErrorDetails(response.exceptionOrNull(), response.getOrNull()?.error)

        return BaseResponse(result, error)
    }
```

And function that helps me handle exceptions:
```
suspend fun <T: Any> handleRequest(requestFunc: suspend () -> T): Result<T> {
        return try {
            Result.success(requestFunc.invoke())
        } catch (e: BadResponseCodeException) {
            Result.failure(e) //exception throws at this step
        }
    }
```

EDIT:
BadResponseCodeException is _CopyableThrowable_, but simple Exception works with the same result

**Comment by JakeWharton** [comment]
You're catching `BadResponseCodeExceptoin` but Retrofit is throwing an `HttpException` which isn't caught.

Can you reduce this to a minimally-reproducing test case? Here's our test case which asserts that exceptions are thrown (and can be caught): https://github.com/square/retrofit/blob/7128bf34c649daca5977b1fbf93f0278fab4267c/retrofit/src/test/java/retrofit2/KotlinSuspendTest.kt#L72-L87
