### ISSUE TITLE
  onRun HTTP 500 Server Error

### ISSUE THREAD

**Issue by johnjeremih** [square/retrofit#3530]
What kind of issue is this?
 was trying to send the data to the server.

E/CreateExpense: onRun
    retrofit2.adapter.rxjava2.HttpException: HTTP 500 Server Error
        at retrofit2.adapter.rxjava2.BodyObservable$BodyObserver.onNext(BodyObservable.java:57)
        at retrofit2.adapter.rxjava2.BodyObservable$BodyObserver.onNext(BodyObservable.java:38)
        at retrofit2.adapter.rxjava2.CallExecuteObservable.subscribeActual(CallExecuteObservable.java:48)
        at io.reactivex.Observable.subscribe(Observable.java:12284)
        at retrofit2.adapter.rxjava2.BodyObservable.subscribeActual(BodyObservable.java:35)
        at io.reactivex.Observable.subscribe(Observable.java:12284)
        at io.reactivex.internal.operators.observable.ObservableSingleSingle.subscribeActual(ObservableSingleSingle.java:35)
        at io.reactivex.Single.subscribe(Single.java:3666)
        at io.reactivex.Single.blockingGet(Single.java:2869)
        at com.programproductions.nativeandroid.data.work.job.expense.CreateExpense.onRun(CreateExpense.java:37)
        at com.birbit.android.jobqueue.Job.safeRun(Job.java:229)
        at com.birbit.android.jobqueue.JobHolder.safeRun(JobHolder.java:132)
        at com.birbit.android.jobqueue.ConsumerManager$Consumer.handleRunJob(ConsumerManager.java:413)
        at com.birbit.android.jobqueue.ConsumerManager$Consumer.access$000(ConsumerManager.java:333)
        at com.birbit.android.jobqueue.ConsumerManager$Consumer$2.handleMessage(ConsumerManager.java:361)
        at com.birbit.android.jobqueue.messaging.SafeMessageQueue.consume(SafeMessageQueue.java:36)
        at com.birbit.android.jobqueue.ConsumerManager$Consumer.run(ConsumerManager.java:395)
        at java.lang.Thread.run(Thread.java:919)

**Comment by JakeWharton** [comment]
This is normal behavior on server error.

**Comment by johnjeremih** [comment]
> This is normal behavior on server error.

What do you mean by that?

**Comment by JakeWharton** [comment]
The RxJava adapter will send an HttpException for non-200 responses per its documentation: 

https://github.com/square/retrofit/blob/fbf1225e28e2094bec35f587b8933748b705d167/retrofit-adapters/rxjava3/src/main/java/retrofit2/adapter/rxjava3/RxJava3CallAdapterFactory.java#L51-L53
