### ISSUE TITLE
Retrofit JAXB Converter does not work with Jakarta JAXB

### ISSUE THREAD

**Issue by KrishnaST** [square/retrofit#3536]
Not sure if it is a bug report or feature request. In my recent project I have both old java.xml.bind and jakarta.xml.bind implementations are on classpath. My classes are annotated with jakarta.xml.bind.*. I am getting following error

 ```
java.lang.IllegalArgumentException: Unable to create @Body converter for class com.sil.upi.jaxb.RespListAccount (parameter #3)
    for method UPIService.sendRespListAccount
        at retrofit2.Utils.methodError(Utils.java:54)
        at retrofit2.Utils.parameterError(Utils.java:60)
        at retrofit2.RequestFactory$Builder.parseParameterAnnotation(RequestFactory.java:781)
        at retrofit2.RequestFactory$Builder.parseParameter(RequestFactory.java:325)
        at retrofit2.RequestFactory$Builder.build(RequestFactory.java:206)
        at retrofit2.RequestFactory.parseAnnotations(RequestFactory.java:67)
        at retrofit2.ServiceMethod.parseAnnotations(ServiceMethod.java:26)
        at retrofit2.Retrofit.loadServiceMethod(Retrofit.java:202)
        at retrofit2.Retrofit$1.invoke(Retrofit.java:160)
        at com.sun.proxy.$Proxy78.sendRespListAccount(Unknown Source)
        at com.sil.upi.application.RetroClient.sendRespListAccount(RetroClient.java:101)
        at com.sil.upi.services.meta.ListAccount.run(ListAccount.java:110)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
        at java.base/java.lang.Thread.run(Thread.java:832)
Caused by: java.lang.IllegalArgumentException: Could not locate RequestBody converter for class com.sil.upi.jaxb.RespListAccount.
  Tried:
   * retrofit2.BuiltInConverters
   * retrofit2.converter.jaxb.JaxbConverterFactory
   * retrofit2.OptionalConverterFactory
        at retrofit2.Retrofit.nextRequestBodyConverter(Retrofit.java:335)
        at retrofit2.Retrofit.requestBodyConverter(Retrofit.java:293)
        at retrofit2.RequestFactory$Builder.parseParameterAnnotation(RequestFactory.java:778)
        ... 12 more
```

I can understand retrofit jaxb converter is compiled with java.xml.bind so I am getting error on deserialization. Is there a possibility that future converter release will work for both implementations?

**Comment by JakeWharton** [comment]
We'll need a new module that copy/pastes the old and updates imports. Sigh. Easy enough though.
