### ISSUE TITLE
Fatal Exception : NullPointerException 

### ISSUE THREAD

**Issue by arunabimanyu7** [square/retrofit#3578]
We are getting intermittent crash from the Production application.

**Retrofit version** -> 2.9.0 

**BuildToolsVersion** 30.0.3

**Android Version** -> 8.0.0

**Brand** -> Samsung

**Model** -> Galaxy Wide3

`
      Fatal Exception: java.lang.NullPointerException: ssl == null
       at com.android.org.conscrypt.NativeCrypto.SSL_write(NativeCrypto.java)
       at com.android.org.conscrypt.OpenSSLSocketImpl$SSLOutputStream.write(OpenSSLSocketImpl.java:832)
       at okio.OutputStreamSink.write(JvmOkio.kt:53)
       at okio.AsyncTimeout$sink$1.write(AsyncTimeout.kt:103)
       at okio.RealBufferedSink.flush(RealBufferedSink.kt:267)
       at okhttp3.internal.http2.Http2Writer.goAway(Http2Writer.kt:233)
       at okhttp3.internal.http2.Http2Connection.shutdown(Http2Connection.kt:429)
       at okhttp3.internal.http2.Http2Connection.close$okhttp(Http2Connection.kt:449)
       at okhttp3.internal.http2.Http2Connection$ReaderRunnable.invoke(Http2Connection.kt:627)
       at okhttp3.internal.http2.Http2Connection$ReaderRunnable.invoke(Http2Connection.kt:609)
       at okhttp3.internal.concurrent.TaskQueue$execute$1.runOnce(TaskQueue.kt:98)
       at okhttp3.internal.concurrent.TaskRunner.runTask(TaskRunner.kt:116)
       at okhttp3.internal.concurrent.TaskRunner.access$runTask(TaskRunner.kt:42)
       at okhttp3.internal.concurrent.TaskRunner$runnable$1.run(TaskRunner.kt:65)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
       at java.lang.Thread.run(Thread.java:764)`

**Comment by JakeWharton** [comment]
This is many, many layers below Retrofit and certainly outside of the realm of control that Retrofit would possibly have to affect the crash from happening or correct it from not happening. Moreover, there's no information about how or why the crash occurs to even identify where to start. I would start with the Android OS and its bundling of Conscrypt, however.
