### ISSUE TITLE
Kotlin + OkHttp + Retrofit could not handle 204 responses

### ISSUE THREAD

**Issue by luiges90** [square/retrofit#3595]
What kind of issue is this?

 - [ ] Question. This issue tracker is not the place for questions. If you want to ask how to do
       something, or to understand why something isn't working the way you expect it to, use Stack
       Overflow. https://stackoverflow.com/questions/tagged/retrofit

 - [x] Bug report. If you’ve found a bug, spend the time to write a failing test. Bugs with tests
       get fixed. Here’s an example: https://gist.github.com/swankjesse/6608b4713ad80988cdc9

 - [ ] Feature Request. Start by telling us what problem you’re trying to solve. Often a solution
       already exists! Don’t send pull requests to implement new features without first getting our
       support. Sometimes we leave features out on purpose to keep the project small.

Expected: No error.
Actual:
```
Aug 03, 2021 1:11:25 PM okhttp3.internal.platform.Platform log
INFO: --> GET https://stag-hk.gogovan.tech/api/d2/user/revoke
Aug 03, 2021 1:11:25 PM okhttp3.internal.platform.Platform log
INFO: --> END GET
Aug 03, 2021 1:11:25 PM okhttp3.internal.platform.Platform log
INFO: <-- 204 No Content https://stag-hk.gogovan.tech/api/d2/user/revoke (792ms)
Aug 03, 2021 1:11:25 PM okhttp3.internal.platform.Platform log
INFO: Server: nginx/1.17.8
Aug 03, 2021 1:11:25 PM okhttp3.internal.platform.Platform log
INFO: Date: Tue, 03 Aug 2021 05:11:27 GMT
Aug 03, 2021 1:11:25 PM okhttp3.internal.platform.Platform log
INFO: Connection: keep-alive
Aug 03, 2021 1:11:25 PM okhttp3.internal.platform.Platform log
INFO: X-Frame-Options: SAMEORIGIN
Aug 03, 2021 1:11:25 PM okhttp3.internal.platform.Platform log
INFO: X-XSS-Protection: 1; mode=block
Aug 03, 2021 1:11:25 PM okhttp3.internal.platform.Platform log
INFO: X-Content-Type-Options: nosniff
Aug 03, 2021 1:11:25 PM okhttp3.internal.platform.Platform log
INFO: Cache-Control: no-cache
Aug 03, 2021 1:11:25 PM okhttp3.internal.platform.Platform log
INFO: X-Request-Id: 08ac5012791832b15e91e39f7a529e4b
Aug 03, 2021 1:11:25 PM okhttp3.internal.platform.Platform log
INFO: X-Runtime: 0.495503
Aug 03, 2021 1:11:25 PM okhttp3.internal.platform.Platform log
INFO: <-- END HTTP
Exception in thread "main" kotlin.KotlinNullPointerException: Response from com.example.retrofit_okhttp_kotlin.WebInterface.logout was null but response body type was declared as non-null
	at retrofit2.KotlinExtensions$await$2$2.onResponse(KotlinExtensions.kt:43)
	at retrofit2.OkHttpCall$1.onResponse(OkHttpCall.java:129)
	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:174)
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

Reproduce code:
```
package com.example.retrofit_okhttp_kotlin

import kotlinx.coroutines.runBlocking
import okhttp3.OkHttpClient
import retrofit2.Retrofit
import retrofit2.http.GET

fun main() = runBlocking {
    val okhttp = OkHttpClient.Builder()
        .addInterceptor { chain ->
            val newRequest = chain.request().newBuilder()
                .addHeader("Authorization", "Bearer <token>").build()
            chain.proceed(newRequest)
        }
        .build()
    val retrofit = Retrofit.Builder()
        .baseUrl("https://stag-hk.gogovan.tech/api/")
        .client(okhttp)
        .build()
        .create(WebInterface::class.java)

    retrofit.logout()
}

interface WebInterface {
    // This API returns 204 No Content
    @GET("d2/user/revoke")
    suspend fun logout()
}

```

**Comment by songsongtao** [comment]
+1

**Comment by akka81** [comment]
No news about this issue?

**Comment by lukaszkalnik** [comment]
You might want to take a look at a Retrofit adapter for Either (currently in PR): https://github.com/arrow-kt/arrow/pull/2621
It lets you define your API as returning `Unit` in case of success and then accepts `null` response body:
```
fun postSomething(): Either<CallError, Unit>
```

**Comment by victor-munoz** [comment]
Is using https://github.com/arrow-kt/arrow/pull/2621 the only solution for this issue?

**Comment by lukaszkalnik** [comment]
Actually there is an even simpler workaround: change the return type of your API call to `Response<Unit>`:

```
import retrofit2.Response

interface WebInterface {

    @GET("user/revoke")
    suspend fun logout(): Response<Unit>
}
```

https://github.com/square/retrofit/issues/3075#issuecomment-515400245

**Comment by victor-munoz** [comment]
Thanks [lukaszkalnik](https://github.com/lukaszkalnik), Sadly, I need to perform specific actions in case of 4xx or 5xx responses, so do not throw an exception will be a problem.

Currently I am replacing the 204 code with a 200 code using a `NetworkInterceptor` to avoid trowing a `KotlinNullPointerException`


```
          OkHttpClient.Builder().addNetworkInterceptor { chain ->
                val request = chain.request()
                val response: Response = chain.proceed(request)
                if(response.code() == 204) response.newBuilder().code(200).build()
                else response
            }.build().run {
                Retrofit.Builder()
                    .baseUrl(YOUR_URL)
                    .addConverterFactory(GsonConverterFactory.create(GsonBuilder().create()))
                    .addCallAdapterFactory(CoroutineCallAdapterFactory())
                    .client(this)
                    .build()
                    .create(YourService::class.java)
            }
```

**Comment by mtwolak** [comment]
We had a production incident because of this bug. Sadly we also had to make some manual workarounds.
