### ISSUE TITLE
Can't run Retrofit 2.9.0 and java 16

### ISSUE THREAD

**Issue by eric-gymondo** [square/retrofit#3601]
I have a project running on java 16 and the latest retrofit available, I read the main documentation it does not mention anything about Retrofit not being compatible with java 16, but when I try to use retrofit I get the following error.

```
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make java.lang.invoke.MethodHandles$Lookup(java.lang.Class,int) accessible: module java.base does not "opens java.lang.invoke" to unnamed module @c7a8a6ee
	at java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:357) ~[?:?]
	at java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297) ~[?:?]
	at java.lang.reflect.Constructor.checkCanSetAccessible(Constructor.java:188) ~[?:?]
	at java.lang.reflect.Constructor.setAccessible(Constructor.java:181) ~[?:?]
	at retrofit2.Platform.<init>(Platform.java:59) **~[retrofit-2.9.0.jar:?]**
	at retrofit2.Platform.findPlatform(Platform.java:44) ~[retrofit-2.9.0.jar:?]
	at retrofit2.Platform.<clinit>(Platform.java:35) ~[retrofit-2.9.0.jar:?]
	at retrofit2.Retrofit$Builder.<init>(Retrofit.java:441) ~[retrofit-2.9.0.jar:?]
```

**Java Details**
```
openjdk 16.0.1 2021-04-20
OpenJDK Runtime Environment AdoptOpenJDK-16.0.1+9 (build 16.0.1+9)
Eclipse OpenJ9 VM AdoptOpenJDK-16.0.1+9 (build openj9-0.26.0, JRE 16 Mac OS X amd64-64-Bit Compressed References 20210421_24 (JIT enabled, AOT enabled)
OpenJ9   - b4cc246d9
OMR      - 162e6f729
JCL      - cea22090ecf based on jdk-16.0.1+9)
```

Could you please offer some direction on how I can get this running?

**Comment by JakeWharton** [comment]
Thanks I think this is tracked by #3535. I've actually started it locally just haven't had time to finish.
