### ISSUE TITLE
Here seems to have a little bug when configuring baseUrl

### ISSUE THREAD

**Issue by WilliamChen-luckbob** [square/retrofit#3658]
I'm a quite new beginner to write android.

When Using retrofit to do a request , I have found something strange here:

My test server side api is set as `http://192.168.0.200:8080/web-security/android/test/conn` and accept a POST request.

Here is my retrofit code block:

**WAY 1**

Interface:
```
public interface SecurityApi {
    @Post("/web-security/android/test/conn")
    Call<JSONObject> testConn();
}
```
Calling of the interface:
```
...

new Retrofit.Builder()
                .baseUrl("http://192.168.0.200:8080/")
                .addConverterFactory(GsonConverterFactory.create())
                .addCallAdapterFactory(RxJava2CallAdapterFactory.create())
                .client(HttpClient.getInstance().getOkHttpClient())
                .build()
                .create(SecurityApi.class)
                .testConn()
                .enqueue(...processing code...);
...
```
It works quite well in this way nothing wrong.

But when I'm trying to change the code to this way, it crashed.

**WAY 2**

Interface:
```
public interface SecurityApi {
    @Post("/android/test/conn")
    Call<JSONObject> testConn();
}
```
Calling of the interface:
```
...

new Retrofit.Builder()
                .baseUrl("http://192.168.0.200:8080/web-security/")
                .addConverterFactory(GsonConverterFactory.create())
                .addCallAdapterFactory(RxJava2CallAdapterFactory.create())
                .client(HttpClient.getInstance().getOkHttpClient())
                .build()
                .create(SecurityApi.class)
                .testConn()
                .enqueue(...processing code...);
...
```

```
E/LoginViewModelLog: {"timestamp":"2021-11-12T06:19:34.634+00:00","status":404,"error":"Not Found","message":"","path":"/android/test/conn"}
    java.lang.RuntimeException: {"timestamp":"2021-11-12T06:19:34.634+00:00","status":404,"error":"Not Found","message":"","path":"/android/test/conn"}
        at com.infiai.simplesender.activities.login.LoginViewModel.request4EncryptObject(LoginViewModel.java:126)
        at com.infiai.simplesender.activities.login.LoginViewModel.lambda$login$0$com-infiai-simplesender-activities-login-LoginViewModel(LoginViewModel.java:65)
        at com.infiai.simplesender.activities.login.LoginViewModel$$ExternalSyntheticLambda0.run(Unknown Source:6)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
```
To fix this problem, I found that by changing `/android/test/conn` to `android/test/conn` will work.
I think there may be a little bug here. If `WAY 1` will work, why `WAY 2` crashed? I think in the source code of retrofit, the first `/` at the beginning of the api should be trimmed automatically.

Can I raise a PR to fix this?

**Comment by WilliamChen-luckbob** [comment]
Well, it seems nothing to do with retrofit, I checked the source code, in HttpUrl.class line 1450, the prefix was deleted...

**Comment by yschimke** [comment]
This is the documented behaviour.  Not a bug.

https://square.github.io/retrofit/

"android/test/conn" is relative

"/android/test/conn" is absolute.

**Comment by WilliamChen-luckbob** [comment]
This is the documented behaviour. Not a bug.  [see here](https://github.com/square/okhttp/issues/6909#issuecomment-966921258)
