### ISSUE TITLE
@Streaming with slow internet connection (for example GPRS) returns SocketTimeoutException

### ISSUE THREAD

**Issue by JackoxD** [square/retrofit#3719]
I have to download a file (30mb).
When I work on Emulator with internet connection sets to full or LTE, or when I work on real device with LTE SIM card everything works well, but when I change internet connection in emulator to GPRS or on real device I use GPRS then connection returns SocketTimeoutException after +- 40 seconds:
` java.net.SocketTimeoutException: timeout
        at okhttp3.internal.http2.Http2Stream$StreamTimeout.newTimeoutException(Http2Stream.kt:677)
        at okhttp3.internal.http2.Http2Stream$StreamTimeout.exitAndThrowIfTimedOut(Http2Stream.kt:686)
        at okhttp3.internal.http2.Http2Stream$FramingSource.read(Http2Stream.kt:382)
        at okhttp3.internal.connection.Exchange$ResponseBodySource.read(Exchange.kt:276)
        at okio.RealBufferedSource.read(RealBufferedSource.kt:189)
        at okio.ForwardingSource.read(ForwardingSource.kt:29)
        at retrofit2.OkHttpCall$ExceptionCatchingResponseBody$1.read(OkHttpCall.java:314)
        at okio.RealBufferedSource.request(RealBufferedSource.kt:206)
        at okio.RealBufferedSource.require(RealBufferedSource.kt:199)
        at okio.RealBufferedSource.readByte(RealBufferedSource.kt:209)
        at com.examplePackage.actualizationFeature.data.repositories.ActualizationRepositoryImpl.saveFile(ActualizationRepositoryImpl.java:148)
        at com.examplePackage.actualizationFeature.data.repositories.ActualizationRepositoryImpl.save(ActualizationRepositoryImpl.java:117)
        at com.examplePackage.actualizationFeature.domain.usescases.DownloadActualizationUseCase.lambda$invoke$1$com-examplePackage-actualizationFeature-domain-usescases-DownloadActualizationUseCase(DownloadActualizationUseCase.java:43)
        at com.examplePackage.actualizationFeature.domain.usescases.DownloadActualizationUseCase$$ExternalSyntheticLambda7.call(Unknown Source:4)
        at io.reactivex.rxjava3.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:43)
        at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)
        at io.reactivex.rxjava3.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
        at io.reactivex.rxjava3.core.Scheduler$DisposeTask.run(Scheduler.java:644)
        at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:65)
        at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:56)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)`

I tried to change the timeouts to much longer ones (10 min). The only difference is that the error occurs later (between 3 - 6 min).
My current settings are as follows:
`new OkHttpClient.Builder()
.connectionSpecs(specList)
 .sslSocketFactory(sslSocketFactory, (X509TrustManager) trustManagers[0])
.connectTimeout(30, TimeUnit.SECONDS)
 .readTimeout(30, TimeUnit.SECONDS)
 .writeTimeout(15, TimeUnit.SECONDS)`
In wireshark I see that device cant release Window buffer:
![image](https://user-images.githubusercontent.com/49169245/161489940-edb45e38-2090-4b0f-93d7-2dfdb9ce6485.png)

What I use (the response may come as .apk or JSON thats why I read first byte in `save` function):
`new Retrofit.Builder()
                .baseUrl(url)
                .client(okHttpClient)
                .addConverterFactory(GsonConverterFactory.create())
                .addCallAdapterFactory(RxJava3CallAdapterFactory.createWithScheduler(Schedulers.io()))
                .build();`

`@GET
    @Streaming
    Single<Response<ResponseBody>> downloadFile(@Url @NonNull final String url);`

`repository.downloadFile(
                getFirmwareUrl())
                .concatMap(responseBody -> {
                    if (responseBody.isSuccessful())
                        return Single.fromCallable(() ->repository.save(responseBody.body())).subscribeOn(Schedulers.io());
                    else
                        return Single.error(new Throwable("Błędna odpowiedź serwera"));
                })`

`public Result<Void> save(ResponseBody responseBody) {
        try {
            Logs.d(TAG, "retrofitSaveFile: path: " + DOWNLOADED_PATH);
            File file = new File(DOWNLOADED_PATH);
            if (!file.exists()) {
                if (!file.mkdirs())
                    return Result.ERROR(new Throwable("Nie można utworzyć pliku"));
            }
            File outputFile = new File(file, file_name);
            if (outputFile.exists()) {
                if (!outputFile.delete())
                    return Result.ERROR(new Throwable("Nie można usunąć pliku"));
            }
            FileOutputStream ffos = new FileOutputStream(outputFile);
            DataOutputStream fos = new DataOutputStream(ffos);
            final BufferedSource source = responseBody.source();
            long lengthOfFile = responseBody.contentLength();
            final int firstByte = source.readByte();
            if (firstByte == '{') {
                saveFile(fos, source, lengthOfFile);
            } else {
                save2File(fos, source, lengthOfFile, firstByte);
            }
            fos.flush();
            fos.close();
            source.close();
            return Result.SUCCESS();
        } catch (Throwable throwable) {
            Log.e(TAG, "save: ", throwable);
            return Result.ERROR(new NetworkExceptions.DownloadingException());
        }
    }`

`private void save2File(DataOutputStream fos, BufferedSource is, long lengthOfFile, int firstByte) throws IOException {
        int count;
        byte[] data = new byte[1024];
        long total = 0;
        fos.write(firstByte);
        while ((count = is.read(data)) != -1) {
            total += count;
            fos.write(data, 0, count);
        }
    }`

In Network Inspector it looks like:
![image](https://user-images.githubusercontent.com/49169245/161492005-72aeba97-e30c-41f1-9334-2000dc427447.png)

If connection  is LTE it looks:
![image](https://user-images.githubusercontent.com/49169245/161492752-b725ed3b-02e3-4210-bc1d-1657db035afb.png)

**Comment by JackoxD** [comment]
I tried with UrlHttpConnection - the same.
I think the problem might be coused by OkHttp.
Can you move this issue to OkHttp?
