### ISSUE TITLE
UnknownHostException when trying to test Retrofit call

### ISSUE THREAD

**Issue by sarimmehdi** [square/retrofit#3722]
What kind of issue is this?

 - [ ] Question. This issue tracker is not the place for questions. If you want to ask how to do
       something, or to understand why something isn't working the way you expect it to, use Stack
       Overflow. https://stackoverflow.com/questions/tagged/retrofit

 - [x] Bug report. If you’ve found a bug, spend the time to write a failing test. Bugs with tests
       get fixed. Here’s an example: https://gist.github.com/swankjesse/6608b4713ad80988cdc9

 - [ ] Feature Request. Start by telling us what problem you’re trying to solve. Often a solution
       already exists! Don’t send pull requests to implement new features without first getting our
       support. Sometimes we leave features out on purpose to keep the project small.

I believe this is a bug because Retrofit calls work fine when I run them normally but fail when I try to test them. This is the code I use to initialize my interface methods with retrofit:

```
OkHttpClient.Builder builder = new OkHttpClient.Builder();
builder.readTimeout(30, TimeUnit.SECONDS);
String url = "https://xkcd.com";
Retrofit retrofit = new Retrofit.Builder()
        .baseUrl(url)
        .client(builder.build())
        .addConverterFactory(GsonConverterFactory.create())
        .build();
xkcdInterface = retrofit.create(XkcdInterface.class);
```
My xkcd interface looks like this:

```
public interface XkcdInterface {

    @GET("info.0.json")
    Call<Comic> getRecentlyAddedComic();

    @GET("{id}/info.0.json")
    Call<Comic> getComic(@Path("id") int id);
}
```
I will now show how I deal with the response of `getComic`:

```
public void getComic(int id, Consumer<Comic> comicConsumer) {
    Call<Comic> call = xkcdInterface.getComic(id);
    Log.d(TAG, "the url is " + call.request().url());
    call.enqueue(new Callback<Comic>() {
        @Override
        public void onResponse(@NotNull Call<Comic> call,
                               @NotNull Response<Comic> response) {
            Log.d(TAG, "response code for getComic: " + response.code());
            Log.d(TAG, "response message for getComic: " + response.message());
            if (response.isSuccessful()) {
                Comic comic = response.body();
                comicConsumer.accept(comic);
            }
            else {
                comicConsumer.accept(null);
            }
        }
        @Override
        public void onFailure(@NotNull Call<Comic> call,
                              @NotNull Throwable t) {
            Log.e(TAG, "stack trace for getComic");
            t.printStackTrace();
            comicConsumer.accept(null);
        }
    });
}
```
Normally, calling the above function in code works as expected. For example, the below code works fine:

```
retrofitHelper.getComic(1, comic -> {
            // some code to handle the comic
        });
```
But, if I try to use similar code for testing purposes, it doesn't work. I even tried using execute instead of enque and even a latch:

```
@Test
public void testGetComic() {
    CountDownLatch latch = new CountDownLatch(1);
    retrofitHelper.getComic(1, comic -> {
        assertEquals(comic.getNum(), 234);
        latch.countDown();
    });

    try {
        latch.await();
    } catch (InterruptedException e) {
        e.printStackTrace();
    }
}
```
But the code doesn't work. I get the following error:

```
04-18 22:33:05.567 14435 14471 D RetrofitHelper: the url is https://xkcd.com/1/info.0.json
04-18 22:33:05.608 14435 14435 E RetrofitHelper: stack trace for getComic
04-18 22:33:05.609 14435 14435 W System.err: java.net.UnknownHostException: Unable to resolve host "xkcd.com": No address associated with hostname
04-18 22:33:05.610 14435 14435 W System.err: 	at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:156)
04-18 22:33:05.610 14435 14435 W System.err: 	at java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:103)
04-18 22:33:05.610 14435 14435 W System.err: 	at java.net.InetAddress.getAllByName(InetAddress.java:1152)
04-18 22:33:05.610 14435 14435 W System.err: 	at okhttp3.Dns$Companion$DnsSystem.lookup(Dns.kt:49)
04-18 22:33:05.610 14435 14435 W System.err: 	at okhttp3.internal.connection.RouteSelector.resetNextInetSocketAddress(RouteSelector.kt:164)
04-18 22:33:05.610 14435 14435 W System.err: 	at okhttp3.internal.connection.RouteSelector.nextProxy(RouteSelector.kt:129)
04-18 22:33:05.610 14435 14435 W System.err: 	at okhttp3.internal.connection.RouteSelector.next(RouteSelector.kt:71)
04-18 22:33:05.610 14435 14435 W System.err: 	at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:205)
04-18 22:33:05.610 14435 14435 W System.err: 	at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:106)
04-18 22:33:05.610 14435 14435 W System.err: 	at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:74)
04-18 22:33:05.610 14435 14435 W System.err: 	at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:255)
04-18 22:33:05.610 14435 14435 W System.err: 	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32)
04-18 22:33:05.610 14435 14435 W System.err: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
04-18 22:33:05.611 14435 14435 W System.err: 	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
04-18 22:33:05.611 14435 14435 W System.err: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
04-18 22:33:05.611 14435 14435 W System.err: 	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
04-18 22:33:05.611 14435 14435 W System.err: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
04-18 22:33:05.611 14435 14435 W System.err: 	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
04-18 22:33:05.611 14435 14435 W System.err: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
04-18 22:33:05.611 14435 14435 W System.err: 	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
04-18 22:33:05.611 14435 14435 W System.err: 	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:517)
04-18 22:33:05.611 14435 14435 W System.err: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
04-18 22:33:05.611 14435 14435 W System.err: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
04-18 22:33:05.611 14435 14435 W System.err: 	at java.lang.Thread.run(Thread.java:920)
04-18 22:33:05.612 14435 14435 W System.err: Caused by: android.system.GaiException: android_getaddrinfo failed: EAI_NODATA (No address associated with hostname)
04-18 22:33:05.613 14435 14435 W System.err: 	at libcore.io.Linux.android_getaddrinfo(Native Method)
04-18 22:33:05.613 14435 14435 W System.err: 	at libcore.io.ForwardingOs.android_getaddrinfo(ForwardingOs.java:136)
04-18 22:33:05.613 14435 14435 W System.err: 	at libcore.io.BlockGuardOs.android_getaddrinfo(BlockGuardOs.java:221)
04-18 22:33:05.613 14435 14435 W System.err: 	at libcore.io.ForwardingOs.android_getaddrinfo(ForwardingOs.java:136)
04-18 22:33:05.613 14435 14435 W System.err: 	at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:135)
```
The website xkcd.com works just fine plus I am actually calling the `https://xkcd.com/1/info.0.json`. If anyone can explain to me this behavior while testing, that would be great.

**Comment by JakeWharton** [comment]
URL resolution happens many layers below Retrofit as the stacktrace indicates. We're nowhere near the code that is running. Retrofit just hands the URL to OkHttp and OkHttp just hands the URL to Android internals which are responsible for DNS resolution. Neither Retrofit nor OkHttp have any ability to influence whether a host name can be resolved or not. This is entirely outside the control of both libraries. This means that the problem lies elsewhere, such as in the configuration of your APK permissions, the test device, or something else. You would see the same exception if you started with Java's `InetAddress` of that URL and tried to resolve it in your test which further illustrates that neither OkHttp or Retrofit are involved here. It's impossible to know what the underlying cause is, but whatever it is once resolved OkHttp and Retrofit will happily start working again.
