### ISSUE TITLE
 java.lang.TypeNotPresentException: Type okhttp3.MultipartBody$Part not present

### ISSUE THREAD

**Issue by jeevanvns** [square/retrofit#3764]
After start kotlin in my project getting crash look like below. its working fine before using kotlin 

 Caused by: java.lang.TypeNotPresentException: Type okhttp3.MultipartBody$Part not present
        at libcore.reflect.ParameterizedTypeImpl.getRawType(ParameterizedTypeImpl.java:69)
        at libcore.reflect.ParameterizedTypeImpl.getResolvedType(ParameterizedTypeImpl.java:77)
        at libcore.reflect.GenericArrayTypeImpl.getGenericComponentType(GenericArrayTypeImpl.java:32)

**Comment by JakeWharton** [comment]
So this could happen if you use a bytecode rewriting tool that is updating type names and signatures but not attributes (where generic information is stored). There's not really anything we can do about this, as the tool is creating a technically-invalid Java class. Something is rewriting your bytecode and that's the tool that needs to get the bug report.
