### ISSUE TITLE
Current version of OkHttp3 crashes on android 5.1.1 and below (prior to API 23)

### ISSUE THREAD

**Issue by yuridiniz** [square/retrofit#3792]
I'm receiving reports of crashes on devices of the mentioned version, I searched the Okhttp3 repository and realized that they already fixed it at the end of 2019, I suspect that the version Retrofit uses does not have the fix

The problem occurs when trying to instantiate a class via reflation in an old version of android, this exception is not caught by a try/catch

They solved it by putting a condition for androids of this version

I am attaching here the commit from the Okhttp3 repository that solves the bug in the library

Is it possible to update the Okhttp3 version to a newer one supported by the current retrofit version?

Commit: https://github.com/square/okhttp/commit/3cde60c06bac804a98c60022c9b72b6526bde707

Stacktrace:
```

# Crashlytics - Stack trace
# Application: br.com.projectnetwork.onibus
# Platform: android
# Version: 4.0.1 (4010)
# Issue: 533810bc211fa3a60eed2cf3b98c933d
# Session: 63A04D7A014F00023BDF692952621975_DNE_0_v2
# Date: Mon Dec 19 2022 08:39:40 GMT-0300 (GMT-03:00)

Fatal Exception: java.lang.NoClassDefFoundError: android.security.NetworkSecurityPolicy
       at java.lang.Class.classForName(Class.java)
       at java.lang.Class.forName(Class.java:309)
       at java.lang.Class.forName(Class.java:273)
       at okhttp3.internal.platform.AndroidPlatform.isCleartextTrafficPermitted(AndroidPlatform.java)
       at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:38)
       at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.java:53)
       at okhttp3.internal.connection.ExchangeFinder.b(ExchangeFinder.java:11)
       at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.java:47)
       at okhttp3.internal.connection.Transmitter.newExchange(Transmitter.java:47)
       at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:47)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:146)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java)
       at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:118)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:146)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java)
       at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:217)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:146)
       at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:158)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:146)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java)
       at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:101)
       at okhttp3.RealCall$AsyncCall.execute(RealCall.java:13)
       at okhttp3.internal.NamedRunnable.run(NamedRunnable.java)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:818)

```

**Comment by JakeWharton** [comment]
The fix you linked was [released in OkHttp 3.12.4](https://square.github.io/okhttp/changelogs/changelog_3x/#version-3124). The fix was not merged to `master`, however, because [OkHttp 3.13 dropped support for Android 4.x](https://square.github.io/okhttp/changelogs/changelog_3x/#version-3130) and the fix was to work around a bug where the try/catch for `ClassNotFoundException` was not working correctly on a Xaoimi 4.x device (probably with a broken Dalvik modification for "reasons").

The latest release of Retrofit, 2.9.0, depends on OkHttp 3.14.9. The code for this function is here: https://github.com/square/okhttp/blob/parent-3.14.9/okhttp/src/main/java/okhttp3/internal/platform/AndroidPlatform.java#L168-L179

The `Class.forName` call [is documented](https://docs.oracle.com/javase/8/docs/api/java/lang/Class.html#forName-java.lang.String-) to throw `ClassNotFoundException` when the class does not exist. Unlike the report which led to that fix in OkHttp 3.12.4 your devices are throwing `NoClassDefFoundError`s which is not the spec of `Class.forName`. That sounds like a very broken Android fork!

Retrofit cannot update its OkHttp version at this time. You can read about why here: https://github.com/square/retrofit/discussions/3753#discussioncomment-3189578.

OkHttp 4.x and the forthcoming OkHttp 5.x are binary compatible with OkHttp 3.14.9, the version we depend on. I would suggest adding an explicit dependency on your desired version of OkHttp so that your build system can select a newer version, provided you are comfortable with the Kotlin dependency.

For now, there's no action on our side that we can take to remedy this.
