### ISSUE TITLE
FATAL EXCEPTION: main

### ISSUE THREAD

**Issue by maq796113** [square/retrofit#3801]
I was running my mobile app that basically uploads files to a smb server but the upload fails everytime. The following is my code that I am using on Android Studio Kotlin. 
[Github Gist](https://gist.github.com/maq796113/06332ade664b2ab7dd872e42c3ff2cf3)
I am using 2.9.0 version of com.squareup.retrofit2:retrofit with JDK version 18.0.2.1. 

The following is the error I am getting whenever I run the app on my phone. 

```
FATAL EXCEPTION: main
                                                                                                    Process: com.example.qurantutor, PID: 32057
                                                                                                    java.lang.ExceptionInInitializerError
                                                                                                    	at com.example.qurantutor.RecitationActivity.uploadRecitation(RecitationActivity.kt:108)
                                                                                                    	at com.example.qurantutor.RecitationActivity.stopRecording(RecitationActivity.kt:99)
                                                                                                    	at com.example.qurantutor.RecitationActivity.onRecord(RecitationActivity.kt:73)
                                                                                                    	at com.example.qurantutor.RecitationActivity.onCreate$lambda$2(RecitationActivity.kt:155)
                                                                                                    	at com.example.qurantutor.RecitationActivity.$r8$lambda$l2q5Kdsoz5WoCTU6P_F4HSTWP04(Unknown Source:0)
                                                                                                    	at com.example.qurantutor.RecitationActivity$$ExternalSyntheticLambda0.onClick(Unknown Source:4)
                                                                                                    	at android.view.View.performClick(View.java:7465)
                                                                                                    	at com.google.android.material.button.MaterialButton.performClick(MaterialButton.java:1219)
                                                                                                    	at android.view.View.performClickInternal(View.java:7438)
                                                                                                    	at android.view.View.access$3600(View.java:813)
                                                                                                    	at android.view.View$PerformClick.run(View.java:28511)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:938)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loop(Looper.java:268)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8017)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:627)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:997)
                                                                                                    Caused by: java.lang.IllegalArgumentException: Expected URL scheme 'http' or 'https' but was 'smb'
                                                                                                    	at okhttp3.HttpUrl$Builder.parse(HttpUrl.java:1327)
                                                                                                    	at okhttp3.HttpUrl.get(HttpUrl.java:917)
                                                                                                    	at retrofit2.Retrofit$Builder.baseUrl(Retrofit.java:506)
                                                                                                    	at com.example.qurantutor.network.RetrofitBuilderSmb.<clinit>(RetrofitBuilderSmb.kt:11)
                                                                                                    	at com.example.qurantutor.RecitationActivity.uploadRecitation(RecitationActivity.kt:108) 
                                                                                                    	at com.example.qurantutor.RecitationActivity.stopRecording(RecitationActivity.kt:99) 
                                                                                                    	at com.example.qurantutor.RecitationActivity.onRecord(RecitationActivity.kt:73) 
                                                                                                    	at com.example.qurantutor.RecitationActivity.onCreate$lambda$2(RecitationActivity.kt:155) 
                                                                                                    	at com.example.qurantutor.RecitationActivity.$r8$lambda$l2q5Kdsoz5WoCTU6P_F4HSTWP04(Unknown Source:0) 
                                                                                                    	at com.example.qurantutor.RecitationActivity$$ExternalSyntheticLambda0.onClick(Unknown Source:4) 
                                                                                                    	at android.view.View.performClick(View.java:7465) 
                                                                                                    	at com.google.android.material.button.MaterialButton.performClick(MaterialButton.java:1219) 
                                                                                                    	at android.view.View.performClickInternal(View.java:7438) 
                                                                                                    	at android.view.View.access$3600(View.java:813) 
                                                                                                    	at android.view.View$PerformClick.run(View.java:28511) 
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:938) 
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99) 
                                                                                                    	at android.os.Looper.loop(Looper.java:268) 
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8017) 
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:627) 
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:997) 
```

**Comment by JakeWharton** [comment]
OkHttp, the HTTP client that Retrofit uses, only supports the http and https protocols. smb is not supported. You'll need to access it over some kind of HTTP bridge or API.

**Comment by maq796113** [comment]
I am using Smb file
