### ISSUE TITLE
Request cancelled randomly on interceptors

### ISSUE THREAD

**Issue by sarthakgandhidunzo** [square/retrofit#3848]
`Non-fatal Exception: java.io.IOException: Canceled
       at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:208)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:166)
       at com.chuckerteam.chucker.api.ChuckerInterceptor.intercept(ChuckerInterceptor.java:9)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:166)
       at com.pharmasentinel.medsii.retrofit.HeaderInterceptor.intercept(HeaderInterceptor.java:37)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:166)
       at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.java:113)
       at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.java:51)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
       at java.lang.Thread.run(Thread.java:1012)`

Getting this exception randomly without cancelling the request. I am using a suspend functions along with CoroutineCallAdapterFactory

**Comment by jbaris** [comment]
Any progress on this? We have the same issue.

**Comment by JakeWharton** [comment]
If the scope in which your suspend function is executing is cancelled the request will also be cancelled. Aside from that, Retrofit is not involved in OkHttp behaviors. Request cancellation is a normal thing that you need to expect to happen, like any other transport-level exceptions.
