### ISSUE TITLE
`serviceMethodCache` can cause lock contention (and ANR)

### ISSUE THREAD

**Issue by yogurtearl** [square/retrofit#3992]
With `moshi-kotlin` `1.15.0` and Retrofit `2.9.0`. 

(and putting aside the "this shouldn't be on the main thread" and "use code gen not reflection" issues)

Getting some ANRs related to the `synchronized` block on `serviceMethodCache`: 

https://github.com/square/retrofit/blob/f044ddc18bda15a8189d93a6cd6c3167c06d440e/retrofit/src/main/java/retrofit2/Retrofit.java#L205-L211

As you pointed out here (https://github.com/square/retrofit/pull/2017#discussion_r79294227), the syncronized block could be avoided with `computeIfAbsent` in JDK 8+: 
https://github.com/square/retrofit/pull/2017#discussion_r79294227

Thoughts on adding a call `computeIfAbsent` to retrofit? 

ANR here: 
```
main (blocked):tid=1 systid=22841 | waiting to lock <0x03b3cdae> (java.util.concurrent.ConcurrentHashMap) held by thread 60
       at retrofit2.Retrofit.loadServiceMethod(Retrofit.java:199)
       at retrofit2.Retrofit$1.invoke(Retrofit.java:160)
       at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
       at com.example.MyRetrofitService.getStuff(MyRetrofitService.kt)
       at com.example.StuffRepository.getStuff(StuffRepository.kt:48)
       at com.example.StuffRepository.getStuff$initStuffState$1.invokeSuspend(StuffRepository.kt:45)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
       at android.os.Handler.handleCallback(Handler.java:958)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:205)
       at android.os.Looper.loop(Looper.java:294)
       at android.app.ActivityThread.main(ActivityThread.java:8177)
       at java.lang.reflect.Method.invoke(Native method)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
```

With this in the background:
```
DefaultDispatcher-worker-13 (runnable):tid=60 systid=23035 
       at kotlin.collections.EmptyMap.getValues(Maps.kt:29)
       at kotlin.collections.EmptyMap.values(Maps.kt:14)
       at kotlin.reflect.jvm.internal.impl.serialization.deserialization.TypeDeserializer.getOwnTypeParameters(TypeDeserializer.kt:57)
       at kotlin.reflect.jvm.internal.impl.serialization.deserialization.MemberDeserializer.loadFunction(MemberDeserializer.kt:216)
       at kotlin.reflect.jvm.internal.impl.serialization.deserialization.descriptors.DeserializedMemberScope$OptimizedImplementation.computeFunctions(DeserializedMemberScope.kt:276)
       at kotlin.reflect.jvm.internal.impl.serialization.deserialization.descriptors.DeserializedMemberScope$OptimizedImplementation.access$computeFunctions(DeserializedMemberScope.kt:228)
       at kotlin.reflect.jvm.internal.impl.serialization.deserialization.descriptors.DeserializedMemberScope$OptimizedImplementation$functions$1.invoke(DeserializedMemberScope.kt:251)
       at kotlin.reflect.jvm.internal.impl.serialization.deserialization.descriptors.DeserializedMemberScope$OptimizedImplementation$functions$1.invoke(DeserializedMemberScope.kt:251)
       at kotlin.reflect.jvm.internal.impl.storage.LockBasedStorageManager$MapBasedMemoizedFunction.invoke(LockBasedStorageManager.java:578)
       at kotlin.reflect.jvm.internal.impl.storage.LockBasedStorageManager$MapBasedMemoizedFunctionToNotNull.invoke(LockBasedStorageManager.java:681)
       at kotlin.reflect.jvm.internal.impl.serialization.deserialization.descriptors.DeserializedMemberScope$OptimizedImplementation.getContributedFunctions(DeserializedMemberScope.kt:329)
       at kotlin.reflect.jvm.internal.impl.serialization.deserialization.descriptors.DeserializedMemberScope$OptimizedImplementation.addFunctionsAndPropertiesTo(DeserializedMemberScope.kt:360)
       at kotlin.reflect.jvm.internal.impl.serialization.deserialization.descriptors.DeserializedMemberScope.computeDescriptors(DeserializedMemberScope.kt:115)
       at kotlin.reflect.jvm.internal.impl.serialization.deserialization.descriptors.DeserializedClassDescriptor$DeserializedClassMemberScope$allDescriptors$1.invoke(DeserializedClassDescriptor.kt:277)
       at kotlin.reflect.jvm.internal.impl.serialization.deserialization.descriptors.DeserializedClassDescriptor$DeserializedClassMemberScope$allDescriptors$1.invoke(DeserializedClassDescriptor.kt:276)
       at kotlin.reflect.jvm.internal.impl.storage.LockBasedStorageManager$LockBasedLazyValue.invoke(LockBasedStorageManager.java:408)
       at kotlin.reflect.jvm.internal.impl.storage.LockBasedStorageManager$LockBasedNotNullLazyValue.invoke(LockBasedStorageManager.java:527)
       at kotlin.reflect.jvm.internal.impl.serialization.deserialization.descriptors.DeserializedClassDescriptor$DeserializedClassMemberScope.getContributedDescriptors(DeserializedClassDescriptor.kt:287)
       at kotlin.reflect.jvm.internal.impl.resolve.scopes.ResolutionScope$DefaultImpls.getContributedDescriptors$default(ResolutionScope.kt:50)
       at kotlin.reflect.jvm.internal.KDeclarationContainerImpl.getMembers(KDeclarationContainerImpl.kt:58)
       at kotlin.reflect.jvm.internal.KClassImpl$Data$declaredNonStaticMembers$2.invoke(KClassImpl.kt:173)
       at kotlin.reflect.jvm.internal.KClassImpl$Data$declaredNonStaticMembers$2.invoke(KClassImpl.kt:173)
       at kotlin.reflect.jvm.internal.ReflectProperties$LazySoftVal.invoke(ReflectProperties.java:70)
       at kotlin.reflect.jvm.internal.ReflectProperties$Val.getValue(ReflectProperties.java:32)
       at kotlin.reflect.jvm.internal.KClassImpl$Data.getDeclaredNonStaticMembers(KClassImpl.kt:173)
       at kotlin.reflect.jvm.internal.KClassImpl$Data$allNonStaticMembers$2.invoke(KClassImpl.kt:182)
       at kotlin.reflect.jvm.internal.KClassImpl$Data$allNonStaticMembers$2.invoke(KClassImpl.kt:182)
       at kotlin.reflect.jvm.internal.ReflectProperties$LazySoftVal.invoke(ReflectProperties.java:70)
       at kotlin.reflect.jvm.internal.ReflectProperties$Val.getValue(ReflectProperties.java:32)
       at kotlin.reflect.jvm.internal.KClassImpl$Data.getAllNonStaticMembers(KClassImpl.kt:182)
       at kotlin.reflect.full.KClasses.getMemberProperties(KClasses.kt:148)
       at com.squareup.moshi.kotlin.reflect.KotlinJsonAdapterFactory.create(KotlinJsonAdapter.kt:234)
       at com.squareup.moshi.Moshi.adapter(Moshi.java:146)
       at com.squareup.moshi.kotlin.reflect.KotlinJsonAdapterFactory.create(KotlinJsonAdapter.kt:292)
       at com.squareup.moshi.Moshi.adapter(Moshi.java:146)
       at com.squareup.moshi.kotlin.reflect.KotlinJsonAdapterFactory.create(KotlinJsonAdapter.kt:292)
       at com.squareup.moshi.Moshi.adapter(Moshi.java:146)
       at com.squareup.moshi.Moshi.adapter(Moshi.java:106)
       at com.squareup.moshi.Moshi.adapter(Moshi.java:75)
       at com.squareup.moshi.CollectionJsonAdapter.newArrayListAdapter(CollectionJsonAdapter.java:54)
       at com.squareup.moshi.CollectionJsonAdapter$1.create(CollectionJsonAdapter.java:38)
       at com.squareup.moshi.Moshi.adapter(Moshi.java:146)
       at com.squareup.moshi.kotlin.reflect.KotlinJsonAdapterFactory.create(KotlinJsonAdapter.kt:292)
       at com.squareup.moshi.Moshi.adapter(Moshi.java:146)
       at com.squareup.moshi.kotlin.reflect.KotlinJsonAdapterFactory.create(KotlinJsonAdapter.kt:292)
       at com.squareup.moshi.Moshi.adapter(Moshi.java:146)
       at com.squareup.moshi.Moshi.adapter(Moshi.java:106)
       at com.squareup.moshi.Moshi.adapter(Moshi.java:75)
       at com.squareup.moshi.CollectionJsonAdapter.newArrayListAdapter(CollectionJsonAdapter.java:54)
       at com.squareup.moshi.CollectionJsonAdapter$1.create(CollectionJsonAdapter.java:38)
       at com.squareup.moshi.Moshi.adapter(Moshi.java:146)
       at com.squareup.moshi.kotlin.reflect.KotlinJsonAdapterFactory.create(KotlinJsonAdapter.kt:292)
       at com.squareup.moshi.Moshi.adapter(Moshi.java:146)
       at com.squareup.moshi.Moshi.adapter(Moshi.java:106)
       at retrofit2.converter.moshi.MoshiConverterFactory.responseBodyConverter(MoshiConverterFactory.java:89)
       at retrofit2.Retrofit.nextResponseBodyConverter(Retrofit.java:362)
       at retrofit2.Retrofit.responseBodyConverter(Retrofit.java:345)
       at retrofit2.HttpServiceMethod.createResponseConverter(HttpServiceMethod.java:124)
       at retrofit2.HttpServiceMethod.parseAnnotations(HttpServiceMethod.java:85)
       at retrofit2.ServiceMethod.parseAnnotations(ServiceMethod.java:39)
       at retrofit2.Retrofit.loadServiceMethod(Retrofit.java:202)
       at retrofit2.Retrofit$1.invoke(Retrofit.java:160)
       at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
       at com.example.MyRetrofitService.getUsers(MyRetrofitService.kt)
       at com.example.UserFetcher$fetchUser$1$loadInfo$4.invokeSuspend(UserFetcher.kt:66)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
```

**Comment by JakeWharton** [comment]
#3893 also addresses this, I believe.

**Comment by yogurtearl** [comment]
It helps, but in the case I ran into recently it was actually all part of the same Service interface (probably too much in one interface)

https://github.com/square/retrofit/pull/3893 still has the potentially expensive call to `parseAnnotations` inside the `synchronized` block in a code path that will likely be called from different threads.

**Comment by JakeWharton** [comment]
As of Retrofit 2.7 we require Java 8, however, our minimum-supported Android version remains API 21 (where `computeIfAbsent` is API 24). Now it is available via desugaring, but so far neither us nor our dependencies require the use of desugaring.

I think we'll have to solve this with granular lock objects in the map and only take the map lock when one is missing. Will try.
