### ISSUE TITLE
BodyObservable$BodyObserver.onNext - FIREBASE CRASH

### ISSUE THREAD

**Issue by rushilalgiyabrainvire** [square/retrofit#4276]
Fatal Exception: io.reactivex.rxjava3.exceptions.OnErrorNotImplementedException: The exception was not handled due to missing onError handler in the subscribe() method call. Further reading: https://github.com/ReactiveX/RxJava/wiki/Error-Handling | retrofit2.adapter.rxjava3.HttpException: HTTP 403 
       at io.reactivex.rxjava3.exceptions.OnErrorNotImplementedException.<init>(OnErrorNotImplementedException.java:39)
       at io.reactivex.rxjava3.exceptions.OnErrorNotImplementedException.<init>(OnErrorNotImplementedException.java:51)
       at io.reactivex.rxjava3.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:718)
       at io.reactivex.rxjava3.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:715)
       at io.reactivex.rxjava3.internal.observers.LambdaObserver.onError(LambdaObserver.java:77)
       at io.reactivex.rxjava3.internal.operators.observable.ObservableSubscribeOn$SubscribeOnObserver.onError(ObservableSubscribeOn.java:63)
       at io.reactivex.rxjava3.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.checkTerminated(ObservableObserveOn.java:282)
       at io.reactivex.rxjava3.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.drainNormal(ObservableObserveOn.java:173)
       at io.reactivex.rxjava3.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.run(ObservableObserveOn.java:256)
       at io.reactivex.rxjava3.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:123)
       at android.os.Handler.handleCallback(Handler.java:1000)
       at android.os.Handler.dispatchMessage(Handler.java:104)
       at android.os.Looper.loopOnce(Looper.java:242)
       at android.os.Looper.loop(Looper.java:362)
       at android.app.ActivityThread.main(ActivityThread.java:8448)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:992)
        

          Caused by retrofit2.adapter.rxjava3.HttpException: HTTP 403 
       at retrofit2.adapter.rxjava3.BodyObservable$BodyObserver.onNext(BodyObservable.java:57)
       at retrofit2.adapter.rxjava3.BodyObservable$BodyObserver.onNext(BodyObservable.java:38)
       at retrofit2.adapter.rxjava3.CallEnqueueObservable$CallCallback.onResponse(CallEnqueueObservable.java:62)
       at retrofit2.OkHttpCall$1.onResponse(OkHttpCall.java:164)
       at com.google.firebase.perf.network.InstrumentOkHttpEnqueueCallback.onResponse(InstrumentOkHttpEnqueueCallback.java:71)
       at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:535)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
       at java.lang.Thread.run(Thread.java:1012)

**Comment by JakeWharton** [comment]
This is telling you that you didn't implement onError when subscribing to an observable returned by Retrofit, and when a subsequent HTTP request failed it had nowhere to deliver to the error.
