### ISSUE TITLE
url == null exception

### ISSUE THREAD

**Issue by julio-cotta-edx** [square/retrofit#487]
Hi, My rest calls are comming with this error:

``` JAVA
 <--- END HTTP (1517-byte body)
 ---- ERROR $MY_URL
 GC_FOR_ALLOC freed 10166K, 45% free 13584K/24404K, paused 100ms, total 101ms
java.lang.IllegalArgumentException: url == null
    at retrofit.client.Response.<init>(Response.java:33)
    at retrofit.Utils.replaceResponseBody(Utils.java:97)
    at retrofit.RestAdapter$RestHandler.invokeRequest(RestAdapter.java:371)
    at retrofit.RestAdapter$RestHandler.invoke(RestAdapter.java:241)

```

Any ideas of what can it be? Could it be any missing header in the response?
Thanks

**Comment by evrenozturkhurriyet** [comment]
Maybe this will help someone.
I had the same error.
When I debug I saw that, this method:
okhttp3.HttpUrl.Builder.parse(HttpUrl base, String input)
returns "UNSUPPORTED_SCHEME" as a result.
Which means url == null exception. :)

Yea my bad...
The way I fix the error is changing those lines:
```

    private static Retrofit buildRetrofit() {
        return new Retrofit.Builder().baseUrl("https://yoururl/somepath/**yourmethodname/**")
       ...
   }
   public interface YourServiceInterface {
       @GET("{yourRelativePath}")
       Call<YourResponse> getYourData(@Path("yourRelativePath") String yourRelativePathParam);
   }
```

------------------
with those lines:
```

    private static Retrofit buildRetrofit() {
        return new Retrofit.Builder().baseUrl("https://yoururl/somepath/")
       ...
   }
   public interface YourServiceInterface {
       @GET("**yourmethodname/**{yourRelativePath}")
       Call<YourResponse> getYourData(@Path("yourRelativePath") String yourRelativePathParam);
   }
```
