### ISSUE TITLE
RetrofitError cannot be serialized, extends RuntimeException

### ISSUE THREAD

**Issue by Lien** [square/retrofit#669]
A RuntimeException is thrown if you attempt to serialize a RetrofitError that was created with a non-null Converter.

The converter field should be marked `transient`.

```
java.lang.RuntimeException: Parcelable encountered IOException writing serializable object 
...
Caused by: java.io.NotSerializableException: retrofit.converter.GsonConverter
       at java.io.ObjectOutputStream.writeNewObject(ObjectOutputStream.java:1364)
       at java.io.ObjectOutputStream.writeObjectInternal(ObjectOutputStream.java:1671)
       at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:1517)
       at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:1481)
       at java.io.ObjectOutputStream.writeFieldValues(ObjectOutputStream.java:979)
       at java.io.ObjectOutputStream.defaultWriteObject(ObjectOutputStream.java:368)
       at java.io.ObjectOutputStream.writeHierarchy(ObjectOutputStream.java:1074)
       at java.io.ObjectOutputStream.writeNewObject(ObjectOutputStream.java:1404)
       at java.io.ObjectOutputStream.writeObjectInternal(ObjectOutputStream.java:1671)
       at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:1517)
       at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:1481)
       at java.io.ObjectOutputStream.writeFieldValues(ObjectOutputStream.java:979)
       at java.io.ObjectOutputStream.defaultWriteObject(ObjectOutputStream.java:368)
       at java.io.ObjectOutputStream.writeHierarchy(ObjectOutputStream.java:1074)
       at java.io.ObjectOutputStream.writeNewObject(ObjectOutputStream.java:1404)
       at java.io.ObjectOutputStream.writeObjectInternal(ObjectOutputStream.java:1671)
       at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:1517)
       at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:1481)
       at java.io.ObjectOutputStream.writeFieldValues(ObjectOutputStream.java:979)
       at java.io.ObjectOutputStream.defaultWriteObject(ObjectOutputStream.java:368)
       at java.lang.Throwable.writeObject(Throwable.java:446)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:511)
       at java.io.ObjectOutputStream.writeHierarchy(ObjectOutputStream.java:1053)
       at java.io.ObjectOutputStream.writeNewObject(ObjectOutputStream.java:1404)
       at java.io.ObjectOutputStream.writeObjectInternal(ObjectOutputStream.java:1671)
       at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:1517)
       at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:1481)
       at android.os.Parcel.writeSerializable(Parcel.java:1274)
       at android.os.Parcel.writeValue(Parcel.java:1233)
       at android.os.Parcel.writeMapInternal(Parcel.java:591)
       at android.os.Bundle.writeToParcel(Bundle.java:1627)
       at android.os.Parcel.writeBundle(Parcel.java:605)
       at android.content.Intent.writeToParcel(Intent.java:6751)
       at android.app.ActivityManagerProxy.finishActivity(ActivityManagerNative.java:2074)
       at android.app.Activity.finish(Activity.java:4230)
```

**Comment by WVan** [comment]
Any news on this? I'm using ACRA to report 500 errors and ACRA serialises the RetrofitError caused by the 500 error.
