### ISSUE TITLE
[Question] $Proxy1.getProfessionalProfile(Unknown Source)

### ISSUE THREAD

**Issue by Salma7amed** [square/retrofit#699]
I get a `retrofitError` when trying to preform a synchronous execution although the same request doesn't give me an error when changing the api to performing the same request asynchronous.

Client side:
```java
RestAdapter restAdapter = new RestAdapter.Builder()
       .setEndpoint(BASE_URL)
       .setConverter(converter)
       .setLogLevel(RestAdapter.LogLevel.FULL)
       .build();
apiService = restAdapter.create(ApiService.class); 
apiService.getProfessionalProfile(id);
```
Retrofit Api:
```java
@GET("/api/professionals/{id}")
Professional getProfessionalProfile(@Path("id") int userId);
```

**Comment by JakeWharton** [comment]
Paste the entire error.

**Comment by Salma7amed** [comment]
```
01-08 00:27:32.000: E/AndroidRuntime(21584): FATAL EXCEPTION: main
01-08 00:27:32.000: E/AndroidRuntime(21584): Process: com.hipolink.application, PID: 21584
01-08 00:27:32.000: E/AndroidRuntime(21584): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.hipolink.application/com.hipolink.activities.MainActivity}: retrofit.RetrofitError
01-08 00:27:32.000: E/AndroidRuntime(21584): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2298)
01-08 00:27:32.000: E/AndroidRuntime(21584): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2360)
01-08 00:27:32.000: E/AndroidRuntime(21584): 	at android.app.ActivityThread.access$800(ActivityThread.java:144)
01-08 00:27:32.000: E/AndroidRuntime(21584): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1278)
01-08 00:27:32.000: E/AndroidRuntime(21584): 	at android.os.Handler.dispatchMessage(Handler.java:102)
01-08 00:27:32.000: E/AndroidRuntime(21584): 	at android.os.Looper.loop(Looper.java:135)
01-08 00:27:32.000: E/AndroidRuntime(21584): 	at android.app.ActivityThread.main(ActivityThread.java:5221)
01-08 00:27:32.000: E/AndroidRuntime(21584): 	at java.lang.reflect.Method.invoke(Native Method)
01-08 00:27:32.000: E/AndroidRuntime(21584): 	at java.lang.reflect.Method.invoke(Method.java:372)
01-08 00:27:32.000: E/AndroidRuntime(21584): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
01-08 00:27:32.000: E/AndroidRuntime(21584): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
01-08 00:27:32.000: E/AndroidRuntime(21584): Caused by: retrofit.RetrofitError
01-08 00:27:32.000: E/AndroidRuntime(21584): 	at retrofit.RestAdapter$RestHandler.invokeRequest(RestAdapter.java:395)
01-08 00:27:32.000: E/AndroidRuntime(21584): 	at retrofit.RestAdapter$RestHandler.invoke(RestAdapter.java:240)
01-08 00:27:32.000: E/AndroidRuntime(21584): 	at java.lang.reflect.Proxy.invoke(Proxy.java:397)
01-08 00:27:32.000: E/AndroidRuntime(21584): 	at $Proxy1.getProfessionalProfile(Unknown Source)
01-08 00:27:32.000: E/AndroidRuntime(21584): 	at com.hipolink.activities.MainActivity.getProfileFragment(MainActivity.java:268)
01-08 00:27:32.000: E/AndroidRuntime(21584): 	at com.hipolink.activities.MainActivity.displayView(MainActivity.java:217)
01-08 00:27:32.000: E/AndroidRuntime(21584): 	at com.hipolink.activities.MainActivity.onCreate(MainActivity.java:156)
01-08 00:27:32.000: E/AndroidRuntime(21584): 	at android.app.Activity.performCreate(Activity.java:5933)
01-08 00:27:32.000: E/AndroidRuntime(21584): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1105)
01-08 00:27:32.000: E/AndroidRuntime(21584): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2251)
01-08 00:27:32.000: E/AndroidRuntime(21584): 	... 10 more
01-08 00:27:32.000: E/AndroidRuntime(21584): Caused by: android.os.NetworkOnMainThreadException
01-08 00:27:32.000: E/AndroidRuntime(21584): 	at android.os.StrictMode$AndroidBlockGuardPolicy.onNetwork(StrictMode.java:1147)
01-08 00:27:32.000: E/AndroidRuntime(21584): 	at libcore.io.BlockGuardOs.recvfrom(BlockGuardOs.java:249)
01-08 00:27:32.000: E/AndroidRuntime(21584): 	at libcore.io.IoBridge.recvfrom(IoBridge.java:553)
01-08 00:27:32.000: E/AndroidRuntime(21584): 	at java.net.PlainSocketImpl.read(PlainSocketImpl.java:485)
01-08 00:27:32.000: E/AndroidRuntime(21584): 	at java.net.PlainSocketImpl.access$000(PlainSocketImpl.java:37)
01-08 00:27:32.000: E/AndroidRuntime(21584): 	at java.net.PlainSocketImpl$PlainSocketInputStream.read(PlainSocketImpl.java:237)
01-08 00:27:32.000: E/AndroidRuntime(21584): 	at okio.Okio$2.read(Okio.java:136)
01-08 00:27:32.000: E/AndroidRuntime(21584): 	at okio.AsyncTimeout$2.read(AsyncTimeout.java:211)
01-08 00:27:32.000: E/AndroidRuntime(21584): 	at okio.RealBufferedSource.indexOf(RealBufferedSource.java:244)
01-08 00:27:32.000: E/AndroidRuntime(21584): 	at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:191)
01-08 00:27:32.000: E/AndroidRuntime(21584): 	at com.squareup.okhttp.internal.http.HttpConnection.readResponse(HttpConnection.java:187)
01-08 00:27:32.000: E/AndroidRuntime(21584): 	at com.squareup.okhttp.internal.http.HttpTransport.readResponseHeaders(HttpTransport.java:78)
01-08 00:27:32.000: E/AndroidRuntime(21584): 	at com.squareup.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:665)
01-08 00:27:32.000: E/AndroidRuntime(21584): 	at com.squareup.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:429)
01-08 00:27:32.000: E/AndroidRuntime(21584): 	at com.squareup.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:374)
01-08 00:27:32.000: E/AndroidRuntime(21584): 	at com.squareup.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:469)
01-08 00:27:32.000: E/AndroidRuntime(21584): 	at retrofit.client.UrlConnectionClient.readResponse(UrlConnectionClient.java:73)
01-08 00:27:32.000: E/AndroidRuntime(21584): 	at retrofit.client.UrlConnectionClient.execute(UrlConnectionClient.java:38)
01-08 00:27:32.000: E/AndroidRuntime(21584): 	at retrofit.RestAdapter$RestHandler.invokeRequest(RestAdapter.java:321)
01-08 00:27:32.000: E/AndroidRuntime(21584): 	... 19 more
```

**Comment by JakeWharton** [comment]
You are trying to make an HTTP call on the Android main thread. The Android OS does not allow this. You need to use your own thread if you want to make a synchronous call or you have to use the async `Callback` approach.

**Comment by Salma7amed** [comment]
Thanks a lot.
