### ISSUE TITLE
404 Document with the given Id not found

### ISSUE THREAD

**Issue by saadfarooq** [square/retrofit#743]
I see the following error in my logs on Android. It does not crash the app but I am wondering what causes this and possibly what I'm doing wrong that might cause this ?

    retrofit.RetrofitError: 404 Document with the given Id not found
            at retrofit.RestAdapter$RestHandler.invokeRequest(RestAdapter.java:388)
            at retrofit.RestAdapter$RestHandler.access$100(RestAdapter.java:220)
            at retrofit.RestAdapter$RestHandler$2.obtainResponse(RestAdapter.java:278)
            at retrofit.CallbackRunnable.run(CallbackRunnable.java:42)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at retrofit.Platform$Android$2$1.run(Platform.java:142)
            at java.lang.Thread.run(Thread.java:818)

**Comment by casidiablo** [comment]
This doesn't look like a retrofit problem. It rather looks like a 404 returned by the server you are hitting. I'd try logging retrofit requests and play around with them from curl or httpie.

**Comment by JakeWharton** [comment]
Indeed. That is the response code and message from the HTTP server.

**Comment by kingsammalik** [comment]
i am getting 404 not found error in retrofit. the URL is fine, i checked it.

**Comment by wesseljb** [comment]
I'm getting the same issue
