### ISSUE TITLE
EOFException handling gzip response with Retrofit + OkHttp

### ISSUE THREAD

**Issue by dfpalomar** [square/retrofit#755]
I'm trying to process a gzipped response from my web services but I'm always getting ***EOFException: source exhausted prematurely***. 

These are the versions of my libraries:

    retrofit: 1.9.0
    okhttp: 2.2.0
    okhttp-urlconnection: 2.2.0
    gson: 2.3.1

Below my code and outputs:

    RestAdapter restAdapter = new RestAdapter.Builder()
        .setLogLevel(RestAdapter.LogLevel.FULL)
        .setClient(new OkClient(new OkHttpClient()))
        .setEndpoint("http://myserver.com/services")
        .build();

    ... 

    @GET("/mobile/user/new") 
    String registerNewAccount();

*Request registered by Charles (debugging proxy)*

    GET /services/mobile/user/new HTTP/1.1
    User-Agent: Dalvik/1.6.0 (Linux; U; Android 4.3; GT-I9300 Build/JSS15J)
    Host: myserver.com
    Connection: Keep-Alive
    Accept-Encoding: gzip

*Response registered by Charles*

    HTTP/1.1 200 OK
    Date	Fri, 20 Feb 2015 00:47:13 GMT
    Server	Apache-Coyote/1.1
    Content-Encoding	gzip
    Content-Type	application/json
    Content-Length	32
    Via	1.1 myserver.com
    Keep-Alive	timeout=5, max=100
    Connection	Keep-Alive

*Retrofit log output*

    <--- HTTP 200 http://myserver.com/services/mobile/user/new (666ms)
    Date: Fri, 20 Feb 2015 00:59:44 GMT
    Server: Apache-Coyote/1.1
    Content-Type: application/json
    Via: 1.1 myserver.com
    Keep-Alive: timeout=5, max=100
    Proxy-Connection: Keep-alive
    OkHttp-Selected-Protocol: http/1.1
    OkHttp-Sent-Millis: 1424393970658
    OkHttp-Received-Millis: 1424393971268
    
    ---- ERROR http://myserver.com/services/mobile/user/new
    java.io.EOFException: source exhausted prematurely
    	at okio.InflaterSource.read(InflaterSource.java:77)
    	at okio.GzipSource.read(GzipSource.java:80)
    	at okio.RealBufferedSource$1.read(RealBufferedSource.java:298)
    	at java.io.InputStream.read(InputStream.java:163)
    	at retrofit.Utils.streamToBytes(Utils.java:43)
    	at retrofit.Utils.readBodyToBytesIfNecessary(Utils.java:81)
    	at retrofit.RestAdapter.logAndReplaceResponse(RestAdapter.java:483)
    	at retrofit.RestAdapter.access$500(RestAdapter.java:107)
    	at retrofit.RestAdapter$RestHandler.invokeRequest(RestAdapter.java:338)
    	at retrofit.RestAdapter$RestHandler.invoke(RestAdapter.java:240)
    	at $Proxy0.registerNewAccount(Native Method)
    	at com.myapp.tasks.RegisterUserTask.doInBackground(RegisterUserTask.java:36)
    	at com.myapp.tasks.RegisterUserTask.doInBackground(RegisterUserTask.java:19)
    	at android.os.AsyncTask$2.call(AsyncTask.java:287)
    	at java.util.concurrent.FutureTask.run(FutureTask.java:234)
    	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:230)
    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
    	at java.lang.Thread.run(Thread.java:841)
    D/Retrofit(9508): ---- END ERROR

I've been trying to figure out what's happening for hours with no results :$ Any help will be really appreciated :)

**Comment by JakeWharton** [comment]
So at the very least, this isn't a Retrofit problem. If there *is* a problem with a library (which I'm doubtful of) it would be in OkHttp or potentially even in Okio. So that's good news for me.

I strongly suspect that your problem is in the HTTP response. Are you able to see how many bytes are in the actual response body in Charles? Is it 32, as the header reports?

Also, as of Retrofit 1.9.0 you no longer need to include the `okhttp-urlconnection` dependency. Kill that thing! (It's completely unused)

**Comment by deionalims** [comment]
Hello.

I have the exact same problem. It's on a 204 http response though okio tries to read the body and it ends up as a EOFException. We can easily see that it appears in the logAndReplaceResponse() method. It logs correctly the headers and for some reason it wants to log the body that is empty and it crashes. 
I'm out of ideas. Any advice would really help. Thanks.

**Comment by JakeWharton** [comment]
@deionalims Your bug is #735.

**Comment by JakeWharton** [comment]
@dfpalomar Without access to the actual bytes I cannot diagnose this problem. This error occurs when the gzip is malformed or gets truncated in some way. Bottom line: this isn't a Retrofit problem. If a problem exists it's in Okio's gzip code. That is an unlikely scenario, so I feel much more confident that it's a malformed response from your server.

**Comment by kenorb** [comment]
It's Varnish configuration issue, it unset your cookies. See similar thing for [Drupal](http://drupal.stackexchange.com/q/46137/1908).

**Comment by dfpalomar** [comment]
@JakeWharton you were right... thanks for your reply :)
