### ISSUE TITLE
NPE on exception

### ISSUE THREAD

**Issue by FedericoOldrini** [square/retrofit#784]
I get this error on async calls. Retrofit 1.9.0 and default client

```E/AndroidRuntime﹕ FATAL EXCEPTION: Retrofit-Idle
    Process: com.example.federico.test, PID: 12735
    java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.Throwable.getMessage()' on a null object reference
            at retrofit.CallbackRunnable.run(CallbackRunnable.java:50)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at retrofit.Platform$Android$2$1.run(Platform.java:142)
            at java.lang.Thread.run(Thread.java:818)```

**Comment by JakeWharton** [comment]
There is no `getMessage()` call on that line in Retrofit 1.9.0: https://github.com/square/retrofit/blob/parent-1.9.0/retrofit/src/main/java/retrofit/CallbackRunnable.java#L50

**Comment by FedericoOldrini** [comment]
My error implementign errorhandler, sorry. Closed
