### ISSUE TITLE
0-byte gzip response causes java.io.EOFException

### ISSUE THREAD

**Issue by igokoro** [square/retrofit#804]
I'm using Retrofit (1.9.0) with OhHttp/okio (2.3.0/1.3.0) to implement communication with OneDrive REST API. While almost everything works amazingly well, there is a problem with ```java.io.EOFException``` on [action.copy](http://onedrive.github.io/items/copy.htm). 

OneDrive server returns 
```
HTTP 202 Accepted
Content-Length: 0
Content-Encoding: gzip
```
Under the hood OkHttp uses ```GzipSource``` to work with  gzip stream. The problem is that GzipSource tries to consume 10-byte gzip header from 0-length stream, so the ```java.io.EOFException``` is thrown because of seemingly missing 10 bytes.

Here is the original stack trace from my application:
```
retrofit.RetrofitError
            at retrofit.RestAdapter$RestHandler.invokeRequest(RestAdapter.java:395)
            at retrofit.RestAdapter$RestHandler.invoke(RestAdapter.java:240)
            at java.lang.reflect.Proxy.invoke(Proxy.java:397)
            at $Proxy13.copy(Unknown Source)
            at com.ncryptedcloud.cloudprovider.onedrive.OneDriveCloudProvider.copy(OneDriveCloudProvider.java:731)
            at com.ncryptedcloud.operation.cloudprovider.CopyFileOperation.execute(CopyFileOperation.java:72)
            at com.foxykeep.datadroid.service.RequestService.onHandleIntent(RequestService.java:145)
            at com.foxykeep.datadroid.service.MultiThreadedIntentService$IntentRunnable.run(MultiThreadedIntentService.java:170)
            at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:818)
     Caused by: java.io.EOFException
            at okio.RealBufferedSource.require(RealBufferedSource.java:64)
            at okio.GzipSource.consumeHeader(GzipSource.java:114)
            at okio.GzipSource.read(GzipSource.java:73)
            at okio.RealBufferedSource$1.read(RealBufferedSource.java:338)
            at java.io.InputStream.read(InputStream.java:162)
            at retrofit.Utils.streamToBytes(Utils.java:43)
            at retrofit.Utils.readBodyToBytesIfNecessary(Utils.java:81)
            at retrofit.RestAdapter$RestHandler.invokeRequest(RestAdapter.java:348)
            at retrofit.RestAdapter$RestHandler.invoke(RestAdapter.java:240)
            at java.lang.reflect.Proxy.invoke(Proxy.java:397)
            at $Proxy13.copy(Unknown Source)
            at com.ncryptedcloud.cloudprovider.onedrive.OneDriveCloudProvider.copy(OneDriveCloudProvider.java:731)
            at com.ncryptedcloud.operation.cloudprovider.CopyFileOperation.execute(CopyFileOperation.java:72)
            at com.foxykeep.datadroid.service.RequestService.onHandleIntent(RequestService.java:145)
            at com.foxykeep.datadroid.service.MultiThreadedIntentService$IntentRunnable.run(MultiThreadedIntentService.java:170)
            at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:818)
```

While the problem is almost 100% likely on the OkHttp side, I wonder if it's possible to handle it on the Retrofit side?

**Comment by sohayb** [comment]
Hey @igokoro , check #755

**Comment by igokoro** [comment]
@sohayb, thanks for the reference - I'm aware that issue. This situation, I believe, is a little different, because I'm getting explicit ```Content-Length: 0``` from server.

**Comment by JakeWharton** [comment]
This is an OkHttp bug. Working on it.

**Comment by JakeWharton** [comment]
Actually the right fix is down in Okio.

**Comment by swankjesse** [comment]
There's no such thing as a 0-byte gzip response. Your server is returning a malformed document.

**Comment by igokoro** [comment]
Discussed this problem with OneDrive REST API developers. They agree that defect is on their side and will fix this problem at some point, see https://github.com/OneDrive/onedrive-api-docs/issues/80.

Until this problem is fixed there's workaround: specify the following on your faulty interface method:
```
@Headers("Accept-Encoding: identity")
```
This will request uncompressed response from server.
