### ISSUE TITLE
Can't get the genericity?

### ISSUE THREAD

**Issue by BiaoWu** [square/retrofit#807]
#my service
```
public interface BaseHttpService {
    @POST("/{requestUrl}")
    <T> void post(@Path("requestUrl") String requestUrl, @QueryMap Map<String, Object> map, Callback<T> callback);
}
```

#my request
```
 BaseHttpService service = restAdapter.create(BaseHttpService.class);
 Map<String, Object> params = new HashMap<>();
 addParams(0, params);
 service.post("xxx", params, callback);
```

#my callback
```
 private Callback<DishListResponse<DishDetail>> callback = new Callback<DishListResponse<DishDetail>>() {
        @Override
        public void success(DishListResponse<DishDetail> dishListResponse, Response response) {
        }

        @Override
        public void failure(RetrofitError retrofitError) {
        }
    };
```

#the exception
```
    java.lang.ClassCastException: java.util.LinkedHashMap cannot be cast to xxx.DishListResponse
            at xxx$2.success(DishKitchenFragment.java:116)
            at retrofit.CallbackRunnable$1.run(CallbackRunnable.java:45)
            at android.os.Handler.handleCallback(Handler.java:615)
            at android.os.Handler.dispatchMessage(Handler.java:92)
            at android.os.Looper.loop(Looper.java:137)
            at android.app.ActivityThread.main(ActivityThread.java:4898)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:511)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1008)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:775)
            at dalvik.system.NativeStart.main(Native Method)
```

#but change callback like this , it's ok.
```
@POST("/xxx")
void listDish(@QueryMap Map<String, Object> map, Callback<DishListResponse<DishDetail>> callback);
```

**Comment by JakeWharton** [comment]
This will never work because we do not have access to the type information. I will leave the issue open as a reminder to throw an exception when parsing the method in this case.
