### ISSUE TITLE
Observable.error and RetrofitError Crash

### ISSUE THREAD

**Issue by danielgomezrico** [square/retrofit#939]
I´m trying to test no connection error and http requests with Espresso and Retrofit in this way:

I´m using MockRestAdapter (will be cool to have more docs about how to use it) and a MockedService that Implements the service interface returning an Observable. It works for objects and normal Exceptions but I try to return an Observable of RetrofitError (trying to use the static constructors and not creating exceptions manually) it breaks.

```
TypedInput bodyTypedInput = new TypedString(body);
Response response = new Response("", status, body, new ArrayList<>(0), bodyTypedInput);
RetrofitError error = RetrofitError.httpError("", response, new GsonConverter(JsonHelper.GSON), null)
Observable<MyObject> observable = Observable.error(error);  // <- BOOM
```

But I get:

```
java.lang.IllegalStateException: Fatal Exception thrown on Scheduler.Worker thread.
at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:62)
at android.os.Handler.handleCallback(Handler.java:733)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.support.test.espresso.base.UiControllerImpl.loopUntil(UiControllerImpl.java:467)
at android.support.test.espresso.base.UiControllerImpl.loopUntil(UiControllerImpl.java:408)
at android.support.test.espresso.base.UiControllerImpl.loopMainThreadForAtLeast(UiControllerImpl.java:393)
at android.support.test.espresso.action.Tap$1.sendTap(Tap.java:44)
at android.support.test.espresso.action.GeneralClickAction.perform(GeneralClickAction.java:98)
at android.support.test.espresso.ViewInteraction$1.run(ViewInteraction.java:144)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
at java.util.concurrent.FutureTask.run(FutureTask.java:237)
at android.os.Handler.handleCallback(Handler.java:733)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:146)
at android.app.ActivityThread.main(ActivityThread.java:5694)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:515)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1291)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1107)
at dalvik.system.NativeStart.main(Native Method)
Caused by: rx.exceptions.OnErrorFailedException: Error occurred when trying to propagate error to Observer.onError
at rx.observers.SafeSubscriber._onError(SafeSubscriber.java:201)
at rx.observers.SafeSubscriber.onError(SafeSubscriber.java:111)
at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.pollQueue(OperatorObserveOn.java:197)
at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber$2.call(OperatorObserveOn.java:170)
at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
... 19 more
Caused by: rx.exceptions.CompositeException: 2 exceptions occurred.
... 24 more
Caused by: rx.exceptions.CompositeException$CompositeExceptionCausalChain: Chain of Causes for CompositeException In Order Received =>
at org.junit.runner.notification.Failure.getTrace(Failure.java:75)
at android.support.test.internal.runner.listener.InstrumentationResultPrinter.reportProcessCrash(InstrumentationResultPrinter.java:204)
at android.support.test.runner.AndroidJUnitRunner.onException(AndroidJUnitRunner.java:297)
at android.support.test.runner.MonitoringInstrumentation$2.uncaughtException(MonitoringInstrumentation.java:168)
at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:66)
... 19 more
Caused by: retrofit.RetrofitError: 400 PickError{message='Error', name='Error', type='Error', value='Error', path='Error'}
at com.pickupnow.customer.mocks.MockManager.createHttpError(MockManager.java:45)
at com.pickupnow.customer.ForgotActivityTests.failureShowsError(ForgotActivityTests.java:61)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:515)
at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
at android.support.test.internal.statement.UiThreadStatement.evaluate(UiThreadStatement.java:55)
at android.support.test.rule.ActivityTestRule$ActivityStatement.evaluate(ActivityTestRule.java:257)
at org.junit.rules.RunRules.evaluate(RunRules.java:20)
at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at org.junit.runners.Suite.runChild(Suite.java:128)
at org.junit.runners.Suite.runChild(Suite.java:27)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
at android.support.test.internal.runner.TestExecutor.execute(TestExecutor.java:54)
at android.support.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:228)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1729)
```

**Comment by JakeWharton** [comment]
If you want to trigger an HTTP exception you should throw `MockHttpException` which will automatically be handled. You can see an example in this test: https://github.com/square/retrofit/blob/parent-1.9.0/retrofit-mock/src/test/java/retrofit/MockRestAdapterTest.java#L456-L460

The mock stuff is all changing for v2.0 which is being worked on now so there's unlikely to be any effort updating the (admittedly brittle) behavior of the current implementation.

The problem you are seeing is that we assume a returned observable will never immediately error and it looks like the error is being swallowed in RxJava.
