### ISSUE TITLE
ClassCastException while using generics 

### ISSUE THREAD

**Issue by youranshul** [square/retrofit#963]
I am getting classCastException while using generics in the code.Please refer the StackOverFlow for more info.
http://stackoverflow.com/questions/31427212/java-util-linkedhashmap-cannot-be-cast-to-datalist

java.lang.ClassCastException: java.util.LinkedHashMap cannot be cast to cuiserve.com.volleyframework.requestData.DataList
            at cuiserve.com.volleyframework.activity.RetrofitActivity$1.onDataReceived(RetrofitActivity.java:18)
            at cuiserve.com.volleyframework.httpConnection.ConnectionHelper.success(ConnectionHelper.java:44)
            at retrofit.CallbackRunnable$1.run(CallbackRunnable.java:45)
            at android.os.Handler.handleCallback(Handler.java:733)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:136)
            at android.app.ActivityThread.main(ActivityThread.java:5001)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
            at dalvik.system.NativeStart.main(Native Method)

**Comment by JakeWharton** [comment]
I will answer on StackOverflow. There is no need to post twice.
