### ISSUE TITLE
not able to send request body with DELETE mehtod

### ISSUE THREAD

**Issue by wasaig** [square/retrofit#974]
I get following error everytime I try to send request body with a DELETE call.

D/Retrofit﹕ ---- ERROR
D/Retrofit﹕ java.lang.IllegalArgumentException: TNTService.storeOffline: Non-body HTTP method cannot contain @Body or @TypedOutput.
            at retrofit.RestMethodInfo.methodError(RestMethodInfo.java:107)
            at retrofit.RestMethodInfo.parseParameters(RestMethodInfo.java:416)
            at retrofit.RestMethodInfo.init(RestMethodInfo.java:118)
            at retrofit.RestAdapter$RestHandler.invokeRequest(RestAdapter.java:294)
            at retrofit.RestAdapter$RestHandler.access$100(RestAdapter.java:220)
            at retrofit.RestAdapter$RestHandler$2.obtainResponse(RestAdapter.java:278)
            at retrofit.CallbackRunnable.run(CallbackRunnable.java:42)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at retrofit.Platform$Android$2$1.run(Platform.java:142)
            at java.lang.Thread.run(Thread.java:841)
D/Retrofit﹕ ---- END ERROR

**Comment by JakeWharton** [comment]
The spec is ambiguous thus we forbid it. If you need this, create your own DELETE annotation: https://github.com/square/retrofit/issues/330#issuecomment-25179351

**Comment by wasaig** [comment]
Thanks, I will do that.

**Comment by lakinkintu** [comment]
public interface RetrofitClass {
    @HTTP(method = "DELETE", path = "api/v3/details/", hasBody = true)
    Call<ResponseBody> RESPONSE_BODY_CALL(@Header("Authorization") String authorization, @Body HashMap<String, List> stringListHashMap);
}
and simpaly call it
Call<ResponseBody> responseBodyCall = (Call<ResponseBody>) retrofitClass.RESPONSE_BODY_CALL(token,stringListHashMap);
        responseBodyCall.enqueue(new Callback<ResponseBody>() {
            @Override
            public void onResponse(Call<ResponseBody> call, Response<ResponseBody> response) {

                int code = response.code();
                String message = response.message();
                Log.d("message", message);
            }

            @Override
            public void onFailure(Call<ResponseBody> call, Throwable t) {

                t.printStackTrace();
            }
        });
It's work

**Comment by fengyongge** [comment]
@lakinkintu    
 there is a mistake，you will be find
 java.lang.IllegalArgumentException: Unable to create @Body converter for class java.util.HashMap (parameter #2)

**Comment by VinRichard** [comment]
使用@Body 请求,报错,    Non-body HTTP method cannot contain @Body  下面是源码截图的地方,版本是2.5.0
![image](https://user-images.githubusercontent.com/29241989/57344434-cfa21c00-7179-11e9-8a16-e23755ee7dc7.png)
![image](https://user-images.githubusercontent.com/29241989/57344462-e47eaf80-7179-11e9-8426-7d477145413d.png)
